README.md
apps/eth-events-service/src/environments/environment.prod.ts
apps/eth-events-service/src/environments/environment.ts
apps/eth-events-service/src/main.ts
apps/eth-events-service/tslint.json
apps/ip-upload/ip-upload/src/environments/environment.prod.ts
apps/ip-upload/ip-upload/src/environments/environment.ts
libs/ip/src/lib/contracts/IpHash.sol
libs/ip/src/lib/contracts/ip-hash.ts
package-lock.json
package.json

Implements the ETH Events Service that:
- subscribe to a list of contracts listed in the env,
- forward these events to a pub/sub topics to be processed by our backends (gcloud functions)
Adds Timestamp events to the ScriptHash Smart Contract.

Add eth-event-service

---

.dockerignore
Dockerfile
README.md

Basic to bundle the eth-events server into a Docker container.
For simplicity we do it from the repos' root for now.

Dockerized eth-events server

---

functions/package-lock.json
functions/src/delivery.ts
functions/src/notify.ts
functions/src/stakeholder.ts
libs/material/src/lib/delivery/+state/delivery.model.ts
libs/material/src/lib/delivery/+state/delivery.query.ts
libs/material/src/lib/delivery/delivery-form/delivery-form.component.html
libs/material/src/lib/delivery/delivery-form/delivery-form.component.scss
libs/material/src/lib/delivery/delivery-form/delivery-form.component.ts
libs/material/src/lib/delivery/delivery-item/delivery-item.component.html
libs/material/src/lib/delivery/delivery-item/delivery-item.component.ts
libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.html
libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.ts
libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
libs/material/src/lib/material/+state/material.query.ts
libs/material/src/lib/material/+state/material.service.ts
libs/material/src/lib/material/material-delivery-form/material-delivery-add-form.component.ts
libs/material/src/lib/material/material-delivery-form/material-delivery-form.component.scss
libs/material/src/lib/material/material-delivery-item/material-delivery-item.component.html
libs/material/src/lib/material/material-delivery-item/material-delivery-item.component.scss
libs/material/src/lib/material/material-delivery-item/material-delivery-item.component.ts
libs/material/src/lib/material/material.module.ts
libs/material/src/lib/template/+state/template.query.ts
libs/material/src/lib/template/+state/template.service.ts
libs/material/src/lib/template/template-picker/template-picker.component.ts
libs/ui/src/lib/notification/+state/notification.service.ts
libs/ui/src/lib/notification/notification-item/notification-item.component.html
libs/ui/src/lib/notification/notification-item/notification-item.component.ts
package-lock.json

Demos todos #2

---

apps/backend-functions/src/backup.ts
apps/backend-functions/src/delete.ts
apps/backend-functions/src/delivery.ts
apps/backend-functions/src/main.ts
apps/backend-functions/src/material.ts
apps/backend-functions/src/migrations.ts
apps/backend-functions/src/notify.ts
apps/backend-functions/src/stakeholder.ts
apps/backend-functions/src/template.ts
apps/backend-functions/src/utils.ts
libs/material/src/lib/delivery/+state/delivery.service.ts
libs/material/src/lib/delivery/delivery-settings-item/delivery-settings-item.component.ts
libs/material/src/lib/delivery/delivery.module.ts
libs/material/src/lib/template/+state/template.model.ts
libs/material/src/lib/template/+state/template.query.ts
libs/material/src/lib/template/+state/template.service.ts
libs/material/src/lib/template/template-item/template-item.component.html
libs/material/src/lib/template/template-item/template-item.component.scss
libs/material/src/lib/template/template-item/template-item.component.ts
libs/utils/src/lib/firequery/firequery.ts

Various fixes around templates and deliveries

---

apps/backend-functions/src/delete.ts
apps/backend-functions/src/delivery.ts
libs/material/src/lib/material/+state/material.service.ts
libs/material/src/lib/template/+state/template.query.ts
libs/material/src/lib/template/template-form/template-form.component.ts

Issue#386 check deliveries ids

---

libs/movie/src/lib/movie/components/movie-form/movie.form.ts

since form reset only set value to null, forms arrays needs to be cleared or else data will be duplicated (with null values) when re-populating

sub formsArrays needs to be cleared on form reset

---

apps/backend-functions/src/data/index.ts
apps/backend-functions/src/data/internals.ts
apps/backend-functions/src/data/types.ts
apps/backend-functions/src/delete.ts
apps/backend-functions/src/delivery.ts
apps/backend-functions/src/local/testPDFExport.ts
apps/backend-functions/src/main.ts
apps/backend-functions/src/material.ts
apps/backend-functions/src/migrations.ts
apps/backend-functions/src/notify.ts
apps/backend-functions/src/pdf.ts
apps/backend-functions/src/stakeholder.ts
apps/backend-functions/src/utils.ts
firebase.json
libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.html
libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.scss
libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
package-lock.json
package.json

Contributes to #534 next steps are blocked by other tasks, details in the linked issue.

Issue 534: pdf export for deliveries

---

libs/material/src/lib/delivery/+state/delivery.query.ts
libs/material/src/lib/delivery/+state/delivery.service.ts
libs/material/src/lib/delivery/components/delivery-sign/delivery-sign.component.ts
libs/material/src/lib/delivery/guards/delivery-active.guard.ts
libs/material/src/lib/delivery/guards/delivery-list.guard.ts
libs/material/src/lib/template/+state/template.service.ts
libs/material/src/lib/template/guards/template-list.guard.ts
libs/movie/src/lib/movie/+state/movie.model.ts
libs/movie/src/lib/movie/+state/movie.service.ts
libs/movie/src/lib/movie/components/movie-title-form/movie-title-form.component.ts
libs/movie/src/lib/movie/guards/movie-active.guard.ts
libs/movie/src/lib/movie/guards/movie-list.guard.ts
libs/movie/src/lib/stakeholder/+state/stakeholder.model.ts
libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
libs/movie/src/lib/stakeholder/components/stakeholder-repertory/stakeholder-repertory.component.ts
libs/organization/src/lib/+state/organization.service.ts
libs/organization/src/lib/components/org-widget/org-widget.component.html
libs/organization/src/lib/components/org-widget/org-widget.component.ts
libs/organization/src/lib/guard/organization.guard.ts
libs/organization/src/lib/pages/member-list/member-list.component.html
libs/organization/src/lib/pages/member-list/member-list.component.ts
libs/organization/src/lib/pages/org-view/org-view.component.html
libs/organization/src/lib/pages/org-view/org-view.component.ts
libs/organization/src/lib/permissions/+state/permissions.service.ts
libs/organization/src/lib/permissions/guard/permissions.guard.ts

One transaction movie

---

apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
firestore.indexes.json
firestore.rules
libs/contract/src/lib/+state/contract.service.ts
libs/contract/src/lib/+state/contract.store.ts
libs/contract/src/lib/version/+state/contract-version.service.ts
libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
libs/movie/src/lib/movie/+state/movie.service.ts

- Update contract list query to avoid  fetching unwanted contracts.
- Add new functions to get contracts information when they are displayed as a list.
- Rename `distributiondeals` sub-collection into `distributionDeals`.
- Remove useless `@CollectionConfig` from subcollection services.

Issue#1568 contract list query

---

libs/contract/src/lib/contract/+state/contract.service.ts
libs/contract/src/lib/version/+state/contract-version.model.ts
libs/contract/src/lib/version/+state/contract-version.service.ts
libs/material/src/lib/delivery/+state/delivery.service.ts
libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
libs/movie/src/lib/movie/+state/movie.service.ts
libs/organization/src/lib/permissions/+state/permissions.service.ts

- Add onCreate hooks for Movie, Delivery and Contract document => related permissions are created when a document is added to firestore.
- Update services with CollectionService methods. (fix #1644 )

Fixing permissions creation / Update services

---

firestore.rules
libs/organization/src/lib/+state/organization.service.ts

- Remove unused appsPermissions subcollection (until we meet again)
- Add new rule in permissions collection when creating an organization (checks that organization document doesn't exist and checks that userId will be in the organization document to be created).

Fixing permissions again

---

apps/catalog/catalog/src/app/app.module.ts
libs/utils/src/lib/error-logger.module.ts
libs/utils/src/lib/sentry.module.ts

At some point we lost errors in the front, this PR adds an error handler that make sure we log the errors!
Only in cases where there are no sentry (we'll keep sentry in prod).

With errors

---

apps/backend-functions/src/main.ts
apps/backend-functions/src/permissions.ts
apps/backend-ops/src/firebaseSetup.ts
apps/backend-ops/src/firestoreMigrations/0004.ts
apps/backend-ops/src/firestoreMigrations/0005.ts
apps/backend-ops/src/firestoreMigrations/index.ts
apps/backend-ops/src/main.ts
apps/backend-ops/src/migrations.ts
apps/main/main/src/test-rules/006-permissions.spec.ts
apps/main/main/src/test-rules/mock.ts
firestore.rules

Fix "a user can give themselves permission for a document owned by another org (R003)"
When a user creates document permission, we index this document (allDocPermission/{docId}) => now we have ONE location with all the documents ids that have permission attached to them.
In the rules, we forbid the creation of a permission doc if there's already a corresponding document id in the index. => document permission for an object that ALREADY exists is created by the backend as admin.

Add docId Index

---

libs/utils/src/lib/pipes/translate-slug.pipe.ts

Inner function `formatSlug` now returns an empty string if slug is undefined or null to avoid errors.
close #2121

Update translateSlug pipe for null/undefined values

---

.firebaserc

We introduced multiple Firebase hosting targets in production, ci, and staging: `storybooks`, `maintenance`, and `next` targets.
Developpers do not have these targets, which will introduce errors on deploy. This patch adds the `current` target for everyone, this is the minimum they need.
The error:
```
Error: Deploy target current not configured for project blockframes-USER. Configure with:
firebase target:apply hosting current <resources...>
```
The patch was generated with the command:
```
cat .firebaserc | jq -r '.projects[]' | while IFS=$"\n" read -r c; do firebase use $c && firebase target:apply hosting current $c; done
```

firebaserc: add current target for everyone

---

libs/organization/src/lib/+state/organization.model.ts

Convert organization timestamps to date to avoid errors.
close #2109

Convert organization timestamps to dates before sending into store

---

apps/backend-ops/src/algolia.ts

When inserting movies to the algolia index encounter an error, simply skip the movie instead of throwing away the whole process

fix algolia insert error

---

apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
apps/catalog/catalog/src/app/dashboard/title/view/view.module.ts
firestore.rules

- Remove unused/useless guards from dashboard.module and title view.module
- Move `OrganizationContractListGuard` in the right place to call it once
- Remove deprecated function from rules
close #2389

Fix permissions denied in Dashboard movie view

---

apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
apps/catalog/catalog/src/app/dashboard/layout/layout.component.ts
apps/catalog/catalog/src/app/marketplace/layout/layout.component.html
apps/catalog/catalog/src/app/marketplace/layout/layout.component.ts

close #2123 
now by every forward navigation in dashbord and marketplace we start at the top of the page.
But also on every backward navigation, we start also at the top.
There is a followup issue ref #2502 which explains why we have such behaviour. 
TLDR;
Its because we are in a mat side nav and which has his own scroll container, so the angular router cant access this container and set the position to scrollY position to 0.
Cause we need to go quick for the release 1.3 this is the intermediate solution.

set scrollY to 0 when route change is happening

---

.circleci/deploy-and-test-e2e.sh
env/demo/env.demo1.ts

Running e2e tests in a serialized queue relies on do-exclusively orb, we can't use the "always" option from circleci.
This tweaks the e2e testing to run all tests and gather their result to fail or succeed the test.
piggyback Vincent's demo1 config with this PR

ci: tweak test to run all in a bash

---

libs/media/src/lib/+state/media.firestore.ts
libs/media/src/lib/+state/media.model.ts
libs/media/src/lib/+state/media.service.ts
libs/media/src/lib/components/cropper/cropper.component.ts
libs/media/src/lib/directives/image-reference/image-reference.form.ts
libs/movie/src/lib/movie/+state/movie.service.ts
libs/organization/src/lib/organization/pages/organization/organization.component.ts
libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts

Fix deleting other media values when uploading new image

---

apps/backend-functions/src/environments/environment.prod.ts
apps/backend-functions/src/environments/environment.ts
apps/backend-functions/src/internals/sentry.ts
env/demo/env.demo1.ts
env/env.ci.ts
env/env.prod.ts
env/env.staging.ts
libs/utils/src/lib/sentry.module.ts

This will help us to differentiate staging errors from prod errors in the sentry dashboard

Adding sentry env

---

apps/backend-ops/src/firestoreMigrations/temporary-0028.ts

Transform every `movie.promotionalElements` arrays into `Record<string, ...>`.
You should not change the inner elements, this will be done later depending on their types.
You can use the index teh string key of the record :
```TypeScript
still_photo: [
{ poster0 },
{ poster1 },
{ poster2 },
// ...
]
```
Should become :
```TypeScript
still_photo: {
'0': { poster0 },
'1': { poster1 },
'2': { poster2 },
// ...
}
```

Migrate still_photo

---

libs/media/src/lib/+state/media.service.ts
libs/media/src/lib/components/upload/widget/upload-widget.component.html
libs/media/src/lib/components/upload/widget/upload-widget.component.ts
libs/media/src/lib/pipes/task-progress.pipe.ts
libs/utils/src/lib/error-logger.module.ts

Fix upload cancel and updatable items in UploadWidgetComponent

---

libs/media/src/lib/+state/media.firestore.ts
libs/media/src/lib/+state/media.service.ts
libs/media/src/lib/components/upload/widget/upload-widget.component.html
libs/media/src/lib/components/upload/widget/upload-widget.component.ts
libs/utils/src/lib/helpers.ts

Fix upload cancel and updatable items in UploadWidgetComponent v2

---

apps/festival/festival/src/app/marketplace/organization/title/title.component.html
apps/festival/festival/src/app/marketplace/organization/title/title.component.ts

Fix to do in issue #3412 
"When you go from org public page on marketplace (e.g. /c/o/marketplace/organization/e1VXeusNJK6pb8kmVnUn/title) and then on wishlist only the films from that sales agents + included in your wishlist are visible."

Get accepted movies without resetting the store

---

libs/ui/src/lib/app-bar.ts

Fix to do from issue #3412 
"On top of #3355, top search bar that should appear when you scroll down doesn't appear if you do this flow:
1. go on all films
2. go on a public org page (e.g. `c/o/marketplace/organization/GdFUevWIifjk6VEYgfCT/title`)
3. go back on the page all films. Don't know why but the 2 look linked..."
Actually this bug happens on all pages which use the pageBar directive. This is caused by the values in `entry.rootBounds` to be all 0. After a small delay the `entry.rootBounds` do have the values they should have.
I expected animations to be the cause of this issue, but even when disabling animations this bug still happens...

Added delay to prevent the bug from happening

---

apps/backend-functions/src/internals/invitations/organizations.ts
apps/backend-functions/src/templates/mail.ts

Fix to do in issue #3412 
"Acceptation to an org email doesn't display org name properly; it's working as intended when sending the request"

Added user and organization name to email data

---

libs/invitation/src/lib/components/item/item.component.html
libs/invitation/src/lib/components/item/item.component.ts

Fix multiple to do's from issue #3412 
1. "Wrong invitation when a user request to join an organization:
"Go to event" action should be renamed "More details" to be generic
"Go to event" action should redirect to https://staging.archipelmarket.com/c/o/organization/e1VXeusNJK6pb8kmVnUn/view/members when it's an invitation for organization and to https://staging.archipelmarket.com/c/o/dashboard/event/gST9ZDOPoWoYBuXUeVEW/edit when it's an event (and you are the organizer receiving a request)"
2. "On dashboard, when you receive an invitation to an event which is not yours and click on the more details button, the user is redirected to the dashboard view of the event as it was his/her own. It should redirect to the marketplace event view instead.
To avoid too many use cases every invitations …

Fix invitation links and text

---

libs/ui/src/lib/app-bar.ts
package-lock.json
package.json

To do in issue #3412 
Intersection Observer is not supported for Safari version lower than 12.2. Therefore it needs to be polyfilled.

Polyfill Intersection Observer

---

libs/movie/src/lib/movie/form/search.form.ts

Fix for clear button for budget filter on movie list page causing the search to crash

Fix clear button on budget filter

---

apps/backend-ops/src/users.ts
env/env.ci.ts
env/env.prod.ts
env/env.staging.ts

prepareForTesting - generateWatermarks fails due to interconnection issues sometimes.
`export async function runChunks(rows: any[], cb: any, rowsConcurrency = 10, verbose = true)`
by introducing an env var to tune rowsConcurrency to suitable values gives chance to script to run.

Update(backend-ops): Introduce env var to deal with internet issues.

---

apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
apps/festival/festival/src/app/marketplace/event/session/session.component.html
apps/festival/festival/src/app/marketplace/event/session/session.component.scss
apps/festival/festival/src/app/marketplace/event/session/session.component.ts
libs/event/src/lib/guard/session.guard.ts
libs/event/src/lib/layout/edit/edit.component.html
libs/event/src/lib/layout/edit/edit.component.ts
libs/event/src/lib/layout/view/view.component.html
libs/event/src/lib/layout/view/view.component.ts

improve flow & meeting prototype

---

apps/backend-ops/src/main.ts
libs/firebase-utils/src/lib/maintenance.ts

- added guard clause to maintenance methods if maintenance is disabled
- backend-ops which is what CI runs when making a release, will check for this flag
- even without the flag, maintenance mode can be disabled with an environment variable
- `BLOCKFRAMES_MAINTENANCE_DISABLED`
- Pros: freedom to disable it from environment, in CI setup, in terminal, in .env, and also via flag
- cons: maybe add a `console.warn` in `startMaintenance` if it's disabled

feat(backend-ops): disable maintenance mode with --skipMaintenance flag

---

libs/invitation/src/lib/components/item/item.component.html
libs/invitation/src/lib/guard/invitations.guard.ts

"Request to access a screening from buyer to seller has a wrong link id, it uses the invitation id instead of the event id"
Also, users that are not an admin didn't have access to requests to attend the event. Now they do.

Fix attendEvent permission and link on invitation

---

apps/festival/festival/src/app/marketplace/home/home.component.ts
apps/festival/festival/src/app/marketplace/organization/title/title.component.ts

"`/c/o/marketplace/home` Change the New films carousel on marketplace homepage to really display new films, i.e. sort films by creation dates and display them from the newest to oldest"
"Same sort by should be use for films in `c/o/marketplace/organization/orgId/title` > newest to oldest"

Order movies by release year

---

apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
apps/catalog/catalog/src/app/marketplace/title/list/list.component.scss
apps/festival/festival/src/app/marketplace/title/list/list.component.html
apps/festival/festival/src/app/marketplace/title/list/list.component.scss

"The search bar on the film page is confusing, it looks like an image that didn't load. Should have a placeholder, and generally, the same design as the original search bar"
See result below:

Update UI for search bar in pageBar

---

libs/media/src/lib/+state/media.service.ts

"Clicks on the page are not registered anymore when the upload component is active"

cdkOverlay too big

---

libs/event/src/lib/layout/edit/edit.component.html
libs/event/src/lib/layout/edit/edit.component.ts
libs/ui/src/lib/form/time-picker/time-picker.component.ts

"When we change start date of an event, end date should adapt: event should stay the same duration. E.g. Start date 09/15/20 10:00 am / End date 09/15/20 11:00 am > start date changed to 09/16/20 11:00 am, end date should be automatically updated to 09/16/20 noon"

Move end date with changing start date

---

libs/movie/src/lib/movie/components/card/card.component.scss

Fix UI issue for Safari

---

libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.html
libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.scss

Fix static checkbox ui

---

apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
apps/festival/festival/src/app/marketplace/title/list/list.component.html
apps/festival/festival/src/app/marketplace/title/list/list.component.ts
libs/movie/src/lib/movie/layout/list/title-list.component.html
libs/movie/src/lib/movie/layout/list/title-list.component.ts

Fix movie counts indicators

---

libs/event/src/lib/components/list/list.component.html
libs/event/src/lib/components/list/list.component.ts
libs/movie/src/lib/movie/marketplace/shell/shell.component.html
libs/utils/src/lib/pipes/filter-by-date.pipe.ts

To do issue #3674 
"Screening lists (/c/o/marketplace/event + /c/o/marketplace/organization/orgId/screening + /c/o/marketplace/title/movieId/screenings) display events based on their starting date but for multiple day screenings they should appear on every day of the screening.
For example: an event from 10/15 to 10/17 is currently shown only for the 15th while it should be displayed on 15th, 16th and 17th"
-- And --
"Images section title shouldn't be displayed if there is no stills on the film"

Show multi day even at every day it is screening

---

libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts

To do issue #3674 
"Cookie preferences bar stays visible after setting the preferences, it should disappear (need to refresh for now)"

Close cookie banner after saving preferences

---

apps/festival/festival/src/app/marketplace/home/home.component.html
apps/festival/festival/src/app/marketplace/home/home.component.scss
libs/movie/src/lib/movie/components/credit-card/credit-card.component.html
libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html

To do issue #3674 
"Person Card: 
- add a tooltip for the no status icon: "Status is not provided" 
- for cast card, change "Comedian" for "Actor"
-- and --
"Screening banner:
- change text for "There are no screening scheduled at the moment. You can contact {{orgName}} for any questions." 
- screening CTA button text is: "Contact Sales Agent"
-- and --
Move upward "check out upcoming screenings" banner on homepage so it's just before the top banner "the ongoing film market" this is to help the users find their screening more easily. Mb good to check quickly with @stephanie-cascade8 if there should be some margin between the 2 banners but the goal is to see the screenings banner without scrolling."

Tiny ui fixes

---

libs/event/src/lib/layout/view/view.component.html
libs/event/src/lib/layout/view/view.component.scss
libs/event/src/lib/layout/view/view.component.ts
libs/event/src/lib/pipes/event-range.pipe.ts
libs/invitation/src/lib/components/action/action.component.html
libs/invitation/src/lib/components/action/action.component.ts

"When the event is public and the user not invited, the CTA button should be "Access event" > this would create the request and automatically accept it as it does already + leading to the event page so the user can access the screening
On the marketplace event view, if the user is not invited, the CTA should also be "Access event"
Also, here we would need an observable so after clicking on "Access event" the "accepted" state + "Access Screening Room" should appear without the user reloading the page
"
-- and --
"-When a user creates a multiple day event, it should automatically starts from 00:00 AM on the first day to 11:59PM last day and this info should be displayed on the time of the event, same as the all day event (already implemented) 
-- and --
"When event …

Navigate to event immediately when its already running

---

libs/user/src/lib/auth/+state/auth.service.ts

Fix error "zone.js:3324 Mixed Content: The page at 'https://staging.archipelmarket.com/auth/connexion#login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.ipify.org/?format=json'. This request has been blocked; the content must be served over HTTPS."

Get api over https instead of http

---

firestore.rules
libs/invitation/src/lib/components/item/item.component.ts

To do issue #3674 
"Invitations: can't accept a request to attend an event, it goes back to pending right after I click on accept (currently with dev+crystel-fhw@cascade8.com)"
""More details" on the action list for that same invitation (request to attend to an event) links to a dead url https://staging.archipelmarket.com/c/o/marketplace/event/4MeCa9BVCC7lkSCih9T8/edit > it's not marketplace but dashboard (for the owner of the event)
[Update: url marketplace in fact depends on the user being already in the marketplace or dashboard; sellers being able to be on both apps, the link should be agnostic of that and always redirect to dashboard when the org is owner of the event ]"

Navigate user to dashboard event

---

libs/movie/src/lib/movie/marketplace/shell/shell.component.html

Upcoming screening banner needs some more bug fixes. Therefore we chose to disable it for now and fix it for the next release.

Remove upcoming screening component for now

---

libs/user/src/lib/auth/+state/auth.service.ts

Fix issue #3929 
Reload page on sign out didn't seem to be needed.
The issue was first mentioned 4 months ago in [issue#2782](https://github.com/blockframes/blockframes/issues/2782) and fixed in [PR #3214](https://github.com/blockframes/blockframes/pull/3214). I removed the reload page part and tested on Firefox, Chrome and Safari and all tabs logged out and navigated to the home page.

Removed reload on signout

---

apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
apps/festival/festival/src/app/dashboard/event/edit/edit.module.ts
apps/festival/festival/src/app/dashboard/event/review/review.component.html
apps/festival/festival/src/app/dashboard/event/review/review.component.scss
apps/festival/festival/src/app/dashboard/event/review/review.component.ts
apps/festival/festival/src/app/dashboard/event/review/review.module.ts
libs/event/src/lib/components/analytics/analytics.component.html
libs/event/src/lib/components/analytics/analytics.component.scss
libs/event/src/lib/components/analytics/analytics.component.ts
libs/event/src/lib/components/analytics/analytics.module.ts
libs/event/src/lib/form/event.form.ts

Display statistics of an event at the end of the event form; same as event dashboard view. For the moment, you can't access the view before the event is finished (or with the direct url) and that's annoying for multiple day screenings since they'd like to have their stats asap

Event analytics hotfix

---

libs/media/src/lib/directives/image-reference/background-reference.directive.ts

it's a problem with file names, it has some `()` , in the code the background directive do this to the element css
```
background-image: url(https://....../myFile(1).png), url(assets/fallback.png)
```
☝️  here the `()`  in the file name are messing with the first `url()`  so the browser simply ignore it, thus displaying the fallback
I have fixed it by putting `""` around the `url` so that the parenthesis are preserved.

Fix backgound image bug

---

apps/festival/festival/src/app/dashboard/files/files.component.html
libs/media/src/lib/components/file-explorer/file-explorer.component.html
libs/media/src/lib/components/file-explorer/file-explorer.component.ts
libs/media/src/lib/components/file-explorer/file-explorer.model.ts
libs/media/src/lib/components/file-explorer/file-explorer.module.ts

Add subtitle to my files page, navigate one back in breadcrumbs

---

libs/media/src/lib/components/dialog/file/file.component.html
libs/media/src/lib/components/dialog/image/image.component.html
libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
libs/media/src/lib/components/file-explorer/file-explorer.component.ts
libs/media/src/lib/components/file-explorer/file-explorer.model.ts
libs/movie/src/lib/movie/form/media-files/media-files.component.html

Updating file explorer ui 2 

---

libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.html
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
libs/media/src/lib/components/upload/widget/upload-widget.component.html
libs/media/src/lib/components/upload/widget/upload-widget.component.scss
libs/media/src/lib/pipes/task-state.pipe.ts

To do in issue #4290  NOT FIXED
There is an issue in AngularFire where cancelling results in an error response. This should be fixed in AngularFire 6.1.1
https://github.com/angular/angularfire/issues/1805
This PR doesn't change anything in the current UI, but does support cancel status once AngularFire has fixed the issue and we've updated our packages.
Accidently added commit:
To do issue #4290

Status canceled support

---

apps/festival/festival/src/app/dashboard/title/list/list.component.html
apps/festival/festival/src/app/dashboard/title/list/list.component.ts
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.html
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
libs/ui/src/lib/list/table-filter/table-filter.component.html
libs/ui/src/lib/list/table-filter/table-filter.component.ts

Disable sorting per column

---

apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
apps/festival/festival/src/app/dashboard/event/edit/edit.module.ts
libs/event/src/lib/layout/edit/edit.component.html
libs/event/src/lib/layout/edit/edit.module.ts
libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.ts

To do in issue #4290 
"Add the files you'll want to share during the meeting.
(line break) If you can't find the files you're looking for, you can upload them directly in My Files (hyperlink) page."
Result:

Rework event details form

---

libs/event/src/lib/components/week/week.component.ts
libs/event/src/lib/event.module.ts
libs/event/src/lib/form/create/create.component.html
libs/event/src/lib/form/create/create.component.ts
libs/event/src/lib/form/event.form.ts

Rework create event dialog

---

libs/media/src/lib/components/file-selector/file-selector.component.html
libs/media/src/lib/components/file-selector/file-selector.component.scss
libs/utils/src/lib/pipes/fileName.pipe.ts

Update file select modal ui

---

apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
apps/festival/festival/src/app/marketplace/event/session/session.component.html
apps/festival/festival/src/app/marketplace/event/session/session.component.ts
libs/event/src/lib/components/meeting/media-list/media-list.component.html
libs/event/src/lib/components/meeting/media-list/media-list.component.scss
libs/event/src/lib/components/meeting/media-list/media-list.component.ts
libs/event/src/lib/components/meeting/media-list/media-list.module.ts
libs/event/src/lib/components/meeting/room/video-room.component.html
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
libs/media/src/lib/components/viewers/media-viewer.component.html
libs/media/src/lib/components/viewers/media-viewer.component.scss
libs/media/src/lib/components/viewers/media-viewer.component.ts
libs/media/src/lib/components/viewers/media-viewer.module.ts

To do in issue #4290 
1. On the left add the icon + "Presentation shared with participants" for reassurance 
2. On the right, add the icon + Stop Sharing option (button that stops sharing)

Update UI of event lobby and session

---

libs/ui/src/lib/carousel/carousel.component.ts

To do in issue #4290 
Items can dynamically be added/removed to the carousel in file selector during meeting therefore a subscription is needed to check if arrow is needed when items are added.
Also, tiny numbers as offset caused arrows to not disappear even though they should. Rounding to 0 decimals fixed this.

Fix arrow bug

---

apps/festival/festival/src/app/marketplace/marketplace.component.scss
libs/media/src/lib/components/dialog/file/file.component.html
libs/media/src/lib/components/dialog/file/file.component.scss
libs/media/src/lib/components/dialog/image/image.component.html
libs/media/src/lib/components/dialog/image/image.component.scss
libs/media/src/lib/components/dialog/image/image.component.ts
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.html
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.module.ts
libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.scss
libs/ui/src/lib/layout/marketplace/marketplace.component.scss
libs/ui/src/lib/list/table-filter/table-filter.component.scss

To do's issue #4337 
Add same margin around tables in the same area. (if space is not enought, have a horizontal scroll inside tables like it's the case in some existing components (see tables inside dashboard)
If you can (not mandatory at all) use a lighter shade of primary palette.

Polishing file explorer and icon header

---

apps/festival/festival/src/app/marketplace/event/session/session.component.html
apps/festival/festival/src/app/marketplace/event/session/session.component.scss
apps/festival/festival/src/app/marketplace/event/session/session.component.ts
libs/event/src/lib/guard/event.guard.ts
libs/media/src/lib/components/viewers/media-viewer.component.html
libs/media/src/lib/components/viewers/media-viewer.component.scss
libs/media/src/lib/components/viewers/media-viewer.module.ts
libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.html
libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.scss
libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.ts

related to Meeting Bug Tracker #4393

bug fix and style improvement

---

libs/media/src/lib/components/cropper/cropper.component.ts
libs/media/src/lib/components/dialog/file-viewer/viewer.component.scss
libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.scss
libs/media/src/lib/components/file-explorer/file-explorer.model.ts
libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.scss
libs/movie/src/lib/movie/form/media-notes/notes.component.html

To do's in issue #4437 
And maybe fixes for documents not previewing/downloading. I'll have to check that tomorrow on Staging

Update file explorer

---

libs/media/src/lib/components/cropper/cropper.component.ts

Improvement on issue #4451 
It's not fully fixed. Dragging the image to the sides or top it does work, but if you drag the image to the bottom it still bugs - This is due to changing height of the drop-cropper dependent on the image within it.
I'll keep the issue open but it's already an improvement for now

Improvement of drop cropper

---

libs/organization/src/lib/organization/pages/organization/organization.component.scss
libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.scss
libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
libs/utils/src/lib/safari-banner/safari-banner.component.ts

Fix issue #4442 
Cookies without an expiration date (or max-age) are set to last only for a session. Closing the browser ended the session and thus removing this cookie. By setting the max-age, the cookie is only deleted after one year.

Persistant cookie

---

libs/landing/src/lib/shell/shell.component.html
libs/landing/src/lib/shell/shell.component.ts

Fix input on landing page, and the Archipel/Media financiers team name just before the `Want to learn more` form.

Input and name team

---

apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html

- all the ones included in Storyline Elements (logline, synopsis, Key assets, Keywords)
- technical information format

Fix links on media form

---

libs/movie/src/lib/movie/form/filters/languages/language-filter.component.html

Exclude all languages from filter

---

libs/movie/src/lib/movie/form/filters/budget/budget.component.html
libs/movie/src/lib/movie/form/filters/budget/budget.component.ts
libs/movie/src/lib/movie/form/search.form.ts

To do in issue #4514 
E.g. I go halfway from 20M to 10M and got all films that have budget range between 10M & 20M$
I am curious if this is the way to go. If the value in budget is for example 1.000.000, it will search for movies of 19.000.000+. The user doesn't notice this because the label on the slider will be 19.000.000. It's just the value in the form that might cause later confusion.

Invert budget filter

---

libs/media/src/lib/directives/image-reference/image-reference.directive.ts

Fix #4585 
Couldn't find any bugs caused by removing the `if (!image) return` line. Also can't find why it was added in the first place. Do you know potential bugs?

Fix 4585: wrong image shown

---

apps/backend-functions/src/internals/invitations/events.ts
apps/backend-functions/src/templates/ids.ts
apps/backend-functions/src/templates/mail.ts

Add a new function to create email when organization accepted a request from an user to attend one of its event.
Will need several changes on the template on Sendgrid :
- OrgName variable in the subject need to be changed
- I don't put different variable for the time and the date of the event. It's in one variable (instead of 'month/day/year' and 'hours/min/sec', I have 'month/day/year hours:min:sec GMT')
See with Vincent but maybe we need an URL redirecting to the event page ?
Fix #4092

Email for request to event accepted by org

---

apps/backend-functions/src/invitation.ts
apps/backend-functions/src/main.ts
libs/invitation/src/lib/+state/invitation.firestore.ts
libs/invitation/src/lib/+state/invitation.service.ts
libs/organization/src/lib/organization/components/member-add/member-add.component.ts

Here is the problem :
when an admin invite user to join org, then remove the invitation, and invite again the same user, there is only one email sent to the user to invite him on the platform, but 2 invitations were sent.
This is because we don't remove the user in the authentication part when we delete the first invitation, so the second email isn't sent correctly.
I create a backend function when an invitation is removed to delete also the user in the authentication part IF the user hasn't orgId already (that would mean he joined an other org or create his own) and if there is no other invitation (if 2 organizations sent him an invitation, we don't want to delete his account if one of the org cancel its invitation).
I'm opened to more improvement and in case I didn't think about an …

Admin invite user to join org

---

libs/movie/src/lib/movie/components/title-features/title-features.component.ts
libs/movie/src/lib/movie/pipes/movie-feature.pipe.ts
libs/utils/src/lib/static-model/static-model.ts

Fix issue #4765 
Original issue said 'production country' which is something else than 'origin country'.
@phpgeekfr should this be merged into release/2.1 directly or does this go via a different branch? There will probably be more fixes this week since Vincent made a list for fixes: https://github.com/blockframes/blockframes/issues/4767

4765 change production country to origin country

---

styles/style.scss

Fix issue #4551
`color-scheme: light dark;` was also applied to iframe which causes the background color to be set according to UA (white)

4551 Fix intercom white background color

---

apps/rules/src/tests/firestore/fixtures/data.ts
apps/rules/src/tests/firestore/movies.spec.ts
firestore.rules

Fix issue #4716 
Users are automatically redirected to homepage if they try to access the title page. This is because they can't read the movie doc due to the rules and therefore they can't pass the guard

4716 deny access to draft or refused titles if no edit rights

---

apps/rules/src/tests/firestore/movies.spec.ts
firestore.rules

This fixes rules update #4799 .
The  rule change introduced in #4799 is causing permissions errors when we attempt to fetch movies in `/c/o/dashboard/title` . The query should have worked since every movie document had correct permissions and if we attempt to fetch movies one by one, no issue with current rules. So ... My guess is that ` orgCan('canUpdate', userOrgId(), existingData().id) )` for "n" movies was making to much operation and we hit the limit..
Using `userOrgId() in existingData().orgIds`, no problem (and it fit the actual query in front  `fromOrg = (orgId: string): QueryFn => ref => ref.where('orgIds', 'array-contains', orgId);`).  But only users belonging to org that is in movie.orgIds will be allowed, if user from another org but with "canRead" permissions for this movie …

fix rules for reading multiple movies

---

apps/backend-functions/src/internals/invitations/events.ts
apps/backend-functions/src/notification.ts
apps/backend-functions/src/orgs.ts

Move email sending of `invitationToAttendEventAccepted`, `organizationAcceptedByArchipelContent` notifications and prepare one for `requestToAttendEventSent` notification, but need a template from sendgrid.

Event email notif

---

apps/backend-functions/src/internals/email.ts
apps/backend-functions/src/notification.ts
apps/backend-functions/src/templates/ids.ts

Add a new parameter to let us send to sendgrid an group id. It will allow us to split email into several group and users will be able to unsubscribe to some group or every group depending on which emails they want to receive.
Close #4710

Unsubscribe group

---

apps/backend-ops/src/generate-fixtures.ts
apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
libs/event/src/lib/components/week/week.component.ts
libs/event/src/lib/form/edit-details/edit-details.component.html

@xmano `Felicità` is still used but is in draft. Tests are falling here on my side. 
I did not had issue about no-organization-guard

small fixes for e2e tests

---

libs/firebase-utils/src/lib/algolia/algolia.ts
libs/utils/src/lib/algolia/algolia.interfaces.ts

Add the activity of the org on its algolia index
Fix #4946 
Screen of an org after the `upgradeAlgoliaOrgs` command

Org Algolia

---

apps/backend-ops/src/algolia.ts

no issue created for this but this PR resolve the issue. the org's and movie's list didn't display because in `blockframes\apps\backend-ops\src\algolia.ts` the `await clearIndex()` has to be written before the `setConfigurationIndex()` (for each await of them, so 3). Don't forget to launch `npm run backend-ops upgradeAlgoliaMovies` and `npm run backend-ops upgradeAlgoliaOrgs` to apply this properly.
@fritzschoff has found this, thanks to him.

fix algolia issue - no result found (org list and movie list)

---

libs/media/src/lib/+state/file-uploader.service.ts
libs/media/src/lib/file/upload-widget/task.pipe.ts
libs/media/src/lib/file/upload-widget/upload-widget.component.html
libs/media/src/lib/file/upload-widget/upload-widget.component.ts

Workaround for #4800
AngularFireUploadTask state is not updated with the latest state of the firebase.UploadTask. Therefore we use a workaround to get the state directly from firebase UploadTask until AngularFire fixes this bug.
This bug exists since update to firebase version 8 and higher.
Also, fixed the bug where it would remove the file when clicking on the button of completed uploads.

4800 workaround for AngularFire bug

---

apps/backend-functions/src/orgs.ts
libs/organization/src/lib/organization/pages/request-access/request-access.component.html
libs/organization/src/lib/organization/pages/request-access/request-access.component.ts

Remove a call to email function when org is updated.
- When an org is created, it sends an email to C8 admin to let them know a new organization is waiting their approval. CRM link is sent inside the email.
- An organization can ask a new access only if someone of the org connects to a wrong app, like for example, they have access to festival and an user connects on catalog. He will be stucked on the new request access page.
- C8 admin will received email only when an org is created and if an user clicks on the request access button on the request access page.
- We can change the appAccess of an org only on CRM. If we change it, we can choose to send email or not to the admin's org to let them know they have now a new access.
I don't think they can ask for access to a new app in an other …

App access email

---

libs/movie/src/lib/movie/form/main/main.component.html

When the status of running time is 'to be determined', we hide the running time 'time'
OR

hide running time

---

libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
libs/user/src/lib/auth/pages/identity/identity.component.html

The hidden `<mat-option style="display:none;"></mat-option>` is added so `lastOptionRef` is displayed even if there is no results coming from Algolia
I hope there is a better solution than this.

KFH - fix mat-option in templateRef issue

---

apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceCalendarPage.ts
package-lock.json
package.json

Test results were not generated properly due to ffmpeg video err. The Cypress 6.8.0 rel has fix for this.
For festival create screening test fail - added some wait and timeout to make the element available in more stable way.

e2e ci err fix

---

libs/e2e/src/lib/pages/organization/OrganizationLiteFormPage.ts

Fix `should not be visible` by `should not exist` in the org creation test

Fix e2e catalog

---

libs/ui/src/lib/static-autocomplete/group/group.component.html
libs/ui/src/lib/static-autocomplete/group/group.component.ts
libs/ui/src/lib/static-autocomplete/group/group.module.ts
libs/utils/src/lib/form/forms/static-value.form.ts

5410 fix avails filter

---

apps/catalog/catalog/src/app/landing/landing.component.scss
apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts

5410 improve avails

---

apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
apps/catalog/catalog/src/app/landing/landing.component.scss
apps/festival/festival/src/app/dashboard/title/list/list.component.ts
libs/invitation/src/lib/+state/invitation.service.ts
libs/utils/src/lib/apps.ts

Fix issue #5049 && to do in #5505

5505 5049 replace crm by first accessible app

---

libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.module.ts
libs/event/src/lib/components/doorbell/doorbell.module.ts
libs/movie/src/lib/movie/components/movie-imdb-search/movie-imdb-search.module.ts
libs/ui/src/lib/confirm/confirm.module.ts

entryComponents and ANALYZE_FOR_ENTRY_COMPONENTS no longer required
Previously, the entryComponents array in the NgModule definition was used to tell the compiler which components would be created and inserted dynamically. With Ivy, this isn't a requirement anymore and the entryComponents array can be removed from existing module declarations. The same applies to the ANALYZE_FOR_ENTRY_COMPONENTS injection token.

removed entry components

---

apps/backend-functions/src/internals/sentry.ts
apps/backend-functions/src/users.ts
libs/utils/src/lib/sentry.module.ts

- Errors in backend will now be catched by sentry but still logged in firebase functions log.
- Errors in frontend are still pushed to sentry if `sentryDsn` is enabled but if environment is not production, errors will still be logged into browser console for debugging

fix #5011 and #5384

---

apps/backend-functions/src/notification.ts
apps/backend-functions/src/orgs.ts
apps/backend-functions/src/templates/mail.ts
libs/notification/src/lib/+state/notification.store.ts

Some to do's on issue #5356
Cause here it's sent also for requests being accepted but we already have 3 mails related to requests, it's a bit too much

5356 notifications improvements

---

apps/backend-functions/src/notification.ts
apps/backend-functions/src/offer.ts
apps/backend-functions/src/templates/mail.ts
libs/notification/src/lib/+state/notification.firestore.ts
libs/notification/src/lib/+state/notification.store.ts
libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts
libs/user/src/lib/auth/forms/notifications-form/notifications.form.ts

Renamed the notification in order to make room for a notification which will be made in the future for which this is a more appropriate name.

5356 rename notification

---

apps/backend-functions/src/notification.ts
apps/backend-functions/src/orgs.ts
apps/backend-functions/src/templates/mail.ts
libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
libs/notification/src/lib/+state/notification.firestore.ts
libs/notification/src/lib/+state/notification.store.ts
libs/organization/src/lib/organization/+state/organization.service.ts

5356 notification improvements

---

apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts
apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
libs/contract/src/lib/bucket/form.ts

- text: "Search & Buy Rights"
- action: links to same movie page but avails tab
- start: MM/DD/YYYY
- end: MM/DD/YYYY
- text: "Rights added."
- time: 5 sec
- action: scroll down the page to the related expansion panels
- action text: 'Show 👇'

5811 User Feedback Avails

---

.circleci/config.yml
env/env.blockframes-demo-2.ts

This PR allow, when code is pushed to branch `upgrade/blockframes-XXXX` to perform an upgrade on the env `blockframes-XXXX`
To do so, firebase-adminsdk-2sn1n@blockframes-ci.iam.gserviceaccount.com must be allowed for the project `blockframes-XXXX`
Test in progress: https://app.circleci.com/pipelines/github/blockframes/blockframes/17865/workflows/da43e366-4f8b-4a57-9330-b12c6555bba7/jobs/28730

upgrade CI command

---

apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.scss
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
libs/contract/src/lib/term/components/detailed/detailed.component.ts

5811 UI Feedback Avails

---

apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.scss
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.scss
apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss
apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
apps/catalog/catalog/src/app/marketplace/title/view/view.module.ts
libs/contract/src/lib/avails/form/avails.form.ts

5924 Avail improvements

---

apps/rules/src/tests/firestore/invitation.spec.ts
firestore.rules

Accepting an invitation was not possible anymore because we reached the maximum number of operations allowed to verify a rule.
I updated the rules to make less operations
Also replaced docId by eventId because the notification interface was changed few months ago.

prevent to many operations trigger

---

libs/landing/src/lib/shell/shell.component.ts

Initialize the light theme for the landing page. If you use the dark theme and disconnect, the landing page will be in light theme anyway.
I don't think we can force completely users to use the light theme as it exists some extension to force browser in dark mode.
Related to #6064

Light theme for landing page

---

firestore.rules

Incomes data model was updated to remove `contractId` and instead use the contract id as the income id.
However the firestore rules have been updated to reflect this change.
This PR fix that.

fix rule datamodel

---

libs/firebase-utils/src/lib/firestoreMigrations/0064.ts
libs/user/src/lib/auth/forms/profile/profile.component.html
libs/user/src/lib/auth/forms/profile/profile.component.ts
libs/user/src/lib/auth/forms/profile/profile.module.ts
libs/user/src/lib/auth/guard/email-verified.guard.ts

6111 Verify email of old users

---

libs/ui/src/lib/marketplace/pages/wishlist/wishlist.component.html
libs/utils/src/lib/pipes/to-label.pipe.ts

Use case: 
```
{{ text | toLabel:'offerStatus' | titlecase }}
```
this would fails, because the output can be an array. by overloading you say that if the first param is a string, then the return value is a string.

overload toLabel

---

libs/contract/src/lib/avails/avails.ts
libs/contract/src/lib/avails/tests/territories.spec.ts

solve one item of #7347
Exclusivity wasn't handle the right way, so I updated it with the following truth tables:
|Avails➡<br/>Mandate⬇|Exclusive|Non-Exclusive|
|-|-|-|
|Exclusive|✅|✅|
|Non-Exclusive|❌|✅|
|Avails➡<br/>Sale⬇|Exclusive|Non-Exclusive|
|-|-|-|
|Exclusive|❌|❌|
|Non-Exclusive|❌|✅|
> The above tables where defined during a discussion with @cams-goussale & @Jackseed

Fix avail exclusivity check

---

apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts
libs/contract/src/lib/contract/+state/contract.service.ts

- set negotiationForm as pristine only once we've finished adding the negotiation.
- added lacking contractId during addition of new negotiation.

send contractId on addNegotiation

---

.circleci/config.yml

looks like gsutils transfer can take too long : 
```
Running command: gsutil -m -q rsync -d -r "gs://blockframes-ci-storage-backup/LATEST-ANON-STORAGE" "gs://blockframes-staging.appspot.com"
Too long with no output (exceeded 10m0s): context deadline exceeded
```

no_output_timeout for PFT

---

apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts

Fix #7644
`status$` wasn't triggered anymore after `availabilities$`

7644 Fix overlay not showing

---

libs/contract/src/lib/avails/avails.ts
libs/contract/src/lib/avails/fixtures/availsFilters.ts
libs/contract/src/lib/avails/fixtures/mandatesAndSales.ts
libs/contract/src/lib/avails/tests/avails-map.spec.ts

* Filter out terms of same mandate that don't match with current search.
* unit test mandates with multiple terms on same media for difference in available territories.
* refactor
* Refactor

hotfix map filter (#7881)

---

apps/festival/festival/src/app/marketplace/marketplace.component.html
apps/festival/festival/src/styles.scss
libs/media/src/lib/image/uploader/uploader.component.ts
libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts
libs/user/src/lib/auth/pages/profile/profile.component.ts

#7981
#7983
Impossible to remove the profil image alone, for remove it, I have to change another field too.
Might be : "Your screening request was successfully sent"

fixes for 7981 7983

---

apps/crm/crm/src/app/crm/pages/organization/organization.component.ts
libs/media/src/lib/file/explorer/explorer.component.scss
libs/media/src/lib/file/file-uploader/file-uploader.component.html
libs/media/src/lib/image/uploader/uploader.component.html
libs/organization/src/lib/organization/+state/organization.service.ts

fixes for 7981 and 7979

---

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
libs/contract/src/lib/avails/avails.ts

#7982
In the background I'm redirected to https://staging.archipelcontent.com/c/o/marketplace/selection but popin does not disappear and I have this error in console : 
```
TypeError: l is null
l https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
c https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
c https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
a https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
value https://staging.archipelcontent.com/polyfills.d8563f0a7951ef3c12a9.js:1
onInvoke https://staging.archipelcontent.com/main.e6dcec4c7ce508c5b805.js:1
```
Already described in https://github.com/blockframes/blockframes/issues/7830

7982 fix creating offer

---

libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.scss

Start from: https://github.com/blockframes/blockframes/issues/7896

Fix overlapping of main content and the cookie banner

---

apps/festival/festival/src/app/dashboard/home/home.component.html
apps/festival/festival/src/app/dashboard/home/home.component.scss
apps/festival/festival/src/app/dashboard/home/home.component.ts
apps/festival/festival/src/app/dashboard/home/home.module.ts
libs/movie/src/lib/movie/pipes/has-app-status.pipe.ts
libs/ui/src/lib/dashboard/pages/home/home.component.html
libs/ui/src/lib/dashboard/pages/home/home.component.scss
libs/ui/src/lib/dashboard/pages/home/home.component.ts
libs/ui/src/lib/dashboard/pages/home/home.module.ts

The states of dashboard where an organization doesn't have any (accepted) movie yet was accidentally removed. This PR adds it back.

7689 add back no titles ui for dashboard

---

libs/import/src/lib/utils.ts
libs/import/src/lib/view-extracted-elements/contract/utils.ts

For optional fields like `caption` , `dubbed` and `subtitle`, we set a default value of `[]` during term creation.

made languages optional in import template

---

apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts
apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts
apps/festival/festival/src/app/dashboard/home/home.component.html
apps/festival/festival/src/app/dashboard/home/home.component.ts
libs/analytics/src/lib/components/line-chart/line-chart.component.html
libs/analytics/src/lib/components/line-chart/line-chart.component.scss
libs/analytics/src/lib/components/line-chart/line-chart.component.ts
libs/analytics/src/lib/components/line-chart/line-chart.module.ts
libs/analytics/src/lib/components/map/map.component.html
libs/analytics/src/lib/components/map/map.component.scss
libs/analytics/src/lib/components/map/map.component.ts
libs/analytics/src/lib/components/map/map.module.ts
libs/analytics/src/lib/components/pie-chart/pie-chart.component.html
libs/analytics/src/lib/components/pie-chart/pie-chart.component.scss
libs/analytics/src/lib/components/pie-chart/pie-chart.component.ts
libs/analytics/src/lib/components/pie-chart/pie-chart.module.ts

#7834
title: `Split by Company Activity`
subtitle:` Learn who are the users who were interested in this Title.` 
title: `Split by Company Territory` 
subtitle: `Learn where are the interested people from.`
title: `Interactions`
subtitle: `Learn how people interact with your Title.`
title: `Film Page Views`
subtitle: `See how many Buyers viewed your Film Page recently.`

7834 sellers analytics remarks

---

libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.ts

When I'm connected as an anonymous user (for the Public Presentations, no account on Archipel Market) I can still "add" a title to wishlist...

8299 prevent add to wishlist for users without org

---

libs/event/src/lib/components/screening-item/screening-item.component.html
libs/movie/src/lib/movie/marketplace/shell/shell.component.scss

#8299
Proposed several solutions to Ana and hiding the scrollbar was her favorite. See proposals further down in this PR.
1. Same navigation as on the tabs (image 1 and 2) rather big change in UI and code
2. Keep it as it is but with an invisible scrollbar (image 3)
3. Keep it as it is but with a visible scrollbar (image 4)
4. As you suggested, hide the toolbar for small screen
Image 1:
Image 2:
Image 3:
Image 3:

8299 scroll app bar on small screen

---

apps/festival/festival/src/app/marketplace/title/list/list.component.html
libs/media/src/lib/video/viewer/viewer.component.scss
libs/movie/src/lib/movie/marketplace/shell/shell.component.html
libs/movie/src/lib/movie/marketplace/shell/shell.component.scss

#8299
https://user-images.githubusercontent.com/93206363/166881794-f1f1ac5d-3310-4cb9-af44-5253f97556b4.mp4

8299 fix video section and request screening

---

libs/ui/src/lib/confirm/confirm.component.scss

Add space of 36px between text and button like :

General UI - CrossApp Confirm Modals

---

libs/media/src/lib/image/uploader/uploader.component.ts

8299 fix component added in media list when unsupported file

---

libs/devops/src/lib/firebase-utils/firestore/emulator.ts

I had some problem with the emulator
On commands :
- `npm start emulators`
- `npm run backend-ops prepareEmulators gs://ci-backups-blockframes/LATEST-ANON-SHRINKED-DB`
When it tried to launch the command
```sh
npx firebase emulators:start --project blockframes-kevin-d --only auth,functions,firestore,pubsub --import G:\Mes Documents\blockframes\.firebase\emulator
```
The command crashed because of the path after `--import` who had space within (`Mes Documents`).
So, to resolve the problem, we add (with Bruce) two quotes, something like `--import '<path_here>'`
(Thanks windows paths)

Emulator - Fix import path with space

---

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
apps/festival/festival/src/app/dashboard/home/home.component.html
apps/festival/festival/src/app/dashboard/home/home.component.scss

Avoid showing NAN as result of division in percentage fields.
Fixed https://github.com/blockframes/blockframes/issues/8512#issuecomment-1134610130 : missing `View all buyers' activies` button on dashboard.

avoid diving 0 by zero and missing buyers page button

---

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html
apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts
apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.html
apps/festival/festival/src/app/dashboard/home/home.component.html
apps/festival/festival/src/app/dashboard/home/home.component.ts

#8512
If this isn't possible then we shouldn't put this title for the table because it's misleading `Buyer was interested in these titles`

8512 Page view in tables and more

---

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts
libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.html
libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.scss

8512 top 5 in bar chart and cursor on metric card

---

apps/festival/festival/src/app/dashboard/home/home.component.html
libs/contract/src/lib/bucket/service.ts

* called `document.exists()` and not `document.exist`
* Renamed from `TOP 5 COUNTRIES` to `TOP COUNTRIES`.

top countries

---

apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts
apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts
apps/festival/festival/src/app/dashboard/home/home.component.ts

Fixed: #8644
Ignore seller analytics on following pages:
1. Festival Dashboard `c/o/dashboard/home`
2. title list `/c/o/dashboard/home/title`
3. title analytics `/c/o/dashboard/home/title/{titleId}`
4. buyer list `/c/o/dashboard/home/buyer`

feat: ignore competitor analytics when showing title/buyer analytics

---

apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts
libs/organization/src/lib/organization/service.ts

fix #8702
To reproduce the bug consistently I went to
1. /c/o/dashboard/title
2. Navigate to Dashboard
3. Click on "View all Buyers' Activitites"
On /c/o/dashboard/title, all the titles of the sellers org are queried. When going to the Buyers Activities page, it triggers the observables twice. First is for the sellers' org, and then again with more data. This is a bug that has been seen on CRM before.
However, this time, the `orgService.valueChanges(orgIds)` kept triggering infinitely (and thus the pie chart kept trying to re-render). Turning of memorization helped, or changing valueChangess to getValue also helped.
This is likely a bug in ngfire lib 
Might be caused by the same bug as https://github.com/blockframes/blockframes/issues/8509

8702 fix loading pie chart

---

apps/backend-functions/src/media.ts

fix #8681
I checked the db and no orgs have video file saved as map instead of in an array at the moment. So I didn't create a migration. Although, it could happen in the upcoming time because it happens when an org doesn't have `videos` in `documents.videos` yet (empty array).

8681 fix video saved as map instead of array

---

apps/crm/crm/src/app/crm/pages/users/users.component.ts

ERROR: firebase/firestore: Firestore (9.6.10): Using maximum backoff delay to prevent overloading the backend.
This is because Firestore doesn't like it if the same doc is queried multiple times at once.
In the code, we iterated over 4000 users and queried their permissions document. There is one permissions document per organization, and since users share the same organization, the same doc was queried many times at once.

Fix user export

---

libs/contract/src/lib/avails/sets.ts
libs/contract/src/lib/avails/tests/sets.spec.ts

Fixed: #8670
All the other non exported set methods like `discreteAllOf`, `continuousAllOf`, `discreteNoneOf` are helper functions to other tested methods like `allOf` for example, so I guess they're indirectly tested as well.

unit tested set functions.

---

apps/crm/crm/src/app/crm/pages/users/users.component.ts

Original: https://github.com/blockframes/blockframes/pull/8820
ERROR: firebase/firestore: Firestore (9.6.10): Using maximum backoff delay to prevent overloading the backend.
This is because Firestore doesn't like it if the same doc is queried multiple times at once.
In the code, we iterated over 4000 users and queried their permissions document. There is one permissions document per organization, and since users share the same organization, the same doc was queried many times at once.

Fix user export hotfix

---

apps/crm/crm/src/app/crm/pages/movies/movies.component.html
apps/crm/crm/src/app/crm/pages/movies/movies.component.scss
apps/crm/crm/src/app/crm/pages/movies/movies.component.ts
apps/crm/crm/src/app/crm/pages/users/users.component.html
apps/crm/crm/src/app/crm/pages/users/users.component.scss
apps/crm/crm/src/app/crm/pages/users/users.component.ts

8834 export analytics

---

apps/catalog/catalog-e2e/src/integration/dashboard/deal-seller-negotiatiation.spec.ts
apps/crm/crm-e2e/src/fixtures/create-org.ts

quickfixes

---

package-lock.json
package.json

In version 11.22.0 I could not use the filters in the UI at http://localhost:4000/firestore/data
The last 11 version (11.30.0) works fine :

firebase-tools update

---

libs/utils/src/lib/error-logger.module.ts

error should be displayed to console even if snackbar is already open

error should be displayed to console even if snackbar is already open
