blockframes/blockframes

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- libs/ui/src/lib/assets/icons/refresh-filters.svg
- libs/ui/src/lib/icon-service.ts
Fix to do for issue #3412 
Changed icon for clearing filters
> Changed icon for clearing filters

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel-routing.module.ts
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.scss
- libs/movie/src/lib/movie/pages/promotional-elements/media-images/media-images.component.html
- libs/movie/src/lib/movie/pages/promotional-elements/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/pages/promotional-elements/media-videos/media-videos.component.scss
- libs/movie/src/lib/movie/pages/promotional-elements/media-videos/media-videos.component.ts
- libs/movie/src/lib/movie/pages/promotional-elements/media-videos/media-videos.module.ts
- libs/movie/src/lib/movie/pages/shell/shell.component.ts
> Videos page and fixes

- apps/festival/festival/src/app/dashboard/home/home.component.html
- apps/festival/festival/src/app/dashboard/home/home.component.ts
- apps/festival/festival/src/app/dashboard/home/home.module.ts
- libs/movie/src/lib/movie/components/festival-prize-card/festival-prize-card.component.html
- libs/movie/src/lib/movie/components/festival-prize-card/festival-prize-card.component.scss
- libs/movie/src/lib/movie/components/festival-prize-card/festival-prize-card.component.ts
- libs/movie/src/lib/movie/components/festival-prize-card/festival-prize-card.module.ts
> Issue 2364

- apps/backend-ops/src/main.ts
- apps/backend-ops/src/users.ts
- added generate fixtures script in users.ts
- added command to run it in main.ts
To run/test: `npx ts-node -P tools/tsconfig.tools.json apps/backend-ops/src/main.ts generateUserFixtures`
> feat(generateUserFixtures): add feature to users.ts in backend-ops

- libs/movie/src/lib/movie/form/budget/budget.component.html
- libs/movie/src/lib/movie/form/budget/budget.component.scss
- libs/movie/src/lib/movie/form/budget/budget.component.ts
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.ts
- libs/movie/src/lib/movie/pages/additional-information/additional-information.module.ts
- libs/movie/src/lib/movie/pages/artistic/artistic.component.html
- libs/movie/src/lib/movie/pages/artistic/artistic.module.ts
- libs/movie/src/lib/movie/pages/reviews/reviews.component.html
- libs/movie/src/lib/movie/pages/reviews/reviews.module.ts
> Issue cleanup 3

- apps/catalog/catalog/src/app/marketplace/wishlist/wishlist.component.ts
- apps/festival/festival/src/app/marketplace/wishlist/wishlist.component.ts
- libs/organization/src/lib/cart/+state/cart.query.ts
- libs/ui/src/lib/layout/marketplace/marketplace.component.ts
Fix wishlist to do's in issue #3412
> Filter out undefined movies and improved wishlist query

- libs/invitation/src/lib/components/item/item.component.ts
> Fix url if case invitation is toOrg

- libs/media/src/lib/components/upload/file-upload/file-upload.component.ts
> Fix file status for drag n drop

- libs/ui/src/lib/layout/footer/footer.component.html
- libs/ui/src/lib/static-informations/contact/contact.module.ts
To do in issue #3412 
"Remove (or debug) "Contact us" from the footer and please warn the person who implemented it that it doesn't work (it's always removed then added again, then..)"
Fixed bug
> Fix contact page

- libs/movie/src/lib/movie/pages/summary/summary.component.html
- libs/movie/src/lib/movie/pages/summary/summary.component.scss
- libs/movie/src/lib/movie/pages/summary/summary.component.ts
Adding the warning showing to the top of the page.
> App summary page design completion

- libs/movie/src/lib/movie/pages/main/main.component.html
- libs/movie/src/lib/movie/pages/shell/shell.component.ts
- libs/movie/src/lib/movie/pages/summary/summary.component.html
- libs/movie/src/lib/movie/pages/summary/summary.component.ts
> More changes to the summary page

- apps/festival/festival/src/app/marketplace/organization/member/member.component.html
> titlecase org address

- libs/ui/src/lib/form/table/form-table.component.ts
> No longer data is being shown there but just an empty element.

- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
- libs/organization/src/lib/organization/pages/member/member.component.ts
- libs/organization/src/lib/permissions/+state/permissions.query.ts
- libs/organization/src/lib/permissions/+state/permissions.service.ts
> Fix wrong orgId used when updating user

- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.scss
- libs/movie/src/lib/movie/pages/artistic/artistic.component.scss
- libs/movie/src/lib/movie/pages/available-materials/available-materials.component.html
- libs/movie/src/lib/movie/pages/available-materials/available-materials.component.scss
- libs/movie/src/lib/movie/pages/main/main.component.scss
- libs/movie/src/lib/movie/pages/production/production.component.html
- libs/movie/src/lib/movie/pages/production/production.component.scss
- libs/movie/src/lib/movie/pages/promotional-elements/media-images/media-images.component.html
- libs/movie/src/lib/movie/pages/promotional-elements/media-images/media-images.component.scss
- libs/movie/src/lib/movie/pages/promotional-elements/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/pages/reviews/reviews.component.html
- libs/movie/src/lib/movie/pages/reviews/reviews.component.scss
- libs/movie/src/lib/movie/pages/summary/summary.component.html
- libs/movie/src/lib/movie/pages/summary/summary.component.scss
- libs/movie/src/lib/movie/pages/summary/summary.component.ts
- libs/movie/src/lib/movie/pages/summary/summary.module.ts
- libs/movie/src/lib/movie/pages/synopsis/synopsis.component.scss
- libs/movie/src/lib/movie/pages/technical-info/technical-info.component.html
- libs/movie/src/lib/movie/pages/technical-info/technical-info.component.scss
- libs/movie/src/lib/movie/pages/title-status/title-status.component.scss
- libs/ui/src/lib/form/table/form-table.component.html
- libs/ui/src/lib/tunnel/layout/nav/nav.component.scss
- styles/components/mat-button.scss
- styles/components/mat-list.scss
Review the tunnel, fix little bug and display correctly some informations, css also
> Review tunnel

- libs/media/src/lib/directives/image-reference/image-reference.directive.ts
Fix for error on sentry: https://sentry.io/organizations/cascade-8/issues/1850806475/?project=1540126&referrer=slack
> Fix image ref being undefined

- libs/movie/src/lib/movie/pages/summary/main/main.component.html
- libs/movie/src/lib/movie/pages/summary/summary.component.html
- libs/movie/src/lib/movie/pages/summary/summary.component.ts
- libs/ui/src/lib/missing-control/missing-control.component.html
- libs/ui/src/lib/missing-control/missing-control.component.ts
Used the time today to work on the recursive function, but I'm not accomplishing the expected behavior.
I'm pushing some changes I did while working on the function.
> Updated some variables and methods inside summary-page

- libs/import/src/lib/components/view-extracted-elements/organizations/view-extracted-organizations.component.ts
Fix first to do in issue #3592
> Organization email no longer required

- apps/backend-ops/src/generate-fixtures.ts
Needed names in user fixtures for tests. Update the generate-fixture scripts.
> Update(gen-fixtures): Added required fields to User Fixtures.

- apps/backend-ops/src/firebaseSetup.ts
- package.json
- add convenience command `npm run backend-ops`
- add generateFixtures to prepareForTesting
> build(package.json): add command for backend-ops

- libs/admin/src/lib/admin-panel/pages/movies/movies.component.html
- libs/admin/src/lib/admin-panel/pages/movies/movies.component.ts
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.html
- libs/admin/src/lib/admin-panel/pages/users/users.component.html
- libs/admin/src/lib/admin-panel/pages/users/users.component.ts
to do in issue #3592 
"pages take a lot of time to load, would be great to optimize that. If that means reducing the nb of info on 1 page, than I think a good number would be 50 per page by default (and then we can change if need be)"
> Improved performance for CRM overview

- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/internals/email.ts
- apps/backend-functions/src/internals/invitations/events.ts
- libs/admin/src/lib/admin-panel/pages/event/event.component.html
- libs/invitation/src/lib/form/user/user.component.ts
- libs/utils/src/lib/apps.ts
to do in issue #3592 
"event invitation through CRM : should come from the org organizing the screening, not the org of the connected blockframesAdmin"
> Send event invitation email from org contact email

- apps/festival/festival/src/app/dashboard/home/home.component.html
- libs/event/src/lib/+state/event.service.ts
- libs/media/src/lib/components/cropper/cropper.component.ts
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.scss
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.ts
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.module.ts
- libs/movie/src/lib/movie/layout/view/view.component.html
- libs/movie/src/lib/movie/layout/view/view.component.ts
- libs/movie/src/lib/movie/layout/view/view.module.ts
- libs/movie/src/lib/movie/pages/promotional-elements/media-images/media-images.component.html
- libs/organization/src/lib/organization/+state/organization.service.ts
not sure about the image reference directive. If I do ref on the img tag, the pictures won't load
> Issue movie view layout

- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
To do in issue #3592 
"Move user from one org to another without invitation"
Notifications are still on since they can't be disabled
> Added ability to update organization id

- apps/backend-functions/src/users.ts
- libs/admin/src/lib/admin-panel/admin-panel.module.ts
- libs/admin/src/lib/admin-panel/pages/user/user.component.html
- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
To do in issue #3592 
"we need to add a delete button (+ confirmation dialog) on users. The delete should delete the user and all corresponding entry in the db (id in org userIds, invitations, notifications,...)"
> Added ability to remove user from CRM

- apps/festival/festival/src/app/dashboard/title/view/view.component.html
- apps/festival/festival/src/app/dashboard/title/view/view.component.scss
- apps/festival/festival/src/app/dashboard/title/view/view.component.ts
- apps/festival/festival/src/app/dashboard/title/view/view.module.ts
- libs/movie/src/lib/movie/dashboard/components/view/main/main.component.html
- libs/movie/src/lib/movie/dashboard/components/view/main/main.component.scss
- libs/movie/src/lib/movie/dashboard/components/view/main/main.component.ts
- libs/movie/src/lib/movie/dashboard/components/view/main/main.module.ts
- libs/movie/src/lib/movie/form/summary/main/main.component.scss
- libs/utils/src/lib/pipes/get-path.pipe.ts
Dashboard movie view component in the movie lib
> Dashboard view in movie lib

- apps/backend-functions/src/orgs.ts
- apps/financiers/financiers/src/app/app.module.ts
- apps/financiers/financiers/src/environments/environment.ci.ts
- apps/financiers/financiers/src/environments/environment.prod.ts
- apps/financiers/financiers/src/environments/environment.staging.ts
- apps/financiers/financiers/src/environments/environment.ts
- firebase.json
- libs/utils/src/lib/apps.ts
- libs/utils/src/lib/pipes/workspace.pipe.ts
Make sure `appAccess` do not break apps each time we add a new one.
> Set appAccess optional chaining

- libs/admin/src/lib/admin-panel/admin-panel.module.ts
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.html
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.scss
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.ts
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.html
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.scss
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.ts
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.module.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.scss
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.module.ts
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.html
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.ts
- libs/media/src/lib/+state/media.model.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
To do in issue #3592 - Create org manually
> Create org on CRM

- apps/backend-ops/src/admin.ts
- apps/backend-ops/src/firebaseSetup.ts
- apps/backend-ops/src/generate-fixtures.ts
- apps/backend-ops/src/main.ts
- apps/backend-ops/src/tools.ts
- apps/backend-ops/src/users.ts
- libs/firebase-utils/src/lib/util.ts
- libs/firebase-utils/src/lib/watermark.ts
- libs/testing/src/lib/firebase/auth.ts
- tools/static-users.json
- a new fixture is generated - static-users.json
- to determine which users to fetch, we read tools/static-users.json
- a few small bug fixes
- we have additional shorter commands for devs, "prepareStorage" "prepareDb" "syncUsers"
> George/prepare for testing - static users and more commands

- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
To do on issue #3674 
Movie titles page loading infinitely
> fix filterForm not triggering initially

- libs/media/src/lib/components/cropper/cropper.component.ts
- libs/media/src/lib/form/media.form.ts
"When I hover an already uploaded image with another image, it deletes the previous one"
> Fix wrong state on leave hover

- libs/invitation/src/lib/invitation.component.ts
"Accept all butons turns all invitations to accepted, even the declined one, it should only affect the pending ones"
> Filter out non-pending invitations

- apps/backend-functions/src/player.ts
- apps/backend-functions/src/users.ts
- libs/event/src/lib/components/player/player.component.ts
- libs/firebase-utils/src/lib/watermark.ts
When a user ask for the screening url, in the backend, we check if he has a watermark, and if not we generate it to prevent error on the screening.
> [DO NOT MERGE] watermark fallback

- README.md
- apps/backend-functions/src/player.ts
- apps/backend-functions/src/users.ts
- libs/event/src/lib/components/player/player.component.ts
- libs/firebase-utils/src/lib/watermark.ts
- package-lock.json
- package.json
> From hotfix watermark to master

- apps/backend-ops/src/firestoreMigrations/0036.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
- apps/catalog/catalog/src/app/marketplace/home/home.component.ts
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- apps/financiers/financiers/src/app/marketplace/home/home.component.ts
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/dashboard/main/main.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- libs/movie/src/lib/movie/form/artistic/artistic.component.html
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/reviews/reviews.component.html
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/movie/src/lib/movie/form/summary/review/review.component.html
- libs/movie/src/lib/movie/form/title-status/title-status.component.ts
- libs/utils/src/lib/static-model/staticConsts.ts
Correct some typo on movie and distribution right collection.
Also move every prizes into the new customPrizes field because of the introduction of the new static about festival prizes.
> Typo + prizes

- libs/organization/src/lib/organization/components/card/card.component.html
"There is a glitch when you click on the movie icon on the org card"
> Removed lazy loading for tab

- apps/backend-functions/src/player.ts
- watermark fix on develop #3650 
- watermark fix on master #3734
- watermark fix on production #3732
> await for delete

- apps/backend-functions/src/player.ts
- apps/backend-functions/src/users.ts
- libs/event/src/lib/components/player/player.component.ts
- libs/firebase-utils/src/lib/watermark.ts
- watermark fix on develop #3650
- ~watermark fix on master #3734~
- ~watermark fix on production #3732~
> watermark fallback

- apps/catalog/catalog-e2e/src/integration/landing/organization-creation.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalDashboardHomePage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalInvitationsPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceHomePage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalOrganizationListPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
Make Catalog e2e work and other tests more reliable.
> Update(e2e): Make Catalog test pass and Festival more reliable.

- libs/invitation/src/lib/+state/invitation.service.spec.ts
- libs/invitation/src/test-setup.ts
> Invitation unit test

- libs/e2e/src/lib/pages/auth/AuthLoginPage.ts
- libs/e2e/src/lib/pages/organization/OrganizationHomePage.ts
- libs/e2e/src/lib/utils/env.ts
Greenlight account-creation.spec.ts
Created a new env constant file to handle app wide timeout changes. This will help in quickly fixing test cases.
> Update(e2e): Greenlight Catalog account creation.

- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceOrganizationTitlePage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalOrganizationListPage.ts
- libs/e2e/src/lib/utils/env.ts
Fixes Timeout issue seen in https://e2e.blockframes.io//result/21115
> Festival e2e timeout issue

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.module.ts
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/+state/event.model.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/components/meeting/media-list/media-list.component.html
- libs/event/src/lib/components/meeting/media-list/media-list.component.scss
- libs/event/src/lib/components/meeting/media-list/media-list.component.ts
- libs/event/src/lib/components/meeting/media-list/media-list.module.ts
- libs/event/src/lib/form/event.form.ts
- styles/components/mat-button.scss
> meeting file list

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.routes.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.scss
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.ts
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.module.ts
- libs/ui/src/lib/form/list/form-list.component.html
- libs/utils/src/lib/helpers.ts
- libs/utils/src/lib/static-model/staticConsts.ts
- libs/utils/src/lib/static-model/types.ts
New page : shooting information
> New form pages

- apps/catalog/catalog/src/app/dashboard/tunnel/movie-tunnel.routes.ts
- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.routes.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/promotional-elements/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/promotional-elements/sales-pitch/sales-pitch.component.scss
- libs/movie/src/lib/movie/form/promotional-elements/sales-pitch/sales-pitch.component.ts
- libs/movie/src/lib/movie/form/promotional-elements/sales-pitch/sales-pitch.module.ts
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/utils/src/lib/static-model/staticConsts.ts
- libs/utils/src/lib/static-model/types.ts
> New sales pitch page

- apps/backend-ops/src/algolia.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- libs/event/src/lib/layout/edit/edit.component.html
- libs/invitation/src/lib/form/user/user.component.html
- libs/invitation/src/lib/form/user/user.component.ts
- libs/invitation/src/lib/form/user/user.module.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
- libs/utils/src/lib/pipes/deep-key.pipe.ts
We shouldn't be able to send an invitation to someone who was already invited.
> Filter out already invited emails

- apps/backend-functions/src/invitation.ts
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/invitation/src/lib/form/user/user.component.html
- libs/invitation/src/lib/form/user/user.component.scss
- libs/invitation/src/lib/form/user/user.component.ts
- styles/components/mat-button.scss
> Limit meeting

- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
Using filter on marketplace/title page added the movies to the list of movies instead of replacing them. Now only when more data is loaded, the movies are added to the list.
Also, most likely some code disappearing during a merge, the chips-autocomplete component didn't make the form dirty anymore.
> Fix movie titles page

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-ops/src/firestoreMigrations/0037.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
- apps/catalog/catalog/src/app/app.module.ts
- apps/financiers/financiers/src/app/app.module.ts
- apps/financiers/financiers/src/app/dashboard/dashboard.component.scss
- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/financial-details/financial-details.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/financial-details/financial-details.component.scss
- apps/financiers/financiers/src/app/dashboard/tunnel/financial-details/financial-details.component.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/financial-details/financial-details.module.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/movie-tunnel.routes.ts
- apps/financiers/financiers/src/app/marketplace/marketplace.component.scss
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
- libs/movie/src/lib/movie/form/summary/main/main.component.html
Financial details page on movie form only for Media Financiers
> Financial page

- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.module.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0037.ts
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.scss
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.ts
- libs/movie/src/lib/movie/form/summary/shooting-information/shooting-information.component.html
- libs/movie/src/lib/movie/form/summary/shooting-information/shooting-information.component.scss
- libs/movie/src/lib/movie/form/summary/shooting-information/shooting-information.component.ts
- libs/movie/src/lib/movie/form/summary/summary.module.ts
New shooting information summary component
New sales pitch summary component
> Summary components

- apps/catalog/catalog-e2e/src/integration/dashboard/contract-tunnel.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelContractLobby.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelContractPage.ts
- libs/e2e/src/lib/pages/auth/AuthLoginPage.ts
Skipping the tests for now. 
UI needs to be updated and tests will have to be rewritten again.
> Update(e2e): Due to change in design expected, skip tests for now.

- apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html
- apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.module.ts
- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html
- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.module.ts
- apps/financiers/financiers/src/app/dashboard/title/financial-details/financial-details.component.html
- apps/financiers/financiers/src/app/dashboard/title/financial-details/financial-details.component.scss
- apps/financiers/financiers/src/app/dashboard/title/financial-details/financial-details.component.ts
- apps/financiers/financiers/src/app/dashboard/title/financial-details/financial-details.module.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.module.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/financial-details/financial-details.component.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/financial-details/financial-details.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/financial-details/financial-details.component.scss
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/financial-details/financial-details.component.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/financial-details/financial-details.module.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.module.ts
- libs/movie/src/lib/movie/dashboard/main/main.component.html
- libs/movie/src/lib/movie/pipes/budget.pipe.ts
Add the new section to the dashboard view for every app
> Dashboard view

- libs/organization/src/lib/organization/components/member-add/member-add.component.html
- libs/organization/src/lib/organization/components/member-add/member-add.component.scss
- libs/organization/src/lib/organization/components/member-add/member-add.component.ts
- libs/organization/src/lib/organization/components/member-add/member-add.module.ts
- libs/organization/src/lib/organization/forms/member.form.ts
- libs/ui/src/lib/form/list/form-list.component.scss
- libs/ui/src/lib/form/list/form-list.component.ts
- libs/utils/src/lib/form/forms/list.form.ts
It wasn't possible to invite a member to an organization anymore. Old code is also refactoring to use the new bf-form-list component instead.
> Fix invite members for organization

- libs/user/src/lib/auth/+state/auth.service.ts
- libs/user/src/lib/auth/pages/identity/identity.component.ts
- libs/user/src/lib/auth/pages/login/login.component.ts
- libs/user/src/lib/user/+state/user.firestore.ts
To do in issue #2403 
"Register IP address and date when user accept policy privacy"
> Save date and ip of user accepting privacy policy

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.module.ts
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
Update form and summary component to match new design on sales pitch page
> Audience & goals changes

- apps/catalog/catalog/src/app/marketplace/title/finance/finance.component.html
- apps/catalog/catalog/src/app/marketplace/title/finance/finance.module.ts
- apps/financiers/financiers/src/app/marketplace/title/finance/finance.component.html
- apps/financiers/financiers/src/app/marketplace/title/finance/finance.module.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0038.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.scss
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.scss
- libs/utils/src/lib/static-model/staticConsts.ts
> Box Office

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/production/production.component.html
- libs/movie/src/lib/movie/form/reviews/reviews.component.html
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
Fix the bug the year of shooting date was invalid at the submission of the form
> Year Validator

- libs/media/src/lib/components/upload/file-upload/file-upload.component.ts
> fix file estimate

- apps/catalog/catalog/src/app/app.component.ts
- apps/catalog/catalog/src/app/app.module.ts
- apps/crm/crm/src/app/app.module.ts
- apps/festival/festival/src/app/app.module.ts
- apps/financiers/financiers/src/app/app.component.ts
- apps/financiers/financiers/src/app/app.module.ts
Added cookie consent to all applications
> Cookie form

- libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts
Booting app failed sometimes. This fixes the bug.
> Fix inconsistency

- libs/invitation/src/lib/components/guest-item/guest-item.component.html
- libs/media/src/lib/directives/image-reference/image-reference.directive.ts
weird bugs, weird fixes
fixes:
> weird bugs, weird fixes

- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
"Search bar on marketplace is not filtering movies"
> Fix search on titles page

- libs/invitation/src/lib/form/user/user.component.html
- libs/utils/src/lib/pipes/deep-key.pipe.ts
Fix for algolia autocomplete filter. For invitations, the email can be on fromUser and toUser object on the invitation doc.
> Pass in multiple deepKeys

- apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/landing/LandingPage.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.html
Accept cookies to enable all  DOM access.
> Update(e2e): Accept cookies to allow test to work.

- apps/festival/festival/src/app/dashboard/title/list/list.component.html
- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- apps/festival/festival/src/app/dashboard/title/list/list.module.ts
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.ts
- apps/financiers/financiers/src/app/dashboard/title/list/list.module.ts
- libs/movie/src/lib/movie/pipes/analytics.pipe.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.html
- libs/utils/src/lib/pipes/deep-key.pipe.ts
- libs/utils/src/lib/pipes/max-length.pipe.ts
fix deep key pipe
update dashboard title list on festival
update dashboard title list on financiers
use mat-button instead of mat-stroked-button
> Fix dashboard title list

- apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/landing/LandingPage.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.ts
- libs/movie/src/lib/movie/marketplace/production/production.component.html
- libs/movie/src/lib/movie/pipes/shooting.pipe.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.html
Change cities of shooting locations
> Utils financiers

- apps/backend-functions/src/contract.ts
- apps/backend-functions/src/internals/firebase.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/media.ts
- apps/backend-functions/src/movie.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/permissions.ts
- apps/backend-functions/src/player.ts
- apps/catalog/catalog/src/app/app.module.ts
- apps/crm/crm/src/app/app.module.ts
- apps/festival/festival/src/app/app.module.ts
- apps/financiers/financiers/src/app/app.module.ts
- identify correct string for best function location
- create additional resource locations in one line
- update type imports in files that rely on `functions`
> build(backend-functions): create eu-based function resource locations

- libs/movie/src/lib/movie/form/summary/shooting-information/shooting-information.component.html
Update dashboard and summary view
> Cities view

- .circleci/config.yml
- docker image temporarily updated until we get the blockframes org access
> update docker image used in CI

- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- libs/movie/src/lib/movie/form/reviews/reviews.component.html
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
- libs/movie/src/lib/movie/form/summary/review/review.component.html
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/movie/src/lib/movie/marketplace/main/main.module.ts
- libs/ui/src/lib/missing-control/missing-control.component.html
- libs/utils/src/lib/pipes/duration.pipe.ts
> fixed some release issues

- apps/festival/festival/src/app/dashboard/event/list/list.component.ts
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.ts
- libs/event/src/lib/components/week/week.component.ts
- libs/organization/src/lib/organization/pages/view/view.component.ts
- libs/organization/src/lib/organization/pages/view/view.module.ts
- libs/user/src/lib/auth/components/widget/widget.component.html
> remove meetings

- apps/catalog/catalog/src/app/dashboard/title/view/view.component.ts
- apps/catalog/catalog/src/app/dashboard/title/view/view.module.ts
- apps/festival/festival/src/app/dashboard/title/view/view.component.ts
- apps/festival/festival/src/app/dashboard/title/view/view.module.ts
- libs/movie/src/lib/movie/dashboard/additional/additional.component.html
- libs/movie/src/lib/movie/dashboard/additional/additional.component.scss
- libs/movie/src/lib/movie/dashboard/additional/additional.component.ts
- libs/movie/src/lib/movie/dashboard/additional/additional.module.ts
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.scss
Additional tab for dashboard view
> Additional Tab For Release

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
> comment meeting page

- apps/festival/festival/src/app/marketplace/home/home.component.ts
- libs/organization/src/lib/organization/components/card/card.component.html
"In the "In production" section, add also the movies with productionStatus "post_production" (on top of "shooting""
> Add post_production to in production carousel

- libs/invitation/src/lib/components/action/action.component.html
> Revert text for private event

- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/marketplace/additional/additional.component.html
- libs/movie/src/lib/movie/marketplace/additional/additional.component.scss
- libs/movie/src/lib/movie/marketplace/additional/additional.component.ts
- libs/movie/src/lib/movie/marketplace/additional/additional.module.ts
Additional Tab for marketplace reworked
> additional tab for marketplace reworked

- libs/media/src/lib/components/viewers/media-viewer.component.html
- libs/media/src/lib/components/viewers/media-viewer.module.ts
- libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.html
- libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.scss
- libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.ts
- libs/media/src/lib/directives/image-reference/imgix-helpers.ts
> pdf viewer

- libs/admin/src/lib/admin-panel/components/edit-party/edit-party.component.ts
- libs/admin/src/lib/admin-panel/pages/contract/contract.component.html
- libs/contract/src/lib/contract/+state/contract.firestore.ts
- libs/contract/src/lib/contract/+state/contract.model.ts
- libs/contract/src/lib/contract/form/party/party.component.ts
- libs/firebase-utils/src/lib/firestoreMigrations/old-types.ts
- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/movie/src/lib/movie/components/promotional-links/promotional-links.pipe.ts
- libs/utils/src/lib/common-interfaces/identity.ts
- libs/utils/src/lib/static-model/staticConsts.ts
- libs/utils/src/lib/static-model/staticModels.ts
- libs/utils/src/lib/static-model/types.ts
- Legal Document
- Promotional Elements Types
- Resource ratios (move into old type file)
- Resource Sizes (move into old type file)
- Stakeholder Roles
- Legal Roles
- Sub Licensor Role
> Statics data

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.scss
- libs/event/src/lib/components/player/player.component.ts
- libs/media/src/lib/components/viewers/media-viewer.component.html
- libs/media/src/lib/components/viewers/media-viewer.module.ts
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.html
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.scss
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.ts
- libs/utils/src/lib/utils.ts
> video viewer

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/title/list/list.component.html
- libs/movie/src/lib/distribution-rights/components/avails-filter/avails-filter.component.html
- libs/movie/src/lib/distribution-rights/form/territory/territory.component.html
- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.html
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/production/production.component.html
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.html
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.module.ts
- libs/utils/src/lib/pipes/to-label.pipe.ts
- libs/utils/src/lib/pipes/translate-slug.pipe.ts
Fix chips autocomplete component with constant
> chips autocomplete

- libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.html
- libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.scss
- libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.ts
- libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.module.ts
- libs/user/src/lib/auth/pages/profile-view/profile-view.component.html
- libs/user/src/lib/auth/pages/profile-view/profile-view.component.scss
- libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts
- libs/user/src/lib/auth/pages/profile-view/profile-view.module.ts
- libs/user/src/lib/auth/pages/profile/profile.component.html
- libs/user/src/lib/auth/pages/profile/profile.component.scss
- libs/user/src/lib/auth/pages/profile/profile.component.ts
- libs/user/src/lib/auth/pages/profile/profile.module.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.module.ts
- libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.html
- libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.scss
- libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.ts
- libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.module.ts
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.module.ts
- libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts
To do issue #3935
https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview
> Add cookie settings to profile page

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/marketplace/organization/meeting/meeting.component.html
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/+state/event.model.ts
- libs/event/src/lib/form/create/create.component.ts
- libs/event/src/lib/form/event.form.ts
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.ts
> Remove video call link and always fill organization

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.module.ts
- libs/organization/campaign/src/lib/dashboard/dashboard.component.html
- libs/organization/campaign/src/lib/dashboard/dashboard.component.scss
- libs/organization/campaign/src/lib/dashboard/dashboard.component.ts
- libs/organization/campaign/src/lib/dashboard/dashboard.module.ts
- libs/organization/campaign/src/lib/form/form.ts
- libs/organization/campaign/src/lib/form/perks/perks.component.html
- libs/organization/campaign/src/lib/form/perks/perks.component.ts
- libs/organization/campaign/src/lib/form/perks/perks.module.ts
- libs/organization/campaign/src/lib/form/proposal/proposal.component.html
- libs/organization/campaign/src/lib/form/proposal/proposal.component.ts
- libs/organization/campaign/src/lib/form/summary/perks/perks.component.html
- libs/organization/campaign/src/lib/form/summary/perks/perks.component.scss
- libs/organization/campaign/src/lib/form/summary/perks/perks.component.ts
- libs/organization/campaign/src/lib/form/summary/proposal/proposal.component.ts
- libs/ui/src/lib/missing-control/missing-control.component.ts
- libs/utils/src/lib/form/forms/entity.form.ts
- libs/utils/src/lib/form/matchers.ts
- libs/utils/src/lib/pipes/form.pipe.ts
- libs/utils/src/lib/pipes/index.ts
Create dashboard page for campaign
Add cross validation on campaign form
Small fixes
> Add dashboard & validators

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.scss
- libs/event/src/lib/components/meeting/media-list/media-list.component.html
- libs/media/src/lib/components/viewers/media-viewer.component.html
- libs/media/src/lib/components/viewers/media-viewer.component.scss
- libs/media/src/lib/components/viewers/media-viewer.module.ts
- libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.html
- libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.scss
- libs/media/src/lib/components/viewers/pdf-viewer/pdf-viewer.component.ts
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.html
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.scss
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.ts
- libs/ui/src/lib/assets/icons/fullscreen.svg
- libs/ui/src/lib/assets/icons/fullscreen_exit.svg
- libs/ui/src/lib/icon-service.ts
- styles/components/mat-icon.scss
> pdf & video fullscreen & meeting css improvement

- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/movie/components/title-filter/title-filter.component.html
- libs/movie/src/lib/movie/components/title-filter/title-filter.component.ts
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts
Production filter with color and checkbox are now cleared also when the form is cleared
> Production filter

- apps/financiers/financiers/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts
- libs/utils/src/lib/form/forms/list.form.ts
> Issue list campaigne

- libs/media/src/lib/+state/media.service.spec.ts
- libs/media/src/lib/+state/media.service.ts
- libs/media/src/lib/directives/image-reference/imgix-helpers.ts
Added unit test for media service 
Closing the earlier PR #3128
`npx jest media.service.spec.ts`
> UT: Add unit test for media service.

- apps/catalog/catalog/src/app/app.module.ts
- apps/festival/festival/src/app/app.module.ts
- apps/financiers/financiers/src/app/app.module.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie.form.ts
- libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts
Google analytics enable everywhere, anytime
> authorize google analytics

- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.scss
- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
- apps/festival/festival/src/app/marketplace/event/lobby/lobby.module.ts
- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/event/src/lib/layout/view/view.component.ts
> Add lobby page

- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html
- libs/media/src/lib/directives/image-reference/imgix-helpers.ts
- libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
Modify definition for stills photos
Fix #3822
> still photo in HD

- apps/financiers/financiers/src/app/dashboard/tunnel/financial-details/financial-details.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/routes.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.ts
- libs/organization/campaign/src/lib/+state/campaign.model.ts
- libs/organization/campaign/src/lib/form/form.ts
- libs/organization/campaign/src/lib/form/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/fundings/fundings.component.ts
- libs/organization/campaign/src/lib/form/fundings/fundings.module.ts
- libs/organization/campaign/src/lib/form/perks/perks.module.ts
- libs/organization/campaign/src/lib/form/profits/profits.component.html
- libs/organization/campaign/src/lib/form/profits/profits.component.scss
- libs/organization/campaign/src/lib/form/profits/profits.component.ts
- libs/organization/campaign/src/lib/form/profits/profits.module.ts
- libs/organization/campaign/src/lib/form/proposal/proposal.module.ts
- libs/organization/campaign/src/lib/form/summary/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/summary/fundings/fundings.component.scss
- libs/organization/campaign/src/lib/form/summary/fundings/fundings.component.ts
- libs/organization/campaign/src/lib/form/summary/perks/perks.component.ts
- libs/organization/campaign/src/lib/form/summary/profits/profits.component.html
- libs/organization/campaign/src/lib/form/summary/profits/profits.component.scss
- libs/organization/campaign/src/lib/form/summary/profits/profits.component.ts
- libs/organization/campaign/src/lib/form/summary/proposal/proposal.component.ts
- libs/organization/campaign/src/lib/form/summary/summary.module.ts
- libs/organization/campaign/src/lib/pipes/fundings.pipe.ts
- libs/organization/campaign/src/lib/pipes/index.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.html
- libs/ui/src/lib/list/table-filter/table-filter.component.ts
- libs/utils/src/lib/pipes/number.pipe.ts
> Update MF summary

- .firebaserc
- firebase.json
> updated financiers targets

- angular.json
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- apps/financiers/financiers/src/app/marketplace/title/view/view.module.ts
- libs/media/src/lib/+state/media.service.ts
- libs/organization/campaign/src/lib/form/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/profits/profits.component.html
- libs/organization/campaign/src/lib/marketplace/financing/financing.component.html
- libs/organization/campaign/src/lib/marketplace/financing/financing.component.scss
- libs/organization/campaign/src/lib/marketplace/financing/financing.component.ts
- libs/organization/campaign/src/lib/marketplace/financing/financing.module.ts
- libs/utils/src/lib/pipes/number.pipe.ts
- styles/components/apex-chart.scss
- styles/components/bf-font-color.scss
- styles/theme.scss
> Marketplace financial elements

- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- libs/event/src/lib/guard/session.guard.ts
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/ui/src/lib/confirm/confirm.component.html
- libs/ui/src/lib/confirm/confirm.component.scss
- libs/ui/src/lib/confirm/confirm.component.ts
- styles/components/mat-dialog.scss
Add a security pop up when user wants to delete an event (to ask confirmation of the deletion).
Also add this on the screening page, when the screening is running and the user wants to leave the page.
> Security pop up

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/components/prize-card/prize-card.component.html
- libs/movie/src/lib/movie/components/prize-card/prize-card.module.ts
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/movie/src/lib/movie/marketplace/main/main.component.ts
Add the ToLabel pipe on the prize card, the premiere data is a static data, so I use the pipe to display it correctly.
Fix #4027  issue from Sentry
> Invalid Pipe

- libs/media/src/lib/+state/media.model.ts
- libs/media/src/lib/components/dialog/file/file.component.html
- libs/media/src/lib/components/dialog/file/file.component.ts
- libs/media/src/lib/components/dialog/file/file.module.ts
- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.module.ts
> Movies in file explorer

- apps/financiers/financiers/src/app/dashboard/tunnel/routes.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.ts
- apps/financiers/financiers/src/app/marketplace/marketplace.component.html
- apps/financiers/financiers/src/app/marketplace/organization/member/member.component.ts
- apps/financiers/financiers/src/app/marketplace/organization/title/title.component.ts
- apps/financiers/financiers/src/app/marketplace/organization/view/view.component.ts
- apps/financiers/financiers/src/app/marketplace/organization/view/view.module.ts
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/organization/campaign/src/lib/marketplace/investment/investment.component.ts
- libs/ui/src/lib/preview-modal/dialog-preview/dialog-preview.component.scss
- libs/ui/src/lib/tunnel/layout/layout.component.html
- libs/ui/src/lib/tunnel/layout/layout.component.scss
- libs/ui/src/lib/tunnel/layout/layout.component.ts
- libs/utils/src/lib/form/validators/validators.ts
- styles/components/mat-button.scss
Cleanup some stuff on media financiers
> First cleanup on financiers

- apps/festival/festival/src/app/marketplace/organization/list/list.component.ts
> fix a bug for #4067

- libs/movie/src/lib/movie/components/title-features/title-features.component.scss
- libs/movie/src/lib/movie/components/title-features/title-features.component.ts
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/movie/src/lib/movie/form/summary/main/main.component.ts
- libs/movie/src/lib/movie/form/summary/summary.module.ts
- libs/movie/src/lib/movie/pipes/movie-feature.pipe.ts
- libs/movie/src/lib/movie/pipes/running-time.pipe.ts
Homogenize display for the running time data
> Running time

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.module.ts
- libs/media/src/lib/components/file-selector/file-selector.component.html
- libs/media/src/lib/components/file-selector/file-selector.component.scss
- libs/media/src/lib/components/file-selector/file-selector.component.ts
- libs/media/src/lib/components/file-selector/file-selector.module.ts
- libs/movie/src/lib/movie/components/header/header.component.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts
- libs/ui/src/lib/icon-service.ts
- libs/utils/src/lib/pipes/fileName.pipe.ts
- libs/utils/src/lib/utils.ts
> update file selector

- apps/catalog/catalog-e2e/src/integration/marketplace/create-wishlist.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/WishlistPage.ts
Component tag seems to have changed.
Also changed location of accept cookie to improve the speed and reliability
> Fix(E2E): Create Wishlist test fix. Fixes #4067

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/festival/festival/src/app/dashboard/dashboard.module.ts
- apps/financiers/financiers/src/app/dashboard/dashboard.module.ts
- libs/event/src/lib/guard/event-organization.guard.ts
- libs/movie/src/lib/movie/guards/movie-tunnel.guard.ts
Add a new guard to prevent user from other org to go on the event form page of event of other org
Fix #3930
> Event guard dashboard

- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.scss
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
- libs/movie/src/lib/movie/form/movie.form.ts
> other videos

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/organization/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/title/list/list.component.html
- apps/financiers/financiers/src/index.html
- libs/movie/src/lib/movie/components/card/card.component.html
- libs/movie/src/lib/movie/components/card/card.component.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/organization/campaign/src/lib/form/profits/profits.component.html
- libs/organization/campaign/src/lib/form/profits/profits.component.ts
- libs/utils/src/lib/pipes/display-name.pipe.ts
> Issue mf debug

- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.html
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.scss
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.module.ts
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.ts
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.module.ts
- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.scss
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.model.ts
- libs/media/src/lib/components/file-explorer/file-explorer.module.ts
Reworked the way navigation works in the file explorer
> Folders in file explorer view

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.module.ts
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.ts
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.ts
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.ts
- libs/movie/src/lib/movie/marketplace/additional/additional.component.html
- libs/movie/src/lib/movie/marketplace/additional/route.ts
- libs/movie/src/lib/movie/marketplace/main/main.component.html
Rename "Audience & Goal" to "Positioning" (ui only)
Move it from "main" & "sales pitch" to "additional information"
> Move Audience & Goal to Positioning

- libs/invitation/src/lib/invitation.component.html
- libs/invitation/src/lib/invitation.component.ts
- libs/invitation/src/lib/invitation.module.ts
- libs/notification/src/lib/notification.component.html
- libs/notification/src/lib/notification.component.ts
- libs/notification/src/lib/notification.module.ts
> Feat 4136 added loader to invitations and notifications pages

- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.html
- libs/ethers/src/lib/wallet/components/wallet-import-key-form/wallet-import-key-form.component.html
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.html
- libs/media/src/lib/components/cropper/cropper.component.html
- libs/media/src/lib/components/cropper/cropper.component.ts
- libs/media/src/lib/components/dialog/file/file.component.html
- libs/media/src/lib/components/dialog/image/image.component.html
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.model.ts
- libs/media/src/lib/components/upload/file-upload/file-upload.component.html
- libs/media/src/lib/components/upload/file-upload/file-upload.component.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.html
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/media-files/media-files.component.html
- libs/movie/src/lib/movie/form/media-images/media-images.component.html
- libs/movie/src/lib/movie/form/media-notes/notes.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/organization/campaign/src/lib/form/budget/budget.component.html
- libs/organization/campaign/src/lib/form/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/profits/profits.component.html
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.html
- libs/user/src/lib/auth/forms/profile/profile.component.html
- libs/utils/src/lib/utils.ts
> Dynamic content in file uploader and cropper

- libs/admin/src/lib/admin-panel/components/edit-party/edit-party.component.ts
- libs/contract/src/lib/contract/form/party/party.component.ts
- libs/contract/src/lib/version/form/price/price.component.ts
- libs/organization/src/lib/organization/pages/organization-find/organization-find.component.ts
- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.ts
FIx for Algolia Autocomplete Component receiving the wrong input
> Fix algolia autocomplete

- apps/financiers/financiers/src/app/marketplace/organization/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/organization/list/list.component.ts
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.scss
- libs/movie/src/lib/movie/components/title-features/title-features.component.scss
- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
- libs/movie/src/lib/movie/pipes/shooting.pipe.ts
- libs/organization/campaign/src/lib/form/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/fundings/fundings.component.scss
- libs/organization/campaign/src/lib/form/proposal/proposal.component.html
- libs/organization/campaign/src/lib/form/proposal/proposal.component.scss
- libs/organization/campaign/src/lib/marketplace/financing/financing.component.html
Solve most of the issues from #4101
> Cleanup MF again

- libs/movie/src/lib/movie/form/available-materials/available-materials.component.html
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.html
- libs/ui/src/lib/missing-control/missing-control.component.ts
> validator for languages

- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.scss
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.model.ts
> refactoring

- libs/organization/campaign/src/lib/components/perk-card/perk-card.component.html
- libs/organization/campaign/src/lib/form/form.ts
- libs/organization/campaign/src/lib/form/perks/perks.component.html
- libs/organization/campaign/src/lib/form/perks/perks.component.ts
- libs/organization/campaign/src/lib/form/summary/perks/perks.component.html
- libs/organization/campaign/src/lib/pipes/perks.pipe.ts
> reanable priv

- apps/catalog/catalog/src/app/marketplace/home/home.component.html
- apps/catalog/catalog/src/app/marketplace/home/home.component.scss
- apps/catalog/catalog/src/app/marketplace/home/home.component.spec.ts
- apps/catalog/catalog/src/app/marketplace/marketplace.component.html
- apps/catalog/catalog/src/app/marketplace/marketplace.component.scss
- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.scss
- apps/festival/festival/src/app/marketplace/marketplace.component.html
- apps/festival/festival/src/app/marketplace/marketplace.component.scss
- apps/financiers/financiers/src/app/marketplace/home/home.component.html
- apps/financiers/financiers/src/app/marketplace/home/home.component.scss
- apps/financiers/financiers/src/app/marketplace/marketplace.component.html
- apps/financiers/financiers/src/app/marketplace/marketplace.component.scss
- libs/ui/src/lib/layout/marketplace/marketplace.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.scss
> Issue catalog update

- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
> Only unsubscribe on when there is a subscription

- libs/invitation/src/lib/components/item/item.component.html
- libs/invitation/src/lib/components/item/item.component.ts
- libs/notification/src/lib/+state/notification.store.ts
A first attempt to homogenize the way users are displayed on notifications and invitations
related to #3868 and #3958
> Homogenize meeting notifications and invitations

- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
fix #3961 Invitation bug with email address starting with "s"
> fix #3961 Invitation bug with email address starting with "s"

- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.ts
Algolia Index was initialised incorrectly
> Fix initialising wrong index

- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/title/list/list.component.html
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
Algolia Index was initialised incorrectly and removed app filters (there are now separate indices for each app)
> Fix initialising index and removed app filters

- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.scss
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.ts
> Snackbar on delete files and little margin for update button

- libs/event/src/lib/components/list/list.component.html
- libs/invitation/src/lib/components/list/list.component.html
- libs/invitation/src/lib/components/list/list.component.ts
- libs/notification/src/lib/components/list/list.component.html
- libs/notification/src/lib/components/list/list.component.ts
removed paginator - Buggy invitation pagination #4180
> removed paginator - Buggy invitation pagination #4180

- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
> International titles and fix select movie same title

- apps/catalog/catalog/src/app/marketplace/home/home.component.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0041.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/title-features/title-features.component.ts
- libs/movie/src/lib/movie/form/available-materials/available-materials.component.html
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/movie/src/lib/movie/marketplace/main/main.module.ts
- libs/movie/src/lib/movie/pipes/movie-feature.pipe.ts
- libs/movie/src/lib/movie/pipes/running-time.pipe.ts
- libs/ui/src/lib/layout/dashboard/dashboard.component.html
- libs/ui/src/lib/marketplace/pages/wishlist/wishlist.component.html
- libs/ui/src/lib/marketplace/pages/wishlist/wishlist.module.ts
- libs/ui/src/lib/static-informations/contact/contact.component.html
- libs/ui/src/lib/static-informations/contact/contact.component.scss
Rework running time to set time as a number only
Fix #4124
> Runningtime data

- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.html
- libs/admin/src/lib/admin-panel/forms/organization-admin.form.ts
- libs/organization/src/lib/organization/forms/organization-form-description/organization-form-description.component.html
- libs/organization/src/lib/organization/forms/organization-form-description/organization-form-description.component.ts
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.html
- libs/organization/src/lib/organization/forms/organization.form.ts
Re-implement the description for organisation.
Fix #4036
> organisation description

- .circleci/config.yml
> demo1 deploy hotfix

- apps/backend-ops/src/algolia.ts
- apps/backend-ops/src/db-cleaning.spec.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0042.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0043.ts
> Issue 4254

- apps/backend-ops/src/firestore-rules.spec.ts
- apps/backend-ops/src/fixtures/data.ts
Events security rules unit tests
> Feat(UT): Add unit tests for events security rules.

- apps/backend-functions/src/bigQuery.ts
> fix requestMovieAnalytics

- libs/media/src/lib/components/upload/file-upload/file-upload.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.module.ts
- libs/ui/src/lib/form/list/form-list.component.html
- libs/ui/src/lib/form/list/form-list.component.ts
> Change video list to bf form list

- libs/media/src/lib/components/file-explorer/file-explorer.model.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
issue #4241
Removed a slash from video file path
> Remove slash from video file path

- libs/media/src/lib/components/dialog/file/file.component.html
- libs/media/src/lib/components/dialog/file/file.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.model.ts
> Added video files to file explorer

- apps/festival/festival/src/app/dashboard/files/files.component.scss
- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.scss
A step closer to the design
Result:
> Improved css of file explorer

- libs/media/src/lib/components/dialog/file-viewer/viewer.component.html
- libs/media/src/lib/components/dialog/file-viewer/viewer.component.ts
- libs/media/src/lib/components/dialog/file-viewer/viewer.module.ts
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.html
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.module.ts
Preview pdf, video and images in list of files in file explorer
> file previewer

- apps/festival/festival/src/app/marketplace/title/screening/screening.component.html
- apps/festival/festival/src/app/marketplace/title/view/view.component.html
- apps/festival/festival/src/app/marketplace/title/view/view.module.ts
- env/env.blockframes-samir.ts
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.scss
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.ts
Number of sessions modified (5 sessions max), select option reviewed and adapted and css a bit modified
Fix: #4183
> debug screenings banner

- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/+state/event.model.ts
> Check whether owner is present in meeting sessions

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.html
- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/routes.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/landing/landing.component.html
- apps/financiers/financiers/src/app/landing/landing.component.ts
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- libs/media/src/lib/components/upload/file-upload/file-upload.component.html
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/media-files/media-files.component.html
- libs/movie/src/lib/movie/form/media-images/media-images.component.html
- libs/movie/src/lib/movie/form/media-notes/notes.component.html
- libs/movie/src/lib/movie/form/media-notes/notes.component.scss
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/organization/campaign/src/lib/dashboard/investment/investment.component.html
- libs/organization/campaign/src/lib/form/budget/budget.component.html
- libs/organization/campaign/src/lib/form/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/profits/profits.component.html
- libs/organization/campaign/src/lib/form/summary/proposal/proposal.component.html
- libs/organization/campaign/src/lib/marketplace/financing/financing.component.html
- libs/organization/campaign/src/lib/marketplace/investment/investment.component.html
- libs/ui/src/lib/assets/icons/warning.svg
- libs/ui/src/lib/icon-service.ts
- libs/ui/src/lib/tunnel/layout/layout.component.ts
- libs/ui/src/lib/tunnel/page/page.component.html
- libs/ui/src/lib/tunnel/page/page.component.ts
- libs/utils/src/lib/common-interfaces/navigation.ts
> wording MF

- apps/catalog/catalog/src/app/dashboard/title/view/view.component.ts
- apps/festival/festival/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- libs/movie/src/lib/movie/marketplace/additional/route.ts
- libs/movie/src/lib/movie/marketplace/artistic/route.ts
- libs/movie/src/lib/movie/marketplace/main/route.ts
- libs/movie/src/lib/movie/marketplace/production/route.ts
> update tab titles

- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
Fix the loading state insite the dashboard title page
Fix #4343
> fix spinner titles page

- apps/cms/src/app/app.module.ts
- apps/cms/src/app/forms/chips-autocomplete/chips-autocomplete.component.html
- apps/cms/src/app/forms/firestore/firestore.component.html
- apps/cms/src/app/forms/firestore/firestore.component.scss
- apps/cms/src/app/forms/firestore/firestore.component.ts
- apps/cms/src/app/forms/firestore/firestore.module.ts
- apps/cms/src/app/forms/firestore/firestore.queries.ts
- apps/cms/src/app/forms/firestore/firestore.schema.ts
- apps/cms/src/app/forms/firestore/index.ts
- apps/cms/src/app/forms/select/select.component.html
- apps/cms/src/app/forms/select/select.component.ts
- apps/cms/src/app/forms/text/text.component.html
- apps/cms/src/app/forms/text/text.schema.ts
- apps/cms/src/app/forms/typed-field/index.ts
- apps/cms/src/app/forms/typed-field/typed-field.component.html
- apps/cms/src/app/forms/typed-field/typed-field.component.scss
- apps/cms/src/app/forms/typed-field/typed-field.component.ts
- apps/cms/src/app/forms/typed-field/typed-field.module.ts
- apps/cms/src/app/home/org-titles/org-titles.component.html
- apps/cms/src/app/home/org-titles/org-titles.component.scss
- apps/cms/src/app/home/org-titles/org-titles.component.ts
- apps/cms/src/app/home/orgs/orgs.component.html
- apps/cms/src/app/home/orgs/orgs.component.scss
- apps/cms/src/app/home/orgs/orgs.component.ts
- apps/cms/src/app/home/pipes.ts
- apps/cms/src/app/home/titles/titles.component.html
- apps/cms/src/app/home/titles/titles.component.scss
- apps/cms/src/app/home/titles/titles.component.ts
Create firestore query form
implements in all forms
> Firebase query form

- apps/backend-functions/src/internals/firebase.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/utils.ts
- libs/firebase-utils/src/lib/maintenance.ts
- libs/firebase-utils/src/lib/util.ts
- fix log errors fix with correct fix for log errors
- cache maintenance status between invocations for #3614
> hotfix for incorrect firebase init & more efficient maintenance checks

- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.scss
- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- apps/festival/festival/src/app/marketplace/event/session/session.module.ts
- firestore.rules
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/+state/event.model.ts
- libs/event/src/lib/components/doorbell/doorbell.component.html
- libs/event/src/lib/components/doorbell/doorbell.component.ts
- libs/event/src/lib/components/doorbell/doorbell.module.ts
> Ask to join meeting

- libs/media/src/lib/components/cropper/cropper.component.ts
- libs/media/src/lib/components/dialog/image/image.component.html
- libs/media/src/lib/components/dialog/image/image.component.ts
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/form/media.form.ts
> Disable update btn when cropping

- libs/event/src/lib/guard/event.guard.ts
On the session page, we have a confirm dialog if user wants to leave the session page. But we have conflict between this dialog component when the user logs out. This PR should fix it.
Fix #4146
> Session page and logout

- libs/media/src/lib/components/dialog/file/file.component.html
- libs/media/src/lib/components/dialog/image/image.component.html
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.scss
> Update file explorer ui 5

- apps/backend-functions/src/bigQuery.ts
- libs/admin/src/lib/admin-panel/pages/users/users.component.html
- libs/admin/src/lib/admin/+state/admin.query.ts
- libs/admin/src/lib/admin/+state/admin.service.ts
Format the data inside the SQL query to get the good value of date.
Fix #3972
> Improve SQL query

- libs/media/src/lib/components/cropper/cropper.component.ts
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.ts
- libs/media/src/lib/components/file-explorer/components/single-file-view/single-file-view.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.ts
- libs/media/src/lib/components/file-explorer/file-explorer.model.ts
- libs/media/src/lib/components/file-explorer/file-explorer.module.ts
> Indication on icon to show if file is present

- apps/festival/festival/src/app/marketplace/event/ended/meeting-ended.component.html
- apps/festival/festival/src/app/marketplace/event/ended/meeting-ended.component.scss
- apps/festival/festival/src/app/marketplace/event/ended/meeting-ended.component.ts
- apps/festival/festival/src/app/marketplace/event/ended/meeting-ended.module.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- firestore.rules
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/+state/event.store.ts
- libs/event/src/lib/components/meeting/room/video-room.component.ts
- libs/event/src/lib/pipes/event-link.pipe.ts
- libs/utils/src/lib/pipes/duration.pipe.ts
> Meeting over

- tools/scripts/anonymize-db.ts
@george43g any chances that you can update the anondb we fetch from prepareForTesting with this change ?
> fix jwplayerId for anon db

- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/users.ts
- libs/firebase-utils/src/lib/algolia/algolia.ts
- libs/invitation/src/lib/form/user/user.component.html
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/utils/src/lib/algolia/algolia.interfaces.ts
Update user index on algolia to put the org denomination of the user on it.
Fix #4356
> Algolia org on user

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.module.ts
- libs/media/src/lib/components/dialog/file-viewer/viewer.component.scss
- libs/media/src/lib/components/dialog/file-viewer/viewer.component.ts
- libs/media/src/lib/components/file-selector/file-selector.component.html
- libs/media/src/lib/components/file-selector/file-selector.component.scss
- libs/media/src/lib/components/file-selector/file-selector.component.ts
- libs/media/src/lib/components/file-selector/file-selector.module.ts
> File preview in file selector of event files

- apps/catalog/catalog/src/styles.scss
- apps/cms/src/styles.scss
- apps/crm/crm/src/styles.scss
- apps/festival/festival/src/styles.scss
- apps/financiers/financiers/src/styles.scss
- libs/ui/src/lib/layout/dashboard/dashboard.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.html
- styles/components/mat-button.scss
- styles/style.scss
- styles/themes/builder.scss
Use the theme builder on every app
> Use theme builder

- apps/festival/festival/src/app/marketplace/organization/member/member.component.html
Email clickable on org view on marketplace
> email clickable

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.html
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/organization/campaign/src/lib/dashboard/financing/financing.component.ts
- libs/organization/campaign/src/lib/dashboard/investment/investment.component.ts
- libs/organization/campaign/src/lib/form/summary/fundings/fundings.component.html
- libs/organization/campaign/src/lib/form/summary/profits/profits.component.html
> Issue 4438

- apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
Hide avails tab on movie view for catalog
> hide avails tab

- apps/financiers/financiers/src/app/landing/landing.component.scss
- apps/financiers/financiers/src/app/landing/landing.component.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.scss
- libs/landing/src/lib/shell/shell.component.html
- libs/landing/src/lib/shell/shell.component.ts
Fix some typo on landing MF page
Fix min width for file explorer for CRM
> Fix MF landing and CRM

- env/env.blockframes-samir.ts
- libs/event/src/lib/components/screening-item/screening-item.component.html
- libs/event/src/lib/components/screening-item/screening-item.component.ts
- libs/event/src/lib/layout/view/view.component.html
> invitation debug when the org is owner

- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceEventPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceScreeningPage.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
Make video playback more reliable on E2E.
> Update(E2E): Make screening video playback reliable.

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
- libs/media/src/lib/components/controls/pdf-control/pdf-control.component.scss
- libs/media/src/lib/components/controls/video-control/video-control.component.scss
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.html
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.component.scss
- libs/media/src/lib/components/file-explorer/file-explorer.component.html
- libs/media/src/lib/components/file-explorer/file-explorer.component.scss
To do's from Design Review doc
> Small UI fixes

- libs/utils/src/lib/form/forms/list.form.spec.ts
- libs/utils/src/lib/form/forms/list.form.ts
> Issue 4440

- apps/festival/festival/src/app/dashboard/files/files.component.html
- libs/media/src/lib/components/cropper/cropper.component.scss
- libs/media/src/lib/components/upload/widget/upload-widget.component.scss
> Safari fixes and change of text

- libs/ui/src/lib/layout/footer/footer.component.html
- libs/ui/src/lib/layout/footer/footer.component.scss
- libs/ui/src/lib/layout/footer/footer.module.ts
> Divider above footer

- libs/user/src/lib/auth/+state/auth.service.ts
> branch changes, notifications storage kept in an other account debugged

- apps/catalog/catalog/src/app/landing/key-features/key-features.component.html
- apps/catalog/catalog/src/app/landing/key-features/key-features.component.scss
- apps/catalog/catalog/src/app/landing/landing.component.html
- apps/catalog/catalog/src/app/landing/landing.component.scss
- apps/catalog/catalog/src/app/landing/view-marketplace/view-marketplace.component.scss
- apps/festival/festival/src/app/landing/landing.component.html
- apps/festival/festival/src/app/landing/landing.component.scss
- apps/financiers/financiers/src/app/landing/landing.component.html
- apps/financiers/financiers/src/app/landing/landing.component.scss
- libs/landing/src/lib/shell/shell.component.html
- libs/landing/src/lib/shell/shell.component.scss
- libs/landing/src/lib/shell/shell.component.ts
- libs/landing/src/lib/shell/shell.module.ts
Rework the landing page and its structure
Fix #4335
> Landing CSS and typo

- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
1. Above Cascade8 (first section):
Title: Essential cookies
Subtitle: These are essential to the operation of the platform's services.
2. Above Third party partners
Title: Optional cookies
Subtitle: These are optional but very useful for us to provide you with optimal services.
Sorry no design for that but could be done with the help of @stephanie-cascade8 if needed for text size & typo
> Added text to be more explicit

- angular.json
- apps/catalog/catalog/src/app/landing/key-features/key-features.component.html
- apps/catalog/catalog/src/app/landing/key-features/key-features.component.scss
- apps/catalog/catalog/src/app/landing/landing.component.html
- apps/catalog/catalog/src/app/landing/landing.component.scss
- apps/catalog/catalog/src/app/landing/view-marketplace/view-marketplace.component.scss
- apps/festival/festival/src/app/landing/landing.component.html
- apps/festival/festival/src/app/landing/landing.component.scss
- apps/festival/festival/src/app/marketplace/event/view/view.component.scss
- apps/festival/festival/src/app/marketplace/organization/list/list.component.html
- apps/financiers/financiers/src/app/landing/landing.component.html
- apps/financiers/financiers/src/app/landing/landing.component.scss
- apps/financiers/financiers/src/app/marketplace/marketplace.component.html
- apps/financiers/financiers/src/app/marketplace/organization/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/organization/list/list.component.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/event/src/lib/layout/view/view.component.scss
- libs/invitation/src/lib/components/action/action.component.scss
- libs/landing/src/lib/shell/shell.component.html
- libs/landing/src/lib/shell/shell.component.scss
- libs/landing/src/lib/shell/shell.component.ts
- libs/landing/src/lib/shell/shell.module.ts
- libs/media/src/lib/components/file-selector/file-selector.component.html
- libs/organization/src/lib/organization/forms/search.form.ts
- libs/ui/src/lib/layout/footer/footer.component.html
- libs/ui/src/lib/layout/footer/footer.component.scss
- libs/ui/src/lib/layout/footer/footer.module.ts
- libs/user/src/lib/auth/+state/auth.service.ts
- libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
- styles/themes/builder.scss
> Fix for r2.0 11 12

- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/templates/mail.ts
Add a eventName to the inviteUser function to display it correctly on the Sendgrid template.
> EventName on email template

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.html
- libs/invitation/src/lib/components/guest-item/guest-item.component.html
- libs/invitation/src/lib/components/guest-list/guest-list.component.html
- libs/invitation/src/lib/form/user/user.component.html
> Small changes

- libs/movie/src/lib/movie/form/summary/media-videos/media-videos.component.html
> Issue 4438 2

- libs/notification/src/lib/+state/notification.store.ts
> Redirect more button when project is created

- libs/event/src/lib/layout/view/view.component.html
> Removed double invitation async

- libs/organization/campaign/src/lib/form/campaign.shell.config.ts
> Issue campaign form

- apps/festival/festival/src/app/marketplace/event/view/view.component.html
- apps/festival/festival/src/app/marketplace/event/view/view.component.scss
> Fix issue 4553

- libs/notification/src/lib/+state/notification.service.spec.ts
npx jest --runInBand
```
Test Suites: 2 skipped, 21 passed, 21 of 23 total
Tests:       11 skipped, 120 passed, 131 total
Snapshots:   0 total
Time:        28.31s, estimated 33s
```
> fix notifications unit test

- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
Fetch organization correctly
Fix #4559
> fetch org correctly

- libs/event/src/lib/layout/view/view.component.html
> missing request access button restored

- .firebaserc
- libs/admin/src/lib/admin-panel/pages/contracts/contracts.component.html
- libs/admin/src/lib/admin-panel/pages/contracts/contracts.component.ts
- libs/admin/src/lib/admin-panel/pages/events/events.component.html
- libs/admin/src/lib/admin-panel/pages/events/events.component.ts
- libs/admin/src/lib/admin-panel/pages/invoices/invoices.component.ts
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.html
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.ts
- libs/admin/src/lib/admin-panel/pages/movies/movies.component.html
- libs/admin/src/lib/admin-panel/pages/movies/movies.component.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.html
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.ts
- libs/admin/src/lib/admin-panel/pages/users/users.component.html
- libs/admin/src/lib/admin-panel/pages/users/users.component.ts
> Disable sort on columns and make row clickable

- libs/ui/src/lib/layout/layout.module.ts
> Fix overflow issue on firefox

- libs/notification/src/lib/+state/notification.store.ts
> displaying the title of project in notifications

- .firebaserc
- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
Add user simulation when deleting user on CRM
> simulation for user deletion

- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.ts
> re-import on type change

- libs/invitation/src/lib/components/item/item.component.html
- libs/invitation/src/lib/components/item/item.component.ts
> leads link invitations to lobby page, right align action items

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.html
- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
add percentage of the campaign on movie view dashboard
> Percentage cammpaign

- apps/backend-ops/src/algolia.ts
> ordering aplphabetically orgs and movies

- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.scss
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- libs/ui/src/lib/tel-input/tel-input.component.html
Add a currency icon on the investment dialog form.
I need suggestion for the getCurrencySymbol function, I have the feeling that it is not the best way but I prefer to use the function instead of doing if statement in the html.
> Currency on dialog form

- apps/backend-functions/src/internals/email.ts
Add the from parameter into data using for the body of emails of sendgrid, and change the call to appUrl.
Fix #4602
> From Email

- libs/movie/src/lib/movie/form/summary/synopsis/synopsis.component.html
- libs/ui/src/lib/missing-control/missing-control.component.html
- libs/ui/src/lib/missing-control/missing-control.component.ts
> removed is Last

- libs/user/src/lib/auth/components/widget/widget.component.html
- libs/user/src/lib/auth/components/widget/widget.component.scss
- libs/user/src/lib/auth/components/widget/widget.component.ts
> added bf admin

- apps/backend-functions/src/internals/invitations/organizations.ts
- apps/backend-functions/src/templates/mail.ts
Update memberAdded email with new variables that can be used inside the template of sendgrid.
Fix #4529
> MemberAdded email

- apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
Fix movie tunnel nightly e2e fail.. crew summary is updated.
> Fix(e2e): Update crew summary field.

- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html
Add an input for other video in the movie-form
See #4338
> Title for other videos

- apps/rules/src/tests/firestore/fixtures/data.ts
- apps/rules/src/tests/firestore/invitation.spec.ts
Create new UT to test invitation collection
> Update(UT): Add read invitation test.

- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.html
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.scss
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.scss
Just rework the organization page, because it was like you put a bomb inside the page....
> Have mercy for CRM

- apps/catalog/catalog/src/app/guards/catalog-app.guard.ts
- apps/festival/festival/src/app/dashboard/guards/festival-app.guard.ts
- apps/financiers/financiers/src/app/dashboard/guards/financiers-app.guard.ts
Add a snackbar to inform the user he has no access to the app.
Fix #2892
> Blocking account when no app access

- libs/media/src/lib/components/upload/file-upload/file-upload.component.html
- libs/media/src/lib/components/upload/file-upload/file-upload.component.ts
- libs/movie/src/lib/movie/form/media-notes/notes.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.scss
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.module.ts
- libs/ui/src/lib/form/list/form-list.component.html
- libs/ui/src/lib/form/list/form-list.component.ts
> Movie form debug

- apps/festival/festival/src/app/marketplace/event/lobby/lobby.module.ts
- apps/festival/festival/src/app/marketplace/event/session/session.module.ts
- libs/event/src/lib/layout/edit/edit.module.ts
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.module.ts
Related to : #4514 
This issue is about Mano comment here : https://github.com/blockframes/blockframes/issues/4514#issuecomment-751722360
> css inside confirm dialog for edit/delete or leave a current event fixed

- libs/admin/src/lib/admin-panel/admin-panel.module.ts
- libs/admin/src/lib/admin-panel/forms/movie-admin.form.ts
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.html
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.scss
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.ts
- libs/media/src/lib/+state/media.model.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.html
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.scss
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.ts
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.module.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.html
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.scss
- libs/utils/src/lib/helpers.ts
Add a component on movie page on CRM to be able to change poster, banner and still photos of the movie.
See issue #3189 
EDIT : I change also a bit the form for the productionStatus, we were able to change it one time but not more without refreshing the page. There was also a bug on the appAccess because of a missing data.
> Crm movie picture

- libs/user/src/lib/auth/pages/login/login.component.html
Related to: #4655 
This issue is about Vincent comment : https://github.com/blockframes/blockframes/issues/4655#issue-778989384
> snackbar message in login component edited

- apps/festival/festival/src/app/marketplace/event/lobby/lobby.module.ts
- apps/festival/festival/src/app/marketplace/event/session/session.module.ts
- libs/event/src/lib/layout/edit/edit.module.ts
- libs/media/src/lib/components/file-explorer/components/multiple-files-view/multiple-files-view.module.ts
related to: #4655 
comment : https://github.com/blockframes/blockframes/issues/4655#issue-778989384
(just a reminder : this code is used also in develop branch, care to the double code)
> debug buttons inside dialog confirm

- apps/backend-functions/src/player.ts
- libs/media/src/lib/components/cropper/cropper.component.html
- libs/media/src/lib/components/cropper/cropper.component.scss
- libs/media/src/lib/components/cropper/cropper.component.ts
- libs/media/src/lib/components/player/player.component.html
- libs/media/src/lib/components/player/player.component.scss
- libs/media/src/lib/components/player/player.component.ts
- libs/media/src/lib/components/player/player.module.ts
- libs/media/src/lib/components/viewers/media-viewer.module.ts
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.html
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.scss
- libs/media/src/lib/components/viewers/video-viewer/video-viewer.component.ts
- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
> Multiple sanity fixes

- apps/backend-functions/src/internals/email.ts
- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/templates/ids.ts
- apps/backend-functions/src/templates/mail.ts
- libs/utils/src/lib/apps.ts
Two things here :
- I merge the emails emails when you were invited to join an org
- I prepared a description about application in the appMailSetting object
TODO : Change the id of the template if needed
See #4510 and fix #4528 (already done but needed the description)
> Merge invitation to org email

- apps/backend-ops/src/migrations.ts
- libs/ui/src/lib/maintenance/maintenance.service.ts
- libs/user/src/lib/auth/components/widget/widget.component.html
- libs/user/src/lib/auth/components/widget/widget.component.ts
- libs/utils/src/lib/maintenance/index.ts
> Add app version

- libs/media/src/lib/components/player/player.component.html
- libs/media/src/lib/components/player/player.component.ts
- libs/media/src/lib/components/viewers/media-viewer.component.html
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/movie/src/lib/movie/form/summary/main/main.component.ts
- libs/movie/src/lib/movie/form/summary/media-files/media-files.component.html
- libs/movie/src/lib/movie/form/summary/media-images/media-images.component.html
- libs/movie/src/lib/movie/form/summary/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
- libs/movie/src/lib/movie/marketplace/shell/shell.component.scss
- libs/movie/src/lib/movie/marketplace/shell/shell.module.ts
- libs/ui/src/lib/preview-modal/preview.component.html
- libs/ui/src/lib/preview-modal/preview.component.scss
- libs/ui/src/lib/preview-modal/preview.component.ts
- libs/ui/src/lib/preview-modal/preview.module.ts
> Preview and videos

- apps/festival/festival/src/app/marketplace/marketplace.component.html
> Logo "Screen International" leads to the marketplace home

- apps/festival/festival/src/app/marketplace/marketplace.component.html
fixed
UI size seems still good
> logo Screen International clickable for leads to the homepage

- libs/organization/src/lib/organization/pipes/org-address.pipe.ts
> Deleted the sentence "no adress provided" in the org id

- libs/organization/src/lib/organization/pipes/org-address.pipe.ts
> deletion of 'No adress provided' in org id - develop

- libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.html
- libs/movie/src/lib/movie/marketplace/main/main.component.html
> fixing layout

- libs/utils/src/lib/utils.ts
- storage.rules
> Add support for more video file types

- libs/user/src/lib/user/+state/user.model.ts
> cleaned OrganizationMember interface

- libs/invitation/src/lib/form/user/user.component.html
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.html
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> 4689 Fix bug

- apps/financiers/financiers/src/app/marketplace/home/home.component.html
- libs/media/src/lib/directives/image-reference/image-reference.directive.ts
- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
- libs/ui/src/lib/carousel/carousel.component.html
> Fix carousel

- libs/ui/src/lib/slider/slider.component.ts
Second point mentioned in issue #4724
> 4724 Hide arrows when only one slide

- apps/festival/festival/src/app/marketplace/event/list/list.component.ts
- apps/festival/festival/src/app/marketplace/organization/title/title.component.ts
- firestore.indexes.json
> 4734 sort lineup by createdAt

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/media/src/lib/file/carousel/carousel.component.html
- libs/media/src/lib/file/carousel/carousel.component.ts
> remove event

- libs/movie/src/lib/movie/components/prize-card/prize-card.component.html
> parentheses deleted, word 'Premiere' added

- libs/movie/src/lib/movie/components/title-features/title-features.component.ts
- libs/movie/src/lib/movie/pipes/movie-feature.pipe.ts
> 4729 add production countries to title features

- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/main.ts
- libs/invitation/src/lib/+state/invitation.service.ts
- libs/organization/src/lib/organization/components/member-add/member-add.component.ts
Check if user invited has already an orgId when we want to invite him/her on our organization
Fix #739
> OrgId check for invitation

- libs/media/src/lib/video/puppet/puppet.component.ts
- libs/media/src/lib/video/viewer/viewer.component.scss
- libs/media/src/lib/video/viewer/viewer.component.ts
> default thumbnail

- libs/ui/src/lib/slider/slide/slide.component.scss
> 4724 fix slide width

- libs/media/src/lib/video/puppet/puppet.component.ts
- libs/media/src/lib/video/viewer/viewer.component.scss
- libs/media/src/lib/video/viewer/viewer.component.ts
> Video Thumbnail & Watermark issue

- libs/admin/src/lib/admin-panel/pages/events/events.component.ts
- libs/admin/src/lib/admin-panel/pages/invitations/invitations.component.ts
- libs/admin/src/lib/admin-panel/pages/movies/movies.component.ts
- libs/admin/src/lib/admin-panel/pages/users/users.component.ts
Fix issue #3953 
Replaced the 'caching' strategy by a method to get all the data first and then combine it
> 3953 improve loading time

- libs/firebase-utils/src/lib/firestoreMigrations/0049.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
> fix Public org page line-up not complete

- libs/ui/src/lib/tunnel/layout/layout.component.ts
fix: #4764 
(thanks Max for the quick help)
> Configstore draft accepted in Archipel Market

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.scss
correct PR about https://github.com/blockframes/blockframes/pull/4785
> correct PR

- apps/catalog/catalog/src/index.html
- apps/festival/festival/src/index.html
- apps/financiers/financiers/src/index.html
> added meta desc

- angular.json
Pass unit-test in CI and PRS in future.
> Pass CLI option to run in sequence to avoid failures.

- apps/catalog/catalog/src/app/marketplace/home/home.component.html
- apps/catalog/catalog/src/app/marketplace/home/home.module.ts
- apps/cms/src/app/home/titles/titles.component.html
- apps/cms/src/app/home/titles/titles.component.scss
- apps/cms/src/app/home/titles/titles.component.ts
- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.module.ts
- libs/admin/src/lib/cms/home.ts
- libs/utils/src/lib/pipes/sort-array.pipe.ts
Fix issue #4733 for movie titles
> 4733 Add random sorting on titles

- libs/notification/src/lib/+state/notification.service.spec.ts
- libs/notification/src/test-setup.ts
> Fix(UT): Add notification model and increase timeout for the test. Fixes #4739

- apps/backend-functions/src/test-setup.ts
- apps/backend-functions/tsconfig.app.json
- apps/backend-ops/jest.config.js
- apps/backend-ops/src/test-setup.ts
- apps/backend-ops/tsconfig.app.json
- apps/backend-ops/tsconfig.json
> Fix(UT): Need to set env var. Also increase timeout for test. Fixes #4740

- apps/catalog/catalog-e2e/src/integration/marketplace/create-wishlist.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/HomePage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/NavbarPage.ts
Simple fix to force click the link and increase timeout for reliability
> Fix(E2E): Improve tests to make create wishlist spec more reliable.

- libs/user/src/lib/auth/pages/notifications-settings/notifications-settings.component.html
- libs/user/src/lib/auth/pages/notifications-settings/notifications-settings.component.scss
- libs/user/src/lib/auth/pages/notifications-settings/notifications-settings.component.ts
- libs/user/src/lib/auth/pages/notifications-settings/notifications-settings.module.ts
- libs/user/src/lib/auth/pages/profile-view/profile-view.component.scss
- libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts
- libs/user/src/lib/auth/pages/profile-view/profile-view.module.ts
> UI notif setting page

- apps/backend-functions/src/movie.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-ops/src/algolia.ts
- libs/firebase-utils/src/lib/algolia/algolia.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/organization/src/lib/organization/forms/search.form.ts
- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
- libs/utils/src/lib/algolia/algolia.interfaces.ts
- package-lock.json
- package.json
> updaged algolvia v4

- apps/backend-functions/src/bigQuery.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/pubsub/daily-analytics-import.ts
- apps/catalog/catalog/src/app/dashboard/home/home.component.html
- apps/catalog/catalog/src/app/dashboard/home/home.component.ts
- apps/catalog/catalog/src/app/dashboard/home/home.module.ts
- apps/catalog/catalog/src/app/dashboard/title/activity/activity.component.ts
- apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts
- apps/festival/festival/src/app/dashboard/title/list/list.component.html
- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- firestore.rules
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.html
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
- libs/movie/src/lib/movie/pipes/analytics.pipe.ts
- libs/ui/src/lib/dashboard/pages/home/home.component.html
- libs/ui/src/lib/dashboard/pages/home/home.component.ts
- libs/ui/src/lib/dashboard/pages/home/home.module.ts
- libs/utils/src/lib/analytics/analytics-model.ts
- libs/utils/src/lib/analytics/analytics.service.ts
- libs/utils/src/lib/analytics/analytics.store.ts
> 4693 import analytics in firestore and use

- apps/backend-functions/src/internals/invitations/events.ts
- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/orgs.ts
- libs/notification/src/lib/+state/notification.firestore.ts
Continue to work on notification and emails
- orgAppAccessChanged
> Notifications & Emails

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/internals/invitations/events.ts
- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/orgs.ts
- libs/notification/src/lib/+state/notification.firestore.ts
- libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts
- libs/user/src/lib/user/+state/user.firestore.ts
Split notification type into 2 differents types
> Notification Types

- apps/backend-functions/src/main.ts
> Fix analaytics import

- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/templates/ids.ts
- libs/notification/src/lib/+state/notification.store.ts
> Feat 4046 small fixes

- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
added central org Id as buyer Id in mandate contract
> added central org id

- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/users.ts
Quick proposal for Connexion issue #4837 to allow more verbosity in password creation.
This will help us to gather more information when the case described in #4837 occurs
> proposal for Connexion issue #4837

- libs/firebase-utils/src/lib/firestoreMigrations/0054.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
> 4881 File migration

- libs/contract/src/lib/contract/+state/contract.firestore.ts
- libs/contract/src/lib/contract/+state/contract.model.ts
- libs/media/src/lib/+state/media.firestore.ts
- libs/media/src/lib/+state/media.model.ts
- libs/media/src/lib/form/media.form.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
> refactored forms

- libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
- libs/movie/src/lib/movie/form/media-files/media-files.component.html
> refactor uploader

- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.module.ts
- libs/ui/src/lib/form/list/form-list.component.html
- libs/ui/src/lib/form/table/form-table.component.html
refactor movie tunnel video & excel import
> excel & tunnel video

- env/env.blockframes-bruce.ts
- env/env.blockframes-ci.ts
- env/env.blockframes-clelia.ts
- env/env.blockframes-demo-1.ts
- env/env.blockframes-demo-2.ts
- env/env.blockframes-demo-3.ts
- env/env.blockframes-demo-4.ts
- env/env.blockframes-demo-5.ts
- env/env.blockframes-francois.ts
- env/env.blockframes-george.ts
- env/env.blockframes-mano.ts
- env/env.blockframes-max.ts
- env/env.blockframes-pl-2.ts
- env/env.blockframes-remco.ts
- env/env.blockframes-samir.ts
- env/env.blockframes-staging.ts
- env/env.blockframes-vincent.ts
- env/env.blockframes.ts
- libs/admin/src/lib/admin-panel/pages/user/user.component.html
- libs/admin/src/lib/admin-panel/pages/user/user.component.scss
- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
> 4815 Embed user dashboard

- libs/firebase-utils/src/lib/watermark.ts
> 4916 Fix invalid metadata for watermark

- libs/admin/src/lib/admin-panel/forms/movie-admin.form.ts
- libs/admin/src/lib/admin-panel/forms/organization-admin.form.ts
- libs/campaign/src/lib/form/form.ts
- libs/event/src/lib/components/screening-item/screening-item.component.ts
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.ts
- libs/media/src/lib/+state/media.model.ts
- libs/media/src/lib/+state/media.service.ts
- libs/media/src/lib/file/upload-widget/upload-widget.component.ts
- libs/media/src/lib/form/media.form.ts
- libs/movie/src/lib/movie/form/media-images/media-images.component.ts
- libs/notification/src/lib/+state/notification.model.ts
- libs/notification/src/lib/+state/notification.store.ts
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/organization/src/lib/organization/forms/medias.form.ts
- libs/organization/src/lib/organization/forms/organization.form.ts
- libs/user/src/lib/auth/forms/profile-edit.form.ts
> bunch of fixes

- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.html
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.module.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.module.ts
- libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
- libs/media/src/lib/image/uploader-new/uploader.component.html
- libs/media/src/lib/image/uploader-new/uploader.component.scss
- libs/media/src/lib/image/uploader-new/uploader.component.ts
- libs/media/src/lib/image/uploader-new/uploader.module.ts
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.html
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.ts
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.module.ts
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/main/main.module.ts
- libs/movie/src/lib/movie/form/media-files/media-files.component.ts
- libs/movie/src/lib/movie/form/media-images/media-images.component.html
- libs/movie/src/lib/movie/form/media-images/media-images.module.ts
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.html
- libs/organization/src/lib/organization/forms/organization-form/organization-form.module.ts
- libs/organization/src/lib/organization/no-organization.module.ts
- libs/organization/src/lib/organization/organization.module.ts
- libs/user/src/lib/auth/auth.module.ts
- libs/user/src/lib/auth/forms/profile/profile.component.html
- libs/user/src/lib/auth/forms/profile/profile.module.ts
- libs/user/src/lib/user/user-display.module.ts
> Refactor cropper

- apps/backend-functions/src/media.ts
- apps/backend-functions/src/player.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/media/src/lib/pdf/viewer/viewer.component.ts
- libs/media/src/lib/video/viewer/viewer.component.ts
> video & pdf, back & front

- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/media.ts
- apps/backend-functions/src/users.ts
- apps/backend-ops/src/db-cleaning.ts
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/firebase-utils/src/lib/algolia/algolia.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0054.ts
- libs/invitation/src/lib/components/guest-item/guest-item.component.html
- libs/media/src/lib/+state/file-uploader.service.ts
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/organization/src/lib/organization/forms/member.form.ts
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.ts
- libs/organization/src/lib/organization/pages/organization-create/organization-create.component.html
- libs/user/src/lib/auth/+state/auth.store.ts
- libs/user/src/lib/auth/forms/profile-edit.form.ts
- libs/user/src/lib/user/components/card/card.component.ts
- libs/utils/src/lib/algolia/algolia.interfaces.ts
- libs/utils/src/lib/common-interfaces/identity.ts
> 4002 Refactor user and org media

- apps/backend-ops/src/storage-cleaning.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0054.ts
Media in invitation docs migration
> 4002 invitation media migration

- libs/media/src/lib/file/explorer/uploader-dialog/uploader-dialog.module.ts
- libs/media/src/lib/file/pipes/download.pipe.ts
- libs/movie/src/lib/movie/components/promotional-links/promotional-links.pipe.ts
- libs/movie/src/lib/movie/form/media-files/media-files.module.ts
- libs/movie/src/lib/movie/form/media-images/media-images.module.ts
- libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html
- libs/organization/src/lib/organization/organization.module.ts
- libs/user/src/lib/user/user-display.module.ts
> 4002 refactor media

- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.html
- libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.scss
Fix running time for movie tunnel e2e test.
Also fix CSS in notification table.
(beautiful green movie tunnel test)
> Running time fix

- libs/campaign/src/lib/form/budget/budget.component.html
- libs/campaign/src/lib/form/fundings/fundings.component.html
- libs/campaign/src/lib/form/profits/profits.component.html
- libs/media/src/lib/file/explorer/list/list.component.html
- libs/media/src/lib/file/file-uploader/file-uploader.component.ts
- libs/media/src/lib/image/uploader/uploader.component.ts
- libs/movie/src/lib/movie/form/media-files/media-files.component.html
- libs/movie/src/lib/movie/form/media-notes/notes.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
> 4002 use StorageFileForm

- apps/festival/festival/src/app/dashboard/files/files.component.html
- apps/festival/festival/src/app/dashboard/files/files.component.ts
- libs/media/src/lib/file/explorer/explorer.component.html
- libs/media/src/lib/file/explorer/explorer.model.ts
- libs/media/src/lib/file/explorer/file/file.component.html
- libs/media/src/lib/file/explorer/list/list.component.html
- libs/media/src/lib/file/explorer/list/list.component.ts
> File explorer refactoring

- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.ts
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.html
- libs/admin/src/lib/admin-panel/components/organization/forms/organization-form/organization-form.component.ts
- libs/admin/src/lib/admin-panel/forms/movie-admin.form.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/contract/src/lib/contract/form/contract.form.ts
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.html
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.scss
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.ts
- libs/movie/src/lib/movie/components/banner/banner.component.ts
- libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.html
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.scss
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.module.ts
> refactor excel import

- apps/backend-functions/src/internals/media.ts
- apps/backend-functions/src/media.ts
- apps/backend-functions/src/player.ts
solve circular dependency issue in backend-functions
> extract media helper

- apps/catalog/catalog-e2e/src/integration/marketplace/create-wishlist.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventPage.ts
- libs/e2e/src/lib/utils/screenings.ts
- libs/event/src/lib/form/edit-details/edit-details.component.html
- libs/organization/src/lib/organization/guard/no-organization.guard.ts
Fix event creation issue with Create screening
> Fix event creation issue.

- libs/firebase-utils/src/lib/firestoreMigrations/0054.ts
- libs/media/src/lib/+state/file-uploader.service.ts
- libs/media/src/lib/+state/media.service.ts
- libs/media/src/lib/+state/static-files.ts
- libs/media/src/lib/file/file-uploader/file-uploader.component.ts
- libs/media/src/lib/image/directives/imgix-helpers.ts
- libs/media/src/lib/image/uploader/uploader.component.html
- libs/media/src/lib/image/uploader/uploader.component.ts
- libs/movie/src/lib/movie/form/media-files/media-files.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
> 4002 Fix media bugs

- apps/backend-functions/src/media.ts
Fix images accidently deleted and storagePath for files
> 4002 fix bug

- apps/backend-functions/src/media.ts
- libs/media/src/lib/+state/static-files.ts
- libs/media/src/lib/file/explorer/list/list.component.html
- libs/media/src/lib/file/explorer/list/list.component.ts
- libs/media/src/lib/file/file-uploader/file-uploader.component.ts
- libs/media/src/lib/image/uploader/uploader.component.ts
- libs/movie/src/lib/movie/form/media-notes/notes.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
refactor code to handle file list
> file list backend

- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventPage.ts
Fix intermittent problem with saving of event.
> Improve creation of event to avoid fail to save sometimes.

- apps/backend-functions/src/twilio.spec.ts
fix test issue discovered in https://github.com/blockframes/blockframes/pull/4981
> fix twilio unit test

- apps/backend-functions/src/media.ts
> 4002 change ref to storagePath

- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/templates/ids.ts
- apps/backend-functions/src/templates/mail.ts
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.ts
- libs/invitation/src/lib/+state/invitation.service.ts
- libs/organization/src/lib/organization/pages/organization-feedback/organization-feedback.component.html
- libs/user/src/lib/auth/+state/auth.service.ts
- libs/user/src/lib/auth/components/email-input/email-input.component.ts
- libs/user/src/lib/auth/pages/identity/identity.component.ts
> Feat 4932 4948

- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventPage.ts
Make it all day event.. to help detect later.
> Modifications to improve testability

- apps/backend-functions/src/media.ts
- libs/media/src/lib/+state/static-files.ts
- libs/media/src/lib/image/directives/imgix-helpers.ts
- libs/media/src/lib/image/uploader/uploader.component.ts
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/movie/src/lib/movie/form/summary/media-files/media-files.component.html
- libs/movie/src/lib/movie/form/summary/media-images/media-images.component.html
- libs/movie/src/lib/movie/form/summary/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
- libs/ui/src/lib/preview-modal/preview.component.html
- libs/ui/src/lib/preview-modal/preview.component.ts
> many fixes

- libs/utils/src/lib/static-model/static-model.ts
> value Russia for territories fixed

- apps/catalog/catalog/src/app/app.module.ts
- apps/festival/festival/src/app/app.module.ts
- apps/financiers/financiers/src/app/app.module.ts
- env/env.blockframes-bruce.ts
- env/env.blockframes-ci.ts
- env/env.blockframes-clelia.ts
- env/env.blockframes-demo-1.ts
- env/env.blockframes-demo-2.ts
- env/env.blockframes-demo-3.ts
- env/env.blockframes-demo-4.ts
- env/env.blockframes-demo-5.ts
- env/env.blockframes-francois.ts
- env/env.blockframes-george.ts
- env/env.blockframes-mano.ts
- env/env.blockframes-max.ts
- env/env.blockframes-pl-2.ts
- env/env.blockframes-remco.ts
- env/env.blockframes-samir.ts
- env/env.blockframes-staging.ts
- env/env.blockframes-vincent.ts
- env/env.blockframes.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
- libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts
- libs/utils/src/lib/yandex-metrica/yandex-metrica.service.ts
> 3317 Fix yandex

- apps/catalog/catalog/src/app/app.module.ts
- apps/festival/festival/src/app/app.module.ts
- apps/financiers/financiers/src/app/app.module.ts
- env/env.blockframes.ts
> 4815 add dashboard for production and log app name

- libs/firebase-utils/src/lib/watermark.ts
> Fix watermark

- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/media/src/lib/+state/static-files.ts
- libs/media/src/lib/file/explorer/explorer.model.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
> Fix otherVideo

- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/movie/src/lib/movie/components/title-features/title-features.component.ts
- libs/utils/src/lib/spreadsheet/format.ts
> Issue 4889 2

- apps/cms/src/app/home/banner/banner.component.html
- apps/cms/src/app/home/banner/banner.component.ts
- apps/cms/src/app/home/hero/hero.component.html
- apps/cms/src/app/home/hero/hero.component.ts
- apps/cms/src/app/template/template.component.ts
- libs/admin/src/lib/cms/home.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0054.ts
- libs/media/src/lib/+state/media.firestore.ts
> Support new media structure

- libs/media/src/lib/file/file-uploader/file-uploader.component.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.ts
> Fix extra metadata overwrite

- libs/invitation/src/lib/form/user/user.component.html
- libs/invitation/src/lib/form/user/user.module.ts
- libs/media/src/lib/pipes/storageFile.pipe.ts
- libs/movie/src/lib/movie/components/card/card.component.html
- libs/movie/src/lib/movie/components/card/card.module.ts
- libs/organization/src/lib/organization/components/card/card.component.html
- libs/organization/src/lib/organization/components/card/card.module.ts
On Algolia only the storagePath is stored. Therefore to show images the data for the StorageFile object needs to be collected.
> Algolia storagePaths to StorageFile

- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
> Fix files in movie view

- libs/organization/src/lib/organization/components/card-minimal/card-minimal.component.scss
> fix minicard UI bug long text org name

- apps/catalog/catalog/src/app/catalog.module.ts
- apps/festival/festival/src/app/festival.module.ts
- apps/financiers/financiers/src/app/financiers.module.ts
- libs/organization/src/lib/organization/guard/request-access.guard.ts
Add a guard to check when we refresh the page if organization has now access to the platform and redirect the user if yes.
> add guard for request access page

- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/ui/src/lib/static-autocomplete/select/static-select.component.ts
- libs/utils/src/lib/static-model/static-model.ts
> Issue 4900

- libs/admin/src/lib/admin-panel/admin-panel.module.ts
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.html
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.scss
- libs/admin/src/lib/admin-panel/components/organization/create-organization/create.component.ts
- libs/invitation/src/lib/+state/invitation.service.ts
- libs/organization/src/lib/organization/forms/organization-lite-form/organization-lite-form.component.ts
- libs/user/src/lib/auth/pages/identity/identity.component.ts
- libs/utils/src/lib/static-model/static-model.ts
- Allow admin to choose from which platform he wants to create user when creating an org
Next : use UniqueOrgName in indentity form
> Clean todo 4932

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.module.ts
- libs/movie/src/lib/movie/pipes/analytics.pipe.ts
> reimplemented analytics

- apps/financiers/financiers/src/app/marketplace/home/home.component.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
- libs/utils/src/lib/algolia/algolia.interfaces.ts
- libs/utils/src/lib/algolia/algolia.service.ts
> fix algolia filters on guest list for events

- libs/firebase-utils/src/lib/algolia/algolia.ts
- libs/utils/src/lib/algolia/algolia.interfaces.ts
Removed the denomination that is in fact Public organization on the org algolia object, and flat it
> org algolia reworked

- libs/ui/src/lib/layout/footer/footer.component.html
> 2020 to 2021 copyright footer

- apps/backend-ops/src/storage-cleaning.spec.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/media/src/lib/+state/file-uploader.service.spec.ts
- libs/media/src/lib/+state/file-uploader.service.ts
- libs/media/src/lib/+state/media.service.spec.ts
- libs/media/src/lib/file/explorer/explorer.component.ts
> Fix shadowed name

- apps/catalog/catalog/src/app/marketplace/marketplace.component.html
- apps/catalog/catalog/src/app/marketplace/marketplace.module.ts
- apps/catalog/catalog/src/app/marketplace/organization/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/organization/list/list.component.scss
- apps/catalog/catalog/src/app/marketplace/organization/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/organization/list/list.module.ts
- apps/catalog/catalog/src/app/marketplace/organization/member/member.component.html
- apps/catalog/catalog/src/app/marketplace/organization/member/member.component.scss
- apps/catalog/catalog/src/app/marketplace/organization/member/member.component.ts
- apps/catalog/catalog/src/app/marketplace/organization/member/member.module.ts
- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.html
- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.scss
- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.ts
- apps/catalog/catalog/src/app/marketplace/organization/title/title.module.ts
- apps/catalog/catalog/src/app/marketplace/organization/view/view.component.html
- apps/catalog/catalog/src/app/marketplace/organization/view/view.component.scss
- apps/catalog/catalog/src/app/marketplace/organization/view/view.component.ts
- apps/catalog/catalog/src/app/marketplace/organization/view/view.module.ts
Add the org list and the org view on catalog marketplace
> Catalog org list

- apps/catalog/catalog/src/app/dashboard/dashboard.component.html
- apps/catalog/catalog/src/app/dashboard/home/home.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/marketplace.component.html
- apps/festival/festival/src/app/dashboard/dashboard.component.html
- apps/festival/festival/src/app/marketplace/marketplace.component.html
- apps/financiers/financiers/src/app/dashboard/dashboard.component.html
- apps/financiers/financiers/src/app/marketplace/marketplace.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.ts
- libs/movie/src/lib/movie/dashboard/shell/shell.module.ts
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/organization/src/lib/organization/pipes/org-access.pipe.ts
> fix #5072 & #5071

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- libs/organization/src/lib/organization/components/chip/chip.component.html
Typo on dashboard + org logo in dark-contrast-theme
Fix #5069 #5075
> theme and typo

- libs/consents/src/lib/+state/consents.service.spec.ts
- libs/consents/src/test-setup.ts
Cleanup issue
https://github.com/blockframes/blockframes/issues/4913
> Fix consents unit-test. Separate out tests for httpsCallable.

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
> table 'sales (gross receipt)' removed for the moment

- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.html
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.scss
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.ts
- libs/utils/src/lib/utils.ts
> Fix file import ui

- libs/movie/src/lib/movie/components/credit-card/credit-card.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.module.ts
- libs/movie/src/lib/movie/form/sales-pitch/sales-pitch.component.html
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
- libs/utils/src/lib/static-model/static-model.ts
issue related: #5087 
missed a change in a file when I had some merge conflicts. that's why the PR #5107 is now closed.
> Fixes 5087 movie front improvements

- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/templates/mail.ts
- libs/utils/src/lib/emails/utils.ts
Add 2 links into event email object. Change some variables for Sendgrid templates.
> Notif email update

- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.ts
- libs/user/src/lib/auth/pages/identity/identity.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.ts
- libs/utils/src/lib/algolia/algolia.service.ts
> allow multiple queries against algolia

- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
> fixed date issue

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- libs/contract/src/lib/bucket/+state/bucket.service.ts
Small PR so @RemcoSimonides and I can work at the same time without conflicts
> setup selection page

- libs/admin/src/lib/admin-panel/pages/organization/organization.component.html
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
Fix the CRM organization view bug
Fix #5139
> Fix org view

- libs/user/src/lib/auth/components/accept-conditions/accept-conditions.component.ts
Fix the automatic scroll on the mat-dialog for privacy policy
Fix #5137
> Scroll on mat-dialog

- apps/backend-functions/src/main.ts
- apps/backend-functions/src/player.ts
- libs/media/src/lib/video/viewer/viewer.component.ts
- libs/utils/src/lib/utils.ts
serve embed player through secured url
> secure player

- libs/user/src/lib/auth/pages/login/login.component.ts
I don't understand where the error came from. Looks like there is already a lot of problem/github issue opened with this error. (like this [one](https://github.com/firebase/firebase-js-sdk/issues/4451)).
Here is the Sentry error [linked](https://sentry.io/organizations/cascade-8/issues/2264331088/?project=1540126&query=is%3Aunresolved).
Close #5142
> change message

- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- libs/movie/src/lib/movie/components/promotional-links/promotional-links.pipe.ts
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
I have this error, but not blocking.
@pldespaigne can I have some help on this ?
> WIP fix download & player 

- apps/backend-functions/src/player.ts
Fix issue #5168 
@pldespaigne do we need the extra check in privateVideo function to be sure the user hasn't tempered with the jwPlayerId in the front-end?
> Fix other video preview

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts
- libs/contract/src/lib/bucket/+state/bucket.model.ts
- libs/contract/src/lib/income/+state/income.model.ts
Update UI on selection page
Create method to update the bucket
> Update selection page

- libs/firebase-utils/src/lib/firestoreMigrations/0054.ts
- libs/media/src/lib/video/viewer/viewer.component.ts
Fix issue #5160 
And removed index from media
> fix 5160 and removed index from media list

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/event/list/list.component.ts
- libs/contract/src/lib/avails/avails.spec.ts
- libs/contract/src/lib/avails/avails.ts
- libs/contract/src/lib/term/+state/term.service.ts
- libs/movie/src/lib/movie/form/search.form.ts
> Issue 4996

- libs/media/src/lib/file/file-uploader/file-uploader.component.html
- libs/media/src/lib/file/file-uploader/file-uploader.component.ts
> Uploader bug

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
> link to screening event id added in edit event 5181

- firestore.rules
I did not have time to investigate further but this line is preventing us to save some movies.
> temp fix for rules

- apps/catalog/catalog/src/app/marketplace/home/home.component.ts
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- libs/utils/src/lib/pipes/cms.pipe.ts
> 5196 fix flickering images

- libs/event/src/lib/+state/event.model.ts
- libs/firebase-utils/src/lib/firestoreMigrations/0056.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
- libs/firebase-utils/src/lib/firestoreMigrations/old-types.ts
> migration 56

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts
> 5002 UI and small fixes

- libs/invitation/src/lib/form/user/user.component.ts
> 5217 remove space as separator

- libs/organization/src/lib/organization/forms/organization-lite-form/organization-lite-form.component.html
- libs/organization/src/lib/organization/forms/organization-lite-form/organization-lite-form.component.ts
- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.ts
- libs/user/src/lib/auth/auth.module.ts
- libs/user/src/lib/auth/pages/identity/identity.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.scss
- libs/user/src/lib/auth/pages/identity/identity.component.ts
- libs/user/src/lib/auth/pages/identity/identity.module.ts
Some details about the connection flow, avatar for org, company name input required, etc...
> Details 4932

- libs/ui/src/lib/overlay-widget/overlay-widget.component.ts
Scrollable overlay when screen too small
> Scrollable overlay

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- libs/contract/src/lib/bucket/+state/bucket.model.ts
- libs/contract/src/lib/bucket/+state/bucket.service.ts
- libs/contract/src/lib/term/+state/term.service.ts
- libs/contract/src/lib/term/+state/term.store.ts
> Fix avails filter

- .circleci/Dockerfile
> docker hotfix

- libs/user/src/lib/auth/components/data-validation/data-validation.component.html
- libs/user/src/lib/auth/components/signin-form/signin-form.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.scss
- styles/components/mat-toggle-button.scss
> Improvement

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts
Page for when selection is empty
> empty selection

- tools/scripts/get-prod-backup.ts
> anondb hotfix

- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.module.ts
- libs/user/src/lib/auth/pages/identity/identity.component.html
Various fixes for https://github.com/blockframes/blockframes/issues/5265
> fixes for #5265

- libs/ui/src/lib/layout/footer/footer.component.html
Differentiate location from App name
> Fix footer details

- libs/movie/src/lib/movie/form/reviews/reviews.component.html
- libs/movie/src/lib/movie/form/reviews/reviews.component.ts
- libs/movie/src/lib/movie/form/reviews/reviews.module.ts
> reset value once deselect toggle button fixed

- libs/movie/src/lib/movie/form/summary/media-images/media-images.component.html
> fix eye preview displayed when no image

- apps/festival/festival/src/app/dashboard/files/files.component.html
- libs/media/src/lib/video/viewer/viewer.component.ts
- libs/movie/src/lib/movie/form/summary/media-images/media-images.component.html
- libs/movie/src/lib/movie/form/summary/media-images/media-images.component.scss
- libs/movie/src/lib/movie/form/summary/media-images/media-images.component.ts
- libs/movie/src/lib/movie/form/summary/summary.module.ts
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/ui/src/lib/missing-control/missing-control.module.ts
- libs/utils/src/lib/utils.ts
> Files explorer

- libs/user/src/lib/auth/pages/identity/identity.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.scss
- libs/user/src/lib/auth/pages/login/login.component.html
- libs/user/src/lib/auth/pages/login/login.component.scss
Rework UI of custom snackbar in auth
Close #5313
> UI snackbar

- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/event/src/lib/components/meeting/+state/twilio.service.ts
> Meetings bugfix

- libs/organization/src/lib/organization/forms/organization-form-address/organization-form-address.component.html
- libs/organization/src/lib/organization/forms/organization.form.ts
Org country is mandatory when we create an org. It has to be mandatory also on the org form inside the app.
> country mandatory

- libs/ui/src/lib/dashboard/pages/home/home.component.html
I added a spinner when we wait for analytics card to display. But I think it's weird, I have a feeling it is more long with the spinner than without, I don't know how I can improve this behavior.
Close #5316
> add spinner

- libs/movie/src/lib/movie/components/review-card/review-card.component.html
- libs/movie/src/lib/movie/components/review-card/review-card.component.scss
Less characters of the quote and card a little more responsive
Fix #5269
> Review card

- apps/backend-functions/src/media.ts
Add a condition for cleaning the note on org.
> Clean media org

- apps/backend-ops/src/algolia.ts
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.module.ts
- libs/firebase-utils/src/lib/algolia/algolia.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/ui/src/lib/form/format/format.component.html
- libs/ui/src/lib/form/format/format.component.scss
- libs/ui/src/lib/form/format/format.component.ts
- libs/ui/src/lib/form/format/format.module.ts
- libs/utils/src/lib/algolia/algolia.interfaces.ts
> 4999 format filter

- libs/user/src/lib/auth/components/signin-form/signin-form.component.scss
- libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.scss
- libs/user/src/lib/auth/pages/login/login.component.html
- libs/user/src/lib/auth/pages/login/login.component.scss
- libs/user/src/lib/auth/pages/login/login.module.ts
Add the app logo on the login page
Closed #5326
> App logo login

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.scss
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.module.ts
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/dashboard/files/files.component.ts
- apps/festival/festival/src/app/dashboard/title/list/list.component.html
- apps/festival/festival/src/app/dashboard/title/list/list.component.scss
- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/dashboard.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.scss
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.ts
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- libs/event/src/lib/form/create/create.component.html
- libs/event/src/lib/form/edit-details/edit-details.component.html
- libs/invitation/src/lib/components/guest-list/guest-list.component.html
- libs/invitation/src/lib/components/guest-list/guest-list.module.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/components/promotional-links/promotional-links.pipe.ts
- libs/movie/src/lib/movie/form/movie.shell.config.ts
- libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.html
- libs/ui/src/lib/dashboard/components/no-title/no-title.component.html
- libs/ui/src/lib/dashboard/pages/home/home.component.html
- libs/ui/src/lib/dashboard/pages/home/home.component.ts
- libs/user/src/lib/auth/pages/identity/identity.component.ts
> Text fixes

- apps/festival/festival/src/app/marketplace/title/list/list.component.scss
- libs/event/src/lib/components/analytics/analytics.component.html
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.html
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.scss
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.module.ts
Last UI fixes from #5276 
Add a placeholder when statistic card are empty
> Last UI fixes

- libs/event/src/lib/form/edit-details/edit-details.component.html
> move all day toggle

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/specific-terms/specific-terms.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/specific-terms/specific-terms.component.scss
- apps/catalog/catalog/src/app/marketplace/title/selection/specific-terms/specific-terms.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/specific-terms/specific-terms.module.ts
- libs/contract/src/lib/bucket/+state/bucket.model.ts
- libs/contract/src/lib/bucket/+state/bucket.service.ts
- libs/contract/src/lib/offer/+state/offer.model.ts
> 5311 Add specific terms

- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> snackbar text

- libs/contract/src/lib/bucket/+state/bucket.service.ts
> Fix rules with createOffer

- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
> Contract import v2

- libs/import/src/lib/components/table-extracted-elements/contracts/contracts.component.ts
- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
> 5347 and added back languages to import

- apps/backend-functions/src/media.ts
- apps/backend-functions/src/orgs.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
CF https://github.com/blockframes/blockframes/pull/5378
> update after merge back 2-3 review

- libs/notification/src/lib/+state/notification.firestore.ts
- libs/notification/src/lib/+state/notification.store.ts
> cleaning after release to prod

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- libs/contract/src/lib/bucket/+state/bucket.service.ts
- libs/contract/src/lib/bucket/pipes.ts
- Remove transaction as it was blocking the rules, and there is not much risk of failure
- Keep memory of the array of title to avoid flickering
> Remove transaction & fix flickering

- libs/contract/src/lib/avails/form/avails.form.ts
- libs/contract/src/lib/term/form/filter/avails/avails-filter.component.html
- libs/event/src/lib/form/event.form.ts
- libs/utils/src/lib/form/validators/validators.ts
> 5383 dates should be correct

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- libs/contract/src/lib/avails/avails.spec.ts
- libs/contract/src/lib/avails/avails.ts
- libs/contract/src/lib/bucket/+state/bucket.model.ts
> 5389 Multiple mandates on single title

- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
fix: #5314 
Thanks PL for the small help!
> fix sort titles alphabetically dashboard

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
> 5385 merge terms and display conflict term warning

- firestore.rules
- libs/organization/src/lib/organization/+state/organization.service.ts
Thanks to @xmano help and new authflow (guard update I think), the weird behavior is gone.
fix #2710
> fix Weird behavior when creating an org and permissions

- libs/media/src/lib/file/explorer/explorer.model.ts
fix the bug that prevent to preview video from the file explorer
> fix preview video bug

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> query contracts only that are accepted

- libs/user/src/lib/auth/pages/identity/identity.component.scss
> Identity top of page cut under 1024px width

- libs/ui/src/lib/form/format/format.component.ts
same as libs/movie/src/lib/movie/form/main/main.component.html
> part of #5407 format list update

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.html
- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
- styles/components/mat-form-field.scss
> Issue 5420 layout

- apps/backend-functions/src/internals/invitations/organizations.ts
- apps/backend-functions/src/notification.ts
- libs/notification/src/lib/+state/notification.firestore.ts
> duplicate email "We wanted to let you know that your request to join .." fix

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/event/ended/meeting-ended.component.scss
- apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
- libs/event/src/lib/components/meeting/+state/twilio.service.ts
- libs/media/src/lib/+state/media.model.ts
- libs/media/src/lib/file/carousel/carousel.component.html
fix bugs (0), (2) & (5) from issue #5414
> Meeting file bugs

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts
- libs/contract/src/lib/term/components/detailed/detailed.component.html
- libs/contract/src/lib/term/components/detailed/detailed.component.scss
- libs/contract/src/lib/term/components/detailed/detailed.component.ts
- libs/contract/src/lib/term/components/detailed/detailed.module.ts
- libs/utils/src/lib/pipes/to-label.pipe.ts
> 5390 show more territories

- apps/catalog/catalog/src/app/marketplace/home/home.component.html
> 5418 fix broken image for catalog

- apps/catalog/catalog/src/app/dashboard/title/activity/activity.component.scss
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.scss
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/festival/festival/src/app/dashboard/title/list/list.component.html
- apps/festival/festival/src/app/dashboard/title/list/list.component.scss
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.scss
- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
various updates and debug for #5407
> various updates and debug for #5407

- apps/backend-functions/src/templates/mail.ts
> change text

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.html
- libs/user/src/lib/auth/pages/login/login.component.html
Feat #5417 icon download & part of #5407
> Feat #5417 icon download & part of #5407

- libs/movie/src/lib/movie/form/movie.shell.config.ts
- libs/movie/src/lib/movie/form/shell/shell.component.ts
- libs/utils/src/lib/apps.ts
> Issue 5407 movie form

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.scss
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/media-videos/media-videos.module.ts
- libs/movie/src/lib/movie/form/shell/shell.component.html
- libs/movie/src/lib/movie/form/start/start-tunnel.component.ts
- libs/movie/src/lib/movie/form/summary/media-videos/media-videos.component.html
- libs/movie/src/lib/movie/form/summary/summary.module.ts
> small fixes

- apps/catalog/catalog/src/app/landing/key-features/key-features.component.html
- apps/catalog/catalog/src/app/landing/landing.component.ts
> Update texts landing catalog

- apps/festival/festival/src/app/marketplace/organization/screening/screening.component.html
- apps/festival/festival/src/app/marketplace/organization/screening/screening.module.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/components/screening-item/screening-item.component.html
- libs/event/src/lib/components/screening-item/screening-item.component.ts
- libs/event/src/lib/components/screening-item/screening-item.module.ts
part of #5413  . I added a `debounceTime` 500ms to prevent blinking.
This seems to do the trick but IMO best solution would be not using observables where we don't need it.
> Feat 5413 fix blinking

- apps/catalog/catalog/src/app/marketplace/organization/view/view.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
- apps/catalog/catalog/src/app/marketplace/title/view/view.module.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/financiers/financiers/src/app/marketplace/title/list/list.component.html
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/pipes/is-type.pipe.ts
- libs/ui/src/lib/marketplace/pages/wishlist/wishlist.component.ts
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
- libs/utils/src/lib/static-model/static-model.ts
> Issue new genres

- libs/admin/src/lib/admin-panel/pages/users/users.component.ts
- libs/admin/src/lib/admin-panel/pipes/go-to.pipe.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.html
- libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts
> 5415 Improve users loading, add sales pitch, fix link

- apps/backend-functions/src/internals/email.ts
- apps/backend-functions/src/notification.ts
> Email fixes

- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.html
- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.ts
- apps/festival/festival/src/app/marketplace/event/list/list.component.html
- apps/festival/festival/src/app/marketplace/event/list/list.component.ts
- apps/festival/festival/src/app/marketplace/organization/title/title.component.html
- apps/festival/festival/src/app/marketplace/organization/title/title.component.ts
- apps/financiers/financiers/src/app/marketplace/organization/title/title.component.html
- apps/financiers/financiers/src/app/marketplace/organization/title/title.component.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/components/screening-item/screening-item.component.html
- libs/invitation/src/lib/components/list/list.component.html
- libs/invitation/src/lib/components/list/list.component.ts
- libs/invitation/src/lib/invitation.component.ts
Fix flashing for
> - [x] Catalog
> - [x] Festival
> - [x] Financiers
> 5486 fix flashing pages

- apps/backend-functions/src/internals/invitations/events.ts
- apps/backend-functions/src/internals/invitations/utils.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/users.ts
Fix the invitation email not sent when an user is invited to join org first.
Fix #5519
> Invitation email to event

- apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
> Update title that was failing in the test.

- libs/event/src/lib/components/screening-item/screening-item.component.html
- libs/event/src/lib/components/screening-item/screening-item.component.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/event/src/lib/layout/view/view.component.ts
- libs/invitation/src/lib/+state/invitation.query.ts
- libs/invitation/src/lib/+state/invitation.service.ts
- libs/invitation/src/lib/invitation.component.html
- libs/invitation/src/lib/invitation.component.ts
- libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.ts
- libs/ui/src/lib/layout/dashboard/dashboard.component.ts
- libs/ui/src/lib/layout/marketplace/marketplace.component.ts
> 5486 Rework to service in order to prevent flashes

- libs/firebase-utils/src/lib/util.spec.ts
> getCollectionInBatches test fix

- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelMainPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelTechnicalInfoPage.ts
Hot fix for resolving test compile errors.
Need to add proper fix subsequently if it was meant to make new test pass @fritzschoff
> Fix compile error in tests

- libs/firebase-utils/src/lib/anonymize/lib.ts
fix https://app.circleci.com/pipelines/github/blockframes/blockframes/16802/workflows/4c3633d1-51ab-48ba-9264-0ce9bf7a69d2/jobs/27540
> fix anon script new collection

- libs/firebase-utils/src/lib/commands.ts
- libs/firebase-utils/src/lib/restore-storage-from-ci.ts
as per title
we add a string regex option (will always BE python regex)
we exclude mov and mp4 files under protected dir when generating golden data
voila
> add exclude regex to gsutil transfer function helper

- apps/catalog/catalog/src/app/marketplace/organization/member/member.component.html
- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.html
- apps/festival/festival/src/app/marketplace/event/ended/meeting-ended.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/organization/member/member.component.html
- apps/festival/festival/src/app/marketplace/organization/title/title.component.html
- apps/financiers/financiers/src/app/marketplace/organization/title/title.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- libs/campaign/src/lib/marketplace/investment/investment.component.html
- libs/event/src/lib/components/empty/empty.component.html
- libs/movie/src/lib/movie/marketplace/additional/additional.component.html
- libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html
- libs/movie/src/lib/movie/marketplace/main/main.component.html
- libs/movie/src/lib/movie/marketplace/production/production.component.html
- libs/organization/src/lib/organization/layout/view/view.component.html
> 5405 one h1 per page

- assets/icons/video.svg
- libs/media/src/lib/file/explorer/explorer.component.html
- libs/ui/src/lib/icon.service.ts
> 5548 video icon

- libs/invitation/src/lib/+state/invitation.service.ts
Caused this with changes for issue 5196
> 5196 Prevent error on logout

- apps/catalog/catalog/src/app/marketplace/organization/title/title.component.html
- libs/organization/src/lib/organization/components/card/card.component.html
- libs/organization/src/lib/organization/components/card/card.component.ts
> 5550 from line-up to catalog

- libs/admin/src/lib/admin-panel/pages/events/events.component.html
- libs/admin/src/lib/admin-panel/pages/events/events.component.ts
> 5547 Fix hostedby Column filter and orderBy

- libs/firebase-utils/src/lib/firestoreMigrations/0059.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
- libs/movie/src/lib/movie/form/additional-information/additional-information.component.html
> 5184 change originalRelease hotels for video

- apps/festival/festival/src/app/dashboard/title/activity/activity.component.html
- apps/festival/festival/src/app/dashboard/title/activity/activity.component.scss
- apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts
- apps/festival/festival/src/app/dashboard/title/activity/activity.module.ts
- apps/festival/festival/src/app/dashboard/title/view/view.component.ts
- apps/festival/festival/src/app/dashboard/title/view/view.module.ts
- apps/financiers/financiers/src/app/dashboard/title/activity/activity.component.html
- apps/financiers/financiers/src/app/dashboard/title/activity/activity.component.scss
- apps/financiers/financiers/src/app/dashboard/title/activity/activity.component.ts
- apps/financiers/financiers/src/app/dashboard/title/activity/activity.module.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/title/view/view.module.ts
> 5495 Marketplace tab for financiers and festival

- libs/event/src/lib/components/meeting/video/video.component.html
- libs/event/src/lib/components/meeting/video/video.component.scss
> mirrored local video

- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/offer.ts
- apps/backend-functions/src/templates/ids.ts
- apps/backend-functions/src/templates/mail.ts
- libs/notification/src/lib/+state/notification.firestore.ts
- libs/notification/src/lib/+state/notification.store.ts
- libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts
- libs/user/src/lib/auth/forms/notifications-form/notifications.form.ts
> 5434 Send copy of offer to user

- angular.json
- apps/catalog/catalog-e2e/src/integration/marketplace/create-bucket.spec.ts
- apps/financiers/financiers-e2e/src/integration/app.spec.ts
- libs/invitation/src/lib/components/item/item.component.ts
3 changes addressed with this PR
1. Fix url to display invitation only for Cypress environment 
2. Skip create bucket test for now - will enable after implementing import
3. A new test in App financiers to get started.
> Fix app url to display invitation and make tests work

- apps/backend-functions/src/invitation.ts
- apps/backend-ops/src/backup.ts
- apps/backend-ops/src/db-cleaning.spec.ts
- apps/backend-ops/src/db-cleaning.ts
- apps/backend-ops/src/emulator.ts
- apps/backend-ops/src/firebaseSetup.ts
- libs/firebase-utils/src/lib/firebase-utils.ts
- libs/firebase-utils/src/lib/firestore/clear.ts
feat #5371 cleaning orgs with no users
> feat #5371 cleaning orgs with no users

- apps/festival/festival/src/app/marketplace/home/home.component.html
- styles/style.scss
> added animation

- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/templates/ids.ts
- apps/backend-functions/src/templates/mail.ts
- apps/backend-functions/src/users.ts
Fix issue #5340 
catalog and financiers weren't even used
> 5340 remove app specific template ids

- angular.json
- apps/crm/crm-e2e/tslint.json
- apps/financiers/financiers-e2e/cypress.json
- apps/financiers/financiers-e2e/tslint.json
This has fixed the e2e failure on CI. 
https://app.circleci.com/pipelines/github/blockframes/blockframes/16936/workflows/55f72979-1f9d-4d3b-a1dc-1f4940a51112/jobs/27695
Failure of npm run test is for different reason. It might get fixed by restarting the job or if there is a recent change in backend functions.
> Correct config settings for financiers and cms

- libs/user/src/lib/auth/components/signin-form/signin-form.component.html
- libs/user/src/lib/auth/components/signin-form/signin-form.component.ts
- libs/user/src/lib/auth/pages/login/login.component.html
- libs/user/src/lib/auth/pages/login/login.component.ts
> added dynamic button text

- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/templates/mail.ts
> More info on request access email

- libs/movie/src/lib/movie/marketplace/shell/shell.component.html
- libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
- libs/movie/src/lib/movie/marketplace/shell/shell.module.ts
> 5337 full screen images

- libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
> 5615 prevent browser autocomplete

- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/templates/mail.ts
Fix issue #5172
movieTitle value isnt' used in email
> 5172 Fix email for meeting

- apps/financiers/financiers/src/app/marketplace/home/home.component.ts
> 5273 fix org logo not displayed

- libs/media/src/lib/file/file-uploader/file-uploader.component.html
- libs/media/src/lib/file/file-uploader/file-uploader.component.ts
- libs/media/src/lib/file/file-uploader/file-uploader.module.ts
- libs/media/src/lib/file/pipes/download.pipe.ts
- libs/media/src/lib/image/uploader/uploader.component.html
- libs/media/src/lib/image/uploader/uploader.component.ts
- libs/media/src/lib/image/uploader/uploader.module.ts
- libs/utils/src/lib/utils.ts
> max file size

- libs/event/src/lib/layout/view/view.component.html
- libs/event/src/lib/layout/view/view.component.ts
- libs/event/src/lib/layout/view/view.module.ts
- libs/invitation/src/lib/components/action/action.component.scss
> 5169 Access screening room button before start

- apps/catalog/catalog/src/app/landing/key-features/key-features.component.scss
- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- libs/organization/src/lib/organization/pages/organization-pending/organization-pending.component.html
- libs/user/src/lib/auth/components/data-validation/data-validation.component.html
- libs/user/src/lib/auth/components/signin-form/signin-form.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.html
- styles/components/mat-toggle-button.scss
- styles/themes/builder.scss
> Issue 5626

- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- firestore.rules
- libs/event/src/lib/components/analytics/analytics.component.ts
solve "Screening stats don't load" of #5657
> watchtime fix

- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- styles/themes/builder.scss
> Issue 5667

- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
Issue related : #5625 
comment related: https://github.com/blockframes/blockframes/issues/5625#issuecomment-829295348
> Typo table name # VIEWS to # Views

- libs/ui/src/lib/layout/footer/footer.component.html
- libs/ui/src/lib/static-informations/contact/contact.component.html
- libs/ui/src/lib/static-informations/contact/contact.component.ts
fix: #5673 
Tell me if the string messages is ok for you or not.
> Footer typos + mandatory contact fields

- libs/ui/src/lib/list/filter/list-filter.component.scss
issue: #5625 
comment: https://github.com/blockframes/blockframes/issues/5625#issuecomment-829292167
> Vertical scrollbar safari in filters

- libs/invitation/src/lib/components/action/action.component.html
- libs/media/src/lib/file/explorer/explorer.component.html
- libs/media/src/lib/file/explorer/explorer.component.scss
multiple ui fixes related to #5630 & #5629
> multiple ui fixes

- apps/catalog/catalog-e2e/src/integration/marketplace/create-bucket.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
- apps/festival/festival/src/app/marketplace/organization/screening/screening.component.html
Wait for loading to get over without actual waiting.. detect loading spinner to improve the test.
> Improve detection of screening event

- styles/themes/builder.scss
issue: #5625 
this small PR is about this instruction that I've underlined :
The rest was already set up. I want to make sure that is correct with a review please
> mat-body1 foreground700

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- libs/contract/src/lib/avails/form/avails.form.ts
- libs/contract/src/lib/bucket/form.ts
- libs/ui/src/lib/static-autocomplete/group/group.component.html
- libs/ui/src/lib/static-autocomplete/group/group.component.scss
- libs/ui/src/lib/static-autocomplete/group/group.component.ts
> 5655 Avails Criteria Search

- libs/ui/src/lib/layout/marketplace/marketplace.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.scss
issue: #5695 
comment: Marketplace sidenav
> autofocus around the logo removed

- libs/organization/src/lib/organization/components/chip/chip.component.scss
> 5625 movie banner org logo white background

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/catalog/catalog/src/app/landing/landing.component.scss
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
issue: #5695 
comment: Archipel Content landing
issue and comment about replacing capitals letters by only first capital letter on movies dashboard list (catalog): https://github.com/blockframes/blockframes/issues/5625#issuecomment-829906990
> Several deformed images on Safari

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- libs/contract/src/lib/avails/avails.ts
> 5655 isSold without territories

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- libs/contract/src/lib/avails/form/avails.form.ts
- libs/contract/src/lib/bucket/form.ts
Update form on avails movie tab
> Preselected rights

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.guard.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts
> 5698 Prevent leaving without saving

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
> 5653 Select all available territories

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts
- libs/contract/src/lib/avails/calendar/calendar.component.html
- libs/contract/src/lib/avails/calendar/calendar.component.ts
- libs/contract/src/lib/avails/calendar/calendar.module.ts
> setup component

- libs/ui/src/lib/list/filter/list-filter.component.scss
origin issue: https://github.com/blockframes/blockframes/issues/5625#issuecomment-829292167
issue: #5723 
comment PR: https://github.com/blockframes/blockframes/pull/5721#discussion_r626506479
> vertical scrollbar removed in the right way done

- libs/user/src/lib/auth/components/accept-conditions/accept-conditions.component.html
- libs/user/src/lib/auth/components/accept-conditions/accept-conditions.component.scss
- libs/user/src/lib/auth/components/accept-conditions/accept-conditions.module.ts
> <button> instead of <a>

- libs/invitation/src/lib/form/user/user.component.ts
Issue and comment: https://github.com/blockframes/blockframes/issues/5728#issuecomment-833351276
Estimated: 3 
time spent: 4 hours
Finally, this issue came from an empty space before the email. Thanks for the help @Mussuranae!
> Multiple emails when we c/p issue

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
> 5698 Improvement prevent exit without saving

- libs/event/src/lib/layout/view/view.component.scss
- libs/media/src/lib/file/explorer/explorer.component.scss
- libs/user/src/lib/auth/components/accept-conditions/accept-conditions.component.scss
- libs/user/src/lib/auth/pages/identity/identity.component.scss
Fixes some CSS requested changes from #5723 
Linked to the PR #5721
> CSS request changes

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
- libs/contract/src/lib/bucket/form.ts
Fix issue #5760 
@pldespaigne, I did some text changes in the calendar component too. I guess it doesn't collide with your code too much.
> 5760 Review Avails

- apps/catalog/catalog-e2e/src/support/pages/marketplace/SelectionPage.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
Missing selector re-introduced and other changes
> Fix bucket test regression

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- libs/contract/src/lib/avails/avails.ts
- libs/contract/src/lib/avails/calendar/calendar.component.ts
- libs/contract/src/lib/avails/calendar/calendar.model.ts
- libs/contract/src/lib/avails/tests/bucketForm.spec.ts
- libs/contract/src/lib/avails/tests/territories.spec.ts
- libs/ui/src/lib/static-autocomplete/group/group.component.ts
Take raw data from the DB and display it into the calendar (no filter, no sales are taken into account for now).
> duration markers & db data

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
issue #5654
Edit and remove button on preselected rights
> 5654 Edit and remove preselected rights

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- libs/contract/src/lib/avails/avails.ts
Move mandates terms and stuff like that from map/calendar to parent to factorize code.
> Factorize in parent

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
seems like the currency become "undefined" at some point during the lifecycle of the component.
We should investigate when and why
> fix save to bucket

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.module.ts
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.scss
- apps/festival/festival/src/app/marketplace/title/list/list.component.scss
- apps/financiers/financiers/src/app/marketplace/title/list/list.component.scss
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.scss
- libs/ui/src/lib/map/map.component.ts
- libs/ui/src/lib/static-autocomplete/group/group.component.scss
- libs/user/src/lib/auth/pages/identity/identity.component.scss
- styles/components/mat-form-field.scss
> 5760 Update avails tab UI

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
> 5760 Bugs and added days to runs duration

- apps/backend-functions/src/templates/mail.ts
- apps/backend-functions/src/users.ts
- libs/user/src/lib/auth/forms/profile/profile.component.ts
> 5467 Add firstname as email param

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- libs/contract/src/lib/bucket/form.ts
preselected rights and CTA appear, but no rights added
> part of 5760

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- libs/contract/src/lib/avails/avails.ts
- libs/contract/src/lib/avails/calendar/calendar.component.ts
- libs/contract/src/lib/avails/form/avails.form.ts
- libs/contract/src/lib/avails/tests/mandateTerms.spec.ts
- libs/contract/src/lib/term/+state/term.model.ts
Filter durations based on AvailsForm, DB & bucket
> filters durations

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- libs/campaign/src/lib/+state/campaign.service.ts
- libs/campaign/src/lib/components/perk-card/perk-card.component.ts
- libs/campaign/src/lib/form/campaign.shell.config.ts
- libs/consents/src/lib/+state/consents.service.spec.ts
- libs/consents/src/lib/+state/consents.store.ts
- libs/e2e/src/index.ts
- libs/e2e/src/lib/fixtures/movies.ts
- libs/e2e/src/lib/fixtures/orgs.ts
- libs/e2e/src/lib/utils/functions.ts
- libs/e2e/src/lib/utils/queryinterface.ts
- libs/movie/src/lib/movie/form/movie.shell.config.ts
- libs/movie/src/lib/movie/form/movie.shell.interfaces.ts
> linter cleaning bruce part 2

- libs/import/src/index.ts
- libs/import/src/lib/components/import-spreadsheet/import-spreadsheet.component.ts
- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/import/src/lib/components/view-extracted-elements/organizations/view-extracted-organizations.component.ts
- libs/import/src/lib/import.module.spec.ts
- libs/import/tsconfig.lib.json
`  private mapping = {} as Record<fieldsKey, any>;
`
> Mano nx 12 lintfix import

- libs/testing/src/lib/firebase/auth.ts
- libs/testing/src/lib/firebase/functions.ts
- libs/testing/tsconfig.lib.json
Fix  es-lint errors 
Remove ts-lint rules
> Fix Linter error for testing lib

- apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/commands.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventPage.ts
Fix lint errors in festival-e2e.
> Fix lint errors in festival-e2e

- apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
- apps/financiers/financiers/src/polyfills.ts
2 any types are still used which I couldn't remove.
> financiers linter

- libs/utils/src/lib/animations/animation.ts
- libs/utils/src/lib/common-interfaces/identity.ts
- libs/utils/src/lib/dynamic-title/dynamic-title.service.ts
- libs/utils/src/lib/form/matchers.ts
- libs/utils/src/lib/ip.ts
- libs/utils/src/lib/pipes/sort-array.pipe.ts
- libs/utils/src/lib/static-model/static-model.ts
From 79 warnings to 64 warnings.
> Utils warnings fix

- libs/ui/src/lib/form/table/form-table.component.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.ts
- libs/utils/src/lib/browser/utils.ts
- libs/utils/src/lib/common-interfaces/price.ts
- libs/utils/src/lib/common-interfaces/range.ts
- libs/utils/src/lib/directives/col-ref.directive.ts
- libs/utils/src/lib/emails/utils.ts
- libs/utils/src/lib/file-sanitizer.ts
- libs/utils/src/lib/form/forms/entity.form.ts
- libs/utils/src/lib/form/forms/list.form.ts
- libs/utils/src/lib/form/validators/validators.ts
- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
- libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.ts
- libs/utils/src/lib/imdb/service.ts
- libs/utils/src/lib/models-meta.ts
- libs/utils/src/lib/pipes/deep-key.pipe.ts
- libs/utils/src/lib/pipes/display-user.pipe.ts
- libs/utils/src/lib/pipes/duration.pipe.ts
- libs/utils/src/lib/pipes/filter-by-date.pipe.ts
- libs/utils/src/lib/pipes/find.pipe.ts
- libs/utils/src/lib/pipes/has-keys.pipe.ts
- libs/utils/src/lib/pipes/number.pipe.ts
- libs/utils/src/lib/pipes/to-array.pipe.ts
- libs/utils/src/lib/spreadsheet/format.ts
- libs/utils/src/lib/yandex-metrica/yandex-metrica.service.ts
Fixed all errors, no warnings, for utils lib.
> Utils lint fix

- libs/utils/src/lib/analytics/app-analytics.ts
- libs/utils/src/lib/common-interfaces/price.ts
- libs/utils/src/lib/directives/col-ref.directive.ts
- libs/utils/src/lib/emails/utils.ts
- libs/utils/src/lib/helpers.ts
- libs/utils/src/lib/sentry.module.ts
- libs/utils/src/lib/static-model/static-model.ts
- libs/utils/src/lib/table/table-utils.ts
- libs/utils/src/lib/yandex-metrica/yandex-metrica.service.ts
From 65 warnings to 45 warnings...
> Utils warnings fixes

- libs/utils/src/lib/pipes/deep-key.pipe.ts
- libs/utils/src/lib/pipes/display-name.pipe.ts
- libs/utils/src/lib/pipes/filter-by-date.pipe.ts
- libs/utils/src/lib/pipes/has-keys.pipe.ts
- libs/utils/src/lib/pipes/number.pipe.ts
- libs/utils/src/lib/pipes/sort-array.pipe.ts
- libs/utils/src/lib/pipes/to-array.pipe.ts
Fixed most of the warnings on pipes.
From 45 warnings to 34...
> Warning pipes

- apps/catalog/catalog-e2e/src/plugins/index.js
- apps/crm/crm-e2e/src/plugins/index.js
- apps/festival/festival-e2e/src/plugins/index.js
- apps/financiers/financiers-e2e/src/plugins/index.js
Removed webpack issue
Tests are running without these legacy code.
> Mano e2e fail webpack issue

- apps/catalog/catalog-e2e/src/plugins/index.js
- apps/crm/crm-e2e/src/plugins/index.js
- apps/festival/festival-e2e/src/plugins/index.js
- apps/financiers/financiers-e2e/src/plugins/index.js
Fix webpack error with plugin import
> Remove typescript preprocessor plugin dependency

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- libs/media/src/lib/+state/media.firestore.ts
- libs/media/src/lib/file/explorer/explorer.model.ts
- libs/media/src/lib/file/file-list-uploader/file-list-uploader.component.ts
- libs/media/src/lib/file/upload-widget/upload-widget.component.ts
- libs/movie/src/lib/movie/form/media-notes/notes.component.ts
- libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
- libs/utils/src/lib/error-logger.module.ts
- libs/utils/src/lib/pipes/deep-key.pipe.ts
Some more complicated fixes for the warnings of the utils lib.
> Utils fixes

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
- libs/contract/src/lib/avails/avails.ts
- libs/contract/src/lib/avails/calendar/calendar.component.scss
- libs/contract/src/lib/avails/calendar/calendar.component.ts
- libs/contract/src/lib/avails/calendar/calendar.model.ts
- libs/contract/src/lib/avails/tests/bucketForm.spec.ts
- libs/contract/src/lib/avails/tests/bucketTerm.spec.ts
- libs/contract/src/lib/avails/tests/calendar.spec.ts
- libs/contract/src/lib/bucket/form.ts
tag issue #5706
_moved from #5826_
> Add to preselected rights

- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- libs/contract/src/lib/bucket/+state/bucket.model.ts
> 5811 User Feedback Selection Page

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
> Calendar Modal

- apps/backend-functions/src/internals/invitations/organizations.ts
- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/templates/mail.ts
- apps/backend-functions/src/users.ts
- libs/import/src/lib/components/table-extracted-elements/organizations/organizations.component.ts
- libs/user/src/lib/auth/+state/auth.service.ts
- libs/utils/src/lib/emails/utils.ts
Add a new org object for email templates.
Part of #5186
> Org object email

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- libs/contract/src/lib/avails/calendar/calendar.component.ts
> Reset on clear

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts
- libs/contract/src/lib/term/form/filter/avails/avails-filter.component.html
part of #5887 
- On the avails filter, add placeholders on "start date" & "end date" fields: "MM/DD/YYYY"
- We miss the edit button on each terms cf zeplin
- Warning modale when you haven't saved your rights has broken UI buttons
- On preselected rights, add a tooltip "Edit" and "Delete" on the action buttons
> part of #5887 

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
- libs/contract/src/lib/avails/avails.ts
- libs/contract/src/lib/avails/calendar/calendar.component.ts
- libs/contract/src/lib/avails/tests/bucketForm.spec.ts
- libs/contract/src/lib/avails/tests/bucketTerm.spec.ts
- libs/contract/src/lib/bucket/form.ts
> reactive & refactored

- apps/backend-functions/src/notification.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/templates/ids.ts
- apps/backend-functions/src/templates/mail.ts
- libs/notification/src/lib/+state/notification.firestore.ts
issue: #5806 
Do not forget to deploy the backend-functions after this merge
> email information for users requesting app access ok

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
> Handle in selection calendar markers

- apps/catalog/catalog/src/app/landing/landing.component.html
- apps/festival/festival/src/app/landing/landing.component.html
- apps/financiers/financiers/src/app/landing/landing.component.html
- libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.ts
- libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.ts
> Join now and signup buttons redirected to identity

- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
fix issue #5922 
https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp
> 5922 Fix separator

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
- libs/contract/src/lib/avails/calendar/calendar.component.scss
- libs/contract/src/lib/avails/calendar/calendar.component.ts
- libs/contract/src/lib/avails/calendar/calendar.model.ts
> ui & bug fixes

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.scss
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.html
- apps/financiers/financiers/src/app/dashboard/title/list/list.component.scss
- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.html
- styles/components/mat-list.scss
> Movie release fixes

- apps/cms/src/app/shell/shell.module.ts
> 5907 prevent access cms

- apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.scss
- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.scss
> Remove underline

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> 5900 edit btn on selection page and currency label

- libs/ui/src/lib/error/error-not-found.module.ts
- libs/ui/src/lib/error/not-found/not-found.component.html
- libs/ui/src/lib/error/not-found/not-found.component.scss
- libs/ui/src/lib/form/time-picker/time-picker.component.ts
comment: https://github.com/blockframes/blockframes/issues/5910#issuecomment-853833806
original ticket: #5666
> 404 not found reworked + time hours list event rolled back

- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/utils/src/lib/spreadsheet/format.ts
fix import/update issue  for #5906
> Feat 5898 c

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.scss
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/event/src/lib/guard/event.guard.ts
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/media/src/lib/file/explorer/explorer.component.ts
- libs/media/src/lib/file/picker/picker.component.ts
- libs/media/src/lib/file/preview/preview.component.html
- libs/media/src/lib/file/preview/preview.component.scss
- libs/media/src/lib/file/preview/preview.module.ts
- libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
- libs/ui/src/lib/confirm/confirm.component.html
- libs/ui/src/lib/confirm/confirm.component.scss
- libs/ui/src/lib/confirm/confirm.component.ts
- libs/ui/src/lib/confirm/confirm.module.ts
- libs/ui/src/lib/preview-modal/preview.component.html
- libs/ui/src/lib/preview-modal/preview.component.ts
> 5903 modal

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- libs/contract/src/lib/term/components/detailed/detailed.component.html
- libs/contract/src/lib/term/components/detailed/detailed.component.scss
- libs/contract/src/lib/term/components/detailed/detailed.component.ts
- libs/contract/src/lib/term/components/detailed/detailed.module.ts
> 5900 Padding close icon modal

- libs/movie/src/lib/movie/form/movie.form.ts
- libs/utils/src/lib/form/validators/validators.ts
Related to this [comment](https://github.com/blockframes/blockframes/issues/5897#issuecomment-853835606)
> url validator

- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
- apps/financiers/financiers/src/app/landing/landing.component.html
> 4k fixes 5900 5907

- apps/backend-functions/src/main.ts
- apps/backend-functions/src/users.ts
- libs/admin/src/lib/admin-panel/pages/user/user.component.html
- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
Add ability to verify email in CRM
> manually verify email

- libs/contract/src/lib/avails/calendar/calendar.component.ts
> fix safari

- libs/media/src/lib/image/directives/image.directive.ts
- libs/movie/src/lib/movie/components/card/card.component.html
- libs/movie/src/lib/movie/components/card/card.component.scss
fixed image flicker bug on page load.
> fixed image flicker

- libs/user/src/lib/auth/auth.module.ts
- libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html
- libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.ts
- libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html
- libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.ts
- libs/user/src/lib/auth/pages/identity/identity.component.html
> fixed(privavcy and terms page):hide back arrow on new page

- libs/movie/src/lib/movie/form/movie.shell.config.ts
Fix prod status bug
Close #5529
> fix production status

- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
- libs/ui/src/lib/static-autocomplete/group/group.component.html
- libs/ui/src/lib/static-autocomplete/group/group.component.ts
- styles/components/mat-form-field.scss
> improve style

- libs/media/src/lib/image/directives/image.directive.ts
- libs/movie/src/lib/movie/components/card/card.component.html
fix image bug introduce after img-directive update
> fix image size bug

- libs/firebase-utils/src/lib/anonymize/lib.spec.ts
- libs/firebase-utils/src/lib/anonymize/lib.ts
previous one was removed.
Named this one `DO NOT DELETE - TEST VIDEO.mp4`
> update anon video id Vzo4bhS5

- libs/contract/src/lib/bucket/+state/bucket.service.ts
- libs/contract/src/lib/contract/+state/contract.model.ts
- libs/contract/src/lib/offer/+state/offer.model.ts
resolve some items of the CRM pre-work defined in #5984
> CRM Prework

- apps/financiers/financiers/src/app/dashboard/title/view/view.component.ts
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- libs/campaign/src/lib/dashboard/investment/investment.component.html
- libs/campaign/src/lib/marketplace/financing/financing.component.html
- libs/campaign/src/lib/marketplace/investment/investment.component.html
> 5905 Financiers

- libs/ui/src/lib/list/table-filter/table-filter.component.scss
> Spacing in table

- apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html
- styles/components/mat-form-field.scss
> Fix icon color

- libs/invitation/src/lib/form/user/user.component.html
- libs/invitation/src/lib/form/user/user.component.ts
> Space separator

- libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
- libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.ts
> Disable CTA button when form is invalid fixed

- apps/catalog/catalog/src/app/marketplace/marketplace.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/selection/specific-terms/specific-terms.component.ts
- libs/contract/src/lib/bucket/+state/bucket.service.ts
> Issue login view selection replace akita

- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- libs/media/src/lib/file/carousel/carousel.component.html
- libs/media/src/lib/file/carousel/carousel.component.ts
> 5746 Stop sharing unselects file

- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- libs/movie/src/lib/movie/dashboard/shell/shell.module.ts
> tag movie app access status added (UI WIP)

- apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
- apps/festival/festival/src/app/marketplace/title/view/view.component.html
- apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
- libs/contract/src/lib/bucket/+state/bucket.service.ts
- libs/contract/src/lib/income/+state/income.model.ts
- styles/components/mat-tooltip.scss
Fix https://github.com/blockframes/blockframes/issues/5668
> fix color in tooltip

- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.scss
- styles/components/mat-chips.scss
- styles/themes/builder.scss
issue: #6084 
comment: https://github.com/blockframes/blockframes/issues/6084#issuecomment-866796355
> new tag status movie app access with right css

- apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html
- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html
- apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.html
- libs/movie/src/lib/movie/dashboard/shell/shell.component.ts
> binded some action buttons #6084

- libs/admin/src/lib/admin-panel/pages/user/user.component.html
- libs/firebase-utils/src/lib/firestoreMigrations/0064.ts
- libs/firebase-utils/src/lib/firestoreMigrations/index.ts
- libs/firebase-utils/src/lib/types.ts
- libs/testing/src/lib/firebase/auth.ts
- libs/user/src/lib/auth/+state/auth.service.ts
- libs/user/src/lib/user/+state/user.service.ts
- libs/utils/src/lib/models-meta.ts
> 6089 Add email verified to user meta data

- libs/admin/src/lib/admin-panel/pages/offers/shell/contract-view/contract-view.component.html
- libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html
- libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.html
- libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.scss
- libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
- libs/admin/src/lib/admin-panel/pages/offers/shell/shell.module.ts
- libs/contract/src/lib/bucket/+state/bucket.service.ts
- libs/contract/src/lib/offer/+state/offer.model.ts
- libs/contract/src/lib/offer/+state/offer.service.ts
- libs/organization/src/lib/organization/components/chip/chip.component.html
- libs/organization/src/lib/organization/components/chip/chip.component.ts
> crm offer shel

- libs/movie/src/lib/movie/pipes/analytics.pipe.ts
Potential fix #6101
On my environment I could not reproduce the issue of infinite loading. But I did see the data coming through 5 times. This reduces it to one. It might fix the infinite reload issue too (or at least hide it)
> 6101 Dashboard analytics infinite reload

- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.html
- libs/admin/src/lib/admin-panel/pages/organizations/organizations.component.ts
- libs/admin/src/lib/admin-panel/pages/user/user.component.ts
Anastasiia requested some fields for CRM
> 4815 Updating fields

- apps/backend-functions/src/bigQuery.ts
> 6122 Remove duplicates

- apps/rules/src/tests/firestore/blockframes.spec.ts
- firestore.rules
- libs/testing/src/lib/firebase/auth.ts
- libs/ui/src/lib/maintenance/maintenance.service.ts
Feat 6127 - fiix anon db verified email & disable maintenance screen for next release
> Feat 6127 - fiix anon db verified email & disable maintenance screen for next release

- libs/admin/src/lib/admin-panel/admin-panel.module.ts
- libs/admin/src/lib/admin-panel/pages/offers/list/offer-list.component.html
- libs/admin/src/lib/admin-panel/pages/offers/shell/contract-view/contract-view.component.html
- libs/admin/src/lib/admin-panel/pages/offers/shell/contract-view/contract-view.component.ts
- libs/admin/src/lib/admin-panel/pages/offers/shell/contract-view/contract-view.module.ts
- libs/contract/src/lib/contract/item/contract-item.component.html
Add an input-confirm dialog when deleting a term in the CRM's ContractView.
> ContractView confirm on delete
