libs/admin/src/lib/admin-panel/pages/offers/list/offer-list.component.html
=> Offer Currency

libs/utils/src/lib/spreadsheet/format.spec.ts, libs/utils/src/lib/spreadsheet/format.ts
=> Improve formatSingleValue function

apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
=> Solve e2e failure on bucket

env/env.blockframes-remco.ts, env/env.blockframes-staging.ts, env/env.blockframes.ts, libs/admin/src/lib/admin-panel/pages/events/events.component.html
Add events dashboard for issue #6087
=> 6087 Add events dashboard

apps/backend-functions/src/users.ts, libs/admin/src/lib/admin-panel/pages/user/user.component.ts, libs/utils/src/lib/models-meta.ts
=> 6111 Update email verified meta of user

libs/movie/src/lib/movie/dashboard/actions/actions.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.html
issue: https://github.com/blockframes/blockframes/issues/6084#issuecomment-871583655
=> Small updates

apps/festival/festival/src/app/marketplace/event/view/view.component.html, apps/festival/festival/src/app/marketplace/organization/view/view.component.html
=> Event view and org view contact button stroke to flat

libs/utils/src/lib/pipes/display-user.pipe.ts
=> fix Answering invitations reload user name

apps/backend-functions/src/contracts.ts
=> Avoid deleting offers

apps/backend-functions/src/users.ts, env/env.blockframes-remco.ts, env/env.blockframes-staging.ts, env/env.blockframes.ts, libs/admin/src/lib/admin-panel/pages/events/events.component.html, libs/admin/src/lib/admin-panel/pages/user/user.component.ts, libs/media/src/lib/file/viewers/utils.ts, libs/utils/src/lib/models-meta.ts
Merged #6158 and #6159 into develop already but should have been in fix-for-release-3-2-1
#6171 is not on develop yet but PR was already approved
=> 6158 6159 and 6171

apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
=> 6176 Add margin to currency field

apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts, libs/contract/src/lib/contract/item/contract-item.component.html, libs/contract/src/lib/contract/item/contract-item.module.ts, libs/ui/src/lib/static-autocomplete/group/group.component.html, libs/ui/src/lib/static-autocomplete/group/group.module.ts, libs/utils/src/lib/pipes/group-label.pipe.ts
Refactored to return arrays to permit using with mat-chips.
=> refactor toGroupLabel to return array

apps/catalog/catalog/src/app/marketplace/title/avails/avails.module.ts, libs/contract/src/lib/bucket/+state/bucket.service.ts, libs/utils/src/lib/utils.ts
=> feat(utils):implemented createOfferId method

libs/invitation/src/lib/form/user/user.component.ts, libs/organization/src/lib/organization/components/member-add/member-add.component.ts
=> 6182 No double invitations

libs/user/src/lib/auth/pages/identity/identity.component.html, libs/user/src/lib/auth/pages/identity/identity.component.ts
=> 6200 Show error earlier

apps/festival/festival-e2e/src/integration/landing/email-check.spec.ts, apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
=> Improve code testability to make the tests pass

libs/admin/src/lib/admin-panel/pages/offers/list/offer-list.component.html, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.module.ts, libs/contract/src/lib/contract/+state/contract.model.ts
=> Add a title to an offer.

apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
Fix variable for financiers emails.
=> Financiers email

apps/backend-ops/src/firebaseSetup.ts, apps/backend-ops/src/main.ts
=> revert #6127

libs/admin/src/lib/admin-panel/components/dashboard/dashboard.component.ts, libs/admin/src/lib/admin-panel/pages/user/user.component.html, libs/admin/src/lib/admin-panel/pages/user/user.component.ts
=> 6089 Add snackbar and fix dashboard

libs/utils/src/lib/file-sanitizer.ts
=> replace two or more dots by only one

apps/catalog/catalog-e2e/src/integration/dashboard/import.spec.ts, libs/e2e/src/lib/fixtures/users.ts
=> Mano e2e nightly import fail fix

libs/ui/src/lib/dashboard/pages/home/home.component.html, libs/ui/src/lib/dashboard/pages/home/home.component.ts
=> 5676 dashboard home titles app specific

libs/landing/src/lib/shell/shell.component.ts, libs/ui/src/lib/theme/theme.service.ts
=> 6064 Force light theme on landing page

libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html, libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.ts, libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.module.ts
=> Polishing contract form

libs/invitation/src/lib/form/user/user.component.ts
=> fix inviting issue

libs/admin/src/lib/admin-panel/pages/movies/movies.component.ts
Fixed columns for movie overview issue #3264
=> 3264 Fix movie columns

apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.ts, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.ts, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.ts, libs/movie/src/lib/movie/dashboard/shell/shell.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.scss, libs/ui/src/lib/tunnel/layout/layout.component.ts
Add a new error message on the summary page inside the movie tunnel.
Fix #6181
=> Summary Error Message

apps/catalog/catalog/src/app/marketplace/marketplace.component.html, apps/catalog/catalog/src/app/marketplace/marketplace.module.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.scss, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.module.ts, libs/contract/src/lib/income/pipe.ts, libs/contract/src/lib/offer/pipe.ts
=> marketplace offer shell

apps/catalog/catalog/src/app/dashboard/title/list/list.component.html, apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/title/list/list.module.ts, apps/festival/festival/src/app/dashboard/title/list/list.component.html, apps/festival/festival/src/app/dashboard/title/list/list.component.ts, apps/festival/festival/src/app/dashboard/title/list/list.module.ts, libs/movie/src/lib/movie/+state/movie.service.ts, libs/movie/src/lib/movie/pipes/analytics.pipe.ts, package-lock.json, package.json
=> 6121 add views to movie data

apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.ts, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.ts, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.ts, libs/movie/src/lib/movie/dashboard/shell/shell.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.scss, libs/ui/src/lib/tunnel/layout/layout.component.ts
Add a new error message on the summary page of movie tunnel
=> New Error Message

apps/backend-functions/src/main.ts, apps/backend-functions/src/sendgrid.ts
Listens to SendGrid Events webhook and inserts the data into bigquery
Would be nice to have this in the release 3.3 so we can start gathering data about email traffic
=> 6088 webhook listener sendgrid to bigquery

apps/backend-functions/src/internals/email.ts, apps/backend-functions/src/sendgrid.ts
To do in issue #6088 distinguish between source project so analytics can be filtered accordingly
=> 6088 distinguish between project

libs/movie/src/lib/movie/components/slide/slide.component.html, libs/movie/src/lib/movie/components/slide/slide.component.scss, libs/movie/src/lib/movie/components/slide/slide.component.ts, libs/movie/src/lib/movie/components/slide/slide.module.ts
=> adding logline to slide component

libs/media/src/lib/file/explorer/explorer.component.scss, libs/media/src/lib/file/file-list-uploader/file-list-uploader.component.scss
Change UI of file explorer
Fix #6053
=> File explorer

libs/movie/src/lib/movie/form/filters/release-year/release-year.component.html, libs/movie/src/lib/movie/form/filters/release-year/release-year.component.scss
Removed 2030 label
issue #6066
=> 6066 remove 2030 label

apps/catalog/catalog/src/app/dashboard/title/view/view.component.ts, apps/catalog/catalog/src/app/dashboard/title/view/view.module.ts, apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.module.ts, libs/media/src/lib/pipes/storageFile.pipe.ts, libs/movie/src/lib/movie/dashboard/delivery/delivery.component.html, libs/movie/src/lib/movie/dashboard/delivery/delivery.component.scss, libs/movie/src/lib/movie/dashboard/delivery/delivery.component.ts, libs/movie/src/lib/movie/dashboard/delivery/delivery.module.ts, libs/movie/src/lib/movie/form/available-materials/available-materials.module.ts, libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.html, libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.scss, libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.ts, libs/movie/src/lib/movie/form/summary/summary.module.ts
=> Added available summary materials to movie summary

apps/backend-functions/src/package.json, apps/backend-functions/src/sendgrid.ts, package-lock.json, package.json
=> 6088 verify request is from sendgrid

libs/contract/src/lib/bucket/+state/bucket.service.ts
Fallback to an empy array if the bucket has no holdbacks
=> quickfix on bug introduced by holdbacks

apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts, libs/contract/src/lib/bucket/+state/bucket.service.ts, libs/contract/src/lib/contract/+state/contract.model.ts, libs/contract/src/lib/contract/+state/contract.service.ts
fix #6325
fix total that could be an empty string
use createBucket in formatFromFirestore
=> Fix issues with selection page

apps/backend-ops/src/algolia.ts, apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, apps/festival/festival/src/app/marketplace/title/list/list.component.ts, apps/financiers/financiers/src/app/marketplace/title/list/list.component.ts, libs/firebase-utils/src/lib/algolia/algolia.ts, libs/movie/src/lib/movie/form/search.form.ts, libs/utils/src/lib/algolia/algolia.interfaces.ts
Add some attribute to be searchable by user on the movie on algolia.
Allow also user to do several queries, I mean that they will be able to look for different characteristics.
Ex : user types `France, action, tribeca` in the search bar, it will look for every movie that has at least one of this characteristics.
Fix #6138
=> More searchable attribute

libs/invitation/src/lib/form/user/user.component.ts
=> automatically accept requests to attend event when inviting

apps/backend-functions/src/contracts.ts, apps/backend-functions/src/main.ts, apps/backend-functions/src/utils.ts, firestore.rules, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts, libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.module.ts, libs/contract/src/lib/offer/+state/offer.model.ts, libs/contract/src/lib/offer/list/list.component.html, libs/contract/src/lib/offer/list/list.component.ts, libs/utils/src/lib/pipes/total.pipe.ts
=> Offer status

libs/contract/src/lib/offer/+state/offer.service.ts, libs/contract/src/lib/offer/list/list.component.html, libs/contract/src/lib/offer/list/list.component.ts
=> fix income rule bug

libs/utils/src/lib/operators.ts
Operator to lazily load subcollections
=> create joinWith operator

apps/backend-functions/src/environments/environment.prod.ts, apps/backend-functions/src/environments/environment.ts, apps/backend-functions/src/player.ts, env/env.blockframes-bruce.ts, env/env.blockframes-ci.ts, env/env.blockframes-clelia.ts, env/env.blockframes-demo-1.ts, env/env.blockframes-demo-2.ts, env/env.blockframes-demo-3.ts, env/env.blockframes-demo-4.ts, env/env.blockframes-demo-5.ts, env/env.blockframes-francois.ts, env/env.blockframes-george.ts, env/env.blockframes-jeremie.ts, env/env.blockframes-mano.ts, env/env.blockframes-pl-2.ts, env/env.blockframes-remco.ts, env/env.blockframes-samir.ts, env/env.blockframes-staging.ts, env/env.blockframes-vincent.ts, env/env.blockframes-yonga.ts, env/env.blockframes.ts
Migrate devs toward another jwp property
=> split properties

libs/media/src/lib/file/explorer/explorer.component.ts, libs/media/src/lib/file/explorer/explorer.module.ts, libs/media/src/lib/file/preview-list/preview-list.component.html, libs/media/src/lib/file/preview-list/preview-list.component.scss, libs/media/src/lib/file/preview-list/preview-list.component.ts, libs/media/src/lib/file/preview-list/preview-list.module.ts, libs/media/src/lib/file/preview/preview.component.html, libs/media/src/lib/file/preview/preview.component.scss, libs/media/src/lib/file/preview/preview.component.ts, libs/media/src/lib/file/preview/preview.module.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.module.ts
=> 5799 navigate next and previous in file preview modal

libs/invitation/src/lib/invitation.component.html
Add redirection button on empty invitation page
=> Invitation button page

apps/crm/crm/src/app/crm/pages/offers/shell/offer-view/offer-view.component.ts
=> added paragraph on right delete modal

env/env.blockframes-yonga.ts, libs/admin/src/lib/crm/+state/crm.service.ts
=> fixed(crm):reset password uses sendgrid reset password template

libs/organization/src/lib/organization/guard/pending-organization.guard.ts, libs/organization/src/lib/organization/pages/organization-pending/organization-pending.component.html, libs/organization/src/lib/organization/pages/organization-pending/organization-pending.component.scss, libs/organization/src/lib/organization/pages/organization-pending/organization-pending.component.ts, libs/organization/src/lib/organization/pages/request-access/request-access.component.html, libs/organization/src/lib/organization/pages/request-access/request-access.component.scss, libs/organization/src/lib/organization/pages/request-access/request-access.component.ts
=> #6382 part 1 

apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
=> fixed(avails):show colliding holdbacks only when present

libs/media/src/lib/file/file-uploader/file-uploader.component.html, libs/media/src/lib/image/uploader/uploader.component.html, styles/components/bf-font-color.scss, styles/typography.scss
=> 6443 Make h2 a bit bigger

assets/icons/refresh-filters.svg, libs/invitation/src/lib/components/item/item.component.html, libs/invitation/src/lib/components/item/item.component.scss, libs/invitation/src/lib/invitation.component.html, libs/invitation/src/lib/invitation.module.ts
=> 6493 Fix UI Invitations

apps/backend-functions/src/environments/environment.prod.ts, apps/backend-functions/src/environments/environment.ts, apps/backend-functions/src/jwplayer-api.ts, apps/backend-functions/src/package.json, apps/backend-functions/src/player.ts, apps/backend-functions/src/rescue.ts, apps/backend-functions/src/utils.ts, package-lock.json, package.json
migrate everything that can be migrated to api v2
- video upload
- get video duration (used in meeting)
- delete video
=> migrate to jwp api v2

styles/components/mat-table.scss
=> 6413 fix tiny corner on table

apps/catalog/catalog/src/app/dashboard/dashboard.component.html, apps/festival/festival/src/app/dashboard/dashboard.component.html, apps/financiers/financiers/src/app/dashboard/dashboard.component.html
=> 6448 change icon buyer platform

apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
=> selections empty stste padding.

firestore.rules
=> fix rules that prevent invited users to continue onboarding

libs/user/src/lib/user/+state/user.service.ts
=> fix #6563 issue with "verifiedEmail" when user is invited

angular.json, apps/backend-functions/src/environments/environment.ci.ts, apps/backend-functions/src/environments/environment.ts, apps/backend-functions/src/templates/mail.ts, firestore.rules
=> Fix cypress not found in backend issue

firestore.indexes.json
=> added missing index shown in sentry #6568

libs/organization/src/lib/organization/+state/organization.firestore.ts
=> orgName pipe fix in case of missing denomination attr

apps/crm/crm/src/app/crm/pages/organization/organization.component.ts, apps/crm/crm/src/app/crm/pages/user/user.component.ts, libs/organization/src/lib/organization/+state/organization.service.ts, libs/organization/src/lib/organization/guard/request-access.guard.ts, libs/organization/src/lib/permissions/+state/permissions.service.ts, libs/user/src/lib/auth/pages/identity/identity.component.html, libs/user/src/lib/auth/pages/identity/identity.component.scss, libs/user/src/lib/auth/pages/identity/identity.component.ts, libs/utils/src/lib/routes/app.guard.ts
=> logout on onboarding page if already logged in

angular.json, apps/backend-functions/src/environments/environment.ci.ts, apps/backend-functions/src/environments/environment.ts, apps/backend-functions/src/templates/mail.ts, apps/crm/crm/src/app/crm/pages/organization/organization.component.ts, apps/crm/crm/src/app/crm/pages/user/user.component.ts, apps/festival/festival/src/app/landing/landing.component.html, firestore.indexes.json, firestore.rules, libs/contract/src/lib/avails/sets.ts, libs/organization/src/lib/organization/+state/organization.firestore.ts, libs/organization/src/lib/organization/+state/organization.service.ts, libs/organization/src/lib/organization/guard/request-access.guard.ts, libs/organization/src/lib/permissions/+state/permissions.service.ts, libs/user/src/lib/auth/pages/identity/identity.component.html, libs/user/src/lib/auth/pages/identity/identity.component.scss, libs/user/src/lib/auth/pages/identity/identity.component.ts, libs/user/src/lib/user/+state/user.service.ts, libs/utils/src/lib/routes/app.guard.ts
=> Fix for release 3.4

libs/event/src/lib/components/meeting/+state/twilio.service.ts, libs/organization/src/lib/organization/components/member-repertory/member-repertory.component.html
=> Fix not showing participants when joining meeting

libs/user/src/lib/user/+state/user.service.ts, libs/utils/src/lib/form/validators/validators.ts
=> fixed(validators.ts):proper cross validation of date fields on update

apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts, libs/contract/src/lib/term/form/runs/runs-form.component.html
=> Selection page bugs

apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html, apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html, apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts, libs/contract/src/lib/contract/+state/contract.model.ts, libs/contract/src/lib/contract/holdback/list/list.component.html, libs/contract/src/lib/contract/holdback/list/list.component.ts, libs/contract/src/lib/contract/holdback/list/list.module.ts, libs/contract/src/lib/contract/item/contract-item.component.html, libs/contract/src/lib/offer/list/list.component.html, libs/contract/src/lib/term/components/detailed/detailed.component.ts, libs/utils/src/lib/pipes/group-label.pipe.ts, libs/utils/src/lib/pipes/to-label.pipe.ts, libs/utils/src/lib/static-model/groups.ts, libs/utils/src/lib/static-model/static-model.ts
=> Territories dialog & some other fixes

libs/contract/src/lib/contract/holdback/form.ts, libs/contract/src/lib/contract/holdback/form/form.component.html, libs/contract/src/lib/contract/holdback/form/form.component.ts, libs/contract/src/lib/contract/holdback/list/list.component.html, libs/contract/src/lib/contract/holdback/modal/holdback-modal.component.html
=> Holdbacks page bugs

apps/backend-functions/src/utils.ts
=> 6532 fix video duration

apps/backend-functions/src/internals/email.ts, apps/backend-functions/src/internals/invitations/organizations.ts, apps/backend-functions/src/internals/users.ts, apps/backend-functions/src/movie.ts, apps/backend-functions/src/notification.ts, apps/backend-functions/src/orgs.ts, apps/backend-functions/src/templates/mail.ts, apps/backend-functions/src/users.ts, apps/backend-functions/src/utils.ts, apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts, apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, env/env.blockframes.ts, libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts, libs/utils/src/lib/apps.ts, libs/utils/src/lib/emails/ids.ts, libs/utils/src/lib/request-demo.ts
=> Fix #6527 part 1

apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html, apps/catalog/catalog/src/app/dashboard/contracts/view/view.guard.ts, apps/catalog/catalog/src/app/dashboard/dashboard.module.ts, apps/crm/crm/src/app/crm/pages/offers/shell/contract-form/contract-form.component.scss, apps/crm/crm/src/app/crm/pages/offers/shell/contract-form/contract-form.component.ts, apps/crm/crm/src/app/crm/pages/offers/shell/contract-view/contract-view.component.html, apps/crm/crm/src/app/crm/pages/offers/shell/contract-view/contract-view.component.ts, apps/crm/crm/src/app/crm/pages/offers/shell/contract-view/contract-view.module.ts, libs/contract/src/lib/income/pipe.ts, libs/contract/src/lib/term/components/detailed/detailed.component.ts
=> 6554 last fixes

apps/backend-functions/src/templates/mail.ts, apps/backend-functions/src/users.ts, apps/crm/crm/src/app/crm/pages/user/user.component.ts, libs/admin/src/lib/crm/+state/crm.service.ts, libs/user/src/lib/auth/+state/auth.service.ts, libs/utils/src/lib/emails/ids.ts
Better email when reset password is sent from CRM.
=> 6533 fix reset password from crm

apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.ts, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.ts, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.ts, libs/ui/src/lib/tunnel/layout/layout.component.ts, libs/utils/src/lib/pipes/from-camel-case.pipe.ts, styles/components/bf-tunnel.scss
=> fix blocking fields

apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html, apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.scss, apps/catalog/catalog/src/app/dashboard/contracts/view/view.module.ts
@Jackseed asked me to replace existing header of catalog dashboard view by this
=> org in header

libs/media/src/lib/file/preview-list/preview-list.component.html, libs/media/src/lib/file/preview-list/preview-list.component.scss, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.component.scss
=> part 3 #6527

apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts, libs/contract/src/lib/contract/holdback/list/list.component.html, libs/contract/src/lib/contract/item/contract-item.component.html
solve #6626 and some other small things
=> bugfixes & improvements

apps/catalog/catalog/src/app/marketplace/home/home.component.scss, apps/festival/festival/src/app/marketplace/home/home.component.scss, apps/financiers/financiers/src/app/marketplace/home/home.component.scss
=> 6175 smaller margin on banner

apps/backend-functions/src/users.ts, libs/landing/src/lib/shell/shell.component.ts
=> remove unsubscribe link from demo mail

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/contract/src/lib/avails/avails.ts, libs/utils/src/lib/static-model/static-model.ts
solve #6619 and some items of #6567
=> Refactor list page

apps/backend-functions/src/player.ts, apps/backend-functions/src/rescue.ts, apps/backend-functions/src/utils.ts, apps/backend-ops/src/main.ts, apps/backend-ops/src/rescueJWP.ts, libs/firebase-utils/src/index.ts, libs/firebase-utils/src/lib/firebase-utils.ts, libs/firebase-utils/src/lib/jwplayer-api.ts, libs/firebase-utils/src/lib/node-request.ts, libs/media/src/lib/+state/media.model.ts
=> Better jwp script

libs/movie/src/lib/movie/form/filters/release-year/release-year.component.ts, libs/movie/src/lib/movie/form/search.form.ts
=> 6654 missing titles on titles page

apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, apps/cms/src/app/home/orgs/orgs.component.ts, apps/cms/src/app/home/slider/slider.component.ts, apps/cms/src/app/home/titles/titles.component.ts, apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts, libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/tests/mandateTerms.spec.ts, libs/contract/src/lib/avails/tests/territories.spec.ts, libs/invitation/src/lib/+state/invitation.service.ts, libs/ui/src/lib/dashboard/pages/home/home.component.ts, libs/ui/src/lib/layout/dashboard/dashboard.component.ts, libs/ui/src/lib/layout/layout.module.ts, libs/ui/src/lib/static-autocomplete/group/group.component.ts, libs/ui/src/lib/tunnel/layout/layout.component.ts, libs/utils/src/lib/form/forms/entity.form.ts
=> [CATALOG] Refactoring Marketplace Title List `addAvail()`

apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/form/avails.form.ts, libs/contract/src/lib/avails/tests/mandateTerms.spec.ts, libs/contract/src/lib/bucket/+state/bucket.service.ts
solve the `addAvail` items of #6567
=> Refactoring Avails

apps/crm/crm/src/app/crm/pages/offers/shell/contract-view/contract-view.component.html, libs/contract/src/lib/contract/components/confirm-decline/confirm-decline.component.ts
=> CRM contract decline reason

apps/catalog/catalog/src/app/marketplace/title/list/list.component.html, libs/movie/src/lib/movie/form/filters/languages/language-filter.component.ts
=> 6269 Add back language filter

apps/festival/festival/src/app/marketplace/event/session/session.component.html, libs/contract/src/lib/bucket/+state/bucket.service.ts, libs/contract/src/lib/contract/+state/contract.model.ts
fix a small (and rare) bug preventing a user to watch a screening
=> Screening small bug

apps/festival/festival/src/app/marketplace/home/home.component.html, apps/festival/festival/src/app/marketplace/home/home.component.scss, libs/movie/src/lib/movie/components/header/header.component.scss, libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.ts, libs/ui/src/lib/tunnel/layout/layout.component.html
=> 6645 small UI fixes

apps/crm/crm/src/app/crm/crm.module.ts, apps/crm/crm/src/app/crm/pages/movies/movies.component.html, apps/crm/crm/src/app/crm/pages/movies/movies.component.scss, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.module.ts, apps/crm/crm/src/app/crm/pages/organizations/organizations.component.html, apps/crm/crm/src/app/crm/pages/organizations/organizations.component.ts, apps/crm/crm/src/app/crm/pages/users/users.component.html, apps/crm/crm/src/app/crm/pages/users/users.component.scss, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/crm/crm/src/app/crm/pages/users/users.module.ts, libs/movie/src/lib/movie/+state/movie.service.ts, libs/ui/src/lib/list/table/table.component.html, libs/ui/src/lib/list/table/table.component.scss
implement the new table in CRM users page & movies page
=> Table in CRM users & movies

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/sets.ts, libs/contract/src/lib/avails/tests/avails.spec.ts, libs/contract/src/lib/avails/tests/territories.spec.ts
=> Refactor isMovieAvailable & new tests

apps/catalog/catalog/src/app/dashboard/title/view/view.component.html
=> Title view "Consult Avails" button

apps/backend-functions/src/main.ts, libs/firebase-utils/src/lib/firebase-utils.ts
Hopefully fix #6686 and otherwise improve performance on signup
=> 6686 account creation bug

libs/ui/src/lib/slider/slider.component.html, libs/ui/src/lib/slider/slider.component.ts
=> 6634 slider disappearing

libs/user/src/lib/auth/pages/identity/identity.component.ts
=> 6755 change error message for same invitation pass and password

libs/contract/src/lib/bucket/+state/bucket.firestore.ts, libs/contract/src/lib/bucket/+state/bucket.model.ts, libs/contract/src/lib/contract/+state/contract.firestore.ts, libs/contract/src/lib/contract/+state/contract.model.ts, libs/contract/src/lib/term/+state/term.firestore.ts, libs/contract/src/lib/term/+state/term.model.ts, libs/invitation/src/lib/+state/invitation.firestore.ts, libs/movie/src/lib/movie/+state/movie.firestore.ts, libs/movie/src/lib/movie/form/movie.form.ts, libs/notification/src/lib/+state/notification.firestore.ts, libs/organization/src/lib/organization/+state/organization.firestore.ts, libs/utils/src/lib/apps.ts
movie some models to `****.firestore.ts` and updated `apps.ts`
As @GrandSchtroumpf suggested, I will create an issue to move all firestore.ts files into a new `models` lib
@RemcoSimonides can you try to deploy again with these changes ? It worked on my side  but just to be sure ..
=> cleaning imports

apps/catalog/catalog/src/app/dashboard/dashboard.module.ts, apps/festival/festival/src/app/dashboard/dashboard.module.ts, apps/financiers/financiers/src/app/dashboard/dashboard.module.ts, libs/import/src/lib/import-spreadsheet/import-spreadsheet.component.html, libs/import/src/lib/import-spreadsheet/import-spreadsheet.component.ts, libs/import/src/lib/import-spreadsheet/import-spreadsheet.module.ts, libs/import/src/lib/import.component.html, libs/import/src/lib/import.component.ts, libs/import/src/lib/import.module.ts, libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/movies/view-extracted-movies.component.ts, libs/utils/src/lib/spreadsheet/import.ts, tsconfig.base.json
Removing dead code and refactoring to reduce code base and improve readability.
=> Excle Import : refactoring & cleaning

apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/sales/view/view.component.html, apps/catalog/catalog/src/app/dashboard/sales/view/view.component.ts, apps/catalog/catalog/src/app/dashboard/sales/view/view.module.ts
fixed: #6751
refactored contracts to sales.
=> catalog contract view refactor

apps/catalog/catalog-e2e/src/integration/dashboard/import.spec.ts, apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts, apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
In preparation to merge the E2E with PR process change in develop branch.
=> Fix import spec and skip other test for now

libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts, libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/utils/src/lib/spreadsheet/import.ts
- lot's of bugs
- and also first item of #6988
=> Solve some excel import bugs

apps/backend-functions/src/invitation.ts, apps/backend-functions/src/templates/mail.ts, libs/utils/src/lib/emails/ids.ts
=> send verification email for invit-only event

apps/backend-functions/src/internals/users.ts, libs/utils/src/lib/emails/ids.ts
=> send invit email to user with no orgId

libs/utils/src/lib/utils.ts
=> fixed(utils.ts):now use first 3 letters of org name

apps/backend-functions/src/internals/users.ts, libs/utils/src/lib/emails/ids.ts, libs/utils/src/lib/emails/utils.ts
=> Event reminder

libs/media/src/lib/video/viewer/viewer.component.ts, libs/utils/src/lib/utils.ts
removed anonymous in watermark
=> removed anonymous in watermark

apps/backend-functions/src/environments/environment.emulator.ts, apps/backend-functions/src/environments/environment.prod.ts, apps/backend-functions/src/environments/environment.ts, apps/backend-functions/src/users.ts, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.ts, libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts, libs/import/src/lib/view-extracted-elements/organizations/utils.ts, libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/utils/src/lib/apps.ts, libs/utils/src/lib/spreadsheet/import.ts
fixing bugs related to the creation of org/movie/contract in db just after the ecel import
=> Excel import: creation of objects in db

libs/utils/src/lib/operators.ts
Fixed:
- objects emitted are no longer mutable even after the fact.
=> fixed: could emit objects which are mutable even after the fact

apps/backend-functions/src/internals/invitations/events.ts, apps/backend-functions/src/player.spec.ts, apps/backend-functions/src/player.ts, apps/backend-functions/src/twilio.spec.ts, apps/festival/festival/src/app/event/role/role.component.ts, apps/festival/festival/src/app/event/view/view.component.ts, libs/event/src/lib/form/edit-details/edit-details.component.html, libs/event/src/lib/guard/event-access.guard.ts, libs/event/src/lib/guard/event.guard.ts, libs/event/src/lib/guard/identity.guard.ts, libs/event/src/lib/guard/no-event-identity.guard.ts, libs/event/src/lib/guard/no-event-role.guard.ts, libs/utils/src/lib/static-model/static-model.ts
renamed invitation only to protected #7067
=> renamed invitation only to protected #7067

apps/festival/festival/src/app/event/view/view.component.ts
=> debug for #7060

libs/movie/src/lib/movie/form/filters/languages/language-filter.component.ts, libs/utils/src/lib/form/forms/list.form.ts
Fix todo in issue #7055
https://user-images.githubusercontent.com/14964443/141322126-db11c941-2deb-4c4b-842d-15d156f091cb.mp4
=> 7055 fix language filter

apps/catalog/catalog/src/app/dashboard/title/list/list.component.html, apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts, apps/festival/festival/src/app/dashboard/title/list/list.component.html, apps/festival/festival/src/app/dashboard/title/list/list.component.ts, libs/movie/src/lib/movie/+state/movie.service.ts, libs/ui/src/lib/list/table/table.component.ts, libs/utils/src/lib/pipes/filter-by.pipe.ts
Cleanup title list in dashboard & use joinWith instead of queryChange
=> clean title list dashboard

libs/media/src/lib/+state/media.firestore.ts, libs/media/src/lib/+state/static-files.ts, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.scss, libs/movie/src/lib/movie/marketplace/shell/shell.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.module.ts
=> 7055 fix media

apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/sales/view/view.component.html, firestore.rules, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts, libs/organization/src/lib/organization/pipes/get-org.pipe.ts
=> Contract import bug

apps/catalog/catalog/src/app/marketplace/title/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.scss, apps/festival/festival/src/app/marketplace/title/view/view.component.ts
=> 6888 fix ui multiple orgs

libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts
copy the parent mandate stakeholders into the sale stakeholders
=> Import contract stakeholders

libs/movie/src/lib/movie/dashboard/shell/shell.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.ts, libs/movie/src/lib/movie/pipes/get-title.pipe.ts
=> 7055 back btn and fix error on no titleId on screener

apps/cms/src/app/home/events-slider/events-slider.component.html, apps/cms/src/app/home/events-slider/events-slider.component.scss, apps/cms/src/app/home/events-slider/events-slider.schema.ts, apps/festival/festival/src/app/marketplace/home/home.component.html, apps/festival/festival/src/app/marketplace/home/home.component.scss, libs/admin/src/lib/cms/home.ts, libs/event/src/lib/components/slide/slide.component.html, libs/event/src/lib/components/slide/slide.component.scss, libs/invitation/src/lib/components/action/action.component.ts
=> 7059 event banner improvements

libs/event/src/lib/components/meeting/video/video.component.scss
=> resolve background color problem in video meeting

apps/backend-functions/src/package.json, apps/catalog/catalog/src/app/landing/landing.component.html, apps/festival/festival/src/app/landing/landing.component.html, apps/festival/festival/src/app/landing/landing.component.ts, apps/festival/festival/src/app/marketplace/home/home.component.html, libs/landing/src/lib/shell/shell.component.html
=> 7059 landing page improvements

libs/event/src/lib/form/edit-details/edit-details.component.ts, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.scss, libs/event/src/lib/form/shell/shell.component.ts
=> events modals fixes

libs/movie/src/lib/movie/dashboard/shell/shell.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.scss, libs/movie/src/lib/movie/form/start/start-tunnel.component.html
=> 7055 UI fixes

libs/event/src/lib/components/meeting/room/video-room.component.scss, libs/utils/src/lib/emails/ids.ts
=> Release 3.5 fullscreen button

apps/backend-ops/src/select-environment.ts
=> hotfix to prevent env.ts from being out of sync

libs/landing/src/lib/shell/shell.component.html, libs/user/src/lib/auth/+state/auth.service.ts
=> 7052 restart intercom and fix spelling error

apps/festival/festival/src/app/dashboard/title/view/view.component.html, libs/invitation/src/lib/components/action/action.component.html, libs/invitation/src/lib/components/action/action.module.ts, libs/invitation/src/lib/components/item/item.component.html, libs/invitation/src/lib/components/item/item.module.ts, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html, libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
=> 7166 small improvements

apps/crm/crm/src/app/crm/components/event-info/event-info.component.html, apps/crm/crm/src/app/crm/components/event-info/event-info.component.ts, apps/crm/crm/src/app/crm/pages/event/event.component.html, apps/crm/crm/src/app/crm/pages/event/event.component.ts, apps/crm/crm/src/app/crm/pages/event/event.module.ts, libs/landing/src/lib/shell/shell.component.html
Fix #7169
Also added label to newsletter field on landing page for better UI. Was mentioned in release review notes.
=> 7169 fix margin and add label

libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/movie/src/lib/movie/form/movie.form.ts, libs/movie/src/lib/movie/form/movie.shell.config.ts
=> import & tunnel

apps/backend-functions/src/mailchimp.ts, libs/landing/src/lib/shell/shell.component.ts
=> correct mailchimp tags

libs/event/src/lib/form/edit-details/edit-details.component.html
=> Clean tooltip on event creation

apps/festival/festival/src/app/marketplace/event/list/list.component.html, libs/notification/src/lib/+state/notification.store.ts
=> correct wording

apps/festival/festival/src/app/marketplace/title/list/list.component.ts, libs/movie/src/lib/movie/form/search.form.ts, libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.html, libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts, libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.module.ts
fixed(check-boxes.component):switched from formList to formcontrol and updated forms everywhere necessary to accommodate the switch
=> fixed(check-boxes.component):switched from formList to formcontrol

apps/backend-functions/src/media.ts, libs/firebase-utils/src/lib/node-request.ts
all video deleted resulted in 'crash' in movieUpdateEvent error
Also, it was trying to move files unnecessarily
=> fix onMovieUpdateEvent error

apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html
=> 7023 update summary error sentence

libs/event/src/lib/form/edit-details/edit-details.component.ts, libs/event/src/lib/form/shell/shell.component.ts, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/table-extracted-elements/movies/movies.component.ts, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.ts, libs/movie/src/lib/movie/components/movie-imdb-search/movie-imdb-search.component.ts, libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
=> 7177 remove static: true

apps/catalog/catalog/src/app/dashboard/sales/list/list.component.html, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/sales/list/list.module.ts, firestore.indexes.json, libs/contract/src/lib/contract/+state/contract.service.ts, libs/organization/src/lib/organization/pipes/index.ts, libs/utils/src/lib/static-model/static-model.ts
=> Sales list

apps/catalog/catalog-e2e/src/integration/dashboard/import.spec.ts
=> Skip the test to get PRs to work

apps/backend-functions/src/orgs.ts, libs/event/src/lib/guard/event-auth.guard.ts, libs/organization/src/lib/organization/guard/organization.guard.ts, libs/user/src/lib/auth/guard/identity.guard.ts, libs/user/src/lib/auth/guard/not-fully-verified.guard.ts, libs/utils/src/lib/static-model/static-model.ts
=> 6872 added on hold org status

apps/backend-functions/src/internals/users.ts, libs/import/src/lib/view-extracted-elements/organizations/utils.ts, libs/movie/src/lib/movie/form/movie.shell.config.ts
- solve importing org issue when we don't want any module access for a specific app
- solve movie deep FormList issue when switching from editing a title to another one
=> hotfix release 3.5 b

apps/backend-functions/src/internals/invitations/events.ts, libs/event/src/lib/+state/event.firestore.ts, libs/event/src/lib/+state/event.model.ts, libs/event/src/lib/form/create/create.component.ts, libs/event/src/lib/form/event.form.ts
=> Send mail to user organizer on request to attend

.circleci/config.yml, apps/backend-ops/src/firebaseSetup.ts, apps/backend-ops/src/main.ts, apps/backend-ops/src/tools.ts
- affects issue where we are using too many circle CI resources
- issue #6923
- new command - upgradeEmulators
- more hotfixes
=> optimise 'prepareEmulators' to run only weekly, to reduce caching

apps/catalog/catalog/src/app/dashboard/dashboard.module.ts, apps/catalog/catalog/src/app/marketplace/marketplace.module.ts, libs/contract/src/lib/contract/pages/standard-terms/standard-terms.component.html, libs/contract/src/lib/contract/pages/standard-terms/standard-terms.component.scss, libs/contract/src/lib/contract/pages/standard-terms/standard-terms.component.ts, libs/contract/src/lib/contract/pages/standard-terms/standard-terms.module.ts
=> feat(standard-terms): finished design

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/contract/src/lib/avails/avails.ts, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/table-extracted-elements/movies/movies.component.ts, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.ts, libs/import/src/lib/table-extracted-elements/view-import-errors/view-import-errors.component.html, libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts, libs/import/src/lib/view-extracted-elements/organizations/utils.ts, libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/utils/src/lib/spreadsheet/import.ts
use a single system for import errors & import warnings
=> Refactor import errors

apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.html, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, libs/contract/src/lib/avails/form/avails.form.ts, libs/contract/src/lib/bucket/form.ts, libs/contract/src/lib/negotiation/form.ts, libs/contract/src/lib/negotiation/form/negotiation-form.component.html, libs/contract/src/lib/negotiation/form/negotiation-form.component.ts
Fixed: negotiation form now respects bucket contract structure
=> Negotiation form refactor

libs/event/src/lib/form/screening/screening.component.html, libs/event/src/lib/form/screening/screening.component.scss, libs/event/src/lib/form/screening/screening.component.ts, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.ts, libs/event/src/lib/form/shell/shell.module.ts
=> Display chip if missing screener

libs/organization/src/lib/organization/pages/view/view.component.html, libs/organization/src/lib/organization/pages/view/view.component.ts, libs/organization/src/lib/organization/pages/view/view.module.ts, libs/user/src/lib/auth/pages/profile-view/profile-view.component.html, libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts, libs/user/src/lib/auth/pages/profile-view/profile-view.module.ts
=> 7232 fix page not found

apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html, libs/contract/src/lib/contract/components/item/contract-item.component.html, libs/contract/src/lib/contract/components/item/contract-item.component.ts
=> Selection page

apps/backend-functions/src/mailchimp.ts, apps/backend-functions/src/users.ts, apps/catalog/catalog/src/app/marketplace/home/home.component.ts, apps/catalog/catalog/src/app/marketplace/home/home.module.ts, apps/festival/festival/src/app/marketplace/home/home.component.ts, apps/festival/festival/src/app/marketplace/home/home.module.ts, libs/landing/src/lib/shell/shell.component.ts, libs/user/src/lib/auth/forms/preferences/preferences.component.html, libs/user/src/lib/auth/forms/preferences/preferences.component.scss, libs/user/src/lib/auth/forms/preferences/preferences.component.ts, libs/user/src/lib/auth/forms/preferences/preferences.form.ts, libs/user/src/lib/auth/forms/preferences/preferences.module.ts, libs/user/src/lib/auth/pages/preferences/modal/preferences.component.html, libs/user/src/lib/auth/pages/preferences/modal/preferences.component.scss, libs/user/src/lib/auth/pages/preferences/modal/preferences.component.ts, libs/user/src/lib/auth/pages/preferences/modal/preferences.module.ts, libs/user/src/lib/auth/pages/preferences/page/preferences.component.html, libs/user/src/lib/auth/pages/preferences/page/preferences.component.scss, libs/user/src/lib/auth/pages/preferences/page/preferences.component.ts, libs/user/src/lib/auth/pages/preferences/page/preferences.module.ts, libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts, libs/user/src/lib/auth/pages/profile-view/profile-view.module.ts, libs/user/src/lib/user/+state/user.firestore.ts, libs/user/src/lib/user/+state/user.model.ts, libs/user/src/lib/user/+state/user.utils.ts, libs/utils/src/lib/mailchimp/mailchimp-model.ts
Fix #6996
Waiting for UI check
=> 6996 Buyer preferences

apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.module.ts
=> Marketplace offer page

libs/utils/src/lib/form/form-state-url-encoder.ts
=> 7242 search with a space

apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.scss, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.module.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.ts
=> Marketplace contract view

apps/backend-functions/src/main.ts, apps/backend-functions/src/negotiation.ts
added cloud function to sync [negotiation status]/ declineReason with that of the concerned sale.
=> feat(cloud functions):function to sync negotiation and sales status

apps/catalog/catalog/src/app/marketplace/home/home.component.html, apps/festival/festival/src/app/marketplace/home/home.component.html
=> 7350 query params enabled for banner cta buttons

apps/catalog/catalog/src/app/marketplace/marketplace.component.html
=> 7243 Remove Sellers from sidenav

apps/catalog/catalog/src/app/dashboard/sales/shell/external/external.component.html, apps/catalog/catalog/src/app/dashboard/sales/shell/external/external.component.scss, apps/catalog/catalog/src/app/dashboard/sales/shell/external/external.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/external/external.module.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/shell.component.html, apps/catalog/catalog/src/app/dashboard/sales/shell/shell.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/shell.guard.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/shell.module.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.component.html, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.component.scss, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.module.ts, libs/contract/src/lib/negotiation/pipe.ts
- For external sale use `sale` in `contract-item`
- For internal sale use `negotiation` in `contract-item`
- Fix prices that wasn't shown
- Improve missing states for "accept" / "declined" buttons
=> Separate external & internal sale

apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.ts, libs/contract/src/lib/bucket/+state/bucket.service.ts, libs/contract/src/lib/contract/+state/contract.service.ts, libs/contract/src/lib/negotiation/+state/negotiation.service.ts
=> update sale status on negotiation creation

apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.ts
=> show latest negotiation in marketplace -> offer -> contract view.

apps/catalog/catalog/src/app/dashboard/sales/list/list.component.html, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.html, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, libs/contract/src/lib/bucket/form.ts, libs/contract/src/lib/negotiation/form/negotiation-form.component.ts, libs/contract/src/lib/term/+state/term.service.ts
Fixed:
* Proper handling of terms in formatFromFirestore in terms service
* auto select a term ( default first term) in negotiation form.
* Show proper count of sales in negotiation status.
=> Negotiation bugs

apps/backend-functions/src/internals/users.ts, apps/backend-functions/src/invitation.ts, apps/backend-functions/src/main.ts, apps/backend-functions/src/templates/mail.ts, apps/crm/crm/src/app/crm/components/event-info/event-info.component.ts, apps/festival/festival/src/app/event/view/view.component.html, apps/festival/festival/src/app/event/view/view.component.ts, libs/event/src/lib/form/shell/shell.component.ts, libs/invitation/src/lib/+state/invitation.service.ts, libs/invitation/src/lib/components/action/action.component.html, libs/invitation/src/lib/components/action/action.component.scss, libs/invitation/src/lib/components/action/action.component.ts, libs/invitation/src/lib/components/action/action.module.ts, libs/invitation/src/lib/form/user/user.component.ts, libs/invitation/src/lib/form/user/user.module.ts
fixed: 
-  If I invite an user to my org and then invite him to an event, he will receive 3 emails 
-  On event edit page, form is saved before sending invitations
-  As a guest I received an email, clicked on it, filled in the little form and got access to the event page where I could answer an invitation. Tried to click on "accept invitation", but nothing happened. Same for decline.
=>  Release 3.6 - Event #7349 

libs/event/src/lib/form/screening/screening.component.html, libs/event/src/lib/form/screening/screening.component.ts, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.ts, libs/invitation/src/lib/form/user/user.component.scss
#7349
#7171 (margin under progress bar)
=> Add chip and warning if no title selected

apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, libs/contract/src/lib/avails/new-avails.ts, libs/contract/src/lib/avails/sets.ts
=> Low level logic

apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, libs/contract/src/lib/avails/new-avails.ts, libs/contract/src/lib/avails/sets.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts
=> Logic refactor

libs/media/src/lib/file/explorer/explorer.component.html, libs/media/src/lib/file/explorer/explorer.component.scss, libs/media/src/lib/file/explorer/explorer.model.ts, libs/media/src/lib/file/explorer/explorer.module.ts, libs/media/src/lib/file/file-list-uploader/file-list-uploader.component.html, libs/media/src/lib/file/file-list-uploader/file-list-uploader.component.scss, libs/media/src/lib/file/file-list-uploader/file-list-uploader.component.ts, libs/media/src/lib/file/file-list-uploader/file-list-uploader.module.ts, libs/media/src/lib/file/file-uploader/file-uploader.component.ts, libs/media/src/lib/form/media.form.ts
=> 7330 add privacy checkbox to file explorer

libs/contract/src/lib/avails/new-avails.ts
fix the map & calendar items of #7357
=> Map & Calendar avails refacto

libs/event/src/lib/components/meeting/room/video-room.component.ts, libs/media/src/lib/pdf/viewer/viewer.component.ts, libs/media/src/lib/video/viewer/viewer.component.ts
Fix toggle fullscreen on Safari mentioned in #7349
=> 7349 toggle fullscreen safari

libs/organization/src/lib/organization/pages/view/view.component.html, libs/organization/src/lib/organization/pages/view/view.component.ts, libs/organization/src/lib/organization/pages/view/view.module.ts, libs/user/src/lib/auth/pages/profile-view/profile-view.component.html, libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts, libs/user/src/lib/auth/pages/profile-view/profile-view.module.ts
=> 7362 7346 fix previous button navigation

libs/ui/src/lib/layout/marketplace/marketplace.component.html, libs/ui/src/lib/layout/marketplace/marketplace.component.scss, libs/ui/src/lib/layout/marketplace/marketplace.component.ts
=> Change logo click behaviour

apps/festival/festival/src/app/event/email/email.component.ts, apps/festival/festival/src/app/event/identity/identity.component.ts, apps/festival/festival/src/app/event/login/login.component.ts, apps/festival/festival/src/app/event/view/view.component.ts
=> Go back button on event

apps/catalog/catalog/src/app/landing/landing.component.html, apps/catalog/catalog/src/app/landing/landing.component.ts, apps/festival/festival/src/app/event/view/view.component.ts, libs/ui/src/lib/layout/event/event.component.html
=> Fix previous error on view component

libs/notification/src/lib/+state/notification.model.ts, libs/notification/src/lib/+state/notification.store.ts, libs/notification/src/lib/components/item/item.component.html, libs/user/src/lib/auth/+state/auth.service.ts
=> 6235 links in notification

libs/event/src/lib/form/edit-details/edit-details.component.html, libs/event/src/lib/form/edit-details/edit-details.component.ts, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.ts
=> close popin event form #7171

apps/catalog/catalog/src/app/dashboard/sales/shell/external/external.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.module.ts, libs/contract/src/lib/contract/components/confirm-decline/confirm-decline.component.html, libs/contract/src/lib/contract/components/confirm-decline/confirm-decline.component.ts, libs/contract/src/lib/contract/components/confirm-decline/confirm-decline.module.ts
Fixed: #7389
added decline reason dropdown on seller offer decline.
=> added decline reason dropdown on seller offer decline.

apps/catalog/catalog/src/app/landing/landing.component.html, apps/festival/festival/src/app/event/login/login.component.html, libs/media/src/lib/image/uploader/uploader.component.ts, storage.rules
=> 7336 7257 7432

apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.ts, libs/utils/src/lib/browser/utils.ts
added timeout on snackbar opens.
=> added timeout on snackbar opens

apps/catalog/catalog/src/app/landing/landing.component.html
remove text on Archipel Content landing page #7448
=> remove text on Archipel Content landing page #7448

apps/catalog/catalog/src/app/landing/landing.component.html
=> merge back hotfix - remove text on Archipel Content landing page #7448

apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html, libs/movie/src/lib/movie/dashboard/additional/additional.component.html, libs/movie/src/lib/movie/form/shell/shell.component.ts, libs/movie/src/lib/movie/marketplace/additional/additional.component.html, libs/utils/src/lib/static-model/static-model.ts
=> 7152 available versions to versions

apps/catalog/catalog/src/app/dashboard/avails/calendar/calendar.component.html, apps/catalog/catalog/src/app/dashboard/avails/calendar/calendar.component.ts, apps/catalog/catalog/src/app/dashboard/avails/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/avails/map/map.component.ts, apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.module.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, apps/crm/crm/src/app/crm/pages/offers/shell/contract-form/contract-form.component.ts, libs/contract/src/lib/avails/form/avails.form.ts, libs/contract/src/lib/avails/new-avails.ts
=> Calendar UI

apps/crm/crm/src/app/crm/pages/users/users.component.ts, libs/utils/src/lib/static-model/static-model.ts
=> 7418 7425 buying preference export and empty director category state

apps/catalog/catalog/src/app/dashboard/avails/calendar/calendar.component.html, apps/catalog/catalog/src/app/dashboard/avails/map/map.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html, apps/catalog/catalog/src/app/marketplace/title/list/list.component.html, apps/crm/crm/src/app/crm/pages/offers/shell/contract-form/contract-form.component.html, libs/contract/src/lib/avails/filter/filter.component.html, libs/contract/src/lib/avails/filter/filter.component.ts
=> Update form component

apps/crm/crm/src/app/crm/crm.module.ts, apps/crm/crm/src/app/crm/pages/user/user.component.html, apps/crm/crm/src/app/crm/pages/user/user.component.ts, libs/contract/src/lib/term/components/detailed/detailed.component.html, libs/contract/src/lib/term/components/detailed/detailed.component.ts, libs/movie/src/lib/movie/components/credit-card/credit-card.component.ts
=> 7039 7425 Fix modal and Buying Preferences in CRM

apps/catalog/catalog/src/app/marketplace/offer/list/list.component.ts, apps/crm/crm/src/app/crm/pages/offers/list/offer-list.component.ts, apps/crm/crm/src/app/crm/pages/offers/shell/contract-view/contract-view.component.html, apps/crm/crm/src/app/crm/pages/offers/shell/contract-view/contract-view.component.ts, apps/crm/crm/src/app/crm/pages/offers/shell/offer-view/offer-view.component.html, apps/crm/crm/src/app/crm/pages/offers/shell/offer-view/offer-view.component.ts, apps/crm/crm/src/app/crm/pages/offers/shell/shell.component.html, apps/crm/crm/src/app/crm/pages/offers/shell/shell.component.ts, libs/contract/src/lib/negotiation/pipe.ts, libs/contract/src/lib/offer/+state/offer.model.ts
=> Crm negotiation switch

apps/catalog/catalog/src/app/dashboard/avails/list/list.component.ts, apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, apps/festival/festival/src/app/marketplace/title/list/list.component.ts, apps/financiers/financiers/src/app/marketplace/title/list/list.component.ts, libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/calendar/calendar.component.ts, libs/contract/src/lib/avails/calendar/calendar.model.ts, libs/contract/src/lib/avails/fixtures/availsFilters.ts, libs/contract/src/lib/avails/new-avails.ts, libs/contract/src/lib/avails/tests/avails.spec.ts, libs/contract/src/lib/avails/tests/bucketForm.spec.ts, libs/contract/src/lib/avails/tests/bucketTerm.spec.ts, libs/contract/src/lib/avails/tests/calendar.spec.ts, libs/contract/src/lib/avails/tests/holdbacks.spec.ts, libs/contract/src/lib/avails/tests/mandateTerms.spec.ts, libs/contract/src/lib/bucket/+state/bucket.model.ts, libs/contract/src/lib/bucket/+state/bucket.service.ts, libs/contract/src/lib/bucket/form.ts, libs/contract/src/lib/contract/holdback/pipes/colliding-holdback.pipe.ts, libs/movie/src/lib/movie/form/search.form.ts
=> Clean some avails code

.circleci/config.yml
=> CI optimisation

.firebaserc, apps/catalog/catalog/src/app/dashboard/avails/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/avails/map/map.component.ts, env/env.blockframes-pl-2.ts, libs/contract/src/lib/avails/new-avails.ts, libs/contract/src/lib/avails/sets.ts
solve some items of the review in #7139
=> Solve some bugs

apps/backend-functions/src/main.ts, apps/backend-functions/src/negotiation.ts, apps/backend-functions/src/notification.ts, apps/backend-functions/src/offer.ts, apps/backend-functions/src/templates/mail.ts, libs/contract/src/lib/negotiation/+state/negotiation.firestore.ts, libs/notification/src/lib/+state/notification.firestore.ts, libs/notification/src/lib/+state/notification.store.ts, libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts, libs/user/src/lib/auth/forms/notifications-form/notifications.form.ts, libs/utils/src/lib/emails/ids.ts
Send in app and email notifications when a negotiation is countered, declined or accepted.
=> Create in app notifications on negotiation events

libs/user/src/lib/auth/forms/password/password.component.html, libs/user/src/lib/auth/forms/password/password.component.ts, libs/user/src/lib/auth/forms/password/password.module.ts, libs/user/src/lib/auth/pages/profile/profile.component.ts, libs/utils/src/lib/form/controls/password.control.ts, libs/utils/src/lib/form/matchers.ts, libs/utils/src/lib/form/validators/validators.ts
#6755 part 1: change password on profile form
=> 6755 new password different than current 2 part 1

libs/user/src/lib/auth/forms/identity.form.ts, libs/user/src/lib/auth/pages/identity/identity.component.html, libs/user/src/lib/auth/pages/identity/identity.component.ts, libs/utils/src/lib/form/validators/validators.ts
=> 6755 new password different than current 2 part 2

apps/backend-functions/src/event.ts, apps/backend-functions/src/notification.ts, libs/notification/src/lib/+state/notification.firestore.ts, libs/notification/src/lib/+state/notification.store.ts, libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts, libs/user/src/lib/auth/forms/notifications-form/notifications.form.ts
=> 7502 notification for requestor

tools/scripts/deploy-function-config.ts
=> removed useless and potentially harmful logs #6923

apps/backend-functions/src/main.ts, apps/backend-functions/src/movie.ts, apps/backend-functions/src/notification.ts, apps/backend-functions/src/templates/mail.ts, apps/festival/festival/src/app/event/view/view.component.html, apps/festival/festival/src/app/event/view/view.component.ts, apps/festival/festival/src/app/event/view/view.module.ts, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.ts, apps/festival/festival/src/app/marketplace/title/view/view.module.ts, libs/event/src/lib/components/screening-item/screening-item.component.html, libs/event/src/lib/components/screening-item/screening-item.component.scss, libs/event/src/lib/components/screening-item/screening-item.component.ts, libs/event/src/lib/components/screening-item/screening-item.module.ts, libs/invitation/src/lib/components/action/action.component.scss, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.html, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.scss, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.module.ts, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.ts, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.module.ts, libs/notification/src/lib/+state/notification.firestore.ts, libs/notification/src/lib/+state/notification.store.ts, libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts, libs/user/src/lib/auth/forms/notifications-form/notifications.form.ts, libs/utils/src/lib/emails/ids.ts, libs/utils/src/lib/pipes/max-length.pipe.ts
=> 7503 request asking price

apps/festival/festival/src/app/event/view/view.component.html, apps/festival/festival/src/app/event/view/view.component.scss, apps/festival/festival/src/app/event/view/view.component.ts, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.ts, libs/event/src/lib/components/screening-item/screening-item.component.html, libs/event/src/lib/components/screening-item/screening-item.component.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.ts
=> 7503 disable request asking price button

apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html, apps/catalog/catalog/src/app/landing/landing.component.html, apps/catalog/catalog/src/app/marketplace/organization/list/list.component.html, apps/catalog/catalog/src/app/marketplace/title/list/list.component.html, apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html, apps/festival/festival/src/app/marketplace/event/list/list.component.html, apps/festival/festival/src/app/marketplace/organization/list/list.component.html, apps/festival/festival/src/app/marketplace/title/list/list.component.html, apps/financiers/financiers/src/app/dashboard/tunnel/summary/summary.component.html, apps/financiers/financiers/src/app/marketplace/organization/list/list.component.html, apps/financiers/financiers/src/app/marketplace/title/list/list.component.html, libs/media/src/lib/file/picker/picker.component.html, libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html, libs/movie/src/lib/movie/form/summary/available-versions/available-versions.component.html, libs/movie/src/lib/movie/form/summary/main/main.component.html, libs/movie/src/lib/movie/form/summary/review/review.component.html, libs/organization/src/lib/organization/components/card/card.component.html, libs/organization/src/lib/organization/components/member-add/member-add.component.html
=> i18n typo & landing typo

libs/movie/src/lib/movie/marketplace/main/main.component.html, libs/movie/src/lib/movie/marketplace/main/main.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts, libs/utils/src/lib/analytics/analytics-model.ts
added on salesPitch and otherVideos #7579
=> tracks videos played on movie page #7579 

apps/backend-functions/src/templates/mail.ts, apps/festival/festival/src/app/dashboard/dashboard.module.ts, apps/festival/festival/src/app/dashboard/event/list/list.component.ts, libs/event/src/lib/+state/event.service.ts, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.scss, libs/event/src/lib/form/shell/shell.component.ts, libs/event/src/lib/form/shell/shell.module.ts, libs/event/src/lib/guard/event-edit.guard.ts, libs/event/src/lib/guard/event-organization.guard.ts, libs/event/src/lib/guard/event-type.guard.ts, libs/notification/src/lib/+state/notification.store.ts
#7502
Moved creating new event from `/c/o/dashboard/event` to `/c/o/dashboard/event/new/edit`
=> 7502 ask for screening 2

apps/backend-functions/src/templates/mail.ts, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.html, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/shell.component.html, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts, libs/contract/src/lib/contract/holdback/list/list.component.html, libs/contract/src/lib/contract/pages/standard-terms/standard-terms.component.ts, libs/notification/src/lib/+state/notification.store.ts, libs/ui/src/lib/list/table/paginator.ts, libs/ui/src/lib/list/table/table.component.ts, libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts
=> Deal nego debug

libs/event/src/lib/components/week/week.component.html, libs/event/src/lib/components/week/week.component.scss, libs/event/src/lib/components/week/week.component.ts, libs/event/src/lib/event.module.ts
=> 7502 spinner for dashboard event list page 2

apps/festival/festival/src/app/event/session/session.component.html, apps/festival/festival/src/app/event/session/session.component.scss, apps/festival/festival/src/app/event/session/session.component.ts, apps/festival/festival/src/app/event/session/session.module.ts, libs/notification/src/lib/+state/notification.store.ts
FIx https://github.com/blockframes/blockframes/issues/7552#issuecomment-1016282037
=> 7552 Requesting asking price on screening page

libs/movie/src/lib/movie/marketplace/main/main.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
prevent multiple play events to be recorded
=> prevent multiple play events to be recorded

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.scss
=> 7552 fix titles page and align for mobile

apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
=> 7553 Only accepted contracts

libs/contract/src/lib/contract/holdback/form/form.component.html, libs/contract/src/lib/contract/holdback/form/form.component.ts, libs/ui/src/lib/form/table/form-table.component.html
Fixed: https://github.com/blockframes/blockframes/issues/7558#issuecomment-1016625591
=> disable adding holdbacks when at least one holdback is present

apps/festival/festival/src/app/dashboard/event/list/list.component.html, apps/festival/festival/src/app/dashboard/event/list/list.component.ts, apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.html, apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.ts, libs/utils/src/lib/agenda/agenda.service.ts
=> small events update

apps/backend-functions/src/notification.ts, apps/backend-functions/src/templates/mail.ts, apps/catalog/catalog/src/app/dashboard/avails/calendar/calendar.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html, libs/utils/src/lib/utils.ts
=> fixed: generate email urls cloud functions side

apps/backend-functions/src/notification.ts, apps/backend-functions/src/templates/mail.ts, libs/contract/src/lib/term/+state/term.firestore.ts
fixed: #7616
https://github.com/blockframes/blockframes/issues/7558#issuecomment-1021087315
=> Email rewording

libs/utils/src/lib/utils.ts
=> tiny update

apps/backend-functions/src/templates/mail.ts, apps/catalog/catalog/src/app/dashboard/avails/calendar/calendar.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html, libs/contract/src/lib/term/+state/term.firestore.ts
=> Minor debug

apps/festival/festival/src/app/event/session/session.component.html, apps/festival/festival/src/app/event/view/view.component.html
=> Request Asking Price Button on Private Screenings #7627

apps/backend-functions/src/templates/mail.ts
=> Add user to email

apps/crm/crm/src/app/crm/pages/movies/movies.component.html, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/users/users.component.html, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/festival/festival/src/app/event/session/session.component.html, apps/festival/festival/src/app/event/session/session.component.ts, apps/festival/festival/src/app/event/view/view.component.html, apps/festival/festival/src/app/event/view/view.component.ts, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.ts, libs/event/src/lib/components/screening-item/screening-item.component.html, libs/event/src/lib/components/screening-item/screening-item.component.ts, libs/event/src/lib/pages/analytics/analytics.component.html, libs/event/src/lib/pages/analytics/analytics.component.ts, libs/invitation/src/lib/components/item/item.component.html, libs/invitation/src/lib/components/item/item.component.ts, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.html, libs/movie/src/lib/movie/components/upcoming-screenings/upcoming-screenings.component.ts
=> 7661 replace behaviorstore for markforcheck

libs/contract/src/lib/negotiation/utils.ts
=> functions to diff two negotiations

libs/contract/src/lib/negotiation/form/negotiation-form.component.html, libs/ui/src/lib/form/table/form-table.component.html, libs/ui/src/lib/form/table/form-table.component.scss, libs/ui/src/lib/form/table/form-table.component.ts
=> disable add new terms on negotiation form

libs/event/src/lib/form/meeting-files/meeting-files.component.ts, libs/event/src/lib/form/shell/shell.component.ts
=> Remove useless subform subscription

libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/fixtures/availsFilters.ts, libs/contract/src/lib/avails/fixtures/mandatesAndSales.ts, libs/contract/src/lib/avails/tests/avails-map.spec.ts
=>  Implemented unit tests for single territory avails

libs/contract/src/lib/avails/fixtures/availsFilters.ts, libs/contract/src/lib/avails/fixtures/mandatesAndSales.ts, libs/contract/src/lib/avails/tests/avails-calendar.spec.ts, libs/contract/src/lib/avails/tests/avails-map.spec.ts, libs/contract/src/lib/avails/tests/utils.ts
=> unit test multiple calendar avail states

libs/contract/src/lib/income/pipe.ts, libs/utils/src/lib/pipes/number.pipe.ts
=> fixed: filter out undefined incomes

libs/contract/src/lib/contract/holdback/form/form.component.html, libs/contract/src/lib/contract/holdback/form/form.component.ts, libs/ui/src/lib/form/table/form-table.component.ts
=> fixed: holdbacks correctly display now

apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.scss, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/filter/filter.component.html, libs/contract/src/lib/avails/filter/filter.component.ts
=> 7646 no mandate

libs/event/src/lib/form/shell/shell.component.html
=> Fix date params in calendar view

libs/analytics/src/lib/+state/analytics.service.ts
=> 7736 add analytics service

apps/festival/festival/src/app/dashboard/files/files.component.html
#7761
https://github.com/blockframes/blockframes/issues/7761#issuecomment-1041376641
=> 7761 fix file explorer

apps/festival/festival/src/app/festival.module.ts, libs/utils/src/lib/routes/app.guard.ts
=> 7756 seller to dashboard

libs/firebase-utils/src/lib/firestore/emulator.ts, tools/scripts/deploy-function-config.ts
- writes runtimeconfig.json to correct location for *nix and windows
- populates from .env file rather than functions:config:get
=> fix(backend-ops):  #7723 runtimeconfig.json

apps/catalog/catalog/src/app/landing/landing.component.html, apps/catalog/catalog/src/app/marketplace/home/home.component.scss, apps/catalog/catalog/src/app/marketplace/title/avails/explanation/explanation.component.scss, apps/festival/festival/src/app/landing/landing.component.html, apps/financiers/financiers/src/app/marketplace/marketplace.component.html, libs/landing/src/lib/shell/shell.component.html, libs/landing/src/lib/shell/shell.component.ts, libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.scss
=> General UI fixes 1

libs/event/src/lib/pages/analytics/analytics.component.ts
=> Feat 7763 statistics

libs/invitation/src/lib/form/user/user.component.html
https://github.com/blockframes/blockframes/issues/7764#issuecomment-1041935659
=> Fix invitation limit message

apps/catalog/catalog/src/app/dashboard/avails/calendar/calendar.component.ts, apps/catalog/catalog/src/app/dashboard/avails/map/map.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts, libs/utils/src/lib/pipes/group-label.pipe.ts, libs/utils/src/lib/utils.ts
Fixed: https://github.com/blockframes/blockframes/issues/7766#issuecomment-1041468576
=> group territories when exporting avails csv

libs/contract/src/lib/bucket/form.ts, libs/utils/src/lib/helpers.ts
=> Release 3 8 holdbacks

libs/media/src/lib/file/file-uploader/file-uploader.component.ts, libs/media/src/lib/image/uploader/uploader.component.ts
=> 7759 fix hover state and losing file when switching tab

libs/event/src/lib/form/screening/screening.component.ts, libs/event/src/lib/form/shell/shell.component.ts
https://github.com/blockframes/blockframes/issues/7764#issuecomment-1041935659
(fourth comment)
=> Missing title chip if title is draft

apps/catalog/catalog/src/app/dashboard/avails/list/list.component.html, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.scss, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.html, libs/contract/src/lib/contract/components/item/contract-item.component.scss, libs/event/src/lib/components/request-screening/request-screening.component.ts
=> Last general UI fixes for 3.8

apps/catalog/catalog/src/app/marketplace/marketplace.component.html, libs/movie/src/lib/movie/form/reviews/reviews.component.html, libs/movie/src/lib/movie/form/summary/summary.module.ts, libs/ui/src/lib/form/list/form-list.component.html, styles/components/mat-chips.scss
=> 7759 only enable save button when changes made

libs/movie/src/lib/movie/form/filters/languages/language-filter.component.html, libs/utils/src/lib/agenda/utils.ts
https://github.com/blockframes/blockframes/issues/7764#issuecomment-1041935659
=> Fix event export for outlook calendar

libs/analytics/src/lib/+state/analytics.firestore.ts, libs/analytics/src/lib/+state/analytics.model.ts, libs/firebase-utils/src/lib/firestoreMigrations/0072.ts
#7738
Use uid instead of userId to match existing data in Google Analytics
Fix bug in import
=> 7738 use uid instead of userId

libs/ui/src/lib/static-autocomplete/select/static-select.component.html, libs/ui/src/lib/static-autocomplete/select/static-select.component.ts, libs/utils/src/lib/common-interfaces/identity.ts, libs/utils/src/lib/static-model/static-model.ts
=> 7759 empty state for non-required static selects

libs/contract/src/lib/negotiation/form/negotiation-form.component.html, libs/contract/src/lib/negotiation/form/negotiation-form.component.ts, libs/contract/src/lib/negotiation/form/negotiation.module.ts
=> 7867 fix negotiation table

apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
test screening invitation reliability
=> test screening invitation reliability

apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
Use another uid that already have "preferences" attribute so the modal does not show
=> increase reliability part of #7877

libs/contract/src/lib/avails/avails.ts, libs/contract/src/lib/avails/fixtures/availsFilters.ts, libs/contract/src/lib/avails/fixtures/mandatesAndSales.ts, libs/contract/src/lib/avails/tests/avails-map.spec.ts
=> hotfix map filter

apps/festival/festival/src/app/marketplace/title/list/list.component.html, apps/financiers/financiers/src/app/marketplace/title/list/list.component.html, libs/firebase-utils/src/lib/firestoreMigrations/0073.ts, libs/firebase-utils/src/lib/firestoreMigrations/index.ts, libs/utils/src/lib/static-model/static-model.ts
=> Update movie genres

libs/firebase-utils/src/lib/firestoreMigrations/0072.ts
=> Fix migration 0072 empty content type

libs/movie/src/lib/movie/components/title-features/title-features.component.ts, libs/movie/src/lib/movie/form/main/main.component.html
=> contentType fixes

libs/analytics/src/lib/+state/analytics.firestore.ts, libs/analytics/src/lib/components/movie-analytics-chart/movie-analytics.model.ts, libs/analytics/src/lib/components/movie-analytics-chart/utils.ts, libs/firebase-utils/src/lib/firestoreMigrations/0074.ts, libs/movie/src/lib/movie/marketplace/main/main.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
=> promoReelOpened instead of promoVideoStarted

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.module.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.module.ts, apps/festival/festival/src/app/dashboard/dashboard.module.ts, libs/ui/src/lib/dashboard/pages/home/home.component.html
=> 7838 setup routing and title page header

.firebaserc, env/env.blockframes-kevin-d.ts
=> Edit config firebaserc and Add env-kevin-d.ts

.firebaserc, env/env.blockframes-kevin-m.ts
=> editing '.firebaserc'  & creating 'env.blockframes-kevin-m.ts' file

env/env.blockframes-kevin-d.ts
=> upadting variables 'appUrl'

env/env.blockframes-kevin-d.ts
=> KevinD setup

apps/catalog/catalog/src/app/app.module.ts, apps/festival/festival/src/app/app.module.ts, apps/financiers/financiers/src/app/app.module.ts, libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html, libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.ts, libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts, libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html, libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts, libs/utils/src/lib/yandex-metrica/yandex-metrica.service.ts
removed yandex #7936
code was commented.
If it is totally removed, we will also be able to remove `export const yandex` from blockframes-xxx.ts files
=> removed yandex #7936

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.module.ts, libs/analytics/src/lib/+state/analytics.firestore.ts, libs/analytics/src/lib/+state/analytics.model.ts, libs/analytics/src/lib/+state/analytics.service.ts, libs/firebase-utils/src/lib/firestoreMigrations/0074.ts
=> 7828 title activity page table

libs/utils/src/lib/emails/ids.ts
=> replace email template Id for new contract

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, libs/analytics/src/lib/+state/analytics.firestore.ts, libs/analytics/src/lib/+state/analytics.model.ts
=> 7835 titles activity page table

libs/firebase-utils/src/lib/firestoreMigrations/0074.ts
import analytic model from new model lib.
=> import from new model lib

assets/images/dark/empty_organization.svg, assets/images/light/empty_organization.svg
Issue: https://github.com/blockframes/blockframes/issues/6624
=> Replace empty_organization.svg by the fixed version

libs/firebase-utils/src/lib/firestoreMigrations/0073.ts, libs/notification/src/lib/+state/notification.service.ts, libs/ui/src/lib/tunnel/layout/layout.component.ts, libs/ui/src/lib/tunnel/page/page.component.html, libs/ui/src/lib/tunnel/page/page.component.ts
=> some fixes for movie

libs/movie/src/lib/movie/form/additional-information/additional-information.component.html, libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html, libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html, libs/ui/src/lib/app-bar.ts
=> Fixes 7978 2

apps/catalog/catalog/src/app/landing/landing.component.ts, apps/festival/festival/src/app/landing/landing.component.html, libs/contract/src/lib/avails/filter/filter.component.scss, libs/firebase-utils/src/lib/firestoreMigrations/0073.ts, libs/invitation/src/lib/+state/invitation.service.ts, libs/invitation/src/lib/invitation.component.ts, libs/landing/src/lib/appBridgeBanner/app-bridge-banner.component.html, libs/movie/src/lib/movie/form/additional-information/additional-information.component.html, libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html, libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html, libs/notification/src/lib/+state/notification.service.ts, libs/organization/src/lib/organization/pages/member/member.component.html, libs/ui/src/lib/app-bar.ts, libs/ui/src/lib/tunnel/layout/layout.component.ts, libs/ui/src/lib/tunnel/page/page.component.html, libs/ui/src/lib/tunnel/page/page.component.ts, libs/utils/src/lib/pipes/filter-by-date.pipe.ts, libs/utils/src/lib/static-model/static-model.ts
=> Fixes for release 4-1

libs/movie/src/lib/movie/form/main/main.component.html, libs/movie/src/lib/movie/form/main/main.component.ts, libs/utils/src/lib/form/validators/validators.ts
Part of comment : https://github.com/blockframes/blockframes/issues/7978#issuecomment-1069324639
=> Add a new error when date exceed 2041

apps/backend-functions/src/notification.ts, apps/backend-functions/src/templates/mail.ts
=> Release 4 1 deal negotiation

libs/movie/src/lib/movie/form/budget/range/budget-range.component.html, libs/movie/src/lib/movie/form/media-notes/notes.component.html
=> fix budget range initial value

apps/catalog/catalog/src/app/landing/landing.component.html
=> 7981 smaller and line break

apps/backend-functions/src/notification.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/shell.component.html, apps/catalog/catalog/src/app/marketplace/offer/shell/shell.component.html, apps/catalog/catalog/src/app/marketplace/title/selection/specific-terms/specific-terms.component.html, libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html
=> terms and conditions fixes

libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/import/src/lib/view-extracted-elements/titles/view-extracted-titles.component.ts
Fixed: https://github.com/blockframes/blockframes/issues/7984#issuecomment-1074139291
=> Check for duplicates on movie imports

apps/catalog/catalog/src/app/dashboard/sales/list/list.component.html, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.scss, apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.html, libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.scss
#7985
Decided with Ana to follow the [wireframes](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(IN-PROGRESS)?node-id=174%3A54038)
- if there are internal and external : show both, show title, show CTA on the right
- if there are only external : hide internal, show title, show CTA on the right
- if there are only internal : hide external, show title, show CTA on the right
- ir there is nothing: do not show title on the left (use the text+title in the center), do not show the CTA on the right (put in below the text and above the secondary cta)
=> 7985 fix empty state on my deals page

libs/event/src/lib/form/shell/shell.component.ts, libs/ui/src/lib/confirm/confirm.component.html, libs/ui/src/lib/confirm/confirm.component.ts
issue : https://github.com/blockframes/blockframes/issues/7538
=> Update popin delete - change and add a second part of text ( advice ) 

apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts
=> 7835 add screenings count

apps/catalog/catalog/src/app/app.module.ts, apps/festival/festival/src/app/app.module.ts, apps/financiers/financiers/src/app/app.module.ts, env/env.blockframes-antoine-9e16b.ts, env/env.blockframes-bruce.ts, env/env.blockframes-ci.ts, env/env.blockframes-demo-1.ts, env/env.blockframes-demo-2.ts, env/env.blockframes-demo-3.ts, env/env.blockframes-demo-4.ts, env/env.blockframes-demo-5.ts, env/env.blockframes-francois.ts, env/env.blockframes-george.ts, env/env.blockframes-kevin-d.ts, env/env.blockframes-kevin-m.ts, env/env.blockframes-nicolas.ts, env/env.blockframes-remco.ts, env/env.blockframes-staging.ts, env/env.blockframes-vincent.ts, env/env.blockframes-yonga.ts, env/env.blockframes.ts, libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html, libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.ts, libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts, libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html, libs/utils/src/lib/gdpr-cookie/cookie-form/cookie.form.ts, libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts, libs/utils/src/lib/hotjar/hotjar.service.ts
=> 7935 integrate hotjar

apps/catalog/catalog/src/app/dashboard/sales/list/list.component.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts
Disabled internal imports to avoid this.
https://github.com/blockframes/blockframes/issues/7985#issuecomment-1075360512
=> Disable internal imports

libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/import/src/lib/view-extracted-elements/titles/view-extracted-titles.component.ts
Fix: https://github.com/blockframes/blockframes/issues/7984#issuecomment-1075331416
=> fixed: remove verification of duplicate movie imports

apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts, libs/analytics/src/lib/+state/analytics.service.ts, libs/movie/src/lib/movie/+state/movie.service.ts
=> 7937 track pageView on catalog

apps/catalog/catalog/src/app/landing/landing.component.html
=> change catalog LP font size

libs/import/src/lib/view-extracted-elements/contract/utils.ts, libs/model/src/lib/contract.ts
Fixed: https://github.com/blockframes/blockframes/issues/7984#issuecomment-1076506432
=> fix: change case typo

libs/contract/src/lib/contract/components/confirm-with-validation/confirm-with-validation.component.html, libs/contract/src/lib/contract/components/confirm-with-validation/confirm-with-validation.component.scss, libs/utils/src/lib/hotjar/hotjar.service.ts, libs/utils/src/lib/yandex-metrica/yandex-metrica.service.ts
=> 8095 inject script only if not exists and remove div from modal

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, libs/analytics/src/lib/components/pie-chart/pie-chart.component.ts, libs/ui/src/lib/list/table/table.component.ts
=> 7836 filter table on pie chart click

apps/festival/festival/src/app/dashboard/dashboard.module.ts, apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.scss, apps/festival/festival/src/app/dashboard/home/home.component.ts, apps/festival/festival/src/app/dashboard/home/home.module.ts, libs/ui/src/lib/dashboard/pages/home/home.component.html, libs/ui/src/lib/dashboard/pages/home/home.component.scss, libs/ui/src/lib/map/map.component.ts
- Changes to dashboard should only affect festival
- Fixed routing of buttons
- optional unsubscribe on world-map because of error when destroying component before content is initialised.
=> dashboard changes only affect festival

apps/backend-functions/src/package.json
=> quick fix for #8111

libs/movie/src/lib/movie/+state/movie.service.ts
From issue: https://github.com/blockframes/blockframes/issues/8098
=> Remove the possibility of selecting a movie with access to false

apps/festival/festival/src/app/event/event.component.html
=> 8153 remove screen logo from event toolbar

apps/catalog/catalog/src/app/dashboard/avails/list/list.component.html
- Title
- Total Gross Receipts
* * *
From issue : https://github.com/blockframes/blockframes/issues/6724
=> AC - Tables Inventories - Section: Avails

apps/backend-functions/src/templates/mail.ts
Hotfix for @cams-goussale 
Offer created email weren't sended to support
=> Send offer created email to support

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts
=> 7834 optimize queries

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/+state/analytics.service.ts
The analytics should not display analytics from owners of title
=> 7689 only analytics of non-title owners

apps/festival/festival/src/app/event/login/login.component.ts, libs/event/src/lib/guard/event-access.guard.ts
=> fix Check if user has approved org for Private events #8058

libs/contract/src/lib/avails/calendar/calendar.component.ts
=> fixed: renew matrix state on each calendar draw

apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.scss, libs/event/src/lib/components/request-screening/request-screening.component.html, libs/event/src/lib/components/request-screening/request-screening.component.scss, libs/event/src/lib/components/screening-item/screening-item.component.html, libs/invitation/src/lib/components/action/action.component.html, libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.html, libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.scss, libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.ts, libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.module.ts, styles/components/mat-button.scss
=> 7531 translucent background on buttons

apps/festival/festival/src/app/marketplace/layout/aside/aside.component.html, apps/festival/festival/src/app/marketplace/layout/aside/aside.component.scss, apps/festival/festival/src/app/marketplace/layout/aside/aside.component.ts, apps/festival/festival/src/app/marketplace/layout/aside/aside.module.ts, apps/festival/festival/src/app/marketplace/marketplace.component.html, libs/ui/src/lib/layout/app-logo/app-logo.component.scss, libs/ui/src/lib/layout/marketplace/marketplace.component.html
=> 6613 responsive marketplace toolbar

apps/catalog/catalog/src/app/marketplace/title/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.scss, libs/event/src/lib/components/request-screening/request-screening.component.scss, libs/event/src/lib/components/request-screening/request-screening.component.ts, libs/movie/src/lib/movie/components/header/header.component.html, libs/movie/src/lib/movie/components/header/header.component.scss, libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.html, libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.scss, libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.ts, libs/movie/src/lib/movie/components/promotional-links/promotional-links.module.ts
=> 6878 promotional elements and remove animation

apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
=> update after rjxs upgrade

libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/view-extracted-elements/contract/utils.ts, libs/import/src/lib/view-extracted-elements/contract/view-extracted-contracts.component.ts, libs/media/src/lib/file/explorer/explorer.component.ts, libs/media/src/lib/file/file-list-uploader/file-list-uploader.component.ts, libs/movie/src/lib/movie/+state/movie.service.ts, libs/user/src/lib/user/+state/user.service.ts
to prevent errors like this :
`Firestore` should not be imported `from 'firebase/firestore'`;
=> fixes firebase Imports

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.scss, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/components/line-chart/line-chart.component.scss, libs/analytics/src/lib/components/line-chart/line-chart.component.ts
#8211
Map component
Line chart
=> 8211 remarks for sellers analytics 2

libs/invitation/src/lib/components/action/action.component.html
=> 7961 fix translucent for small

libs/analytics/src/lib/components/line-chart/line-chart.component.html, libs/analytics/src/lib/components/line-chart/line-chart.component.scss, libs/analytics/src/lib/components/line-chart/line-chart.component.ts, libs/analytics/src/lib/components/line-chart/line-chart.module.ts
=> 8211 per unit buttons on line chart

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.module.ts
=> 7841 add user header

apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts, apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts, apps/festival/festival/src/app/dashboard/title/list/list.component.ts, apps/festival/festival/src/app/marketplace/title/view/view.component.ts, libs/analytics/src/lib/+state/analytics.service.ts, libs/event/src/lib/components/request-screening/request-screening.component.ts, libs/movie/src/lib/movie/+state/movie.service.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts, libs/movie/src/lib/movie/marketplace/main/main.component.html, libs/movie/src/lib/movie/marketplace/main/main.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts, libs/organization/src/lib/organization/+state/organization.service.ts
#7689
This prevents circular dependencies
Also removed some unused code
=> 7689 analytics service no longer needs movie or org service

apps/catalog/catalog/src/app/dashboard/title/activity/activity.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.module.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts, apps/financiers/financiers/src/app/dashboard/title/activity/activity.component.ts, libs/analytics/src/lib/+state/analytics.service.ts, libs/analytics/src/lib/+state/utils.ts, libs/utils/src/lib/helpers.ts
=> 7845 buyers activity table

apps/backend-functions/src/notification.ts, apps/backend-functions/src/templates/mail.ts, libs/model/src/lib/bucket.ts, libs/model/src/lib/contract.ts, libs/model/src/lib/static/static-model.ts, libs/utils/src/lib/emails/utils.ts
=> Display currency symbol / format price number

.circleci/config.yml
Trying to resolve the issue when the CI crashes if there is no feedback from Cypress for 10 minutes.
=> festival cypress timeout set to 30min

libs/organization/src/lib/organization/+state/organization.service.ts, libs/user/src/lib/auth/+state/auth.service.ts, libs/utils/src/lib/zone.ts
=> Navigation triggered outside Angular zone #8263

libs/firebase-utils/src/lib/anonymize/lib.ts
=> anon-db-process is failing #8261

libs/ui/src/lib/tunnel/layout/nav/nav.component.html, libs/ui/src/lib/tunnel/layout/nav/nav.component.scss
Issue : https://github.com/blockframes/blockframes/issues/8127
Now :
=> Align icons - nav movie tunnel

libs/analytics/src/lib/components/line-chart/line-chart.component.html, libs/analytics/src/lib/components/line-chart/line-chart.component.ts
=> 7834 add markers

apps/catalog/catalog/src/app/marketplace/title/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.scss, apps/financiers/financiers/src/app/marketplace/title/view/view.component.html, apps/financiers/financiers/src/app/marketplace/title/view/view.component.scss, libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
=> 8310 movie banner

libs/movie/src/lib/movie/form/artistic/artistic.component.html, libs/movie/src/lib/movie/form/artistic/artistic.component.scss, libs/movie/src/lib/movie/form/main/main.component.html, libs/movie/src/lib/movie/form/main/main.component.scss, libs/ui/src/lib/form/table/form-table.component.scss
- Move action buttons from right to left (in cell)
- Add cursor pointer on clickable cell (description, filmography) in movie tunnel (directors, cast & crew members)
=> Fix fast bug from the meeting inventories from today

styles/components/mat-icon.scss
=> 8327 fix icon colors

libs/user/src/lib/auth/components/privacy-policy-text/privacy-policy-text.component.html, styles/style.scss
=> 7969 privacy policy fix links

libs/contract/src/lib/bucket/+state/bucket.service.ts
=> 7830 fix add to bucket on movie card

apps/festival/festival/src/app/event/login/login.component.ts, apps/festival/festival/src/app/event/login/login.module.ts, libs/user/src/lib/auth/pages/identity/identity.component.ts, libs/user/src/lib/auth/pages/identity/identity.module.ts, libs/user/src/lib/auth/pages/login/login.component.ts, libs/user/src/lib/auth/pages/login/login.module.ts
replaced old snackbars `snackBar.open(err.message, ..) ` by the snakbarError component
=> Update snackbars error

apps/crm/crm/src/app/crm/crm.module.ts, apps/crm/crm/src/app/crm/pages/movie/movie.component.html, apps/crm/crm/src/app/crm/pages/movie/movie.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, libs/analytics/src/lib/+state/utils.ts
=> 7937 add analytics to title page on crm

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.html, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.scss, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.ts
=> 7841 vanity metrics filter table and export analytics

libs/ui/src/lib/carousel/carousel.component.scss
=> hide carousel scrollbar for firefox

libs/utils/src/lib/emails/ids.ts
=> Update asking price template

libs/user/src/lib/auth/+state/auth.service.ts
=> access appropriate attrib on user

apps/festival/festival/src/app/event/login/login.component.ts, libs/user/src/lib/auth/pages/login/login.component.ts
From issue: https://github.com/blockframes/blockframes/issues/8290
=> Dismiss the snackbar at the destory event of the component

apps/catalog/catalog/src/app/dashboard/title/activity/activity.component.ts, apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts, apps/financiers/financiers/src/app/dashboard/title/activity/activity.component.ts, libs/movie/src/lib/movie/dashboard/additional/additional.component.ts, libs/movie/src/lib/movie/dashboard/artistic/artistic.component.ts, libs/movie/src/lib/movie/dashboard/delivery/delivery.component.ts, libs/movie/src/lib/movie/dashboard/main/main.component.ts, libs/movie/src/lib/movie/dashboard/production/production.component.ts, libs/movie/src/lib/movie/dashboard/shell/shell.component.ts
=> 8299 fix page title

apps/crm/crm/src/app/crm/components/event-info/event-info.component.html, apps/festival/festival/src/app/event/ended/meeting-ended.component.html, apps/festival/festival/src/app/event/lobby/lobby.component.html, apps/festival/festival/src/app/event/lobby/lobby.module.ts, apps/festival/festival/src/app/event/view/view.component.html, libs/event/src/lib/form/create/create.component.html, libs/invitation/src/lib/components/item/item.component.html, libs/invitation/src/lib/components/item/item.module.ts, libs/notification/src/lib/+state/notification.service.ts
=> Change slate for Slate Presentation in UI

apps/catalog/catalog/src/app/marketplace/title/list/list.component.html, apps/catalog/catalog/src/app/marketplace/title/list/list.component.scss, apps/festival/festival/src/app/marketplace/event/list/list.component.html, apps/festival/festival/src/app/marketplace/organization/list/list.component.html, apps/festival/festival/src/app/marketplace/organization/list/list.component.scss, apps/festival/festival/src/app/marketplace/organization/list/list.component.ts, apps/festival/festival/src/app/marketplace/organization/list/list.module.ts, apps/festival/festival/src/app/marketplace/title/list/list.component.html, apps/festival/festival/src/app/marketplace/title/list/list.component.scss, apps/financiers/financiers/src/app/marketplace/title/list/list.component.html, apps/financiers/financiers/src/app/marketplace/title/list/list.component.scss, libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.component.html, libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.component.scss, libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html, libs/utils/src/lib/emails/utils.ts
#8301
also include last point of #8304
(https://github.com/blockframes/blockframes/issues/8304#issuecomment-1117409751)
=> Release 8301

apps/crm/crm/src/app/crm/pages/organization/organization.component.html, apps/crm/crm/src/app/crm/pages/organization/organization.component.scss, libs/organization/src/lib/organization/+state/organization.service.ts
=> small fixes for #8303 

apps/catalog/catalog/src/app/dashboard/title/list/list.component.html, apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/title/list/list.component.html, apps/festival/festival/src/app/dashboard/title/list/list.component.ts, apps/financiers/financiers/src/app/dashboard/title/list/list.component.html, apps/financiers/financiers/src/app/dashboard/title/list/list.component.ts, libs/ui/src/lib/list/table/filters.ts
Filtering on columns with undefined `colRef` didn't work. We have to create custom filter function for those.
=> 8299 fix filter on bf table

libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.component.html, libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.component.scss, libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.module.ts, libs/ui/src/lib/global-modal/global-modal.component.html, libs/ui/src/lib/global-modal/global-modal.component.scss, libs/user/src/lib/auth/components/privacy-policy-text/privacy-policy-text.component.html, libs/user/src/lib/auth/components/privacy-policy-text/privacy-policy-text.component.scss, libs/user/src/lib/auth/components/privacy-policy-text/privacy-policy-text.component.ts, libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html, libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.scss, libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts, libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.ts
From issue: https://github.com/blockframes/blockframes/issues/8381
=> General UI - CrossApp Modals Privacy Policy

libs/organization/src/lib/organization/pages/organization-pending/organization-pending.component.scss, styles/style.scss
=> General UI fixes

apps/catalog/catalog/src/app/dashboard/sales/shell/external/external.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/negotiation/negotiation.component.ts, apps/catalog/catalog/src/app/dashboard/sales/shell/view/view.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.component.ts, libs/contract/src/lib/contract/components/confirm-decline/confirm-decline.component.html, libs/contract/src/lib/contract/components/confirm-decline/confirm-decline.component.scss, libs/contract/src/lib/contract/components/confirm-with-validation/confirm-with-validation.component.html, libs/contract/src/lib/contract/components/confirm-with-validation/confirm-with-validation.component.scss
Last things of : https://github.com/blockframes/blockframes/issues/8301#issuecomment-1116231415
=> Modal - Contract - Scroll and Checkbox Color

apps/backend-functions/src/orgs.ts, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.html, libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/titles/fieldConfigs.ts, libs/import/src/lib/view-extracted-elements/titles/utils.ts, libs/model/src/lib/movie.ts
=> release-4-2-import debug

libs/movie/src/lib/movie/components/header/header.component.ts, libs/movie/src/lib/movie/marketplace/additional/route.ts
https://github.com/blockframes/blockframes/issues/8301#issuecomment-1118273540
https://github.com/blockframes/blockframes/issues/8299#issuecomment-11174879068299
=> Remove space under movie card / display additional tab in movie page

libs/import/src/lib/table-extracted-elements/contracts/contracts.component.html, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.scss, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/table-extracted-elements/movies/movies.component.html, libs/import/src/lib/table-extracted-elements/movies/movies.component.scss, libs/import/src/lib/table-extracted-elements/movies/movies.component.ts, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.html, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.scss, libs/import/src/lib/table-extracted-elements/organizations/organizations.component.ts, libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/contract/view-extracted-contracts.component.html, libs/import/src/lib/view-extracted-elements/organizations/view-extracted-organizations.component.html, libs/import/src/lib/view-extracted-elements/organizations/view-extracted-organizations.component.ts
Fixes for #8307 
Also tried to uniformize and clean not used code
=> Fixes for #8307

apps/catalog/catalog/src/app/marketplace/home/home.component.ts, apps/catalog/catalog/src/app/marketplace/offer/shell/contract-edit/contract-edit.component.html, apps/festival/festival/src/app/marketplace/home/home.component.ts, libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.html
Renaming: https://github.com/blockframes/blockframes/issues/8301#issuecomment-1117297030
Hide Column: https://github.com/blockframes/blockframes/issues/8301#issuecomment-1117334948
Modal Size: https://github.com/blockframes/blockframes/issues/8301#issuecomment-1118266791
=> General UI - Little of everything

libs/landing/src/lib/shell/shell.component.ts
Issue: https://github.com/blockframes/blockframes/issues/8301#issuecomment-1115924119
=> Update snackbar message from 'subscribe' to a newsletter

apps/catalog/catalog/src/app/marketplace/home/home.component.ts, apps/festival/festival/src/app/marketplace/home/home.component.ts, libs/user/src/lib/auth/pages/preferences/modal/preferences.component.scss
- Revert size from S to L
- Center the title and the text
=> General UI - Fix Preferences modal

apps/catalog/catalog/src/app/dashboard/tunnel/movie-tunnel.routes.ts, apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.routes.ts, apps/financiers/financiers/src/app/dashboard/tunnel/routes.ts, libs/model/src/lib/static/static-model.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.scss, libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
=> Release 4.2 - Movie small issues

libs/movie/src/lib/movie/marketplace/shell/shell.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.component.scss, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
After discussion we opted to go with hiding the page bar instead
https://cascade8.slack.com/archives/CFT9HSPLL/p1652264033670959
=> 8299 hide page bar on small screen instead

libs/movie/src/lib/movie/marketplace/additional/additional.component.html
=> Show version for all production status except development

apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.scss, libs/analytics/src/lib/components/line-chart/line-chart.component.scss, libs/analytics/src/lib/components/map/map.component.html, libs/analytics/src/lib/components/map/map.component.scss, libs/analytics/src/lib/components/pie-chart/pie-chart.component.html, libs/analytics/src/lib/components/pie-chart/pie-chart.component.scss
=> change requests merge back 2

apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.module.ts, apps/festival/festival/src/app/event/view/view.component.html, libs/media/src/lib/file/carousel/carousel.component.html, libs/media/src/lib/file/carousel/carousel.module.ts, libs/ui/src/lib/carousel/carousel.component.ts, libs/ui/src/lib/carousel/carousel.module.ts, libs/ui/src/lib/layout/layout.module.ts
fix #8432
Also related to #8451
=> 8432 fix shaking

apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.ts, apps/festival/festival/src/app/dashboard/home/home.module.ts, libs/analytics/src/lib/+state/utils.ts, libs/model/src/lib/analytics.ts
=> added table of most active buyers

libs/movie/src/lib/movie/form/artistic/artistic.component.html, libs/movie/src/lib/movie/form/main/main.component.html, libs/movie/src/lib/movie/form/media-videos/media-videos.component.html, libs/movie/src/lib/movie/form/movie.form.ts, libs/movie/src/lib/movie/form/reviews/reviews.component.html, libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.html, libs/movie/src/lib/movie/form/story-elements/story-elements.component.html, libs/utils/src/lib/form/validators/validators.ts
From issue: https://github.com/blockframes/blockframes/issues/7863
=> Movie - Add character limit and placeholder

apps/catalog/catalog/src/app/app.module.ts, apps/cms/src/app/app.module.ts, apps/crm/crm/src/app/app.module.ts, apps/festival/festival/src/app/app.module.ts, apps/financiers/financiers/src/app/app.module.ts, libs/user/src/lib/auth/components/widget/widget.component.ts, libs/utils/src/lib/emulator-front-setup.ts, libs/utils/src/lib/pdf/pdf.service.ts
=> update "auth widget"  and cleaned emulator setup

apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/components/line-chart/line-chart.component.ts
=> 8534 fix loading issue

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.module.ts, libs/analytics/src/lib/components/bar-chart/bar-chart.component.html, libs/analytics/src/lib/components/bar-chart/bar-chart.component.scss, libs/analytics/src/lib/components/bar-chart/bar-chart.component.ts, libs/analytics/src/lib/components/bar-chart/bar-chart.module.ts
=> 7848 bar chart

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.module.ts
=> added vanity metrics page views in title analytics page

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
=> added interactions graph

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.module.ts, libs/analytics/src/lib/components/line-chart/line-chart.component.ts, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.ts, libs/analytics/src/lib/components/movie-analytics-chart/utils.ts, libs/model/src/lib/analytics.ts
=> Buyers vanity metrics

libs/media/src/lib/file/file-uploader/file-uploader.component.ts, libs/ui/src/lib/form/list/form-list.component.ts
=> 8100 file no longer stays when save in bf-form-list

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.scss, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.module.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.scss
=> 8581 fix responsiveness and buttons

libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts, libs/user/src/lib/auth/forms/notifications-form/notifications.form.ts
=> Create movie submitted notification settings

apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/ui/src/lib/list/table/filters.ts, libs/ui/src/lib/list/table/table.component.ts
=> 8512 add filter on table

apps/crm/crm/src/app/crm/pages/events/events.component.html, apps/crm/crm/src/app/crm/pages/events/events.component.scss, apps/crm/crm/src/app/crm/pages/events/events.component.ts
Issue: https://github.com/blockframes/blockframes/issues/8566
=> Fix CRM event export data

libs/ui/src/lib/dashboard/components/movie-table-actions/movie-table-actions.component.html, libs/ui/src/lib/dashboard/components/movie-table-actions/movie-table-actions.module.ts
Re-activate tooltips on action buttons on `/dashboard/title`
Update tooltips texts
Update Tooltips Inventory
https://github.com/blockframes/blockframes/issues/8611#issuecomment-1153916272
https://github.com/blockframes/blockframes/issues/8611#issuecomment-1156136893
=> Movie - Fix tooltips on action buttons

apps/backend-functions/src/notification.ts
=> Fix notifs

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.html
=> Analytics 2 release 4 3

libs/movie/src/lib/movie/components/header/header.component.scss
issue: https://github.com/blockframes/blockframes/issues/8612
=> Release 4 3 - General ui

styles/components/mat-tooltip.scss, styles/themes/builder.scss
=> Change tooltip colors

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts
Fixed: https://github.com/blockframes/blockframes/issues/8610#issuecomment-1153971868
=> properly calculate invitations/requests count

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.module.ts, libs/event/src/lib/pages/analytics/analytics.component.html, libs/ui/src/lib/list/table/table.component.ts
=> Analytics watchtime

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.module.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.module.ts, apps/festival/festival/src/app/event/ended/meeting-ended.component.html, apps/festival/festival/src/app/event/session/session.component.ts, firestore.rules, libs/devops/src/lib/firestoreMigrations/0080.ts, libs/devops/src/lib/firestoreMigrations/index.ts, libs/event/src/lib/pages/analytics/analytics.component.html, libs/event/src/lib/pages/analytics/analytics.component.ts, libs/event/src/lib/pages/analytics/analytics.module.ts, libs/event/src/lib/pipes/is-watching-now.pipe.ts, libs/media/src/lib/file/controls/controls.module.ts, libs/model/src/lib/invitation.ts, libs/model/src/lib/user.ts, libs/movie/src/lib/movie/form/summary/summary.module.ts, libs/utils/src/lib/helpers.ts, libs/utils/src/lib/pipes/duration.pipe.ts
fix #8717
results:
Exports CSV & Excel:
[Boiling Point on Archipel Market 06_28_2022 - Report.xlsx](https://github.com/blockframes/blockframes/files/8999947/Boiling.Point.on.Archipel.Market.06_28_2022.-.Report.xlsx)
[buyer-screener-analytics.csv](https://github.com/blockframes/blockframes/files/8999948/buyer-screener-analytics.csv)
[screener-analytics.csv](https://github.com/blockframes/blockframes/files/8999949/screener-analytics.csv)
=> Watching Now - feat 8717 ready

libs/contract/src/lib/avails/sets.ts
=> refactor: added clearer comments

apps/catalog/catalog/src/app/dashboard/avails/select-title/select-title.component.html, apps/catalog/catalog/src/app/dashboard/avails/select-title/select-title.component.scss, apps/catalog/catalog/src/app/dashboard/avails/select-title/select-title.component.ts, apps/catalog/catalog/src/app/dashboard/avails/select-title/select-title.module.ts, apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
=> implemented title selection and route to avails form page

apps/festival/festival/src/app/marketplace/home/home.component.html, apps/festival/festival/src/app/marketplace/home/home.component.scss
=> remove privacy policy banner

libs/user/src/lib/auth/guard/auth.guard.ts
=> 8027 redirect to login page instead of landing page

apps/festival/festival/src/app/event/email/email.component.html, apps/festival/festival/src/app/event/email/email.component.scss, apps/festival/festival/src/app/event/email/email.component.ts, apps/festival/festival/src/app/event/email/email.module.ts, apps/festival/festival/src/app/event/identity/identity.component.html, apps/festival/festival/src/app/event/identity/identity.component.scss, apps/festival/festival/src/app/event/identity/identity.component.ts, apps/festival/festival/src/app/event/identity/identity.module.ts
=> accept TC to access events

apps/backend-functions/src/event.ts, apps/backend-functions/src/main.ts, apps/backend-functions/src/templates/mail.ts
=> Send emails to admin when creating an event

apps/catalog/catalog/src/app/dashboard/avails/manage/manage.component.html, apps/crm/crm/src/app/crm/pages/contracts/term-form/term-form.component.html, apps/crm/crm/src/app/crm/pages/contracts/term-form/term-form.component.ts, firestore.rules, libs/contract/src/lib/avails/filter/filter.component.ts, libs/contract/src/lib/term/components/form/form.component.html, libs/contract/src/lib/term/components/form/form.component.ts, libs/ui/src/lib/form/table/form-table.component.ts
=> Mandate form bugs

apps/backend-functions/src/event.ts
=> no unsubscribe link #8765

apps/backend-functions/src/internals/invitations/events.ts, apps/backend-functions/src/invitation.ts, apps/backend-functions/src/orgs.ts, apps/festival/festival/src/app/event/session/session.component.ts, libs/devops/src/lib/internals/utils.ts, libs/event/src/lib/pages/analytics/analytics.component.ts, libs/model/src/lib/event.ts, libs/organization/src/lib/organization/service.ts
=> event fixes #8765

apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss, libs/movie/src/lib/movie/form/shell/shell.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.html
=> 8771 8769 fixes

libs/contract/src/lib/term/components/form/form.component.ts
Set term from/to to midnight in accordance with [term import date.](https://github.com/blockframes/blockframes/pull/7726/files#diff-6d8f5dfd8f1b19b004db293a9b73f54b78ddb47021d07061d401dbde07f661e4R181)
=> fix(term form): set term from/to to midnight

apps/catalog/catalog/src/app/dashboard/avails/list/list.component.scss, apps/catalog/catalog/src/app/dashboard/avails/manage/manage.component.html, apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.html, apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.scss
multiple change requests in #8802
=> refactor: cleaned css and html.

libs/model/src/lib/emails.ts, libs/user/src/lib/auth/components/signin-form/signin-form.component.html
https://github.com/blockframes/blockframes/issues/8483
https://github.com/blockframes/blockframes/issues/8620
=> 8620 - 8483

apps/crm/crm/src/app/crm/pages/user/user.component.html, apps/crm/crm/src/app/crm/pages/user/user.component.ts
=> 8461 user activity

apps/crm/crm/src/app/crm/pages/movie/movie.component.html, apps/crm/crm/src/app/crm/pages/user/user.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.html, apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/components/line-chart/line-chart.component.ts, libs/analytics/src/lib/components/movie-analytics-chart/movie-analytics-chart.component.ts, libs/analytics/src/lib/components/movie-analytics-chart/movie-analytics.model.ts, libs/analytics/src/lib/components/movie-analytics-chart/utils.ts, libs/analytics/src/lib/utils.ts, libs/devops/src/lib/firestoreMigrations/0083.ts, libs/devops/src/lib/firestoreMigrations/index.ts, libs/model/src/lib/analytics.ts, libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.html, libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.ts, libs/movie/src/lib/movie/marketplace/main/main.component.ts, libs/movie/src/lib/movie/marketplace/shell/shell.component.html, libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
=> 8693 promo elements opened

libs/event/src/lib/form/event.form.ts, libs/event/src/lib/form/screening/screening.component.html, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.scss, libs/event/src/lib/form/shell/shell.component.ts
=> 7537 chip screening file missing

libs/media/src/lib/file/explorer/explorer.component.ts, libs/media/src/lib/file/explorer/explorer.model.ts
=> 8829 public screener in file explorer on CRM

libs/media/src/lib/file-uploader.service.ts, libs/media/src/lib/file/pipes/file-list.pipe.ts, libs/movie/src/lib/movie/form/media-notes/notes.component.html, libs/movie/src/lib/movie/form/media-notes/notes.component.ts, libs/movie/src/lib/movie/form/media-videos/media-videos.component.html, libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts, libs/ui/src/lib/form/list/form-list.component.ts
=> 8578 Remove file from queue when removing from bf-form-list

apps/backend-functions/src/templates/mail.ts, libs/event/src/lib/form/shell/shell.component.html, libs/event/src/lib/form/shell/shell.component.ts, libs/event/src/lib/guard/event-edit.guard.ts, libs/invitation/src/lib/form/user/user.component.ts, libs/notification/src/lib/service.ts, libs/utils/src/lib/algolia/helper.utils.ts
=> 8438 add screening requestor to invitations

libs/devops/src/lib/firestoreMigrations/0084.ts, libs/devops/src/lib/internals/utils.ts, libs/model/src/lib/permissions.ts, libs/testing/cypress/browser/src/lib/helpers.ts, libs/testing/unit-tests/src/lib/fixtures/rules.ts
issue: https://github.com/blockframes/blockframes/issues/7475
=> Remove unused db fields

libs/contract/src/lib/avails/avails.ts
=> hotfix for release 4.4 #8887

apps/backend-functions/src/player.spec.ts, apps/catalog/catalog-e2e/src/integration/marketplace/display-title.spec.ts, apps/catalog/catalog/src/app/marketplace/home/home.component.html, apps/catalog/catalog/src/app/marketplace/title/list/list.component.html, apps/festival/festival-e2e/src/integration/dashboard/Events/create-screening.spec.ts, apps/festival/festival-e2e/src/integration/marketplace/display-title.spec.ts, apps/festival/festival/src/app/marketplace/home/home.component.html, apps/festival/festival/src/app/marketplace/organization/list/list.component.html, apps/festival/festival/src/app/marketplace/organization/title/title.component.html, apps/festival/festival/src/app/marketplace/title/list/list.component.html, libs/organization/src/lib/organization/components/card/card.component.html, libs/ui/src/lib/list/page/list-page.component.ts
=> catalog: load more test / festival: published movie appreas in org titles

libs/utils/src/lib/constants.ts
=> updated app version

libs/user/src/lib/auth/components/data-validation/data-validation.component.ts, libs/user/src/lib/auth/service.ts
https://sentry.io/organizations/cascade-8/issues/3508897482/events/e7c09337bcdd411cb240a19ae7f601bb/events/?project=1540126&referrer=previous-event&statsPeriod=14d
=> fix sentry 3508897482

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/contract/src/lib/bucket/service.ts, libs/model/src/lib/avail.ts
Send orgId when user adds terms to selection with icon feature #8946
=> Send orgId when user adds terms to selection with icon feature #8946

apps/festival/festival/src/app/event/event.component.html, apps/festival/festival/src/app/marketplace/marketplace.component.html, apps/festival/festival/src/styles.scss, styles/themes/screen-daily.scss
Switching to Screen FYC theme #9032
=>  Hotfix r-4-5-3 Switching to Screen FYC theme #9032

apps/festival/festival-e2e/src/integration/profile/access.spec.ts, env/env.blockframes-ci.ts, env/env.demo-blockframes.ts
Permission error snackbar on E2E tests #8968
=> Permission error snackbar on E2E tests #8968

apps/backend-functions/src/notification.ts, apps/crm/crm/src/app/crm/pages/invitations/invitations.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.component.html, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.module.ts, apps/crm/crm/src/app/crm/pages/offers/list/offer-list.component.html, apps/crm/crm/src/app/crm/pages/offers/list/offer-list.component.scss, apps/crm/crm/src/app/crm/pages/offers/list/offer-list.component.ts, apps/crm/crm/src/app/crm/pages/offers/list/offer-list.module.ts, apps/crm/crm/src/app/crm/pages/users/users.component.html, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/crm/crm/src/app/crm/pages/users/users.module.ts, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/utils.ts, libs/model/src/lib/analytics.ts, libs/model/src/lib/invitation.ts, libs/ui/src/lib/list/buttons/list-filter-buttons.component.ts
CRM export - new requests #8931
=> WIP - CRM export - new requests

apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
=> New filters Title List Catalog (festival & qualification)  #8935

apps/backend-functions/src/orgs.ts
store created org with status accepted on algolia #9066
=> store created org with status accepted on algolia

apps/backend-functions/src/orgs.ts, apps/crm/crm/src/app/crm/pages/movie/movie.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/utils.ts, libs/movie/src/lib/movie/service.ts
Co-authored-by: bruce <delorme.bruce.michel@gmail.com>
=> hotfix release 4.5.4

apps/backend-functions/src/orgs.ts, apps/crm/crm/src/app/crm/pages/movie/movie.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/utils.ts, libs/movie/src/lib/movie/service.ts
Co-authored-by: bruce <delorme.bruce.michel@gmail.com>
=> merge-back-hotfix-r-4-5-4

apps/festival/festival/src/app/event/session/session.component.ts
=> fix event bug #9080

apps/catalog/catalog-e2e/src/integration/marketplace/search-title.spec.ts, apps/festival/festival-e2e/src/integration/marketplace/search-title.spec.ts
=> updated e2e tests after #8935

apps/catalog/catalog-e2e/src/integration/marketplace/search-title.spec.ts, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/festival/festival-e2e/src/integration/marketplace/search-title.spec.ts, apps/festival/festival/src/app/event/session/session.component.ts, firestore.rules, libs/analytics/src/lib/service.ts, libs/analytics/src/lib/utils.ts, libs/model/src/lib/analytics.ts, libs/utils/src/lib/constants.ts
=> fixes of the day r 4.5.5

apps/crm/crm/src/app/crm/components/organization/create-organization/create.component.ts, apps/crm/crm/src/app/crm/components/organization/forms/organization-form/organization-form.component.ts, libs/admin/src/lib/crm/forms/organization-crm.form.ts
=> small crm fixes #9085

apps/catalog/catalog-e2e/src/integration/authentification/password-change.spec.ts, apps/festival/festival-e2e/src/integration/_plugins/firestore.spec.ts, apps/festival/festival-e2e/src/integration/authentification/login.spec.ts, apps/festival/festival-e2e/src/integration/authentification/signup-guard.spec.ts, apps/festival/festival-e2e/src/integration/authentification/signup-with-invitation.spec.ts, apps/festival/festival-e2e/src/integration/authentification/signup.spec.ts, apps/festival/festival-e2e/src/integration/profile/access.spec.ts
=> uniformizing clearing process

apps/backend-functions/src/media.ts, libs/model/src/lib/static/static-model.ts, libs/model/src/lib/static/types.ts, libs/movie/src/lib/movie/components/video-upload/video-upload.component.html, libs/movie/src/lib/movie/components/video-upload/video-upload.component.ts, libs/movie/src/lib/movie/components/video-upload/video-upload.module.ts
=> feat- #9044

apps/catalog/catalog-e2e/src/integration/authentification/password-change.spec.ts, libs/user/src/lib/auth/pages/login/login.component.ts
=> test feat-9106

apps/catalog/catalog-e2e/src/integration/authentification/password-change.spec.ts, apps/festival/festival-e2e/src/integration/authentification/login.spec.ts, libs/testing/cypress/browser/src/lib/support.ts
=> trying to fix flaky email input

apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts
debug analytics if org deleted #9125
=> debug analytics if org deleted #9125

apps/backend-functions/src/movie.ts, apps/backend-functions/src/notification.ts, apps/backend-functions/src/templates/mail.ts, apps/catalog/catalog/src/app/marketplace/title/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts, apps/catalog/catalog/src/app/marketplace/title/view/view.module.ts, libs/model/src/lib/emails.ts, libs/model/src/lib/utils.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.html, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.module.ts, libs/notification/src/lib/service.ts, libs/user/src/lib/auth/forms/notifications-form/notifications-form.component.ts, libs/utils/src/lib/emails/ids.ts
=> Feat 8128 asking price

libs/utils/src/lib/pdf/pdf.service.ts
=> Pdf export add dates #8934

apps/catalog/catalog-e2e/src/integration/marketplace/deal-create-offer.spec.ts
=> testing redirects in email links

apps/backend-ops/src/main.ts, libs/devops/src/lib/users.ts
improved change password command
=> improved change password command

libs/ui/src/lib/dashboard/components/empty-movie/empty-movie.component.html
=> solves 404 link #9093

libs/event/src/lib/components/request-screening/request-screening.component.html, libs/event/src/lib/components/request-screening/request-screening.component.ts
Festival - Hide "ask for a screening" button for specific org activities #9116
=> Festival - Hide "ask for a screening" button for specific org activities #9116

apps/crm/crm/src/app/crm/crm.module.ts, apps/crm/crm/src/app/crm/pages/movie/movie.component.html, apps/crm/crm/src/app/crm/pages/movie/movie.component.scss, apps/crm/crm/src/app/crm/pages/movie/movie.component.ts, libs/organization/src/lib/organization/components/chip/chip.component.ts
CRM Movie view - Add Organization name & link to it #8926
=> CRM Movie view - Add Organization name & link to it #8926

apps/crm/crm/src/app/crm/pages/user/user.component.html
CRM - User view - Analytics table - add app access #9109
=> CRM - User view - Analytics table - add app access #9109

apps/crm/crm/src/app/crm/pages/events/events.component.html, apps/crm/crm/src/app/crm/pages/events/events.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.component.html, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/organization/organization.component.html, apps/crm/crm/src/app/crm/pages/organizations/organizations.component.html, apps/crm/crm/src/app/crm/pages/users/users.component.html, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/crm/crm/src/app/dashboard/toolbar-top/toolbar-top.component.html
CRM - Org view - Add an action column with open in a new tab action in the movie list #9117
=> CRM - Org view - Add an action column with open in a new tab action in the movie list #9117

apps/crm/crm/src/app/crm/pages/movie/movie.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/users/users.component.html, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.html, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/titles/titles-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.html, apps/festival/festival/src/app/dashboard/home/home.component.ts, apps/festival/festival/src/app/event/lobby/lobby.component.ts, apps/festival/festival/src/app/event/session/session.component.ts, apps/festival/festival/src/app/marketplace/organization/title/title.component.ts, apps/festival/festival/src/app/marketplace/organization/view/view.component.ts, firestore.rules, libs/analytics/src/lib/components/bar-chart/bar-chart.component.ts, libs/analytics/src/lib/components/metric-card-list/metric-card-list.component.ts, libs/analytics/src/lib/components/pie-chart/pie-chart.component.ts, libs/analytics/src/lib/service.ts, libs/analytics/src/lib/utils.ts, libs/event/src/lib/components/meeting/room/video-room.component.ts, libs/model/src/lib/analytics.ts, libs/user/src/lib/auth/service.ts
=> #9124 WIP analytics

apps/festival/festival/src/app/event/event.component.html, apps/festival/festival/src/app/marketplace/marketplace.component.html, apps/festival/festival/src/app/organization/organization.component.html, apps/festival/festival/src/styles.scss
=> Removed screen-daily theme #9166

apps/catalog/catalog/src/app/marketplace/organization/title/title.component.ts, apps/festival/festival/src/app/marketplace/organization/title/title.component.ts, apps/financiers/financiers/src/app/marketplace/organization/title/title.component.ts
change line up titles order #9165
=> change line up titles order #9165

apps/catalog/catalog/src/app/marketplace/organization/title/title.component.ts, apps/festival/festival/src/app/event/event.component.html, apps/festival/festival/src/app/marketplace/marketplace.component.html, apps/festival/festival/src/app/marketplace/organization/title/title.component.ts, apps/festival/festival/src/app/organization/organization.component.html, apps/festival/festival/src/styles.scss, apps/financiers/financiers/src/app/marketplace/organization/title/title.component.ts, firestore.rules, libs/utils/src/lib/constants.ts
=> fixes of the day release 4.6

apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html, libs/analytics/src/lib/service.ts, libs/movie/src/lib/movie/marketplace/main/main.component.html
=> updates after review

apps/backend-functions/src/data/internals.ts, apps/backend-functions/src/movie.ts, apps/backend-functions/src/templates/mail.ts, apps/crm/crm/src/app/crm/pages/movie/movie.component.html, apps/crm/crm/src/app/crm/pages/movie/movie.component.ts, apps/crm/crm/src/app/crm/pages/movies/movies.component.ts, apps/crm/crm/src/app/crm/pages/offers/list/offer-list.component.ts, apps/crm/crm/src/app/crm/pages/users/users.component.ts, apps/festival/festival/src/app/dashboard/analytics/buyers/buyers-analytics.component.ts, apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts, apps/festival/festival/src/app/dashboard/home/home.component.ts, libs/analytics/src/lib/utils.ts, libs/model/src/lib/utils.ts
=> Small fixes #9190

libs/utils/src/lib/constants.ts
fixes of the day release 4.6.1
=> fixes of the day release 4.6.1

libs/devops/src/lib/db-shrink.ts, libs/devops/src/lib/internals/utils.ts, libs/model/src/lib/meta.ts, libs/movie/src/lib/movie/service.ts
fix https://cascade-8.sentry.io/issues/3822401159/?environment=production&project=1540126&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d
=> fix sentry error

apps/catalog/catalog/src/app/marketplace/offer/shell/contract-view/contract-view.module.ts, apps/festival/festival/src/app/event/session/session.component.html, libs/media/src/lib/video/viewer/viewer.component.ts
=> fixed tooltip

apps/backend-functions/src/internals/invitations/events.ts, apps/backend-functions/src/movie.ts, apps/backend-functions/src/orgs.ts, apps/catalog/catalog-e2e/src/integration/marketplace/deal-create-offer.spec.ts, apps/catalog/catalog-e2e/src/integration/marketplace/display-title.spec.ts, apps/catalog/catalog/src/app/landing/landing.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts, apps/catalog/catalog/src/app/marketplace/title/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss, apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts, apps/festival/festival/src/app/marketplace/organization/title/title.component.ts, libs/devops/src/lib/algolia.ts, libs/devops/src/lib/firestoreMigrations/0086.ts, libs/devops/src/lib/firestoreMigrations/index.ts, libs/firebase-utils/src/lib/algolia.ts, libs/model/src/lib/algolia.ts, libs/model/src/lib/avail.ts, libs/testing/cypress/browser/src/lib/algolia.ts, libs/testing/cypress/browser/src/lib/marketplace.ts, libs/testing/cypress/node/src/lib/plugins/algolia.ts, libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html, libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.scss
=> hotfix release 4.6.1-b

libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts, libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.module.ts, libs/utils/src/lib/gdpr-cookie/cookie-form/cookie.form.ts, libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr.service.ts, libs/utils/src/lib/myapimovies/myapimovies.service.ts, libs/utils/src/lib/pdf.service.ts, libs/utils/src/lib/sentry.module.ts
Fix sentry circular & cleaned utils lib
=> Fix sentry circular & cleaned utils lib

apps/rules/src/tests/firestore/waterfall.spec.ts, apps/waterfall/waterfall-e2e/src/fixtures/example.json, firestore.rules, libs/model/src/index.ts, libs/model/src/lib/waterfall.ts, libs/testing/unit-tests/src/lib/fixtures/rules.ts
=> Feat 9257 rules budget financing plan

libs/devops/src/lib/firestoreMigrations/0087.ts, libs/devops/src/lib/firestoreMigrations/index.ts
=> hotfix release/4.6.1-c

apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.html, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.scss, apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
=> fixing contact link in avails calendar

apps/festival/festival/src/app/dashboard/home/home.component.html
forgot festival home page in issue #9325
=> add festival home

apps/waterfall/waterfall/src/app/dashboard/dashboard.module.ts, apps/waterfall/waterfall/src/app/dashboard/graph/graph.component.ts, libs/waterfall/src/lib/fixtures/terrawilly-demo.ts
=> terrawilly-demo

libs/devops/src/lib/algolia.ts, libs/firebase-utils/src/lib/algolia.ts
=> reduces Algolia API writes solves feat #9337

apps/catalog/catalog/src/app/marketplace/organization/view/view.component.html, apps/catalog/catalog/src/app/marketplace/organization/view/view.component.ts, apps/catalog/catalog/src/app/marketplace/title/view/view.component.html, apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts, apps/festival/festival/src/app/marketplace/organization/view/view.component.html, apps/festival/festival/src/app/marketplace/organization/view/view.component.ts, apps/festival/festival/src/app/marketplace/title/view/view.component.html, apps/festival/festival/src/app/marketplace/title/view/view.component.ts, apps/financiers/financiers/src/app/marketplace/organization/view/view.component.html, apps/financiers/financiers/src/app/marketplace/organization/view/view.component.ts, apps/financiers/financiers/src/app/marketplace/title/view/view.component.html, apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
=> added scroll to top for title & org pages (cross app)

.gitignore, apps/catalog/catalog/src/app/dashboard/title/view/view.component.html, apps/festival/festival/src/app/dashboard/title/view/view.component.html, apps/financiers/financiers/src/app/dashboard/title/view/view.component.html, libs/movie/src/lib/movie/dashboard/actions/actions.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.scss, libs/movie/src/lib/movie/dashboard/shell/shell.module.ts, styles/style.scss
Festival :
Catalog :
Financiers :
=> fix issue #9388 for archipel: smaller headers

apps/catalog/catalog-e2e/src/integration/marketplace/display-title.cy.ts, apps/waterfall/waterfall/src/app/dashboard/title/edit/edit.component.html, libs/movie/src/lib/movie/dashboard/shell/shell.component.html
fix #9388 
smaller header
`save `instead of `edit`
=> fix issue #9388 for waterfall

apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.html, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.scss, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/right-holders/right-holders.component.html, apps/waterfall/waterfall/src/app/dashboard/title/right-holders/right-holders.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/right-holders/right-holders.module.ts, libs/ui/src/lib/card-modal/card-modal.component.html, libs/ui/src/lib/card-modal/card-modal.component.scss, libs/ui/src/lib/card-modal/card-modal.component.ts, libs/ui/src/lib/card-modal/card-modal.module.ts
=> card modal

apps/backend-functions/src/orgs.ts, apps/crm/crm/src/app/crm/pages/movie/movie.component.ts, libs/contract/src/lib/contract/service.ts, libs/notification/src/lib/service.ts
=> Small fixes crm #9444

libs/contract/src/lib/avails/filter/filter.component.html, libs/contract/src/lib/avails/filter/filter.component.ts, libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.component.html, libs/contract/src/lib/contract/holdback/selection-modal/selection-modal.component.ts, libs/model/src/lib/static/groups.ts, libs/model/src/lib/static/static-model.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.html, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts, libs/user/src/lib/auth/forms/preferences/preferences.component.html, libs/user/src/lib/auth/forms/preferences/preferences.component.ts
=> BF New media #9452

apps/catalog/catalog-e2e/src/integration/marketplace/avails-search.cy.ts, apps/catalog/catalog/src/app/marketplace/title/list/list.component.html, apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/ui/src/lib/list/filter/list-filter.component.html, libs/ui/src/lib/list/filter/list-filter.component.ts
=> auto opening avails filter if loading past dates

libs/ui/src/lib/static-autocomplete/group/group.component.html, libs/ui/src/lib/static-autocomplete/group/group.component.ts
=> fix "pay" and "usa" like issues

apps/crm/crm/src/app/crm/pages/movie/movie.component.ts, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.html, libs/import/src/lib/table-extracted-elements/contracts/contracts.component.ts, libs/import/src/lib/table-extracted-elements/table-extracted-elements.module.ts, libs/import/src/lib/view-extracted-elements/organizations/utils.ts, libs/model/src/lib/utils.ts, libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.html, libs/movie/src/lib/movie/form/movie.form.ts, libs/ui/src/lib/logo-spinner/logo-spinner.module.ts, libs/ui/src/lib/static-autocomplete/group/group.component.html, libs/ui/src/lib/static-autocomplete/group/group.component.ts, libs/utils/src/lib/constants.ts, libs/utils/src/lib/error-logger.module.ts, libs/utils/src/lib/sentry.module.ts, package-lock.json, package.json
=> fixes of the day r-4-6-4

apps/backend-functions/src/waterfall.ts, libs/model/src/lib/waterfall/conditions.ts, libs/waterfall/src/lib/main.ts, libs/waterfall/src/lib/waterfall.service.ts
=> removed outdated and unused filterHistory function

apps/crm/crm/src/app/crm/crm.module.ts, apps/crm/crm/src/app/crm/pages/waterfall-rightholder/waterfall-rightholder.component.html, apps/crm/crm/src/app/crm/pages/waterfall-rightholder/waterfall-rightholder.component.scss, apps/crm/crm/src/app/crm/pages/waterfall-rightholder/waterfall-rightholder.component.ts, apps/crm/crm/src/app/crm/pages/waterfall-rightholder/waterfall-rightholder.module.ts, apps/crm/crm/src/app/crm/pages/waterfall/waterfall.component.html
=> rightholder page details

libs/model/src/lib/static/static-model.ts
=> ok feat #9506

libs/utils/src/lib/constants.ts
=> updated appVersion

libs/model/src/lib/waterfall/action.ts
=> Add pool to groups Feat 9502

libs/model/src/lib/static/static-model.ts, libs/utils/src/lib/constants.ts
=> fixes of the day r 4.6.5

apps/crm/crm/src/app/dashboard/toolbar-top/toolbar-top.component.ts, libs/model/src/lib/static/static-model.ts, libs/utils/src/lib/constants.ts
=> Merge back release 4 6 5 develop

apps/rules/src/tests/firestore/waterfall.spec.ts, firestore.rules, libs/testing/unit-tests/src/lib/fixtures/rules.ts
=> updated statement rules

apps/festival/festival/src/app/event/event.component.html, apps/festival/festival/src/app/marketplace/marketplace.component.html, apps/festival/festival/src/styles.scss
switched to screen daily theme #9559
=> switched to screen daily theme #9559

libs/utils/src/lib/constants.ts
=> merge back r4.6.6 - updated app version (#9561)

apps/crm/crm/src/app/crm/pages/waterfall/dashboard/dashboard.component.ts, apps/crm/crm/src/app/crm/pages/waterfall/statement/statement.component.ts, libs/model/src/lib/contract.ts, libs/waterfall/src/lib/dashboard/shell/shell.component.ts, libs/waterfall/src/lib/waterfall.service.ts
=> Feat 9524 compensation

libs/waterfall/src/lib/components/forms/right-form/right-form.ts, libs/waterfall/src/lib/components/graph/conditions/conditions.component.html, libs/waterfall/src/lib/components/graph/conditions/conditions.component.scss, libs/waterfall/src/lib/components/graph/conditions/conditions.component.ts, libs/waterfall/src/lib/components/graph/conditions/conditions.module.ts, libs/waterfall/src/lib/components/graph/conditions/step-item/step-item.component.html, libs/waterfall/src/lib/components/graph/conditions/step-item/step-item.component.scss, libs/waterfall/src/lib/components/graph/conditions/step-item/step-item.component.ts, libs/waterfall/src/lib/components/graph/conditions/step-item/step-item.module.ts, libs/waterfall/src/lib/components/graph/graph.component.html, libs/waterfall/src/lib/components/graph/graph.component.ts, libs/waterfall/src/lib/components/graph/layout.ts
=> crud steps

libs/waterfall/src/lib/components/forms/right-form/right-form.ts, libs/waterfall/src/lib/components/graph/graph.component.html, libs/waterfall/src/lib/components/graph/graph.component.ts
=> contract field

libs/waterfall/src/lib/components/graph/graph.component.html, libs/waterfall/src/lib/components/graph/graph.component.scss, libs/waterfall/src/lib/components/graph/graph.component.ts, libs/waterfall/src/lib/components/graph/graph.module.ts, libs/waterfall/src/lib/components/graph/pool-modal/pool-modal.component.html, libs/waterfall/src/lib/components/graph/pool-modal/pool-modal.component.scss, libs/waterfall/src/lib/components/graph/pool-modal/pool-modal.component.ts, libs/waterfall/src/lib/components/graph/pool-modal/pool-modal.module.ts, libs/waterfall/src/lib/components/graph/right-list/right-list.component.html, libs/waterfall/src/lib/components/graph/right-list/right-list.component.scss, libs/waterfall/src/lib/components/graph/right-list/right-list.component.ts, libs/waterfall/src/lib/components/graph/right-list/right-list.module.ts
=> right list

libs/waterfall/src/lib/components/graph/node/node.component.html, libs/waterfall/src/lib/components/graph/node/node.component.ts, libs/waterfall/src/lib/components/graph/vertical/vertical.component.html, libs/waterfall/src/lib/components/graph/vertical/vertical.component.ts
=> vertical selection

apps/crm/crm/src/app/crm/pages/waterfall/statements/statements.component.ts, apps/crm/crm/src/app/crm/pages/waterfall/statements/statements.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.scss, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.module.ts, apps/waterfall/waterfall/src/app/waterfall.module.ts, libs/model/src/lib/static/static-model.ts, libs/waterfall/src/lib/components/statement-new/statement-new.component.html, libs/waterfall/src/lib/components/statement-table/statement-table.component.html, libs/waterfall/src/lib/components/statement-table/statement-table.component.ts, libs/waterfall/src/lib/dashboard/edit-title/edit.component.ts, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.component.html
=> Review 9586

.circleci/config.yml
=> added no_output_timeout to deploy all

libs/model/src/lib/waterfall/right.ts, libs/model/src/lib/waterfall/statement.ts, libs/waterfall/src/lib/components/empty/empty.component.html, libs/waterfall/src/lib/dashboard/shell/shell.component.ts
=> better checks

env/env.blockframes.ts
=> added hotjar id

libs/campaign/src/lib/marketplace/financing/financing.component.html, libs/campaign/src/lib/marketplace/financing/financing.component.scss, libs/campaign/src/lib/marketplace/investment/investment.component.html
=> debug campagn

libs/utils/src/lib/constants.ts
=> updated appVersion (#9648)

libs/import/src/lib/view-extracted-elements/documents/utils.ts, libs/model/src/lib/static/static-model.ts, libs/waterfall/src/lib/components/forms/document-form/form.component.ts
=> added agent type

apps/backend-functions/src/statementToPdf.ts, apps/backend-functions/src/templates/mail.ts, libs/model/src/lib/emails.ts, libs/model/src/lib/pdf.ts, libs/waterfall/src/lib/components/statement-table/statement-table.component.html, libs/waterfall/src/lib/components/statement-table/statement-table.component.ts
=> added new vars to email

apps/crm/crm/src/app/crm/pages/waterfall/rightholders/rightholders.component.ts, apps/crm/crm/src/app/crm/pages/waterfall/rightholders/rightholders.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/dashboard/dashboard.component.html, apps/waterfall/waterfall/src/app/dashboard/title/dashboard/dashboard.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/right-holders-management/right-holders-management.component.html, apps/waterfall/waterfall/src/app/dashboard/title/right-holders-management/right-holders-management.component.ts, libs/import/src/lib/view-extracted-elements/documents/utils.ts, libs/model/src/lib/static/static-model.ts, libs/waterfall/src/lib/components/contracts-form/contracts-form.component.html, libs/waterfall/src/lib/components/forms/document-form/form.component.html, libs/waterfall/src/lib/components/forms/document-form/form.component.ts, libs/waterfall/src/lib/components/graph/graph.component.ts, libs/waterfall/src/lib/components/right-holder-form/right-holder-form.component.ts, libs/waterfall/src/lib/components/right-holder-form/right-holder-form.module.ts, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.component.html
=> Review 9586 i

libs/ui/src/lib/autocomplete/autocomplete.component.html, libs/waterfall/src/lib/components/forms/document-form/form.component.html, libs/waterfall/src/lib/components/forms/document-form/form.component.ts, libs/waterfall/src/lib/components/graph/graph.component.html, libs/waterfall/src/lib/components/graph/graph.component.ts
=> debug #9657

apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html
=> changed "add statement" btn css

apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.component.html, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.component.ts, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.component.html, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.module.ts, libs/model/src/lib/avail.ts, libs/model/src/lib/static/static-model.ts, libs/model/src/lib/waterfall/waterfall.ts, libs/waterfall/src/lib/components/sales-list/sales-list.component.html, libs/waterfall/src/lib/components/sales-list/sales-list.component.scss, libs/waterfall/src/lib/components/sales-list/sales-list.component.ts, libs/waterfall/src/lib/components/sales-list/sales-list.module.ts, libs/waterfall/src/lib/components/sales-map/sales-map.component.html, libs/waterfall/src/lib/components/sales-map/sales-map.component.ts
=> world sales map #9589

apps/backend-functions/src/assets/style/statement.css, apps/backend-functions/src/assets/templates/statement.html, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.component.html, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.component.ts, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.component.html, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, libs/model/src/lib/avail.ts, libs/model/src/lib/static/static-model.ts, libs/model/src/lib/waterfall/conditions.ts, libs/model/src/lib/waterfall/statement.ts, libs/model/src/lib/waterfall/waterfall.ts, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/sales-list/sales-list.component.html, libs/waterfall/src/lib/components/sales-list/sales-list.component.scss, libs/waterfall/src/lib/components/sales-list/sales-list.component.ts, libs/waterfall/src/lib/components/sales-list/sales-list.module.ts, libs/waterfall/src/lib/components/sales-map/sales-map.component.html, libs/waterfall/src/lib/components/sales-map/sales-map.component.ts, libs/waterfall/src/lib/components/statement-distributor/summary/summary.component.html, libs/waterfall/src/lib/components/statement-distributor/summary/summary.component.scss
=> fix for release 5.0.2

apps/backend-functions/src/assets/style/statement.css, apps/backend-functions/src/assets/templates/statement.html, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.component.html, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.component.ts, apps/crm/crm/src/app/crm/pages/waterfall/sales/sales.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.component.html, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/sales/sales.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, libs/model/src/lib/avail.ts, libs/model/src/lib/static/static-model.ts, libs/model/src/lib/waterfall/conditions.ts, libs/model/src/lib/waterfall/statement.ts, libs/model/src/lib/waterfall/waterfall.ts, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/sales-list/sales-list.component.html, libs/waterfall/src/lib/components/sales-list/sales-list.component.scss, libs/waterfall/src/lib/components/sales-list/sales-list.component.ts, libs/waterfall/src/lib/components/sales-list/sales-list.module.ts, libs/waterfall/src/lib/components/sales-map/sales-map.component.html, libs/waterfall/src/lib/components/sales-map/sales-map.component.ts, libs/waterfall/src/lib/components/statement-distributor/summary/summary.component.html, libs/waterfall/src/lib/components/statement-distributor/summary/summary.component.scss
* updated app version
* changed "add statement" btn css (#9663)
* Feat 9566 (#9665)
* WIP mg recoupment
* pdf
---------
* world sales map #9589 (#9664)
* ok world sales map
* crm
* fixed imports
---------
---------
=> merge back release 5.0.2 develop

libs/ui/src/lib/graph/graph.component.ts, libs/ui/src/lib/graph/graph.service.ts
=> improve gesture

libs/ui/src/lib/graph/graph.component.ts, libs/ui/src/lib/graph/graph.service.ts, libs/user/src/lib/auth/components/privacy-policy-text/privacy-policy-text.component.html, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/statement-table/statement-table.component.html
=> fix for release 5.0.3

libs/ui/src/lib/graph/graph.component.ts, libs/ui/src/lib/graph/graph.service.ts, libs/user/src/lib/auth/components/privacy-policy-text/privacy-policy-text.component.html, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/statement-table/statement-table.component.html
* updated appVersion
* updated privacy policy
* typo
* improve gesture (#9678)
---------
=> fix for release 5.0.3 merge back develop

apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts, libs/model/src/lib/algolia.ts, libs/model/src/lib/utils.ts
=> feat #9709 debug and monitor algolia result count

libs/ui/src/lib/autocomplete/autocomplete.component.html, libs/ui/src/lib/autocomplete/autocomplete.component.ts, libs/user/src/lib/auth/components/hide-email/hide-email.component.html, libs/user/src/lib/auth/components/hide-email/hide-email.component.ts, libs/waterfall/src/lib/components/forms/right-form/right-form.ts, libs/waterfall/src/lib/components/graph/conditions/conditions.component.ts, libs/waterfall/src/lib/components/graph/graph.component.html, libs/waterfall/src/lib/components/graph/graph.component.ts, libs/waterfall/src/lib/components/graph/graph.module.ts, libs/waterfall/src/lib/components/graph/horizontal/horizontal.component.html, libs/waterfall/src/lib/components/graph/horizontal/horizontal.component.scss, libs/waterfall/src/lib/components/graph/horizontal/horizontal.module.ts, libs/waterfall/src/lib/components/graph/vertical/vertical.component.html, libs/waterfall/src/lib/components/graph/vertical/vertical.component.scss
=> Feat 9703 b

apps/backend-functions/src/assets/templates/statement.html, apps/backend-functions/src/statementToPdf.ts, apps/crm/crm/src/app/crm/pages/waterfall/dashboard/dashboard.component.html, apps/waterfall/waterfall/src/app/dashboard/title/dashboard/dashboard.component.html, apps/waterfall/waterfall/src/app/dashboard/title/waterfall/waterfall.component.scss, libs/user/src/lib/auth/components/hide-email/hide-email.component.html, libs/waterfall/src/lib/components/organization/organization-table/organization-table.component.ts, libs/waterfall/src/lib/components/statement/statement-empty-card/statement-empty-card.component.html, libs/waterfall/src/lib/components/version/version-editor/version-editor.component.html, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.component.scss
=> Feat 9703 e

apps/waterfall/waterfall/src/app/dashboard/statement/edit/edit.component.ts, libs/utils/src/lib/pipes/date.pipe.ts, libs/waterfall/src/lib/components/graph/conditions/condition-item/condition.ts, libs/waterfall/src/lib/form/condition.form.ts
=> date debug

apps/waterfall/waterfall/src/app/dashboard/title/right-holders/right-holders.component.html, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.scss, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.ts, libs/model/src/lib/invitation.ts, libs/waterfall/src/lib/components/forms/conditions-form/conditions-form.component.ts, libs/waterfall/src/lib/components/graph/right-list/right-list.component.scss, libs/waterfall/src/lib/components/organization/pending-invitations/pending-invitations.component.html, libs/waterfall/src/lib/components/organization/pending-invitations/pending-invitations.component.ts, libs/waterfall/src/lib/components/organization/pending-invitations/pending-invitations.module.ts, libs/waterfall/src/lib/components/sidebar/sidebar.component.html, libs/waterfall/src/lib/components/sidebar/sidebar.component.ts, libs/waterfall/src/lib/components/sidebar/sidebar.module.ts
=> WIP  #9704

libs/waterfall/src/lib/components/document/contract/contract-list/contract-list.component.ts, libs/waterfall/src/lib/components/document/contract/contract-list/contract-list.module.ts, libs/waterfall/src/lib/components/organization/organization-table/organization-table.component.html, libs/waterfall/src/lib/components/sidebar/sidebar.component.ts, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.component.html, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.component.ts, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.module.ts
=> Feat 9704 b

apps/backend-functions/src/statementToPdf.ts, apps/waterfall/waterfall/src/app/app.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/dashboard/dashboard.component.html, libs/model/src/lib/emails.ts, libs/ui/src/lib/form/time-picker/time-picker.component.ts, libs/utils/src/lib/date-adapter.ts, libs/utils/src/lib/pipes/date.pipe.ts, libs/waterfall/src/lib/components/forms/conditions-form/conditions-form.component.html, libs/waterfall/src/lib/components/forms/conditions-form/conditions-form.component.ts, libs/waterfall/src/lib/components/graph/conditions/condition-item/condition.ts, libs/waterfall/src/lib/components/organization/pending-invitations/pending-invitations.module.ts, libs/waterfall/src/lib/components/statement/statement-payment/statement-payment.component.html, libs/waterfall/src/lib/components/statement/statement-payment/statement-payment.component.ts, libs/waterfall/src/lib/components/statement/statement-period/statement-period.component.html, libs/waterfall/src/lib/components/statement/statement-period/statement-period.component.ts
=> Fix typo graph placeholder

apps/backend-functions/src/assets/templates/statement.html, apps/backend-functions/src/statementToPdf.ts, apps/backend-functions/src/waterfall.ts, apps/waterfall/waterfall/src/app/dashboard/statement/view/view.component.ts, libs/model/src/lib/waterfall/statement.ts, libs/waterfall/src/lib/components/graph/conditions/condition-item/condition.ts, libs/waterfall/src/lib/components/statement/statement-direct-sales/summary/summary.component.html, libs/waterfall/src/lib/components/statement/statement-direct-sales/summary/summary.component.scss, libs/waterfall/src/lib/components/statement/statement-direct-sales/summary/summary.component.ts, libs/waterfall/src/lib/components/statement/statement-distributor/summary/summary.component.html, libs/waterfall/src/lib/components/statement/statement-distributor/summary/summary.component.scss, libs/waterfall/src/lib/components/statement/statement-distributor/summary/summary.component.ts, libs/waterfall/src/lib/components/statement/statement-main-info/statement-main-info.component.html, libs/waterfall/src/lib/components/statement/statement-producer/incoming-statements/incoming-statements.component.ts, libs/waterfall/src/lib/components/statement/statement-producer/summary/summary.component.html, libs/waterfall/src/lib/components/statement/statement-producer/summary/summary.component.scss, libs/waterfall/src/lib/components/statement/statement-producer/summary/summary.component.ts, libs/waterfall/src/lib/components/statement/statement-producer/summary/summary.module.ts
=> Feat 9704 d

apps/backend-functions/src/assets/style/statement.css, apps/backend-functions/src/assets/templates/statement.html, apps/backend-functions/src/notification.ts, apps/backend-functions/src/statementToPdf.ts, apps/waterfall/waterfall/src/app/dashboard/document/document.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/view/view.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/waterfall/waterfall.module.ts, libs/model/src/lib/waterfall/statement.ts, libs/notification/src/lib/service.ts, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/statement/statement-arbitrary-change/statement-arbitrary-change.component.html
=> fixes r 5.0.5

apps/backend-functions/src/assets/style/statement.css, apps/backend-functions/src/assets/templates/statement.html, apps/backend-functions/src/notification.ts, apps/backend-functions/src/statementToPdf.ts, apps/waterfall/waterfall/src/app/dashboard/document/document.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.module.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/view/view.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/waterfall/waterfall.module.ts, libs/model/src/lib/waterfall/statement.ts, libs/notification/src/lib/service.ts, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/statement/statement-arbitrary-change/statement-arbitrary-change.component.html
* updated app version
* debugs #9736 (#9745)
* Feat 9736 (#9746)
* debugs #9736
* pdf cleaning
---------
---------
=> merge back r 5.0.5 develop

apps/waterfall/waterfall/src/app/dashboard/title/view/view.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/waterfall/waterfall.module.ts, libs/model/src/lib/waterfall/right.ts, libs/waterfall/src/lib/components/graph/graph.component.ts, libs/waterfall/src/lib/components/sidebar/sidebar.component.html, libs/waterfall/src/lib/components/sidebar/sidebar.component.ts, libs/waterfall/src/lib/dashboard/shell/shell.component.ts
=> ok feat #9706

libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/graph/conditions/conditions.component.ts, libs/waterfall/src/lib/components/graph/graph.component.ts
=> Fix for release 5 0 7

apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.html, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.scss, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.module.ts, libs/waterfall/src/lib/components/document/budget-list/budget-list.component.html, libs/waterfall/src/lib/components/document/document-share/document-share.component.html, libs/waterfall/src/lib/components/document/document-share/document-share.component.scss, libs/waterfall/src/lib/components/document/document-share/document-share.module.ts, libs/waterfall/src/lib/components/document/financing-plan-list/financing-plan-list.component.html
=> added link to invite rightholder

apps/waterfall/waterfall/src/app/dashboard/title/amortization/amortization.component.html, apps/waterfall/waterfall/src/app/dashboard/title/amortization/amortization.component.scss, apps/waterfall/waterfall/src/app/dashboard/title/amortization/amortization.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/amortization/amortization.module.ts, libs/model/src/lib/static/static-model.ts, libs/model/src/lib/static/types.ts, libs/model/src/lib/waterfall/amortization.ts, libs/waterfall/src/lib/dashboard/edit-amortization/edit.component.html, libs/waterfall/src/lib/dashboard/edit-amortization/edit.component.ts
=> Feat 9753 b

apps/crm/crm/src/app/crm/pages/waterfall/statement/statement.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.html, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.scss, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.module.ts, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/document/budget-list/budget-list.component.html, libs/waterfall/src/lib/components/document/document-share/document-share.component.html, libs/waterfall/src/lib/components/document/document-share/document-share.component.scss, libs/waterfall/src/lib/components/document/document-share/document-share.module.ts, libs/waterfall/src/lib/components/document/financing-plan-list/financing-plan-list.component.html, libs/waterfall/src/lib/components/graph/conditions/conditions.component.ts, libs/waterfall/src/lib/components/graph/graph.component.ts
=> Merge back release 5 0 7 develop

apps/waterfall/waterfall/src/app/dashboard/dashboard.module.ts, libs/model/src/lib/waterfall/conditions.ts, libs/ui/src/lib/layout/footer/footer.component.html, libs/ui/src/lib/static-informations/security/security.component.html, libs/ui/src/lib/static-informations/security/security.component.scss, libs/ui/src/lib/static-informations/security/security.component.ts, libs/ui/src/lib/static-informations/security/security.module.ts
=> data security page en fr

apps/waterfall/waterfall/src/app/dashboard/dashboard.module.ts, libs/waterfall/src/lib/guards/waterfall-active.guard.ts
=> WaterfallActiveGuard

libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/forms/conditions-form/conditions-form.component.ts, libs/waterfall/src/lib/components/graph/conditions/conditions.component.ts, libs/waterfall/src/lib/form/condition.form.ts
=> Merge back release 5 0 8 develop

apps/backend-functions/src/assets/style/statement.css, apps/backend-functions/src/assets/templates/statement.html, libs/import/src/lib/table-extracted-elements/rights/rights.component.ts, libs/import/src/lib/utils.ts, libs/import/src/lib/view-extracted-elements/rights/fieldConfigs.ts, libs/import/src/lib/view-extracted-elements/rights/utils.ts, libs/import/src/lib/view-extracted-elements/rights/view-extracted-rights.component.ts, libs/waterfall/src/lib/dashboard/shell/shell.component.ts
=> amortization condition in excel import

apps/waterfall/waterfall/src/app/dashboard/document/contract/view/view.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/documents/documents.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.html, apps/waterfall/waterfall/src/app/dashboard/title/statements/statements.component.ts, apps/waterfall/waterfall/src/app/dashboard/title/waterfall-edit/waterfall-edit.component.html, libs/model/src/lib/waterfall/waterfall.ts, libs/utils/src/lib/constants.ts, libs/waterfall/src/lib/components/document/budget-list/budget-list.component.html, libs/waterfall/src/lib/components/document/budget-list/budget-list.component.scss, libs/waterfall/src/lib/components/document/budget-list/budget-list.module.ts, libs/waterfall/src/lib/components/document/contract/contract-list/contract-list.component.html, libs/waterfall/src/lib/components/document/contract/contract-list/contract-list.component.scss, libs/waterfall/src/lib/components/document/financing-plan-list/financing-plan-list.component.html, libs/waterfall/src/lib/components/document/financing-plan-list/financing-plan-list.component.scss, libs/waterfall/src/lib/components/document/financing-plan-list/financing-plan-list.module.ts, libs/waterfall/src/lib/components/statement/statement-empty-card/statement-empty-card.component.ts, libs/waterfall/src/lib/components/statement/statement-new/statement-new.component.html, libs/waterfall/src/lib/components/statement/statement-new/statement-new.component.ts, libs/waterfall/src/lib/components/statement/statement-producer/summary/summary.component.ts, libs/waterfall/src/lib/dashboard/edit-waterfall/edit.component.ts
=> app version update

package-lock.json, package.json, styles/components/bf-calendar.scss, styles/themes/builder.scss, styles/typography.scss
=> test cypress revert

styles/components/mat-button.scss, styles/components/mat-tabs.scss, styles/components/mat-toggle-button.scss
=> scss fixes

libs/model/src/lib/waterfall/statement.ts
=> fix brother issue

apps/backend-functions/project.json, apps/catalog/catalog/project.json, apps/cms/project.json, apps/crm/crm/project.json, apps/festival/festival/project.json, apps/financiers/financiers/project.json, apps/waterfall/waterfall/project.json, libs/utils/src/lib/constants.ts
=> fixes r 5.2

libs/devops/src/lib/db-shrink.ts, libs/model/src/lib/waterfall/actions.spec.ts
=> added comment and display error shrinking 9607

apps/festival/festival-e2e/src/integration/dashboard/Events/create-screening.cy.ts
=> #9848 less flak create screeening

libs/landing/src/lib/appBridgeBanner/app-bridge-banner.component.html, libs/ui/src/lib/ongoing-button/ongoing-button.component.html, libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
=> Broken css on "ongoing screening" button #9345

libs/model/src/lib/income.ts, libs/model/src/lib/static/groups.ts, libs/model/src/lib/static/static-model-i18n.ts, libs/model/src/lib/static/static-model.ts
=> Fixes r5 3

apps/waterfall/waterfall/src/app/dashboard/title/dashboard/dashboard.component.ts, libs/import/src/lib/utils.ts, libs/waterfall/src/lib/waterfall.service.ts
=> Sentry fix 207f5ea55

libs/waterfall/src/lib/dashboard/edit-title/edit.component.ts
=> EUR as default currency

apps/catalog/catalog-e2e/src/integration/marketplace/display-title.cy.ts, libs/movie/src/lib/movie/components/card/card.component.html
=> fix flaky Access to title page by clicking on the movie card

apps/backend-functions/src/internals/email.ts, apps/backend-functions/src/internals/users.ts, apps/backend-functions/src/invitation.ts, apps/backend-functions/src/users.ts, apps/crm/crm/src/app/crm/components/organization/create-organization/create.component.html, apps/crm/crm/src/app/crm/components/organization/create-organization/create.component.ts, libs/model/src/lib/emails.ts, libs/model/src/lib/user.ts, libs/user/src/lib/auth/pages/identity/identity.component.ts, libs/user/src/lib/auth/service.ts, libs/utils/src/lib/constants.ts
=> fixes for release 5.4
