- .firebaserc
- apps/eth-events-service/src/environments/environment.prod.ts
- apps/eth-events-service/src/environments/environment.ts
- firebase.json
- firestore.indexes.json
- firestore.rules
- functions/.gitignore
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/tsconfig.json
- functions/tslint.json
Add the function's backend to process timestamp and draft a basic firestore update:
- store timestamp events to track ownership per document
- store accounts info to track usage per user
> eth-events-service: add backend functions

- .gitignore
- README.md
- functions/package-lock.json
- functions/package.json
- functions/src/firebase.ts
- functions/src/generateHash.ts
- functions/src/index.ts
- functions/src/ipHash.ts
- libs/ip/src/lib/contracts/ip-hash.ts
- Split firebase functions into 2 modules (easier to maintain and test)
- Add the function that reacts to file upload -> hash -> firestore
- update firestore operations according to our current data model (`/ip/{ipID}/version/{versionID}`)
This completes the loops from the user uploading a document to the transaction being registered by our firebase backend:
1. The user uploads a document that represents an (IP, Version); to Cloud Storage,
2. A function is triggered, computes the keccack256 hash, and update the firestore document of this (IP, Version),
3. The user's UI is updated with the document hash,
4. The user sends a transaction to the IP Smart Contract to record ownership of this hash,
5. The eth-events-server receive the events, sends it to pubsub,
6. A function is triggered and …
> With file hashing

- apps/delivery/delivery/src/app/app.module.ts
- apps/delivery/delivery/src/app/delivery/delivery.module.ts
- apps/delivery/delivery/src/app/delivery/form/form.component.html
- apps/delivery/delivery/src/app/delivery/form/form.component.ts
- apps/delivery/delivery/src/app/delivery/form/new-template.component.ts
- apps/delivery/delivery/src/app/delivery/list/list.component.html
- apps/delivery/delivery/src/app/delivery/list/list.component.scss
- apps/delivery/delivery/src/app/delivery/list/list.component.ts
- apps/delivery/delivery/src/app/delivery/template-picker/template-picker.component.html
- apps/delivery/delivery/src/app/delivery/template-picker/template-picker.component.ts
- apps/delivery/delivery/src/app/delivery/view/view.component.html
- apps/delivery/delivery/src/app/delivery/view/view.component.scss
- apps/delivery/delivery/src/app/material/+state/material.service.ts
- apps/delivery/delivery/src/app/material/material-form/material-form.component.html
- apps/delivery/delivery/src/app/material/material-form/material-form.component.scss
- apps/delivery/delivery/src/app/template/+state/template.query.ts
- apps/delivery/delivery/src/app/template/+state/template.service.ts
- apps/delivery/delivery/src/app/template/category-list/category-list.component.html
- apps/delivery/delivery/src/app/template/category-list/category-list.component.scss
- apps/delivery/delivery/src/app/template/category-list/category-list.component.ts
- apps/delivery/delivery/src/app/template/template-list/template-list.component.html
- apps/delivery/delivery/src/app/template/template-list/template-list.component.scss
- apps/delivery/delivery/src/app/template/template-list/template-list.component.ts
- apps/delivery/delivery/src/app/template/template.module.ts
- apps/delivery/delivery/src/app/template/template/template.component.html
- apps/delivery/delivery/src/app/template/template/template.component.ts
Delivery templates dialog
Delivery form and save as template
> Delivery App

- libs/ethers/src/lib/erc1077/erc1077.spec.ts
- libs/ethers/src/lib/erc1077/erc1077.ts
- libs/ethers/src/lib/provider/provider.spec.ts
- libs/ethers/src/lib/provider/provider.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.spec.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
- libs/ethers/src/lib/relayer/relayer.ts
Added :
* MockRelayer implementation
* injectable infura provider
* injectable relayer wallet
Also modified ERC1077 accordingly
> Issue#111 relayer wallet

- env/env.template.ts
- libs/ethers/src/lib/erc1077/erc1077.spec.ts
- libs/ethers/src/lib/erc1077/erc1077.ts
- libs/ethers/src/lib/provider/provider.spec.ts
- package-lock.json
- package.json
* let Circle CI use the Goerli network
* modify tests so that they do not depend on the network
> Issue#135 migrate to goerli

- libs/account/src/lib/account-profile/account-profile.component.ts
- libs/account/src/lib/account-view/account-view.component.ts
- libs/auth/src/lib/+state/auth.query.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/guard/auth.guard.ts
- libs/auth/src/lib/login/login.component.ts
- libs/auth/src/lib/root/root.component.html
- libs/auth/src/lib/root/root.component.ts
- libs/auth/src/lib/signup/signup.component.ts
- libs/organization/src/lib/org-list/org-list.component.ts
- libs/organization/src/lib/org-show/org-show.component.ts
- libs/organization/src/lib/org-widget/org-widget.component.ts
- libs/ui/src/lib/toolbar/header/header.component.ts
Keep the requested route in store and use after connection
> Issue#102 redirect after login

- apps/delivery/delivery/src/app/app-routing-module.ts
- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.html
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.ts
- libs/material/src/lib/delivery/delivery-list/delivery-list.component.html
- libs/material/src/lib/delivery/delivery-list/delivery-list.component.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/guards/delivery.guard.ts
- libs/material/src/lib/delivery/movie-materials/movie-materials.component.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/material/src/lib/template/template-picker/template-picker.component.html
- libs/material/src/lib/template/template-picker/template-picker.component.ts
User can create delivery without base template
User can delete delivery and all the subcollections (materials + stakeholders)
Delivery getters moved into DeliveryQuery
> Issue#113 new delivery without template

- functions/src/index.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-list/delivery-list.component.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.html
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
- libs/material/src/lib/template/template-picker/template-picker.component.ts
- libs/movie/src/lib/movie/staticModels.ts
Firebase function works no matters the number of stakeholders / 
Edit delivery now removes signatures from validated array
> Issue#158 materials copied into movie

- functions/src/index.ts
- functions/src/relayer.ts
> Issue#172 change relayer methods

- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/src/relayer.ts
> Issue#180 fix relayer bug

- .circleci/config.yml
- apps/ip-upload/ip-upload/src/app/app.module.ts
- env/env.prod.ts
- env/env.staging.ts
- env/env.template.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/auth.module.ts
- libs/ethers/src/index.ts
- libs/ethers/src/lib/erc1077/erc1077.spec.ts
- libs/ethers/src/lib/erc1077/erc1077.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.spec.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
- libs/ethers/src/lib/relayer/relayer.ts
- libs/ethers/src/lib/vault/vault.ts
Sorry for the weird commit history I have been stuck in a commit/merge/rebase hell 😞
> Issue#134 connect auth wallet

- apps/delivery/delivery/src/app/app.component.ts
- apps/ip-upload/ip-upload/src/app/app.component.ts
- apps/movie-financing/movie-financing/src/app/app.component.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
> Issue#189 prevent user to close tab v2

- apps/delivery/delivery-e2e/src/fixtures/movie.json
- apps/delivery/delivery-e2e/src/integration/app.spec.ts
- apps/delivery/delivery-e2e/src/support/app.po.ts
- apps/delivery/delivery/src/app/app.module.ts
- apps/delivery/delivery/src/app/layout/context-menu.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.html
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.ts
- libs/material/src/lib/delivery/delivery-list/delivery-list.component.ts
- libs/material/src/lib/delivery/delivery-new-template/new-template.component.ts
- libs/material/src/lib/delivery/stakeholder-list/stakeholder-list.component.ts
- libs/material/src/lib/material/material-form/material-form.component.html
- libs/material/src/lib/material/material-item/material-item.component.html
- libs/material/src/lib/template/+state/template.service.ts
- libs/material/src/lib/template/template-list/template-list.component.html
- libs/material/src/lib/template/template-list/template-list.component.scss
- libs/material/src/lib/template/template-picker/template-picker.component.html
- libs/material/src/lib/template/template-picker/template-picker.component.scss
- libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
> Issue#184 teste2e user can save as template

- libs/ethers/src/lib/erc1077/erc1077.ts
- libs/ethers/src/lib/provider/provider.ts
> fix env bug & swith to etherscan provider

- angular.json
- apps/delivery/delivery/src/app/app.module.ts
- libs/utils/jest.config.js
- libs/utils/src/index.spec.ts
- libs/utils/src/index.ts
- libs/utils/src/lib/fire-query.service.ts
- libs/utils/tsconfig.lib.json
- libs/utils/tsconfig.spec.json
- libs/utils/tslint.json
- nx.json
- package-lock.json
- tsconfig.json
Solve issue https://github.com/blockframes/blockframes/issues/198
Create a utils library
Create a service for complexe firebase queries.
> Firebase Query Service

- functions/src/relayer.ts
- libs/account/src/lib/account-profile/account-profile.component.ts
- libs/account/src/lib/account-view/account-view.component.html
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/ethers/src/lib/erc1077/erc1077.spec.ts
- libs/ethers/src/lib/provider/provider.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.spec.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
- libs/ethers/src/lib/relayer/relayer.ts
> Issue#195 add contract address to profile

- libs/ui/src/lib/toolbar/context-menu/context-menu.component.html
- libs/ui/src/lib/toolbar/context-menu/context-menu.component.scss
- libs/ui/src/lib/toolbar/header/header.component.html
- libs/ui/src/lib/toolbar/header/header.component.scss
- libs/ui/src/lib/toolbar/toolbar.module.ts
- styles/style.scss
> Fancier topbar

- apps/delivery/delivery/src/app/layout/context-menu.ts
- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-item/delivery-item.component.ts
- libs/material/src/lib/delivery/delivery-list/delivery-list.component.ts
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.html
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.scss
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.html
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.scss
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.html
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.scss
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.ts
- libs/material/src/lib/delivery/movie-materials/actions/actions.component.html
- libs/material/src/lib/delivery/movie-materials/movie-materials.component.html
- libs/material/src/lib/delivery/movie-materials/movie-materials.component.scss
- libs/material/src/lib/delivery/movie-materials/movie-materials.component.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
- libs/ui/src/lib/icon-component.ts
- styles/style.scss
- styles/theme.scss
> Fancier movie materials

- libs/utils/src/lib/fire-query.service.ts
Fix issue https://github.com/blockframes/blockframes/issues/236
> Improve FireQuery

- libs/utils/src/lib/fire-query.service.ts
Fix issue https://github.com/blockframes/blockframes/issues/238
> Throw Error when query is not found

- functions/src/delivery.ts
- functions/src/firebase.ts
- functions/src/index.ts
- functions/src/notify.ts
Firebase function: Notifications are created when delivery is signed by all stakeholders
> Functions: add notifications in onDeliveryUpdateEvent

- functions/src/delete.ts
- functions/src/index.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
> add delteMovie & deleteDelivery

- libs/auth/src/lib/+state/auth.query.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/ui/src/lib/toolbar/header/header.component.html
- libs/ui/src/lib/toolbar/header/header.component.scss
- libs/ui/src/lib/toolbar/header/header.component.ts
- libs/ui/src/lib/toolbar/toolbar.module.ts
> better feedback

- functions/src/delete.ts
- functions/src/delivery.ts
- functions/src/index.ts
- functions/src/notify.ts
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.html
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.scss
- libs/ui/src/lib/notification/notification-item/notification-item.component.html
- libs/ui/src/lib/notification/notification-item/notification-item.component.ts
- libs/ui/src/lib/toolbar/header/header.component.html
- libs/ui/src/lib/toolbar/header/header.component.scss
- libs/ui/src/lib/toolbar/header/header.component.ts
Prettier rendering of notifications (with number of unread notifications)
User is notified when a delivery is deleted
> Issue#211 notifications

- libs/auth/src/lib/+state/auth.service.ts
- package.json
Sanitize username to prevent relayer crash due to ethers checking if names follows UTS46 normalization
> sanitize username

- functions/src/delivery.ts
Stakeholders are notified when someone sign the delivery
> Issue#251 notifications signature delivery

- functions/src/relayer.ts
- libs/account/src/lib/account-view/account-view.component.html
- libs/account/src/lib/account-view/account-view.component.ts
- libs/account/src/lib/account.module.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/ethers/src/lib/provider/provider.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
- libs/ui/src/index.ts
- libs/ui/src/lib/blockie/blockie.component.html
- libs/ui/src/lib/blockie/blockie.component.scss
- libs/ui/src/lib/blockie/blockie.component.ts
- libs/ui/src/lib/blockie/blockie.module.ts
- package-lock.json
- package.json
> Issue#262 wallet info

- functions/src/delete.ts
- functions/src/delivery.ts
- functions/src/index.ts
- functions/src/stakeholder.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.html
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.html
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.html
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.ts
- libs/material/src/lib/delivery/movie-materials/actions/actions.component.html
- libs/material/src/lib/delivery/movie-materials/actions/actions.component.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.store.ts
- libs/organization/src/lib/+state/organization.query.ts
- libs/ui/src/lib/icon-component.ts
- package-lock.json
Notifications when stakeholder is added to/removed from a movie
> Issue#249 notifications stakeholder movie

- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/material/+state/material.store.ts
- libs/material/src/lib/material/material-delivery-form/material-delivery-add-form.component.ts
- libs/material/src/lib/material/material-delivery-form/material-delivery-form.component.html
- libs/material/src/lib/material/material-delivery-form/material-delivery-form.component.ts
- libs/material/src/lib/material/material-delivery-item/material-delivery-item.component.html
- libs/material/src/lib/material/material-delivery-item/material-delivery-item.component.ts
- package-lock.json
You can select a step that you have created before
> Issue#248 choose step

- libs/auth/src/lib/+state/auth.service.ts
[previous PR](https://github.com/blockframes/blockframes/pull/257) was handling only unicode chars like `漢` but special chars like `*` or `+` were not handled properly, we now replace those char by their ASCII code (`?` = 63) so thath `michel_michel` and `michel+michel` will not collide
> sanitize username for ens

- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/ui/src/lib/notification/notification-item/notification-item.component.html
- libs/ui/src/lib/notification/notification-item/notification-item.component.scss
- libs/ui/src/lib/notification/notification-item/notification-item.component.ts
- libs/ui/src/lib/notification/notification-list/notification-list.component.html
- libs/ui/src/lib/notification/notification-list/notification-list.component.scss
- libs/ui/src/lib/toolbar/header/header.component.html
- styles/style.scss
> Prettier notifications

- functions/src/backup.ts
too verbose = slow and expensive.
> functions(backup): remove logging & secure restore

- functions/package-lock.json
- functions/src/delete.ts
- functions/src/delivery.ts
- functions/src/material.ts
- functions/src/stakeholder.ts
- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.scss
- libs/material/src/lib/delivery/delivery-list/delivery-list.component.scss
- libs/material/src/lib/delivery/delivery-settings-view/delivery-settings-view.component.scss
- libs/material/src/lib/delivery/delivery-team-work-view/team-work-actions/team-work-actions.component.scss
- libs/material/src/lib/delivery/delivery-team-work-view/team-work-filters/team-work-filters.component.scss
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.html
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.html
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.scss
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.html
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.ts
- libs/material/src/lib/delivery/movie-materials/actions/actions.component.scss
- libs/material/src/lib/delivery/movie-materials/filters/filters.component.scss
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/material-list/material-list.component.scss
- libs/material/src/lib/template/template-form/template-form.component.scss
- libs/material/src/lib/template/template-list/template-list.component.scss
- libs/ui/src/lib/notification/notification-item/notification-item.component.html
- libs/ui/src/lib/notification/notification-list/notification-list.component.html
- package-lock.json
> Demos todos

- apps/movie-financing/movie-financing/src/app/app-routing.module.ts
- apps/movie-financing/movie-financing/src/app/app.module.ts
- apps/movie-financing/movie-financing/src/app/explorer/header/header.component.html
- apps/movie-financing/movie-financing/src/app/explorer/header/header.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/header/header.component.ts
- apps/movie-financing/movie-financing/src/app/explorer/movie-card/movie-card.component.html
- apps/movie-financing/movie-financing/src/app/explorer/movie-card/movie-card.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/profile/profile.component.html
- apps/movie-financing/movie-financing/src/app/explorer/profile/profile.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/profile/profile.component.ts
- apps/movie-financing/movie-financing/src/app/explorer/ui/range-slider/range-slider.component.html
- apps/movie-financing/movie-financing/src/app/explorer/ui/range-slider/range-slider.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/ui/range-slider/range-slider.component.ts
- apps/movie-financing/movie-financing/src/app/explorer/ui/range-slider/range-slider.module.ts
- libs/shared-assets/apps/movie-financing/range-thumb.svg
> Issue#267 movie financing ui

- libs/account/src/lib/account-view/account-view.component.html
- libs/account/src/lib/account-view/account-view.component.scss
- libs/account/src/lib/account-view/account-view.component.ts
- libs/account/src/lib/account.module.ts
- libs/auth/src/lib/+state/auth.query.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/auth/src/lib/root/root.component.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.spec.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
- libs/ethers/src/lib/relayer/relayer.ts
> refactoring and bugfixe

- apps/movie-financing/movie-financing/src/app/app.module.ts
- apps/movie-financing/movie-financing/src/app/explorer/header/header.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/movie-card-horizontal/movie-card-horizontal.component.html
- apps/movie-financing/movie-financing/src/app/explorer/movie-card-horizontal/movie-card-horizontal.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/movie-card-horizontal/movie-card-horizontal.component.ts
- apps/movie-financing/movie-financing/src/app/explorer/movie-card/movie-card.component.html
- apps/movie-financing/movie-financing/src/app/explorer/movie-card/movie-card.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/search/search.component.html
- apps/movie-financing/movie-financing/src/app/explorer/search/search.component.scss
> Financing Search

- .firebaserc
- functions/package-lock.json
- functions/src/delete.ts
- functions/src/delivery.ts
- functions/src/notify.ts
- functions/src/stakeholder.ts
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.html
- libs/material/src/lib/delivery/delivery-view-item/delivery-view-item.component.scss
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.html
- libs/material/src/lib/delivery/movie-material-item/movie-material-item.component.scss
- libs/ui/src/lib/notification/+state/notification.service.ts
- libs/ui/src/lib/notification/notification-item/notification-item.component.ts
- package-lock.json
- package.json
> Stakeholder movie invitation

- apps/movie-financing/movie-financing/src/app/explorer/details/details.component.html
- apps/movie-financing/movie-financing/src/app/explorer/navbar/navbar.component.html
- apps/movie-financing/movie-financing/src/app/explorer/navbar/navbar.component.scss
- apps/movie-financing/movie-financing/src/app/explorer/profile/profile.component.html
> Financing tweaks

- libs/ui/src/lib/notification/+state/notification.model.ts
- libs/ui/src/lib/notification/notification-item/notification-item.component.ts
> Fix: fixed a missing property from notification model

- apps/movie-financing/movie-financing/src/app/explorer/movie-card-horizontal/movie-card-horizontal.component.html
- apps/movie-financing/movie-financing/src/app/explorer/movie-card-horizontal/movie-card-horizontal.component.ts
- apps/movie-financing/movie-financing/src/app/explorer/search/search.component.html
- apps/movie-financing/movie-financing/src/app/explorer/search/search.component.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
Really simple implem of filtering movie by tokens, this is mostly hardcoded values for the cannes demo !
It will need a big refactoring after cannes !
> Filter movie by ether

- functions/src/index.ts
- functions/src/relayer.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/ethers/src/lib/relayer-wallet/relayer-wallet.ts
- libs/ethers/src/lib/relayer/relayer.ts
- libs/material/src/lib/delivery/delivery-sign/delivery-sign.component.ts
- libs/material/src/lib/delivery/stakeholder-item/stakeholder-item.component.html
- libs/material/src/lib/delivery/stakeholder-item/stakeholder-item.component.ts
> Issue#295 delivery send tx

- functions/src/backup.ts
- functions/src/relayer.ts
> Restore from backups: fix date encoding

- libs/material/src/lib/material/material-delivery-form/material-delivery-form.component.html
- libs/material/src/lib/template/+state/template.service.ts
- libs/material/src/lib/template/template-add/template-add.component.ts
> fix_delivery-add-step

- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/title-form/title-form.component.ts
- libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
- libs/ui/src/lib/notification/+state/notification.service.ts
If this is supposed to be merged into master for Cannes, I would prefer that someone (@Jackseed) test this feature by adding movie and stakeholders to it.
> add movie to an org only when IsAccepted is true

- functions/src/delivery.ts
- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.ts
- libs/material/src/lib/delivery/delivery-settings-view/delivery-settings-view.component.html
- libs/material/src/lib/delivery/delivery-settings-view/delivery-settings-view.component.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.html
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/guards/delivery-active.guard.ts
- libs/material/src/lib/delivery/movie-materials/movie-materials.component.html
- libs/material/src/lib/delivery/movie-materials/movie-materials.component.ts
- libs/material/src/lib/delivery/stakeholder-list/stakeholder-list.component.html
- libs/material/src/lib/delivery/stakeholder-list/stakeholder-list.component.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/material/guards/delivery-materials.guard.ts
- libs/material/src/lib/material/guards/movie-materials-by-delivery.guard.ts
- libs/material/src/lib/material/guards/signed-delivery-materials.guard.ts
- libs/material/src/lib/material/index.ts
- libs/material/src/lib/material/material-delivery-form/material-delivery-add-form.component.ts
- libs/material/src/lib/material/material-delivery-item/material-delivery-item.component.ts
- libs/material/src/lib/template/template-picker/template-picker.component.ts
> Materials guards

- apps/delivery/delivery-e2e/src/integration/CRUD-movie.spec.ts
- apps/delivery/delivery-e2e/src/support/app.po.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/template/template-picker/template-picker.component.ts
- libs/movie/src/lib/movie/form/form.component.html
> E2e crud movie

- apps/delivery/delivery-e2e/src/integration/CRUD-account-org.spec.ts
- apps/delivery/delivery-e2e/src/support/app.po.ts
- libs/movie/src/lib/movie/home-empty/home-empty.component.html
- libs/organization/src/lib/org-members-show/org-members-show.component.html
> create test CRUD-org

- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/utils.ts
> backend(templates): remove materials when template is deleted

- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/notify.ts
- apps/backend-functions/src/stakeholder.ts
- apps/delivery/delivery/src/app/app.module.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/ip/src/lib/+state/ip.service.ts
- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/delivery/delivery-view/delivery-view.component.html
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/template/+state/template.query.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/movie.module.ts
- libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
- libs/notification/+state/notification.service.ts
- libs/organization/src/lib/+state/org-members.service.ts
- libs/organization/src/lib/+state/organization.service.ts
> Issue#377 change database imports

- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/notify.ts
- apps/backend-functions/src/stakeholder.ts
- apps/backend-functions/src/utils.ts
> refactor_delivery_firebase_functions

- apps/delivery/delivery/src/app/app.module.ts
- apps/delivery/delivery/src/environments/environment.prod.ts
- apps/delivery/delivery/src/environments/environment.ts
- apps/ip-upload/ip-upload/src/environments/environment.prod.ts
- apps/ip-upload/ip-upload/src/environments/environment.staging.ts
- apps/ip-upload/ip-upload/src/environments/environment.ts
- apps/movie-financing/movie-financing/src/app/app.module.ts
- apps/movie-financing/movie-financing/src/environments/environment.prod.ts
- apps/movie-financing/movie-financing/src/environments/environment.ts
- env/env.template.ts
> Enable firestore persistence

- apps/movie-financing/movie-financing/src/app/app.module.ts
- libs/ethers/src/lib/key-manager/+state/key-manager.service.ts
- libs/ethers/src/lib/key-manager/export-dialog/export-dialog.component.html
- libs/ethers/src/lib/key-manager/export-dialog/export-dialog.component.scss
- libs/ethers/src/lib/key-manager/export-dialog/export-dialog.component.ts
- libs/ethers/src/lib/key-manager/key-manager-item/key-manager-item.component.html
- libs/ethers/src/lib/key-manager/key-manager-item/key-manager-item.component.ts
- libs/ethers/src/lib/key-manager/key-manger.module.ts
> Issue#412 export keys

- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/notify.ts
- apps/backend-functions/src/stakeholder.ts
- apps/backend-functions/src/utils.ts
- apps/ip-upload/ip-upload/src/app/app.module.ts
> Refactor functions in stakeholder.ts

- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/delivery-form/delivery-form.component.ts
- libs/material/src/lib/delivery/delivery-new-template/new-template.component.ts
- libs/material/src/lib/delivery/delivery-template-picker/delivery-template-picker.component.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/stakeholder/+state/stakeholder.model.ts
- libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
- libs/movie/src/lib/stakeholder/list/list.component.ts
- libs/utils/src/lib/firequery/firequery.ts
> review services

- libs/material/src/lib/delivery/components/stakeholder-item/stakeholder-item.component.scss
- libs/ui/src/lib/team-work/team-work-filters/team-work-filters.component.scss
- libs/ui/src/lib/toolbar/header/header.component.scss
- styles/components/mat-expansion-panel.scss
- styles/components/mat-form-field.scss
> Global colors

- apps/backend-functions/src/assets/mailTemplates.ts
- apps/backend-functions/src/environments/environment.ci.ts
- apps/backend-functions/src/environments/environment.prod.ts
- apps/backend-functions/src/environments/environment.staging.ts
- apps/backend-functions/src/environments/environment.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/users.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- firebase.json
- ops/deploy_secrets.sh
- package-lock.json
- package.json
> #508: send mail to new users on invite

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/guards/delivery-list.guard.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/stakeholder/+state/stakeholder.service.ts
- libs/organization/src/lib/permissions/+state/permissions.service.ts
- libs/utils/src/lib/abstract-state-guard.ts
> Movies with delivery ids

- apps/delivery/delivery/src/app/app.module.ts
- apps/delivery/delivery/src/app/layout/layout.component.html
- libs/auth/src/lib/+state/auth.query.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/components/email-verify/email-verify.component.html
- libs/auth/src/lib/components/email-verify/email-verify.component.ts
- libs/auth/src/lib/guard/auth.guard.ts
- libs/ui/src/lib/toolbar/header/header.component.html
Add email verify message + icon + flow to the delivery app.
> Issue 578: Add email verification flow to the delivery app

- apps/backend-functions/src/assets/mailTemplates.ts
- apps/backend-functions/src/backup.ts
- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/email.ts
- apps/backend-functions/src/generateHash.ts
- apps/backend-functions/src/internals/algolia.ts
- apps/backend-functions/src/internals/email.ts
- apps/backend-functions/src/internals/firebase.ts
- apps/backend-functions/src/internals/index.ts
- apps/backend-functions/src/internals/pdf.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/ipHash.ts
- apps/backend-functions/src/local/testPDFExport.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/migrations.ts
- apps/backend-functions/src/notify.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/stakeholder.ts
- apps/backend-functions/src/users.ts
- apps/backend-functions/src/utils.ts
- libs/organization/src/lib/+state/organization.model.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/components/member-form/member-form.component.ts
Future PR will take care of the frontend:
> Issue 576: org invite a user (backend part mostly)

- libs/account/src/lib/profile/components/profile-form/profile-form.component.html
- libs/auth/src/lib/components/signup-form/signup-form.component.html
- libs/auth/src/lib/forms/signup.form.ts
- libs/auth/src/lib/pages/identity/identity.component.html
- libs/auth/src/lib/pages/identity/identity.component.ts
> delete validators minLength and add required for all surname and name

- libs/ethers/src/lib/key-manager/+state/key-manager.query.ts
- libs/ethers/src/lib/key-manager/+state/key-manager.service.ts
- libs/ethers/src/lib/key-manager/+state/key-manager.store.ts
- libs/ethers/src/lib/key-manager/key-manager-item/key-manager-item.component.html
- libs/ethers/src/lib/key-manager/key-manager-item/key-manager-item.component.scss
- libs/ethers/src/lib/key-manager/key-manager-item/key-manager-item.component.ts
- libs/ethers/src/lib/key-manager/key-manager-list/key-manager-list.component.html
- libs/ethers/src/lib/key-manager/key-manager-list/key-manager-list.component.ts
- libs/ethers/src/lib/relayer/relayer.ts
- libs/ethers/src/lib/types.ts
- libs/ethers/src/lib/wallet/+state/wallet-known-tx.ts
- libs/ethers/src/lib/wallet/+state/wallet.service.ts
- libs/ethers/src/lib/wallet/wallet-send-tx/wallet-send-tx.component.html
- libs/ethers/src/lib/wallet/wallet-send-tx/wallet-send-tx.component.ts
- libs/ethers/src/lib/wallet/wallet-view/wallet-view.component.html
- libs/ethers/src/lib/wallet/wallet-view/wallet-view.component.ts
- libs/ui/src/lib/feedback/feedback-message.module.ts
> add/delete key & delete feedback message

- apps/delivery/delivery/src/app/app-routing-module.ts
- apps/delivery/delivery/src/app/layout/context-menu.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/pages/delivery-add-choose-starter/delivery-add-choose-starter.component.html
- libs/material/src/lib/delivery/pages/delivery-add-choose-starter/delivery-add-choose-starter.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-find-movie/delivery-add-find-movie.component.html
- libs/material/src/lib/delivery/pages/delivery-add-find-movie/delivery-add-find-movie.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-settings/delivery-add-settings.component.html
- libs/material/src/lib/delivery/pages/delivery-add-settings/delivery-add-settings.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-template-picker/delivery-add-template-picker.component.html
- libs/material/src/lib/delivery/pages/delivery-add-template-picker/delivery-add-template-picker.component.ts
- libs/movie/src/lib/movie/components/movie-picker/movie-picker.component.html
- libs/movie/src/lib/movie/components/movie-picker/movie-picker.component.ts
- libs/movie/src/lib/movie/movie.module.ts
- libs/organization/src/lib/no-organization.module.ts
- libs/organization/src/lib/pages/organization-home/organization-home.component.html
- libs/organization/src/lib/pages/organization-home/organization-home.component.scss
- libs/organization/src/lib/pages/organization-home/organization-home.component.ts
- libs/ui/src/index.ts
- libs/ui/src/lib/actions-list/actions-list.component.html
- libs/ui/src/lib/actions-list/actions-list.component.scss
- libs/ui/src/lib/actions-list/actions-list.component.ts
- libs/ui/src/lib/actions-list/actions-list.module.ts
- libs/ui/src/lib/actions-picker-list/actions-picker-list.component.html
- libs/ui/src/lib/actions-picker-list/actions-picker-list.component.ts
- libs/ui/src/lib/actions-picker-list/actions-picker-list.module.ts
- libs/ui/src/lib/actions-picker/actions-picker.component.html
- libs/ui/src/lib/actions-picker/actions-picker.component.scss
- libs/ui/src/lib/actions-picker/actions-picker.component.ts
- libs/ui/src/lib/actions-picker/actions-picker.module.ts
This implements 1/4th of the "create a delivery" flow (pick a template). Next the other 3/4th, then design and the actual creation + updated app.
Introduce 3 new components to prepare for design & reusability:
The last two are simple wrappers around materials components for now and will be redesigned to follow our guidelines.
> Issue 590: new delivery flow, phase 1

- angular.json
- libs/catalog/README.md
- libs/catalog/jest.config.js
- libs/catalog/src/index.ts
- libs/catalog/src/lib/catalog.module.spec.ts
- libs/catalog/src/lib/catalog.module.ts
- libs/catalog/src/test-setup.ts
- libs/catalog/tsconfig.json
- libs/catalog/tsconfig.lib.json
- libs/catalog/tsconfig.spec.json
- libs/catalog/tslint.json
- nx.json
- tsconfig.json
> Create Catalog Lib

- libs/organization/src/lib/pages/organization-home/organization-home.component.ts
Fix a bug produced during the previous user flow PR review
> Fix accept invitation function

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/notify.ts
- apps/delivery/delivery/src/app/app-routing-module.ts
- apps/delivery/delivery/src/app/layout/context-menu.ts
- libs/material/src/lib/delivery/components/delivery-repertory/delivery-repertory.component.html
- libs/material/src/lib/delivery/components/delivery-repertory/delivery-repertory.component.scss
- libs/material/src/lib/delivery/components/delivery-repertory/delivery-repertory.component.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/pages/delivery-add-settings/delivery-add-settings.component.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.html
- libs/material/src/lib/delivery/pages/delivery-list/delivery-list.component.html
- libs/material/src/lib/delivery/pages/delivery-list/delivery-list.component.scss
- libs/material/src/lib/delivery/pages/delivery-list/delivery-list.component.ts
- libs/material/src/lib/delivery/pages/delivery-settings-editable/delivery-settings-editable.component.html
- libs/material/src/lib/delivery/pages/delivery-view/delivery-view.component.html
- libs/material/src/lib/delivery/pages/movie-materials-view/movie-materials-view.component.html
- libs/movie/src/lib/movie/pages/movie-list/movie-list.component.html
- libs/movie/src/lib/movie/pages/movie-list/movie-list.component.ts
- libs/organization/src/index.ts
- libs/organization/src/lib/permissions/+state/permissions.model.ts
- package-lock.json
> Issue#596 delivery list

- libs/material/src/lib/delivery/+state/delivery.model.ts
- libs/material/src/lib/delivery/+state/delivery.query.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/+state/delivery.store.ts
- libs/material/src/lib/delivery/delivery.module.ts
- libs/material/src/lib/delivery/pages/delivery-add-choose-starter/delivery-add-choose-starter.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-complete/delivery-add-complete.component.html
- libs/material/src/lib/delivery/pages/delivery-add-complete/delivery-add-complete.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-find-movie/delivery-add-find-movie.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-settings/delivery-add-settings.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-specific-delivery-list-picker/delivery-add-specific-delivery-list-picker.component.html
- libs/material/src/lib/delivery/pages/delivery-add-specific-delivery-list-picker/delivery-add-specific-delivery-list-picker.component.ts
- libs/material/src/lib/delivery/pages/delivery-add-template-picker/delivery-add-template-picker.component.html
- libs/material/src/lib/delivery/pages/delivery-add-template-picker/delivery-add-template-picker.component.ts
- libs/material/src/lib/delivery/pages/delivery-template-list/delivery-template-list.component.ts
- libs/ui/src/lib/actions-picker/actions-picker.component.html
- libs/ui/src/lib/actions-picker/actions-picker.component.ts
Finalize the flow for add delivery
> Issue 590: import specific delivery list

- angular.json
- apps/backend-functions/src/admin.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/relayer.ts
- apps/main/main/src/app/home/home.component.ts
- env/env.staging.ts
- firestore.rules
- libs/organization/src/lib/+state/organization.query.ts
- libs/organization/src/lib/permissions/+state/permissions.model.ts
- package-lock.json
- package.json
> Deploy toronto

- apps/catalog-marketplace/catalog-marketplace/src/app/movie/view/view.component.html
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/view/view.component.scss
https://github.com/blockframes/blockframes/issues/812
> movie-view css

- libs/material/src/lib/delivery/+state/delivery.service.ts
Copy template materials into movie when the delivery can't be signed
> Copy materials

- libs/material/src/lib/delivery/pages/delivery-add-find-movie/delivery-add-find-movie.component.html
- libs/material/src/lib/delivery/pages/delivery-add-find-movie/delivery-add-find-movie.component.scss
- libs/material/src/lib/template/pages/template-list/template-list.component.html
- libs/material/src/lib/template/pages/template-list/template-list.component.scss
- libs/material/src/lib/template/pages/template-list/template-list.component.ts
- libs/material/src/lib/template/template.module.ts
- libs/movie/src/lib/movie/components/movie-picker/movie-picker.component.scss
- libs/movie/src/lib/movie/pages/movie-list/movie-list.component.scss
table instead of card for template list, movie-card updated
> Movie card

- apps/backend-functions/src/environments/environment.ci.ts
- apps/backend-functions/src/environments/environment.prod.ts
- apps/backend-functions/src/environments/environment.staging.ts
- apps/backend-functions/src/environments/environment.ts
- apps/backend-functions/src/internals/algolia.ts
- env/demo/env.demo1.ts
- env/demo/env.demo2.ts
- env/demo/env.demo3.ts
- env/demo/env.demo4.ts
- env/demo/env.demo5.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- ops/deploy_secrets.sh
- secrets.template.sh
> More ops for Toronto

- apps/catalog-marketplace/catalog-marketplace/src/app/distribution-right/create/create.component.html
- apps/catalog-marketplace/catalog-marketplace/src/app/distribution-right/create/create.component.scss
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/home/home.component.html
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/search/search.component.html
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/search/search.component.scss
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/search/search.component.ts
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/view/view.component.html
- apps/catalog-marketplace/catalog-marketplace/src/app/movie/view/view.component.scss
- movie-view
- search
- home
- create
> Catalog css

- apps/catalog-marketplace/catalog-marketplace/src/app/distribution-right/+state/basket.service.ts
- apps/catalog-marketplace/catalog-marketplace/src/app/distribution-right/create/create.component.html
- apps/catalog-marketplace/catalog-marketplace/src/app/distribution-right/create/create.component.scss
- apps/catalog-marketplace/catalog-marketplace/src/app/distribution-right/create/create.component.ts
- libs/organization/src/lib/+state/organization.model.ts
- package-lock.json
- package.json
Made some changes to the availability search
> fields are on salesAgent now

- libs/auth/src/lib/components/email-verify/email-verify.component.html
- libs/material/src/lib/delivery/+state/delivery.model.ts
Delivery status starts in negociation and lettre icon is commented
> Issue#878 hugo

- libs/account/src/lib/profile/components/profile-display/profile-display.component.html
- libs/account/src/lib/profile/components/profile-display/profile-display.component.scss
- libs/account/src/lib/profile/components/profile-display/profile-display.component.ts
- libs/account/src/lib/profile/components/profile-form/profile-form.component.html
- libs/account/src/lib/profile/pages/profile-editable/profile-editable.component.html
- libs/material/src/lib/delivery/pages/delivery-add-choose-starter/delivery-add-choose-starter.component.html
- libs/material/src/lib/delivery/pages/delivery-add-choose-starter/delivery-add-choose-starter.component.ts
- libs/material/src/lib/delivery/pages/delivery-list/delivery-list.component.html
- libs/material/src/lib/delivery/pages/delivery-list/delivery-list.component.ts
- libs/notification/invitation/invitation-item/invitation-item.component.html
- libs/notification/invitation/invitation-item/invitation-item.component.scss
- libs/notification/invitation/invitation-item/invitation-item.component.ts
- libs/notification/notification/notification-item/notification-item.component.html
- libs/notification/notification/notification-item/notification-item.component.scss
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/components/organization-display/organization-display.component.html
- libs/organization/src/lib/components/organization-display/organization-display.component.scss
- libs/organization/src/lib/components/organization-display/organization-display.component.ts
- libs/organization/src/lib/components/organization-form/organization-form.component.html
- libs/organization/src/lib/pages/organization-editable/organization-editable.component.html
- libs/ui/src/lib/editable-sidenav/editable-sidenav.component.scss
> Notifications and Editable sidenav small fixes

- libs/material/src/lib/delivery/components/delivery-repertory/delivery-repertory.component.html
Correct display of delivery list mgDeadline
> correct display of mgDeadline in deliveryList

- libs/material/src/lib/delivery/components/delivery-new-template/new-template.component.html
- libs/material/src/lib/delivery/components/delivery-new-template/new-template.component.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/material/src/lib/template/+state/template.service.ts
> correct template service and component delivery-new-template

- apps/backend-functions/src/delete.ts
- libs/material/src/lib/delivery/guards/delivery-list.guard.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
> Firebase function fixes

- package-lock.json
- package.json
- run pwmetrics in your command line with `npm run pwm`
- added in the `package.json` a config. You can test any app you are currently running on localhost:4200.
> added pwmetrics & added script

- apps/delivery/delivery-e2e/src/integration/profil-test.spec.ts
- apps/delivery/delivery-e2e/src/support/pages/EditProfilePage.ts
- apps/delivery/delivery-e2e/src/support/pages/LoginPage.ts
- apps/delivery/delivery-e2e/src/support/pages/ViewProfilePage.ts
- apps/delivery/delivery-e2e/src/support/utils/type.ts
- libs/account/src/lib/profile/components/password-form/password-form.component.html
- libs/account/src/lib/profile/components/password-form/password-form.component.ts
- libs/account/src/lib/profile/components/profile-display/profile-display.component.html
- libs/account/src/lib/profile/components/profile-display/profile-display.component.ts
- libs/account/src/lib/profile/components/profile-form/profile-form.component.html
- libs/account/src/lib/profile/components/profile-form/profile-form.component.ts
- libs/account/src/lib/profile/pages/profile-editable/profile-editable.component.html
- libs/ui/src/lib/editable-sidenav/editable-sidenav.component.html
Profile test : login, navigation to page, change information and password
Fixes #838 use HostBinding for testing
> Test e2e profil

- libs/material/src/lib/delivery/components/delivery-material-form/delivery-material-form.component.ts
- libs/material/src/lib/delivery/components/movie-material-form/movie-material-form.component.ts
- libs/material/src/lib/delivery/forms/material.form.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.html
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/material/src/lib/delivery/pages/movie-editable/movie-editable.component.html
- libs/material/src/lib/delivery/pages/movie-editable/movie-editable.component.ts
- libs/material/src/lib/template/components/template-material-form/template-material-form.component.ts
- libs/material/src/lib/template/forms/material.form.ts
- libs/material/src/lib/template/pages/template-editable/template-editable.component.ts
- libs/utils/src/lib/form/forms/batch.form.ts
Use FormBatch in delivery-editable and movie-editable
> Issue#936 delivery editable

- libs/material/src/lib/delivery/+state/delivery.model.ts
- libs/material/src/lib/delivery/components/delivery-material-form/delivery-material-form.component.html
- libs/material/src/lib/delivery/components/delivery-material-list/delivery-material-list.component.ts
- libs/material/src/lib/delivery/forms/material.form.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/material/guards/delivery-materials.guard.ts
Save only stepId instead of entire step for materials in database
> Issue#779 step

- angular.json
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.scss
- apps/main/main/src/app/app-grid/app-grid.component.scss
- apps/main/main/src/app/home/home.component.scss
- libs/account/src/lib/profile/components/profile-display/profile-display.component.scss
- libs/auth/src/lib/pages/identity/identity.component.scss
- libs/auth/src/lib/pages/login-view/login-view.component.scss
- libs/auth/src/lib/pages/welcome-view/welcome-view.component.scss
- libs/ethers/src/lib/wallet/components/wallet-ask-password-form/wallet-ask-password-form.component.scss
- libs/ethers/src/lib/wallet/components/wallet-create-password-form/wallet-create-password-form.component.scss
- libs/ethers/src/lib/wallet/components/wallet-import-key-form/wallet-import-key-form.component.scss
- libs/ethers/src/lib/wallet/pages/wallet-reveal-mnemonic/wallet-reveal-mnemonic.component.scss
- libs/ethers/src/lib/wallet/pages/wallet-view/wallet-view.component.scss
- libs/material/src/lib/delivery/pages/delivery-list/delivery-list.component.scss
- libs/material/src/lib/template/pages/template-list/template-list.component.scss
- libs/notification/src/lib/invitation/invitation-item/invitation-item.component.scss
- libs/notification/src/lib/notification/notification-item/notification-item.component.scss
- libs/organization/src/lib/components/organization-create/organization-create.component.scss
- libs/organization/src/lib/components/organization-display-actions/organization-display-actions.component.scss
- libs/organization/src/lib/components/organization-display/organization-display.component.scss
- libs/organization/src/lib/pages/organization-find/organization-find.component.scss
- libs/organization/src/lib/pages/organization-home/organization-home.component.scss
- libs/ui/src/lib/actions-list/actions-list.component.scss
- libs/ui/src/lib/editable-sidenav/editable-sidenav.component.scss
- libs/ui/src/lib/feedback/feedback-message.component.scss
- libs/ui/src/lib/toolbar/context-menu/context-menu.component.scss
- libs/ui/src/lib/toolbar/left-menu/left-menu.component.scss
- styles/mixins.scss
- styles/variables.scss
Remove all imports of variables.
Replace it by import mixins (with only mixins and no colors)
> No imports variables

- apps/catalog/dashboard/dashboard/src/polyfills.ts
- apps/catalog/marketplace/marketplace/src/polyfills.ts
- apps/main/main/src/polyfills.ts
- apps/movie-financing/movie-financing/src/polyfills.ts
- package-lock.json
> Update polyfills 2

- README.md
- libs/movie/src/lib/movie/components/import/import-movie.module.ts
- libs/movie/src/lib/movie/components/import/table-extracted-movies/table-extracted-movies.component.html
- libs/movie/src/lib/movie/components/import/table-extracted-movies/table-extracted-movies.component.scss
- libs/movie/src/lib/movie/components/import/table-extracted-movies/table-extracted-movies.component.ts
- libs/ui/src/lib/upload/button-upload/button-upload.component.ts
- libs/ui/src/lib/upload/file-upload/file-upload.component.ts
- libs/utils/src/index.ts
- libs/utils/src/lib/file-sanitizer.ts
- libs/utils/src/lib/image-uploader.ts
> Feat 986 ❤️ : issue #986

- apps/catalog/marketplace/marketplace-e2e/src/integration/Create-distributionRights.spec.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/LandingPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/LoginPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/SearchPage.ts
- libs/movie/src/lib/movie/components/display-card-item/display-card-item.component.ts
- libs/ui/src/lib/movie-card/movie-card.component.html
- libs/ui/src/lib/movie-card/movie-card.component.ts
issue#989 🔨Update catalog-marketplace e2e test after movie-card & search page updated
> Issue #989 update marketplace e2e

- apps/catalog/dashboard/dashboard/src/app/app-routing-module.ts
- apps/catalog/dashboard/dashboard/src/app/layout/context-menu.ts
- libs/movie/src/lib/movie/components/import/import-movie.module.ts
- libs/movie/src/lib/movie/components/import/import-spreadsheet/import-spreadsheet.component.ts
- libs/movie/src/lib/movie/components/import/preview-sheet/preview-sheet.component.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/form/root/root.component.ts
- libs/movie/src/lib/movie/movie-routing.module.ts
- libs/movie/src/lib/movie/movie.module.ts
- libs/utils/src/index.ts
- libs/utils/src/lib/spreadsheet/index.ts
- tsconfig.json
Create links to spreadsheet in utils, and make import-movie-module independent
> resolve-import-excel

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/internals/pdf.ts
- apps/backend-functions/src/local/testPDFExport.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/relayer.ts
- apps/delivery/delivery-e2e/src/support/utils/type.ts
- libs/ethers/src/lib/create-tx.ts
- libs/ethers/src/lib/relayer/relayer.ts
- libs/ethers/src/lib/wallet/pages/wallet-send-tx/wallet-send-tx.component.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/organization/src/lib/+state/organization.model.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/+state/organization.store.ts
- libs/organization/src/lib/components/member-form-role/member-form-role.component.ts
- libs/organization/src/lib/components/organization-create/organization-create.component.html
- libs/organization/src/lib/components/organization-create/organization-create.component.ts
- libs/organization/src/lib/components/organization-display/organization-display.component.html
- libs/organization/src/lib/components/organization-form-operation/organization-form-operation.component.ts
- libs/organization/src/lib/components/organization-form/organization-form.component.html
- libs/organization/src/lib/components/organization-signer-form/organization-signer-form.component.ts
- libs/organization/src/lib/components/organization-signer-repertory/organization-signer-repertory.component.ts
- libs/organization/src/lib/forms/organization-profile-edit-form.ts
- libs/utils/src/lib/form/validators/validators.ts
Requested changes made after merge of PR #993
> requested changes & address disambiguation

- apps/delivery/delivery-e2e/src/integration/CRUD-delivery.spec.ts
- apps/delivery/delivery-e2e/src/support/pages/ConfirmModal.ts
- apps/delivery/delivery-e2e/src/support/pages/delivery/DeliveryEditablePage.ts
- apps/delivery/delivery-e2e/src/support/pages/movie/MovieListPage.ts
- apps/delivery/delivery-e2e/src/support/utils/data.ts
- apps/delivery/delivery-e2e/src/support/utils/functions.ts
- apps/delivery/delivery-e2e/src/support/utils/type.ts
- libs/material/src/lib/delivery/components/delivery-material-form/delivery-material-form.component.html
- libs/material/src/lib/delivery/components/delivery-material-form/delivery-material-form.component.ts
- libs/material/src/lib/delivery/components/delivery-material-list/delivery-material-list.component.html
- libs/material/src/lib/delivery/components/delivery-material-list/delivery-material-list.component.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.html
- libs/ui/src/lib/confirm/confirm.component.html
- libs/ui/src/lib/movie-card/movie-card.component.html
Delivery Materials CRUD operations tests: issue#987
> delivery materials e2e tests

- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/template/+state/template.model.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/material/src/lib/template/components/template-material-form/template-material-form.component.ts
- libs/material/src/lib/template/components/template-material-list/template-material-list.component.ts
- libs/material/src/lib/template/forms/material.form.ts
- libs/material/src/lib/template/material/+state/index.ts
- libs/material/src/lib/template/material/+state/template-material.model.ts
- libs/material/src/lib/template/pages/template-editable/template-editable.component.ts
> Issue#1009 model template material

- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/create.component.html
- libs/auth/src/lib/components/email-verify/email-verify.component.html
- libs/auth/src/lib/pages/identity/identity.component.html
- libs/ethers/src/lib/wallet/components/wallet-ask-password-form/wallet-ask-password-form.component.html
- libs/ethers/src/lib/wallet/components/wallet-create-password-form/wallet-create-password-form.component.html
- libs/ethers/src/lib/wallet/components/wallet-import-key-form/wallet-import-key-form.component.html
- libs/ethers/src/lib/wallet/components/wallet-import-key/wallet-import-key.component.html
- libs/ethers/src/lib/wallet/pages/wallet-add-key/wallet-add-key.component.html
- libs/ethers/src/lib/wallet/pages/wallet-reveal-mnemonic/wallet-reveal-mnemonic.component.html
- libs/ethers/src/lib/wallet/pages/wallet-send-tx/wallet-send-tx.component.html
- libs/movie/src/lib/movie/pages/movie-create/movie-create.component.html
- libs/movie/src/lib/movie/pages/movie-list/movie-list.component.scss
- libs/ui/src/lib/movie-card/movie-card.component.scss
- styles/components/mat-button.scss
- styles/components/mat-card.scss
- styles/components/mat-table.scss
- styles/style.scss
- styles/themes/light.scss
> Global css

- apps/delivery/delivery-e2e/src/integration/CRUD-delivery.spec.ts
- apps/delivery/delivery-e2e/src/support/pages/NavbarPage.ts
- apps/delivery/delivery-e2e/src/support/pages/delivery/DeliveryStakeholdersPage.ts
- apps/delivery/delivery-e2e/src/support/pages/index.ts
- libs/notification/src/lib/notification/notification-item/notification-item.component.html
- libs/organization/src/lib/components/organization-search/organization-search.component.html
> frontend(e2e): tests on delivery stakeholder invitation

- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.model.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/availabilities.util.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/create.component.ts
This PR builds on top of issue#980-availabilities_fixed , it therefore needs to be merged in `issue#980-availabilities_fixed`
> availabilities proposal (builds on top of issue#980-availabilities_fixed)

- libs/organization/src/lib/+state/organization.query.ts
- libs/organization/src/lib/+state/organization.store.ts
Delete OrganizationForm in OrganizationStore
> clean OrganizationStore

- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.service.ts
- apps/catalog/marketplace/marketplace/src/app/guards/catalog-basket-list.guard.ts
- apps/catalog/marketplace/marketplace/src/app/movie/selection/selection.component.ts
- package-lock.json
- package.json
Refactor of the catalog basket guard
> Guard bigger boat

- libs/ethers/src/lib/key-manager/+state/key-manager.query.ts
- libs/ethers/src/lib/wallet/+state/wallet.service.ts
- libs/ethers/src/lib/wallet/guards/wallet-active.guard.ts
> check selfdestructed wallet

- apps/delivery/delivery/src/app/app-routing-module.ts
- libs/material/src/lib/delivery/components/delivery-material-list/delivery-material-list.component.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/guards/movie-organization-list.guard.ts
- libs/movie/src/lib/movie/pages/movie-list/movie-list.component.ts
- libs/notification/src/index.ts
- libs/notification/src/lib/invitation/+state/invitation.query.ts
- libs/notification/src/lib/notification/+state/notification.service.ts
- libs/notification/src/lib/notification/notification-list/notification-list.component.ts
- libs/notification/src/lib/notification/notifications.guard.ts
- package-lock.json
- package.json
> frontend(guards): using akita-ng-fire guards

- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/material/+state/material.service.ts
Create 3 sub-functions to copy materials in movie and update a delivery.
> Issue#844 refactor copy materials 2

- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/internals/pdf.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/local/testPDFExport.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/migrations.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/stakeholder.ts
- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/+state/organization.model.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/+state/organization.store.ts
- tsconfig.json
> create OrganizationDocument model to share it between back and front

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/invitation.ts
- libs/auth/src/lib/+state/auth.firestore.ts
- libs/notification/src/lib/invitation/+state/invitation.firestore.ts
- libs/notification/src/lib/invitation/+state/invitation.model.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/notification/src/lib/invitation/+state/invitation.store.ts
- libs/notification/src/lib/invitation/invitation-item/invitation-item.component.ts
- libs/notification/src/lib/invitation/invitation-list/invitation-list.component.ts
- libs/notification/src/lib/notification-widget/notification-widget.component.ts
- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/+state/organization.model.ts
- libs/organization/src/lib/components/member-invitation/member-invitation.component.ts
- libs/organization/src/lib/components/member-pending/member-pending.component.ts
- libs/organization/src/lib/pages/member-editable/member-editable.component.ts
- libs/organization/src/lib/pages/organization-home/organization-home.component.ts
- tsconfig.json
Added some comments.
Redefined Invitation model to use it in server and client side (contributes to #1043).
> DRY : Invitation model

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/internals/pdf.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/migrations.ts
- apps/backend-functions/src/utils.ts
- apps/catalog/marketplace/marketplace/src/app/movie/selection/selection.component.ts
- libs/material/src/lib/material/+state/material.firestore.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/template/forms/material.form.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/form/main/main.component.ts
- libs/movie/src/lib/movie/form/sales-agent-deal/sales-agent-deal.component.ts
- libs/movie/src/lib/movie/form/sales-info/sales-info.component.ts
- libs/movie/src/lib/movie/form/version-info/version-info.component.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
- libs/utils/src/lib/form/validators/validators.ts
- libs/utils/src/lib/pipes/translate-slug.pipe.ts
- tsconfig.json
> create interface MaterialDocument

- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.model.ts
- apps/catalog/marketplace/marketplace/src/app/movie/selection/selection.component.ts
> change movie data creater function

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/internals/pdf.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/material.ts
- apps/backend-functions/src/stakeholder.ts
- libs/material/src/lib/delivery/+state/delivery.firestore.ts
- libs/material/src/lib/delivery/+state/delivery.model.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/delivery/guards/delivery-active.guard.ts
- libs/material/src/lib/delivery/guards/delivery-list.guard.ts
- tsconfig.json
> Issue#1043 delivery

- apps/backend-functions/src/data/types.ts
Removed AppIcon from type.ts (fix #684)
> Removed AppIcon as we don't use it anymore

- libs/ethers/src/lib/relayer/relayer.ts
- libs/ethers/src/lib/wallet/+state/wallet.service.ts
- libs/ethers/src/lib/wallet/guards/wallet-tx.guard.ts
- libs/ethers/src/lib/wallet/pages/wallet-send-tx/wallet-send-tx.component.html
- libs/ethers/src/lib/wallet/pages/wallet-send-tx/wallet-send-tx.component.ts
- libs/ethers/src/lib/wallet/wallet.module.ts
- libs/organization/src/lib/+state/organization.store.ts
- libs/ui/src/lib/feedback/feedback-message.component.ts
> error handling

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/delete.ts
- apps/backend-functions/src/delivery.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/stakeholder.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.model.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/availabilities.util.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/create.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/sales-agent-deal/sales-agent-deal.form.ts
- libs/movie/src/lib/movie/guards/movie-organization-active.guard.ts
- libs/ui/src/lib/datepicker/datepicker.component.ts
- libs/ui/src/lib/month-calendar/month-calendar.component.ts
- libs/utils/src/lib/date-range.ts
- libs/utils/src/lib/helpers.ts
> Issue#1043 movie

- apps/backend-functions/src/data/types.ts
- libs/material/src/lib/template/+state/template.firestore.ts
- libs/material/src/lib/template/+state/template.model.ts
- tsconfig.json
> create interface TemplateDocument

- libs/movie/src/lib/movie/form/root/root.component.ts
- libs/movie/src/lib/movie/pages/movie-editable/movie-editable.component.html
- libs/movie/src/lib/movie/pages/movie-editable/movie-editable.component.ts
> fix movie form

- .circleci/config.yml
- package-lock.json
- package.json
> Issue#1050 bundlesize

- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/availabilities.util.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/create/create.component.ts
I couldn't add filtering for original language, cause this property doesn't exist on the movie sales interface. So I added support for dubbings and subtitles.
> added dubbings and subtitle support

- libs/organization/src/lib/components/organization-create/organization-create.component.ts
- libs/organization/src/lib/forms/organization.form.ts
- libs/organization/src/lib/pages/organization-editable/organization-editable.component.ts
Rename CreateOrganizationForm to OrganizationForm
Contributes to #1120
> rename CreateOrganizationForm to OrganizationForm

- .circleci/config.yml
Send sizes of apps of master build to zapier
> post request to zapier

- libs/organization/src/lib/components/organization-create/organization-create.component.html
> text change on organization-create html

- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/components/organization-create/organization-create.component.html
- libs/organization/src/lib/components/organization-create/organization-create.component.scss
- libs/organization/src/lib/components/organization-form/organization-form.component.scss
- libs/organization/src/lib/no-organization.module.ts
- libs/ui/src/lib/cropper/cropper/cropper.component.html
- libs/ui/src/lib/cropper/cropper/cropper.component.scss
- libs/ui/src/lib/cropper/cropper/cropper.component.ts
- libs/ui/src/lib/cropper/storage-image.directive.ts
related to #287 
implemented cropper in oraganization creation page
> Issue#287 cropper org creation

- libs/account/src/lib/profile/components/profile-display/profile-display.component.html
- libs/account/src/lib/profile/components/profile-form/profile-form.component.html
- libs/account/src/lib/profile/components/profile-form/profile-form.component.scss
- libs/account/src/lib/profile/forms/profile-edit.form.ts
- libs/account/src/lib/profile/profile-menu/profile-menu.component.html
- libs/account/src/lib/profile/profile.module.ts
- libs/ui/src/lib/assets/icons/changePass.svg
> Issue#1100 profile

- libs/organization/src/lib/components/organization-create/organization-create.component.html
- libs/organization/src/lib/pages/organization-find/organization-find.component.ts
Snackbar message to inform user their request has been sent.
Related to  #1095
> add feedback message to user request

- apps/catalog/marketplace/marketplace/src/app/components/completion.component.ts
- libs/ui/src/lib/feedback/feedback-message.component.scss
> styled feedback message

- .circleci/config.yml
> Production ops: nightly build & deploy

- libs/organization/src/lib/no-organization.module.ts
- libs/organization/src/lib/pages/organization-home/organization-home.component.ts
- libs/organization/src/lib/pages/organization-loading/organization-loading.component.html
- libs/organization/src/lib/pages/organization-loading/organization-loading.component.scss
- libs/organization/src/lib/pages/organization-loading/organization-loading.component.ts
> no org id bug fix

- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/components/organization-create/organization-create.component.ts
- libs/organization/src/lib/guard/no-organization.guard.ts
- libs/organization/src/lib/no-organization.module.ts
- libs/organization/src/lib/pages/organization-feedback/organization-feedback.component.html
- libs/organization/src/lib/pages/organization-feedback/organization-feedback.component.scss
- libs/organization/src/lib/pages/organization-feedback/organization-feedback.component.ts
> NoOrganizationGuard

- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/pages/identity/identity.component.html
- libs/auth/src/lib/pages/identity/identity.component.scss
- libs/auth/src/lib/pages/identity/identity.component.ts
- libs/organization/src/lib/components/organization-create/organization-create.component.html
implement cropper in Account creation page
related to #1104 & #287
> Issue#287 implement cropper

- libs/organization/src/lib/pages/organization-find/organization-find.component.ts
- libs/ui/src/lib/actions-list/actions-list.component.scss
> text and css fixs to OrganizationHome

- apps/catalog/marketplace/marketplace/src/app/app-routing-module.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.service.ts
- apps/catalog/marketplace/marketplace/src/app/layout/context-menu.ts
- apps/catalog/marketplace/marketplace/src/app/movie/selection/selection.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/selection/selection.component.ts
- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/+state/organization.model.ts
close #996 
fixed delete button
> fixed delete button on table

- .circleci/config.yml
- angular.json
- env/env.prod.ts
> Fixing afm production

- libs/organization/src/lib/components/member-add/member-add.component.html
- libs/organization/src/lib/components/member-add/member-add.component.ts
- libs/organization/src/lib/components/member-invitation/member-invitation.component.html
- libs/organization/src/lib/components/member-invitation/member-invitation.component.scss
- libs/organization/src/lib/components/member-pending/member-pending.component.html
- libs/organization/src/lib/components/member-pending/member-pending.component.scss
- libs/organization/src/lib/components/member-repertory/member-repertory.component.html
- libs/organization/src/lib/components/member-repertory/member-repertory.component.scss
- libs/organization/src/lib/components/member-repertory/member-repertory.component.ts
- libs/organization/src/lib/pages/member-editable/member-editable.component.html
- libs/organization/src/lib/pages/member-editable/member-editable.component.ts
close #1096 
sccs css cssssssssssssssssssssssss
> improved css for member panel

- libs/account/src/lib/profile/components/profile-display/profile-display.component.html
- libs/account/src/lib/profile/components/profile-form/profile-form.component.ts
- libs/account/src/lib/profile/forms/profile-edit.form.ts
- libs/ui/src/lib/cropper/cropper/cropper.component.ts
- libs/ui/src/lib/cropper/storage-image.directive.ts
- package-lock.json
> fixed issue#1191

- apps/catalog/marketplace/marketplace/src/app/app-routing-module.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.service.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.scss
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-view/wishlist-view.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-view/wishlist-view.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist.module.ts
- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/+state/organization.model.ts
> Wishlist view update

- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.scss
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.scss
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.scss
- libs/account/src/lib/profile/components/profile-display/profile-display.component.scss
- libs/auth/src/lib/pages/welcome-view/welcome-view.component.html
- libs/movie/src/lib/movie/components/display-film-details/display-film-details.component.html
- libs/movie/src/lib/movie/components/display-film-details/display-film-details.component.scss
- libs/movie/src/lib/movie/components/display-principal-informations/display-principal-informations.component.html
- libs/movie/src/lib/movie/components/display-principal-informations/display-principal-informations.component.scss
- libs/movie/src/lib/movie/components/display-version-info/display-version-info.component.html
- libs/movie/src/lib/movie/components/display-version-info/display-version-info.component.scss
- libs/ui/src/lib/editable-sidenav/editable-sidenav.component.scss
Responsive screen for catalog-marketplace
> Responsive part

- .vscode/settings.json
- apps/backend-functions/src/admin.ts
- apps/backend-functions/src/assets/mail-templates.ts
- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/internals/email.ts
- apps/backend-functions/src/internals/firebase.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/users.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.service.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/pages/identity/identity.component.html
- libs/auth/src/lib/pages/identity/identity.component.scss
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/organization/src/lib/pages/organization-loading/organization-loading.component.ts
- package-lock.json
- package.json
- secrets.template.sh
close #1116 
user gets invitation link with inivtationId for mapping
> invitation link #1116

- libs/auth/src/lib/pages/identity/identity.component.html
- libs/auth/src/lib/pages/identity/identity.component.ts
- libs/ui/src/lib/form/form-groups/password-confirm/password-confirm.component.html
> identity changes

- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-view/wishlist-view.component.scss
- apps/catalog/marketplace/marketplace/src/app/pages/contact-page/contact-page.component.html
- apps/catalog/marketplace/marketplace/src/app/pages/contact-page/contact-page.component.scss
> footer corrections

- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/components/organization-create/organization-create.component.ts
- libs/organization/src/lib/forms/organization.form.ts
- libs/organization/src/lib/pages/organization-editable/organization-editable.component.ts
- libs/utils/src/lib/form/validators/validators.ts
> check uniqueness on firestore

- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.service.ts
- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
- apps/catalog/marketplace/marketplace/src/app/pages/privacy-page/privacy-page.component.ts
- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/components/signin-form/signin-form.component.scss
- libs/auth/src/lib/components/signup-form/signup-form.component.html
- libs/auth/src/lib/components/signup-form/signup-form.component.scss
- libs/auth/src/lib/components/signup-form/signup-form.component.ts
- libs/auth/src/lib/forms/signup.form.ts
- libs/auth/src/lib/pages/identity/identity.component.html
- libs/auth/src/lib/pages/identity/identity.component.scss
- libs/auth/src/lib/pages/identity/identity.component.ts
- libs/auth/src/lib/pages/login-view/login-view.component.html
- libs/auth/src/lib/pages/login-view/login-view.component.ts
- libs/movie/src/lib/movie/components/display-list/display-list.component.html
- libs/movie/src/lib/movie/components/display-list/display-list.component.ts
- styles/style.scss
> Issue#1215 issue#1201

- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.scss
- libs/organization/src/lib/pages/organization-feedback/organization-feedback.component.html
- libs/ui/src/lib/feedback/feedback-message.component.scss
- libs/ui/src/lib/feedback/feedback-message.module.ts
- package.json
> home page responsivity

- apps/catalog/marketplace/marketplace/src/index.html
> With google analytics

- apps/catalog/marketplace/marketplace/src/app/app.module.ts
- libs/auth/src/lib/auth.module.ts
> added perfomance module for analytics - catalog-marketplace

- apps/backend-functions/src/assets/mail-templates.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/users.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/organization/src/lib/+state/organization.service.ts
remove duplicate "Someone wants you to join his org" & user creds emails
> remove email doublon

- .circleci/config.yml
Update the piece of code that pushes stats to zappier with new packages paths.
> ops: fix bundle sizes

- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/components/signup-form/signup-form.component.html
- libs/auth/src/lib/components/signup-form/signup-form.component.ts
- libs/auth/src/lib/pages/identity/identity.component.html
- libs/auth/src/lib/pages/identity/identity.component.ts
- libs/ui/src/lib/terms-conditions/terms-conditions.component.html
- libs/ui/src/lib/terms-conditions/terms-conditions.component.ts
- libs/ui/src/lib/terms-conditions/terms-conditions.module.ts
- tsconfig.json
Reusable component for Terms and Conditions of us checkbox.
> Created reusable component for Terms and Conditions of use checked

- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.ts
> remove DomSanitizer to catalog-movie-view

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/local/testPDFExport.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.query.ts
- apps/catalog/marketplace/marketplace/src/app/layout/layout.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-view/wishlist-view.component.ts
- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/+state/organization.model.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/forms/organization.form.ts
> change Organization Model to manage type of dates

- .circleci/config.yml
- angular.json
> Staging build

- apps/catalog/marketplace/marketplace/src/app/distribution-right/+state/basket.service.ts
- libs/material/src/lib/delivery/pages/delivery-editable/delivery-editable.component.ts
- libs/material/src/lib/material/+state/material.model.ts
- libs/material/src/lib/material/+state/material.service.ts
- libs/material/src/lib/template/+state/template.model.ts
- libs/material/src/lib/template/+state/template.query.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/material/src/lib/template/components/template-add/template-add.component.ts
- libs/material/src/lib/template/pages/template-editable/template-editable.component.ts
- libs/material/src/lib/template/pages/template-list/template-list.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.query.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/notification/src/lib/notification/+state/notification.service.ts
- package-lock.json
- package.json
Using hooks in template and material services.
issue #1258
> Issue#1258 hooks

- libs/account/src/lib/profile/components/profile-display/profile-display.component.html
- libs/account/src/lib/profile/profile-menu/profile-menu.component.html
- libs/movie/src/lib/movie/display/display.module.ts
- libs/movie/src/lib/movie/display/festival-prizes/festival-prizes.component.html
- libs/movie/src/lib/movie/display/main/main.component.html
- libs/movie/src/lib/movie/display/promotional-elements/promotional-elements.component.html
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.component.html
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.component.scss
- libs/movie/src/lib/movie/form/form.module.ts
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/main/main.component.scss
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.component.html
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.component.scss
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.component.ts
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.form.ts
- libs/organization/src/lib/components/organization-display/organization-display.component.html
- libs/ui/src/lib/avatar-list/avatar-list.component.html
- libs/ui/src/lib/cropper/cropper.module.ts
- libs/ui/src/lib/cropper/cropper/cropper.component.html
- libs/ui/src/lib/cropper/cropper/cropper.component.ts
- libs/ui/src/lib/cropper/image-reference.directive.ts
- libs/ui/src/lib/cropper/storage-image.directive.ts
- libs/ui/src/lib/movie-card/movie-card.component.html
- libs/ui/src/lib/movie-card/movie-card.module.ts
> Issue#1259 store display image

- apps/catalog/dashboard/dashboard/src/app/app-routing-module.ts
- apps/catalog/dashboard/dashboard/src/app/dashboard.module.ts
- apps/catalog/dashboard/dashboard/src/app/layout/context-menu.ts
- apps/catalog/dashboard/dashboard/src/app/pages/about-page/about-page.component.html
- apps/catalog/dashboard/dashboard/src/app/pages/about-page/about-page.component.scss
- apps/catalog/dashboard/dashboard/src/app/pages/about-page/about-page.component.ts
- apps/catalog/dashboard/dashboard/src/app/pages/about-page/about.module.ts
- apps/catalog/dashboard/dashboard/src/app/pages/contact-page/contact-page.component.html
- apps/catalog/dashboard/dashboard/src/app/pages/contact-page/contact-page.component.scss
- apps/catalog/dashboard/dashboard/src/app/pages/contact-page/contact-page.component.ts
- apps/catalog/dashboard/dashboard/src/app/pages/contact-page/contact.module.ts
- apps/catalog/dashboard/dashboard/src/app/pages/privacy-page/privacy-page.component.ts
- apps/catalog/dashboard/dashboard/src/app/pages/privacy-page/privacy.module.ts
- apps/catalog/dashboard/dashboard/src/app/pages/team-page/team-page.component.html
- apps/catalog/dashboard/dashboard/src/app/pages/team-page/team-page.component.scss
- apps/catalog/dashboard/dashboard/src/app/pages/team-page/team-page.component.ts
- apps/catalog/dashboard/dashboard/src/app/pages/team-page/team.module.ts
- apps/catalog/marketplace/marketplace/src/app/app-routing-module.ts
- apps/catalog/marketplace/marketplace/src/app/marketplace.module.ts
- apps/main/main/src/app/app-routing-module.ts
- libs/movie/src/lib/movie/guards/movie-organization-list.guard.ts
- tsconfig.json
Update routes for Catalog Dashboard
> Routes for CatalogDashboard

- apps/catalog/marketplace/marketplace/src/app/layout/layout.component.ts
- apps/movie-financing/movie-financing/src/app/explorer/details/details.component.ts
- libs/account/src/lib/profile/pages/profile-editable/profile-editable.component.ts
- libs/account/src/lib/profile/profile-menu/profile-menu.component.ts
- libs/auth/src/lib/+state/auth.query.ts
- libs/auth/src/lib/+state/auth.service.ts
- libs/auth/src/lib/+state/auth.store.ts
- libs/auth/src/lib/auth.module.ts
- libs/auth/src/lib/guard/auth.guard.ts
- libs/auth/src/lib/pages/identity/identity.component.ts
- libs/auth/src/lib/pages/login-view/login-view.component.ts
- libs/material/src/lib/delivery/+state/delivery.service.ts
- libs/material/src/lib/template/+state/template.service.ts
- libs/notification/src/lib/invitation/+state/invitation.model.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/notification/src/lib/invitation/guard/no-organization-invitation.guard.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/guard/no-organization.guard.ts
- libs/organization/src/lib/guard/organization.guard.ts
- package-lock.json
- package.json
- tsconfig.json
> Issue#1258 auth

- libs/auth/src/lib/guard/auth.guard.ts
> fix authGuard

- apps/catalog/marketplace/marketplace-e2e/src/integration/Send-an-offer.spec.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/LandingPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/NavbarPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/SearchPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/WishlistPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/index.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/utils/type.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/utils/users.ts
- apps/catalog/marketplace/marketplace/src/app/app-routing-module.ts
- apps/catalog/marketplace/marketplace/src/app/layout/layout.component.html
- apps/catalog/marketplace/marketplace/src/app/marketplace.module.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
> Issue#1265 send an offer

- apps/backend-ops/src/main.ts
- apps/backend-ops/src/users.fixture.ts
> With vincents users

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-ops/src/admin.ts
- apps/backend-ops/src/main.ts
- apps/catalog/marketplace/marketplace/src/app/movie/search/filter.util.ts
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.scss
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.module.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- libs/movie/src/lib/movie/components/display-list/display-list.component.html
- libs/utils/src/lib/algolia.ts
> added movies deploy function

- apps/catalog/dashboard/dashboard/src/app/app.component.ts
- apps/catalog/dashboard/dashboard/src/app/app.module.ts
- apps/catalog/dashboard/dashboard/src/app/layout/layout.component.html
- apps/catalog/marketplace/marketplace/src/app/app.component.ts
- apps/catalog/marketplace/marketplace/src/app/app.module.ts
- apps/catalog/marketplace/marketplace/src/app/layout/layout.component.html
- apps/catalog/marketplace/marketplace/src/index.html
- apps/delivery/delivery/src/app/app.component.ts
- apps/delivery/delivery/src/app/app.module.ts
- apps/delivery/delivery/src/app/layout/layout.component.html
- apps/main/main/src/app/app.component.ts
- apps/main/main/src/app/app.module.ts
- apps/main/main/src/app/layout/layout.component.html
- apps/main/main/src/index.html
- libs/account/src/lib/profile/profile-menu/profile-menu.component.html
- libs/account/src/lib/profile/profile-menu/profile-menu.component.scss
- libs/ui/src/lib/theme/index.ts
- libs/ui/src/lib/theme/theme-widget/theme-widget.component.html
- libs/ui/src/lib/theme/theme-widget/theme-widget.component.spec.ts
- libs/ui/src/lib/theme/theme-widget/theme-widget.component.ts
- libs/ui/src/lib/theme/theme-widget/theme-widget.module.ts
- libs/ui/src/lib/theme/theme.service.ts
- styles/style.scss
Now theme is stored on localStorage.
Each application can specify a default theme. 
User can chose their theme.
> User can choose a Theme

- apps/catalog/marketplace/marketplace-e2e/src/integration/Send-an-offer.spec.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/HomePage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/NavbarPage.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/utils/movies.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/utils/users.ts
> E2e run ci test

- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.html
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist.module.ts
- libs/catalog/src/lib/components/production-informations/production-informations.component.ts
- libs/catalog/src/lib/components/promotional-elements/promotional-elements.component.html
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.component.html
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.form.ts
- libs/ui/src/lib/movie-card/movie-card.component.html
- libs/utils/src/lib/image-uploader.ts
> Image display

- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.ts
> quick fix on line up page

- apps/backend-functions/src/internals/algolia.ts
> fix for algolia golden data

- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/organization/src/lib/pages/organization-home/organization-home.component.ts
Fix error when a user find an organization after signup and want to send an invitation.
> remove avatar to create an invitation form user to organization

- apps/catalog/marketplace/marketplace-e2e/src/integration/create-wishlist.spec.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/NavbarPage.ts
Remove checkMessage function from the tests
> Remove checkMessage function

- apps/catalog/marketplace/marketplace/src/app/movie/view/view.component.ts
- libs/auth/src/lib/components/email-verify/email-verify.component.html
- libs/notification/src/lib/invitation/invitation-item/invitation-item.component.html
- libs/notification/src/lib/notification-widget/notification-widget.component.html
- libs/ui/src/lib/actions-list/actions-list.component.html
- styles/components/mat-button.scss
- styles/components/mat-card.scss
- styles/components/mat-chips.scss
- styles/components/mat-dialog.scss
- styles/components/mat-divider.scss
- styles/components/mat-expansion-panel.scss
- styles/components/mat-form.scss
- styles/components/mat-list.scss
- styles/components/mat-menu.scss
- styles/components/mat-table.scss
- styles/components/mat-toolbar.scss
- styles/footer.scss
- styles/style.scss
- styles/theme.scss
- styles/themes/dark.scss
- styles/themes/light.scss
Review of the scss files.
Creation of custom mixin to complete angular material mixin for components.
Clean of the light and dark variables.
> Review theme

- apps/backend-functions/src/admin.ts
- apps/backend-functions/src/assets/admin-templates.ts
- apps/backend-functions/src/environments/environment.ci.ts
- apps/backend-functions/src/environments/environment.prod.ts
- apps/backend-functions/src/environments/environment.staging.ts
- apps/backend-functions/src/environments/environment.ts
- ops/deploy_secrets.sh
- secrets.template.sh
Fix issue #700 by adding a simple password form for the admin functions.
> admin: add password check on post

- styles/components/mat-chips.scss
- styles/components/mat-form.scss
> chip and form changes

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
Add new values in static models
> add new value in static models

- libs/utils/src/lib/routes/create-routes.ts
> Better code for scrolling event, using :host in css

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.module.ts
Just create the folder for the tunnel layout
> Creation of movie-tunnel folder

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.module.ts
- libs/ui/src/lib/icon-component.ts
- styles/components/mat-sidenav.scss
- styles/theme.scss
Creation of the layout for the movie creation tunnel
Fix #1468
> Create layout folder

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel-routing.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.ts
- libs/ui/src/lib/assets-directive/assets-theme.directive.ts
related #1415
e2e test needs to be done
> Issue#1415 tunnel welcome

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.guard.ts
- libs/movie/src/lib/movie/form/main/main.component.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/pages/movie-editable/movie-editable.component.ts
Make MovieForm Injectable
Update guard to fill the form with default value if any
Update movie.main.form as an example
> Injectable movie form

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.module.ts
- libs/ui/src/lib/tunnel/page/tunnel-page.component.html
- libs/ui/src/lib/tunnel/page/tunnel-page.component.scss
- libs/ui/src/lib/tunnel/page/tunnel-page.component.ts
- libs/ui/src/lib/tunnel/page/tunnel-page.module.ts
> Issue#1482 tunnel page

- apps/catalog/catalog/src/app/marketplace/marketplace.module.ts
- apps/catalog/marketplace/marketplace-e2e/src/support/pages/SearchPage.ts
- apps/catalog/marketplace/marketplace/src/app/distribution-deal/+state/cart.service.ts
- apps/catalog/marketplace/marketplace/src/app/marketplace.module.ts
- env/env.ci.ts
- package-lock.json
- package.json
> Fix e2e create wishlist

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/keywords/keywords.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/keywords/keywords.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/keywords/keywords.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel-routing.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.guard.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/synopsis/synopsis.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/synopsis/synopsis.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/synopsis/synopsis.module.ts
- libs/movie/src/lib/movie/form/promotional-description/key-assets/key-assets.component.html
- libs/movie/src/lib/movie/form/promotional-description/key-assets/key-assets.component.ts
- libs/movie/src/lib/movie/form/promotional-description/keywords/keywords.component.html
- libs/movie/src/lib/movie/form/promotional-description/keywords/keywords.component.scss
- libs/movie/src/lib/movie/form/promotional-description/keywords/keywords.component.ts
- libs/movie/src/lib/movie/form/promotional-description/promotional-description.module.ts
> Issue#1418 tunnel keywords

- apps/backend-functions/src/movie.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
Cleaning some of movie service code.
Moving create hook operations in the backend.
> Issue#944 refactor movie crud

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/synopsis/synopsis.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/synopsis/synopsis.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/synopsis/synopsis.module.ts
- libs/movie/src/lib/movie/form/promotional-description/key-assets/key-assets.component.html
- libs/movie/src/lib/movie/form/promotional-description/key-assets/key-assets.component.scss
- libs/movie/src/lib/movie/form/promotional-description/key-assets/key-assets.component.ts
- libs/movie/src/lib/movie/form/promotional-description/promotional-description.form.ts
- libs/movie/src/lib/movie/form/story/story.form.ts
- libs/movie/src/lib/movie/form/story/story.module.ts
- libs/movie/src/lib/movie/form/story/synopsis/synopsis.component.html
- libs/movie/src/lib/movie/form/story/synopsis/synopsis.component.scss
- libs/movie/src/lib/movie/form/story/synopsis/sysnopsis.component.ts
> Issue#1416 tunnel synopsis

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
Add 2 news statics models, update one more
> Update static model

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/movies.ts
close #1330 
movies are now synchronized with the algolia index
> added movie update,create and delete hooks

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.guard.ts
- libs/movie/src/lib/form/movie.form.ts
Form is destroyed with the Tunnel component.
> Make the form injectable on the Tunnel only

- libs/ethers/src/lib/dao/forms/operations.form.ts
- libs/material/src/lib/delivery/forms/informations.form.ts
- libs/organization/src/lib/forms/member.form.ts
- libs/organization/src/lib/permissions/+state/permissions.service.ts
- libs/utils/src/lib/form/forms/list.form.ts
FormList get rid of the empty value recursively
```typescript
const form = new FormList([
new FormGroup({
name: new FormControl(''),
description: new FormControl(''),
})
]);
const value = form.value // []
```
> FormList value filter content without value

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel-routing.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/technical-info/technical-info.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/technical-info/technical-info.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/technical-info/technical-info.module.ts
- libs/movie/src/index.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/form.module.ts
- libs/movie/src/lib/movie/form/sales-info/format/format.component.html
- libs/movie/src/lib/movie/form/sales-info/format/format.component.scss
- libs/movie/src/lib/movie/form/sales-info/format/format.component.ts
- libs/movie/src/lib/movie/form/sales-info/format/format.module.ts
- libs/movie/src/lib/movie/form/sales-info/sales-info.form.ts
- libs/movie/src/lib/movie/form/version-info/version-info.component.html
- libs/movie/src/lib/movie/form/version-info/version-info.component.scss
- libs/movie/src/lib/movie/form/version-info/version-info.component.ts
- libs/movie/src/lib/movie/form/version-info/version-info.module.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
part one of the issue ref: #1411
> Issue 1411 rights

- apps/backend-functions/src/movie.ts
Getting organization in TX to be sure it's updated since last iteration
> Fix onMovieCreate function

- apps/catalog/catalog/src/app/app.module.ts
- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/view/view.component.html
- apps/catalog/catalog/src/app/marketplace/movie/view/view.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-view/wishlist-view.component.ts
- apps/catalog/marketplace/marketplace/src/app/app.module.ts
- apps/catalog/marketplace/marketplace/src/app/movie/home/home.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/search/search.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
- apps/catalog/marketplace/marketplace/src/app/movie/wishlist/wishlist-view/wishlist-view.component.ts
- libs/catalog/src/lib/components/production-informations/production-informations.component.ts
- libs/catalog/src/lib/components/promotional-elements/promotional-elements.component.html
- libs/catalog/src/lib/components/promotional-elements/promotional-elements.component.ts
- libs/catalog/src/lib/components/reserved-territories/reserved-territories.component.ts
- libs/utils/src/lib/analytics/app-analytics.ts
> Issue#1517 track clicks

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/form/promotional-description/promotional-description.component.html
- libs/movie/src/lib/movie/form/promotional-description/promotional-description.form.ts
- libs/movie/src/lib/movie/form/sales-info/format/format.component.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
- libs/movie/src/lib/movie/static-model/types.ts
Format, FormatQuality, SoundFormat
Movie review section
Box Office in budget
KeyAssets
> Update data model

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/evaluation/evaluation.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/evaluation/evaluation.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/evaluation/evaluation.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel-routing.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
- libs/movie/src/lib/movie/form/sales-info/scoring/scoring.component.html
- libs/movie/src/lib/movie/form/sales-info/scoring/scoring.component.scss
- libs/movie/src/lib/movie/form/sales-info/scoring/scoring.component.ts
- libs/movie/src/lib/movie/form/sales-info/scoring/scoring.module.ts
> evalutation page

- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/main/main.form.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
> Update data model : customGenre

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-5.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-7.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelBudgetPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelVersionInfoPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
- libs/movie/src/lib/movie/form/budget/estimated-budget/estimated-budget.component.html
- libs/movie/src/lib/movie/form/budget/estimated-budget/estimated-budget.component.ts
> Issue#1479 movie tunnel 5 spec

- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/filter.util.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/view/view.component.ts
- libs/catalog/src/lib/components/promotional-elements/promotional-elements.component.html
- libs/catalog/src/lib/components/promotional-elements/promotional-elements.component.ts
- libs/contract/src/lib/+state/contract.firestore.ts
- libs/contract/src/lib/+state/contract.model.ts
- libs/contract/src/lib/+state/contract.service.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.firestore.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.model.ts
- libs/movie/src/lib/distribution-deals/create/create.component.ts
- libs/movie/src/lib/distribution-deals/form/territory/territory.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/display/promotional-elements/promotional-elements.component.html
- libs/movie/src/lib/movie/display/promotional-elements/promotional-elements.component.ts
- libs/movie/src/lib/movie/form/main/languages/languages.component.ts
- libs/movie/src/lib/movie/form/main/origin-country/origin-country.component.ts
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.component.html
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.form.ts
- libs/movie/src/lib/movie/form/root/root.component.ts
- libs/movie/src/lib/movie/form/sales-info/original-releases/original-releases.component.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
- libs/movie/src/lib/movie/static-model/types.ts
- libs/utils/src/lib/common-interfaces/identity.ts
- libs/utils/src/lib/common-interfaces/price.ts
> promotional elements

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.module.ts
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.component.html
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.component.scss
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.component.ts
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.form.ts
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.module.ts
- libs/movie/src/lib/movie/form/form.module.ts
- libs/movie/src/lib/movie/form/main/directors/directors.component.html
- libs/movie/src/lib/movie/form/main/directors/directors.component.scss
- libs/movie/src/lib/movie/form/main/genres/genres.component.html
- libs/movie/src/lib/movie/form/main/genres/genres.component.scss
- libs/movie/src/lib/movie/form/main/languages/languages.component.html
- libs/movie/src/lib/movie/form/main/languages/languages.component.scss
- libs/movie/src/lib/movie/form/main/languages/languages.module.ts
- libs/movie/src/lib/movie/form/main/main.form.ts
- libs/movie/src/lib/movie/form/main/origin-country/origin-country.component.scss
- libs/movie/src/lib/movie/form/main/total-runtime/total-runtime.component.html
- libs/movie/src/lib/movie/form/main/total-runtime/total-runtime.component.ts
- libs/movie/src/lib/movie/form/main/total-runtime/total-runtime.module.ts
- libs/movie/src/lib/movie/form/root/root.component.html
- libs/movie/src/lib/movie/form/root/root.component.ts
- libs/movie/src/lib/movie/form/sales-info/original-releases/original-releases.component.html
- libs/movie/src/lib/movie/form/sales-info/original-releases/original-releases.component.scss
- libs/movie/src/lib/movie/form/sales-info/original-releases/original-releases.component.ts
- libs/ui/src/lib/form/display-name/display-name.component.html
- libs/ui/src/lib/form/display-name/display-name.component.scss
- styles/footer.scss
Third Generation of PR on Movie Form Main.
A Fourth is coming after update of credits
> Movie form main

- libs/catalog/src/lib/components/promotional-elements/promotional-elements.component.ts
- libs/contract/src/lib/+state/contract.model.ts
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.form.ts
> update for review comment on #1571

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/credits/credits.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/display/sales-cast/sales-cast.component.html
- libs/movie/src/lib/movie/form/root/root.component.ts
- libs/movie/src/lib/movie/form/sales-cast/sales-cast.component.ts
- libs/movie/src/lib/movie/form/sales-cast/sales-cast.form.ts
- libs/movie/src/lib/movie/static-model/staticModels.ts
- libs/movie/src/lib/movie/static-model/types.ts
- libs/utils/src/lib/common-interfaces/identity.ts
> updates on movie.salesCast section

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-4.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelCreditsPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.html
> create movie-tunnel-4 spec

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-4.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-5.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/StartTunnelPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelBudgetPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelKeywordsPage.ts
- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- libs/movie/src/lib/movie/form/budget/estimated-budget/estimated-budget.component.ts
> Fix e2e tests

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.scss
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.module.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.html
- libs/ui/src/lib/list/table-filter/table-filter.component.scss
- libs/ui/src/lib/list/table-filter/table-filter.component.ts
- libs/ui/src/lib/list/table-filter/table-filter.module.ts
- styles/components/mat-button.scss
- styles/components/mat-form-field.scss
- styles/components/mat-list.scss
- styles/components/mat-table.scss
Create a reusable table component.
Apply it on titles list.
For Title List: need data from Hugo & Yohann
> Movie selection table

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/technical-info/technical-info.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/technical-info/technical-info.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/filter.util.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/display/version-info/version-info.component.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/root/root.component.html
- libs/movie/src/lib/movie/form/sales-info/format/format.component.html
- libs/movie/src/lib/movie/form/sales-info/format/format.component.scss
- libs/movie/src/lib/movie/form/version-info/version-info.component.html
- libs/movie/src/lib/movie/form/version-info/version-info.component.scss
- libs/movie/src/lib/movie/form/version-info/version-info.component.ts
- libs/movie/src/lib/movie/form/version-info/version-info.form.ts
- libs/movie/src/lib/movie/form/version-info/version-info.module.ts
- tslint.json
> Issue 1411 part2

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/chain-of-titles/chain-of-titles.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/chain-of-titles/chain-of-titles.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/chain-of-titles/chain-of-titles.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/chain-of-titles/chain-of-titles.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel-routing.module.ts
- libs/contract/src/lib/contract/+state/contract.firestore.ts
- libs/contract/src/lib/contract/+state/contract.model.ts
- libs/contract/src/lib/contract/forms/contract.form.ts
- libs/ui/src/lib/upload/file-upload/file-upload.component.html
> Issue#1432 chain of title

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/credits/credits.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.module.ts
- apps/catalog/catalog/src/app/marketplace/movie/view/view.component.html
- libs/catalog/src/lib/components/production-informations/production-informations.component.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/components/display-film-info-card/display-film-info-card.component.ts
- libs/movie/src/lib/movie/components/import/view-extracted-elements/view-extracted-elements.component.ts
- libs/movie/src/lib/movie/display/main/main.component.html
- libs/movie/src/lib/movie/display/main/main.component.ts
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/movie/src/lib/movie/form/main/main.form.ts
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.html
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.scss
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.ts
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.module.ts
- libs/movie/src/lib/movie/form/root/root.component.ts
- libs/ui/src/lib/form/chips-autocomplete/chips-autocomplete.component.html
- libs/ui/src/lib/form/chips-autocomplete/chips-autocomplete.component.ts
- libs/ui/src/lib/form/chips-autocomplete/chips-autocomplete.module.ts
- libs/utils/src/lib/common-interfaces/identity.ts
- libs/utils/src/lib/form/forms/list.form.ts
Update stakeholder model & UI (in the form)
> Movie form stakeholder

- apps/backend-functions/src/bigQuery.ts
- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/environments/environment.ci.ts
- apps/backend-functions/src/environments/environment.prod.ts
- apps/backend-functions/src/environments/environment.staging.ts
- apps/backend-functions/src/environments/environment.ts
- apps/backend-functions/src/main.ts
- apps/catalog/catalog/src/app/app.module.ts
- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/view/view.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-view/wishlist-view.component.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/utils/src/lib/analytics/analyticsEvents.ts
- libs/utils/src/lib/analytics/app-analytics.ts
- package-lock.json
- package.json
> Issue#1518 bigquery

- .circleci/config.yml
- apps/backend-ops/src/assets/users.fixture.ts
- apps/backend-ops/src/firebaseSetup.ts
- apps/backend-ops/src/main.ts
- apps/backend-ops/src/migrations.ts
- apps/backend-ops/src/users.ts
> ci: staging deploy with migrations

- firestore.rules
Update rules to includes contracts, versions and distribution deals.
:fire: Not final rules, just a simple initialisation :fire:
> Add rules for contracts

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/title/sales/sales.component.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
> Issue#1518 bigquery service

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel-routing.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.guard.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.service.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.module.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/+state/movie.store.ts
- libs/organization/src/lib/permissions/+state/permissions.service.ts
- package-lock.json
- package.json
Create a movie when you enter the tunnel
> Movie form movieid

- apps/catalog/catalog-e2e/src/support/pages/dashboard/StartTunnelPage.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.guard.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.ts
- libs/ethers/src/lib/dao/pages/dao-admin-view/dao-admin-view.component.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/organization/src/lib/pages/member-editable/member-editable.component.ts
- libs/utils/src/lib/form/forms/entity.form.ts
- libs/utils/src/lib/form/forms/list.form.ts
- package-lock.json
- package.json
- styles/footer.scss
Save button save movie to firestore.
> Movie form save

- apps/catalog/catalog/src/app/app.module.ts
- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.guard.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.service.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/delivery/delivery/src/app/app.module.ts
- apps/main/main/src/app/app.module.ts
- apps/movie-financing/movie-financing/src/app/app.module.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/movie/src/lib/movie/guards/movie-active.guard.ts
- libs/utils/src/lib/form/forms/list.form.ts
- package-lock.json
- package.json
Sorry for the branch name, this has nothing to do with the draft.
It makes the tunnel remembers the page it cames from.
> Movie Tunnel Remember Page

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.html
- apps/catalog/catalog/src/app/dashboard/title/details/details.component.html
- apps/catalog/catalog/src/app/dashboard/title/details/details.component.scss
- apps/catalog/catalog/src/app/dashboard/title/details/details.component.ts
- apps/catalog/catalog/src/app/dashboard/title/details/details.module.ts
- apps/catalog/catalog/src/app/dashboard/title/sales/sales.component.ts
- apps/catalog/catalog/src/app/dashboard/title/view/view.component.ts
- libs/movie/src/lib/movie/form/summary/budget/budget.component.ts
- libs/movie/src/lib/movie/form/summary/country/country.component.ts
- libs/movie/src/lib/movie/form/summary/credit/credit.component.ts
- libs/movie/src/lib/movie/form/summary/evaluation/evaluation.component.ts
- libs/movie/src/lib/movie/form/summary/festival-prizes/festival-prizes.component.ts
- libs/movie/src/lib/movie/form/summary/file/file.component.ts
- libs/movie/src/lib/movie/form/summary/information/information.component.ts
- libs/movie/src/lib/movie/form/summary/main/main.component.ts
- libs/movie/src/lib/movie/form/summary/sales-cast/sales-cast.component.ts
- libs/movie/src/lib/movie/form/summary/story/story.component.ts
- libs/movie/src/lib/movie/form/summary/technical-information/technical-information.component.ts
- libs/ui/src/lib/missing-control/missing-control.component.ts
> Issue#1551 film page

- apps/main/main/src/index.html
Change the main app so that it redirects to another app depending on which domain you are visiting:
- staging.blockframes.io/
- staging.delivery.blockframes.io/delivery
- staging.archipelcontent.com/catalog
> main: redirect to sub apps

- apps/backend-functions/src/bigQuery.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
> can call analytics for an array of movieIds

- apps/backend-functions/src/bigQuery.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
> Issue#1636 sort by movie

- apps/catalog/catalog/src/app/dashboard/title/sales/sales.component.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
> update getMovieAnalytics function of movie service

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.scss
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/deal/list/list.module.ts
- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- firestore.indexes.json
- firestore.rules
- libs/contract/src/lib/contract/+state/contract.model.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/contract/src/lib/contract/list/contract-list.component.html
- libs/contract/src/lib/contract/list/contract-list.component.scss
- libs/contract/src/lib/contract/list/contract-list.component.ts
- libs/contract/src/lib/contract/list/contract-list.module.ts
- libs/contract/src/lib/version/+state/contract-version.model.ts
- libs/contract/src/lib/version/+state/contract-version.service.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.model.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
- libs/movie/src/lib/distribution-deals/guards/contracts-deal-list.guard.ts
- libs/movie/src/lib/distribution-deals/right-list/right-list.component.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/utils/src/lib/helpers.ts
- Create deal list with custom table.
- Add new rules for distributionDeals subcollections.
- Add new index for distributionDeals collectionGroup query.
> Issue#1545 deal list

- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.scss
- apps/catalog/catalog/src/app/dashboard/layout/layout.module.ts
- apps/catalog/catalog/src/app/dashboard/title/view/view.component.scss
- apps/catalog/catalog/src/app/marketplace/layout/layout.component.html
- apps/catalog/catalog/src/app/marketplace/layout/layout.component.scss
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss
- styles/components/bf-widget.scss
- styles/components/mat-list.scss
- styles/style.scss
- styles/theme.scss
- styles/themes/dark.scss
- styles/typography.scss
- styles/variables.scss
Clean up dashboard layout
improve CSS variables
Pimp app-bar color
> Catalog dashboard layout

- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.html
> marketplace homepage - routerLink updates

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/previous-deals/previous-deals.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/previous-deals/previous-deals.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/previous-deals/previous-deals.component.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/contract/src/lib/contract/forms/contract.form.ts
- libs/contract/src/lib/contract/forms/party-name/party-name.component.html
- libs/contract/src/lib/contract/forms/party-name/party-name.component.scss
- libs/contract/src/lib/contract/forms/party-name/party-name.component.ts
- libs/contract/src/lib/contract/forms/party-name/party-name.module.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
- libs/movie/src/lib/distribution-deals/form/distribution-deal.form.ts
- libs/movie/src/lib/distribution-deals/form/languages/languages.component.ts
- libs/movie/src/lib/distribution-deals/form/terms/terms.component.ts
- libs/movie/src/lib/distribution-deals/form/terms/terms.form.ts
- libs/utils/src/lib/form/forms/list.form.ts
close #1419 
fetching and altering the contracts coming from the DB.
> Issue 1419 page 9

- apps/catalog/catalog/src/app/dashboard/title/view/view.component.html
- apps/catalog/catalog/src/app/dashboard/title/view/view.component.ts
- libs/movie/src/lib/distribution-deals/selection-map/selection-map.component.html
- libs/movie/src/lib/distribution-deals/selection-map/selection-map.component.scss
- libs/movie/src/lib/distribution-deals/selection-map/selection-map.component.ts
- libs/movie/src/lib/distribution-deals/selection-map/selection-map.module.ts
- libs/ui/src/lib/map/index.ts
- libs/ui/src/lib/map/map.component.html
- libs/ui/src/lib/map/map.component.ts
- libs/ui/src/lib/map/map.module.ts
World Map is a reusable component with structural directives
> Catalog map

- apps/catalog/catalog/src/app/catalog.module.ts
- apps/catalog/catalog/src/app/guards/catalog-app.guard.ts
- libs/organization/src/lib/+state/organization.firestore.ts
- libs/organization/src/lib/guard/no-organization.guard.ts
- libs/organization/src/lib/no-organization.module.ts
- libs/organization/src/lib/pages/organization-app-access/organization-app-access.component.html
- libs/organization/src/lib/pages/organization-app-access/organization-app-access.component.scss
- libs/organization/src/lib/pages/organization-app-access/organization-app-access.component.ts
- libs/organization/src/lib/pages/organization-create/organization-create.component.ts
> Issue#1718 app access

- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.scss
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.ts
- apps/catalog/catalog/src/app/dashboard/layout/layout.module.ts
- apps/catalog/catalog/src/app/dashboard/pages/search/search.component.html
- apps/catalog/catalog/src/app/dashboard/pages/search/search.component.ts
- apps/catalog/catalog/src/app/dashboard/pages/search/search.module.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/layout/layout.component.scss
- libs/material/src/lib/template/pages/template-list/template-list.component.html
- libs/material/src/lib/template/pages/template-list/template-list.component.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.html
- libs/ui/src/lib/list/table-filter/table-filter.component.ts
- libs/ui/src/lib/search-widget/search-widget.component.html
- libs/ui/src/lib/search-widget/search-widget.component.ts
- libs/ui/src/lib/search-widget/search-widget.module.ts
close #1548 
improved also the bf-table component, so there is one less input
> Issue 1548 search

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.ts
- apps/catalog/catalog/src/app/dashboard/title/details/details.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/contract/src/lib/contract/tunnel/index.ts
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.html
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.scss
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.ts
- libs/contract/src/lib/contract/tunnel/lobby/lobby.module.ts
- libs/ui/src/lib/tunnel/tunnel.service.ts
Change the routes for the tunnel
> Reorganize pages for the tunnel in dashboard

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-1.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-4.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-5.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-7.spec.ts
- apps/catalog/catalog-e2e/src/integration/marketplace/create-wishlist.spec.ts
- apps/catalog/catalog-e2e/src/integration/marketplace/send-an-offer.spec.ts
(took the time to clean the code at the same time)
> e2e: skip failing test, at least the ci goes green

- libs/organization/src/lib/components/member-repertory/member-repertory.component.html
- libs/organization/src/lib/components/member-repertory/member-repertory.component.ts
- libs/organization/src/lib/member/+state/member.service.ts
- libs/organization/src/lib/pages/member-editable/member-editable.component.ts
> Issue#1719 fix

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.html
- libs/ui/src/lib/tunnel/exit/exit.component.html
- libs/ui/src/lib/tunnel/exit/exit.component.ts
- libs/ui/src/lib/tunnel/exit/exit.module.ts
- libs/ui/src/lib/tunnel/index.ts
- libs/ui/src/lib/tunnel/layout/layout.component.html
- libs/ui/src/lib/tunnel/layout/layout.component.scss
- libs/ui/src/lib/tunnel/layout/layout.component.ts
- libs/ui/src/lib/tunnel/layout/layout.module.ts
- libs/ui/src/lib/tunnel/layout/nav/nav.component.html
- libs/ui/src/lib/tunnel/layout/nav/nav.component.ts
- libs/ui/src/lib/tunnel/layout/step-stat/step-stat.component.html
- libs/ui/src/lib/tunnel/layout/step-stat/step-stat.component.ts
Make sub components for the layout of the tunnel
> Improve structural tunnel

- apps/backend-functions/src/bigQuery.ts
> fix bigquery when called with empty array

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/main/main.component.html
- apps/catalog/catalog/src/app/dashboard/pages/home/home.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/filter.util.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.form.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.module.ts
- libs/movie/src/lib/movie/form/main/genres/genres.component.html
- libs/movie/src/lib/movie/form/main/genres/genres.component.scss
- libs/movie/src/lib/movie/form/main/genres/genres.component.ts
- libs/movie/src/lib/movie/form/main/genres/genres.module.ts
- libs/movie/src/lib/movie/form/main/main.form.ts
- libs/movie/src/lib/movie/form/summary/country/country.component.html
- libs/movie/src/lib/movie/form/summary/credit/credit.component.html
- libs/movie/src/lib/movie/form/summary/evaluation/evaluation.component.html
- libs/movie/src/lib/movie/form/summary/information/information.component.html
- libs/movie/src/lib/movie/form/summary/information/information.component.ts
- libs/movie/src/lib/movie/form/summary/main/main.component.html
- libs/movie/src/lib/movie/form/summary/technical-information/technical-information.component.html
- libs/ui/src/lib/missing-control/missing-control.component.html
- libs/ui/src/lib/missing-control/missing-control.component.ts
- libs/utils/src/lib/form/forms/static-value.form.ts
- libs/utils/src/lib/form/validators/validators.ts
> Reusable genre form

- apps/catalog/catalog/src/app/marketplace/title/main/main.component.html
- apps/catalog/catalog/src/app/marketplace/title/main/main.component.scss
- apps/catalog/catalog/src/app/marketplace/title/main/main.component.ts
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.scss
- libs/ui/src/lib/movie-card/movie-card.component.ts
fix images & refactor promo links
> update promo link

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/evaluation/evaluation.component.html
- libs/movie/src/lib/movie/form/sales-info/scoring/scoring.component.html
- libs/ui/src/lib/tunnel/page/page.component.html
> evaluation component

- libs/utils/src/lib/common-interfaces/utility.ts
> feat-1838 - add holdername on bank account interface

- libs/contract/src/lib/contract/form/contract.form.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel-routing.module.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.html
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.ts
Solve the issue with the preivous/next button
> Update the paths for sale & mandate

- apps/catalog/catalog/src/app/marketplace/movie/search/filter.util.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.scss
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.form.ts
- libs/movie/src/lib/movie/form/budget/budget.form.ts
- libs/movie/src/lib/movie/form/budget/estimated-budget/estimated-budget.component.ts
> Issue#1742 filters

- libs/auth/src/lib/pages/login/login.component.ts
> LoginComponent

- libs/movie/src/lib/movie/components/movie-analytics-chart/default-chart-options.ts
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.html
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
> issue#1864 update stats

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- libs/account/src/lib/profile/profile-widget/profile-widget.component.html
- libs/account/src/lib/profile/profile-widget/profile-widget.component.scss
- libs/account/src/lib/profile/profile-widget/profile-widget.module.ts
- libs/ui/src/lib/search-widget/search-widget.component.html
> Issue#1858 dashboard

- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.html
- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.scss
- apps/catalog/catalog/src/app/marketplace/movie/home/home.component.ts
- styles/style.scss
- styles/themes/light.scss
> Issue#1857 update marketplace home

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/previous-deals/previous-deals.component.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/contract/src/lib/contract/form/contract.form.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/contract/src/lib/contract/tunnel/details-sale/details-sale.component.ts
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.ts
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.html
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.ts
- libs/contract/src/lib/version/form/version.form.ts
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.html
- libs/movie/src/lib/distribution-deals/form/distribution-deal.form.ts
- libs/utils/src/lib/form/forms/list.form.ts
- package-lock.json
- package.json
You can add/remove title/deal on the tunnel and save it.
> Implement Local state for the tunnel

- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/contract/src/lib/contract/tunnel/summary-mandate/summary-mandate.component.html
- libs/contract/src/lib/contract/tunnel/summary-mandate/summary-mandate.component.ts
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.html
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.ts
- libs/contract/src/lib/version/+state/contract-version.service.ts
- libs/utils/src/lib/form/forms/entity.form.ts
> Implements submit contract

- libs/contract/src/lib/version/form/price/price.component.ts
> removed suscription

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.html
- apps/catalog/catalog/src/app/dashboard/title/details/details.component.html
- libs/movie/src/lib/movie/form/summary/country/country.component.html
- libs/movie/src/lib/movie/form/summary/country/country.component.ts
- libs/movie/src/lib/movie/form/summary/credit/credit.component.html
> add stakeholders to summary page

- libs/ui/src/lib/overlay-widget/overlay-widget.directive.ts
- libs/ui/src/lib/overlay-widget/overlay-widget.module.ts
> added mouseover

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.scss
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.module.ts
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.html
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.scss
- libs/catalog/src/lib/filter.util.ts
- libs/movie/src/lib/movie/form/main/genres/genres.component.html
- libs/ui/src/lib/search-widget/search-widget.component.ts
> Fix filters

- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.scss
- apps/catalog/catalog/src/app/marketplace/layout/layout.component.html
- apps/catalog/catalog/src/app/marketplace/layout/layout.component.scss
> Remove searchbar

- libs/organization/src/lib/components/member-add/member-add.component.html
- libs/organization/src/lib/components/member-add/member-add.component.scss
- libs/organization/src/lib/components/member-repertory/member-repertory.component.html
- libs/organization/src/lib/components/member-repertory/member-repertory.component.scss
- libs/organization/src/lib/pages/member-editable/member-editable.component.scss
> Issue#1921 members

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
> some text changes

- apps/catalog/catalog/src/app/dashboard/pages/home/home.component.html
- apps/catalog/catalog/src/app/dashboard/pages/home/home.component.ts
- apps/catalog/catalog/src/app/dashboard/title/sales/sales.component.html
- apps/catalog/catalog/src/app/dashboard/title/sales/sales.component.scss
- apps/catalog/catalog/src/app/dashboard/title/sales/sales.component.ts
- apps/catalog/catalog/src/app/dashboard/title/view/view.module.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
> sales revenu in sales

- apps/catalog/catalog/src/app/marketplace/layout/layout.component.html
> issue#1929_update_marketplace_layout

- libs/contract/src/lib/contract/list/contract-list.component.html
- libs/contract/src/lib/contract/list/contract-list.component.scss
- libs/ui/src/lib/overlay-widget/overlay-widget.directive.ts
> put widgetTooptip on territories

- libs/contract/src/lib/contract/form/party/party.component.html
- libs/contract/src/lib/contract/form/party/party.component.scss
- libs/contract/src/lib/contract/form/party/party.module.ts
- libs/contract/src/lib/version/form/payment-schedule/payment-schedule.component.ts
close #1801 
- this PR includes contract tunnel page MANDATE
> Issue 1801 part5

- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.html
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-current-repertory/wishlist-current-repertory.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-view/wishlist-view.component.html
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-view/wishlist-view.component.scss
- apps/catalog/catalog/src/app/marketplace/movie/wishlist/wishlist-view/wishlist-view.component.ts
> Issue#1933 wishlist

- libs/organization/src/lib/components/member-add/member-add.component.html
- libs/organization/src/lib/components/member-pending/member-pending.component.html
- libs/organization/src/lib/components/member-request/member-request.component.html
- libs/organization/src/lib/components/member-request/member-request.component.scss
> fix buttons, text on members

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.scss
- libs/movie/src/lib/movie/components/display-list/display-list.component.html
- libs/ui/src/lib/movie-card/movie-card.component.html
- libs/ui/src/lib/movie-card/movie-card.component.scss
- libs/ui/src/lib/movie-card/movie-card.module.ts
> resize movie-card

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.scss
> fix background-color tabs of titles page

- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.scss
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/deal/list/list.module.ts
- apps/catalog/catalog/src/app/marketplace/marketplace.module.ts
- libs/contract/src/lib/contract/+state/contract.model.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/contract/src/lib/contract/guards/organization-contract-list.guard.ts
- libs/contract/src/lib/contract/list/contract-list.component.html
- libs/contract/src/lib/contract/list/contract-list.component.ts
- libs/contract/src/lib/version/+state/contract-version.model.ts
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.html
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.scss
- libs/movie/src/lib/distribution-deals/guards/contracts-deal-list.guard.ts
- libs/movie/src/lib/movie/guards/movie-organization-list.guard.ts
Create marketplace deal list
Update dashboard deal list a little
> Marketplace deal list

- libs/account/src/lib/profile/pages/view/view.component.html
- libs/account/src/lib/profile/pages/view/view.component.ts
- libs/organization/src/lib/pages/view/view.component.html
- libs/organization/src/lib/pages/view/view.component.ts
> org and profile view fixes

- libs/auth/src/lib/pages/identity/identity.component.ts
> accept org invitation on submit of identity form

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/marketplace/marketplace.module.ts
- libs/notification/src/lib/notification/activity-feed/activity-feed.module.ts
- libs/notification/src/lib/notification/notification-widget/notification-widget.component.html
> Issue#1919 update notification widget

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/deal/list/list.module.ts
- apps/catalog/catalog/src/app/dashboard/title/avails/avails.component.html
- apps/catalog/catalog/src/app/dashboard/title/avails/avails.module.ts
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/deal/list/list.module.ts
- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.ts
- libs/contract/src/lib/contract/+state/contract.query.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/contract/src/lib/contract/+state/contract.utils.ts
- libs/contract/src/lib/contract/components/index.ts
- libs/contract/src/lib/contract/components/table/table.component.html
- libs/contract/src/lib/contract/components/table/table.component.ts
- libs/contract/src/lib/contract/components/table/table.module.ts
- libs/contract/src/lib/contract/guards/organization-contract-list.guard.ts
- libs/contract/src/lib/contract/list/contract-list.component.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.query.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
- libs/movie/src/lib/distribution-deals/guards/contracts-deal-list.guard.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.html
- libs/ui/src/lib/list/table-filter/table-filter.component.scss
- libs/ui/src/lib/list/table-filter/table-filter.component.ts
- styles/components/bf-table.scss
- styles/theme.scss
fix #1910 
Update the deal list
Create contract-table shared by dashboard & marketplace.
Use bf-table for contract-table
Create output "rowClick" on bf-table.
Try to update the style, but failed =="
> Dashboard deal list

- .circleci/config.yml
- .firebaserc
- firebase.json
(redoing in another branch so it quick build)
> ops: next mode

- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.html
- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.scss
- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.ts
- apps/catalog/catalog/src/app/dashboard/deal/view/view.module.ts
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.ts
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.html
> Issue#1914 deal view fix

- firestore.rules
> Redefine contract read rule

- apps/catalog/catalog/src/app/dashboard/title/view/view.component.ts
- apps/catalog/catalog/src/app/dashboard/title/view/view.module.ts
Remove sales tab from title view
Remove the route to sales component in TitleViewModule
> Remove Sales tab and route on title view

- libs/utils/src/lib/sentry.module.ts
> remove sentry popup

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/movie/src/lib/movie/form/budget/budget.form.ts
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.form.ts
Improve update of contract
Remove broken urlValidaor
Add redirect after submitted on movie form
> Make the tunnel beautiful again

- libs/auth/src/lib/components/signin-form/signin-form.component.html
- libs/auth/src/lib/components/signin-form/signin-form.component.scss
- libs/auth/src/lib/components/signin-form/signin-form.module.ts
- libs/auth/src/lib/components/signup-form/signup-form.component.html
- libs/auth/src/lib/components/signup-form/signup-form.component.scss
- libs/auth/src/lib/components/signup-form/signup-form.module.ts
- libs/auth/src/lib/pages/login/login.component.html
- libs/auth/src/lib/pages/login/login.component.scss
> fix Forgot password button

- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/movie.ts
- libs/notification/src/lib/notification/+state/notification.firestore.ts
- libs/notification/src/lib/notification/+state/notification.query.ts
- libs/notification/src/lib/notification/notification-list/notification-list.component.html
- libs/notification/src/lib/notification/notification-list/notification-list.component.scss
- libs/notification/src/lib/notification/notification-list/notification-list.component.ts
Add new notifications for movies (when submitted to and accepted by Archipel Content)
> Issue#1987 movie notifications

- libs/contract/src/lib/contract/tunnel/deal/deal.component.html
cleaner way of handeling the context of of ngTemplateOutletContext. Now it is like in the angular docs
> improved ngcontext

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- apps/catalog/catalog/src/app/marketplace/title/avails/territories-filter.ts
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.html
- libs/catalog/src/lib/filter.util.ts
- libs/catalog/src/lib/form/search.form.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
- libs/movie/src/lib/distribution-deals/create/availabilities.util.ts
- libs/notification/src/lib/notification/notification-list/notification-list.component.html
- libs/notification/src/lib/notification/notification-list/notification-list.component.scss
- libs/notification/src/lib/notification/notification-widget/notification-widget.component.scss
Rename Avails Search Form fields to match Distribution Deal fields.
Update notification overlay design.
fix #2033
> Issue#2033 avails search form fields

- libs/notification/src/lib/notification/+state/notification.query.ts
- libs/notification/src/lib/notification/notification-list/notification-list.component.ts
Fix notification path and update the way we define it
> Change the way we handle path in notifications

- libs/contract/src/lib/version/form/payment-schedule/payment-schedule.component.html
- libs/contract/src/lib/version/form/payment-schedule/payment-schedule.component.ts
> added payment term after event

- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
> Update the centralOrgId to match Archipel Content Organization Id

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
> added title as default sort option

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-1.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/StartTunnelPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/NavbarPage.ts
> fix e2e movie tunnel 1

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-4.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelCreditsPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/NavbarPage.ts
- apps/catalog/catalog-e2e/src/support/utils/users.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/credits/credits.component.html
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.html
- libs/ui/src/lib/form/display-name/display-name.component.html
> E2e tunnel 4

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-5.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelBudgetPage.ts
- libs/movie/src/lib/movie/form/budget/box-office/box-office.component.html
- libs/movie/src/lib/movie/form/review/review.component.html
- libs/movie/src/lib/movie/form/sales-info/ratings/ratings.component.html
> fix and finish movie-tunnel 5 e2e test

- libs/notification/src/lib/notification/activity-feed/activity-feed.component.html
- libs/notification/src/lib/notification/activity-feed/activity-feed.component.ts
- libs/notification/src/lib/notification/activity-feed/activity-feed.module.ts
- libs/notification/src/lib/notification/no-activity-feed/no-activity-feed.component.html
- libs/notification/src/lib/notification/no-activity-feed/no-activity-feed.component.scss
- libs/notification/src/lib/notification/no-activity-feed/no-activity-feed.component.ts
- libs/notification/src/lib/notification/no-activity-feed/no-activity-feed.module.ts
Add specific page when there is no notification in activity feed page.
Add count for each notification tabs.
close #2064
> Add a specific empty page when there is no notification

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-2.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelMainPage.ts
- libs/movie/src/lib/movie/form/festival-prizes/festival-prizes.component.html
- libs/movie/src/lib/movie/form/main/content-type/content-type.component.html
- libs/movie/src/lib/movie/form/sales-info/original-releases/original-releases.component.html
- package-lock.json
- package.json
> E2e movie tunnel 2

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-13.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelSummaryPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelValuationPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
> create movie tunnel 13 spec

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-5.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-6.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelBudgetPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelTechnicalInfoPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelVersionInfoPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
- libs/movie/src/lib/movie/form/sales-info/format/format.component.html
> E2e tunnel 6

- apps/catalog/catalog/src/app/app.module.ts
- apps/delivery/delivery/src/app/app.module.ts
- apps/main/main/src/app/app.module.ts
- libs/movie/src/lib/movie/movie.module.ts
> import firebase/storage

- apps/catalog/catalog-e2e/cypress.json
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-1.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-11.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-13.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-2.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-3.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-4.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-5.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-6.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesListPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelChainOfTitlesPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelFilesPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelMainPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
- apps/catalog/catalog-e2e/src/support/utils/utils.ts
> login and navigate to Tunnel Main before each e2e test

- apps/backend-ops/src/assets/users.fixture.ts
> with ci and berlin anon users

- .circleci/config.yml
- .firebaserc
- firebase.json
> With storybooks

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- libs/contract/src/lib/contract/components/table/table.component.ts
If movie configStore status is draft, go to tunnel, every other statuses lead to title page.
close #2058
> Define specific link to tunnel or view

- styles/components/mat-button.scss
- styles/components/mat-icon.scss
Add "path" as a target for the icons color
> Solve issue with icon color

- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.ts
> Review Cart page

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-11.spec.ts
- apps/catalog/catalog-e2e/src/plugins/index.js
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesListPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelFilesPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelMainPage.ts
- apps/catalog/catalog-e2e/src/support/utils/utils.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-file/media-file.component.html
> implements e2e test file upload

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-12.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelChainOfTitlesPage.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/chain-of-titles/chain-of-titles.component.html
> E2e tunnel 12

- .github/ISSUE_TEMPLATE/component.md
Create a template for issues that describe how to create a component.
> Add component template issue

- apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
- styles/components/mat-list.scss
- styles/themes/dark.scss
Movie avails page, wording and color and size of the ink-bar of the tab.
Fix #2008
> Design review 2008

- apps/backend-functions/src/notification.ts
- libs/notification/src/lib/notification/+state/notification.firestore.ts
- package-lock.json
- package.json
> correct timestamp type in notications

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.scss
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.html
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.scss
- libs/movie/src/lib/movie/components/display-list/display-list.component.scss
- libs/movie/src/lib/movie/form/main/genres/genres.component.html
- libs/movie/src/lib/movie/form/main/genres/genres.component.scss
- libs/movie/src/lib/movie/form/promotional-description/keywords/keywords.component.html
- libs/ui/src/lib/form/chips-autocomplete/chips-autocomplete.component.html
- libs/ui/src/lib/form/chips-autocomplete/chips-autocomplete.component.ts
- libs/ui/src/lib/movie-card/movie-card.component.html
- styles/components/mat-chips.scss
- styles/themes/dark.scss
- styles/themes/light.scss
> Design review #2002

- apps/catalog/catalog/src/app/marketplace/layout/layout.component.ts
- libs/account/src/lib/profile/profile-widget/profile-widget.component.ts
- libs/auth/src/lib/+state/auth.service.ts
> added akita ng fire hook when logging out

- apps/catalog/catalog-e2e/src/integration/dashboard/contract-tunnel.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelContractLobby.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelContractPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelContractSummaryPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.html
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.html
- libs/contract/src/lib/version/form/payment-schedule/payment-schedule.component.html
- libs/contract/src/lib/version/form/price/price.component.html
- libs/movie/src/lib/distribution-deals/form/terms/terms.component.html
> Issue#2114 e2e contract

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.html
- libs/catalog/src/lib/components/avails-filter/avails-filter.component.ts
close #2059
I also added chips autocompletion to this form
> added month only and chips auto completion

- apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
- libs/organization/src/lib/forms/organization-form/organization-form.component.html
- libs/organization/src/lib/pages/organization/organization.component.scss
- libs/organization/src/lib/pages/view/view.component.scss
- styles/components/bf-table.scss
- styles/components/mat-card.scss
- styles/components/mat-form-field.scss
- styles/components/mat-snack-bar.scss
- styles/theme.scss
Fix #2014  and #2023 
Design review of the snack-bar and the organization page
> Design review 2014-2023

- apps/catalog/catalog/src/app/marketplace/layout/layout.component.ts
- libs/movie/src/lib/movie/form/sales-info/original-releases/original-releases.component.ts
> added conditional unsubscribe to layout component

- apps/backend-ops/src/users.ts
- package-lock.json
- package.json
> make e2e pass

- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.ts
- apps/catalog/catalog/src/app/landing/components/view-marketplace/view-marketplace.component.html
- apps/catalog/catalog/src/app/landing/components/view-marketplace/view-marketplace.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- libs/ui/src/lib/tunnel/layout/layout.component.html
- libs/ui/src/lib/tunnel/layout/layout.component.ts
- libs/utils/src/index.ts
- libs/utils/src/lib/breakpoint/breakpoints.service.ts
> Issue#1935 service

- libs/organization/src/lib/forms/organization-form/organization-form.component.html
- libs/organization/src/lib/forms/organization-form/organization-form.component.ts
- libs/organization/src/lib/forms/organization.form.ts
- libs/organization/src/lib/pages/organization-create/organization-create.component.ts
- libs/organization/src/lib/pages/organization-editable/organization-editable.component.ts
- libs/organization/src/lib/pages/organization/organization.component.ts
- libs/organization/src/lib/pages/view/view.component.ts
- libs/utils/src/lib/form/validators/validators.ts
disable browser autocomplegte with input attribute autocomplete="off"
autocomplete has no effect on it
close #1876
> added org name validator in the component

- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.module.ts
- libs/movie/src/lib/movie/components/banner/banner.component.html
- libs/movie/src/lib/movie/components/banner/banner.component.scss
> issue#2011 design review cart

- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.component.scss
- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.component.ts
- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.module.ts
- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.html
- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.scss
- apps/catalog/catalog/src/app/dashboard/deal/view/view.component.ts
- apps/catalog/catalog/src/app/dashboard/deal/view/view.module.ts
- apps/catalog/catalog/src/app/marketplace/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/marketplace/deal/view/view.component.ts
- apps/catalog/catalog/src/app/marketplace/deal/view/view.module.ts
- apps/catalog/catalog/tslint.json
- libs/contract/src/lib/contract/+state/contract.query.ts
- libs/utils/src/lib/pipes/display-name.module.ts
- libs/utils/src/lib/pipes/display-name.pipe.ts
- libs/utils/src/lib/pipes/index.ts
Add some useful functions in contract query.
Update dashboard contract view to have the same architecture as contract view from marketplace.
close #1951
> Issue#1951

- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/marketplace/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.html
- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.ts
- libs/contract/src/lib/contract/tunnel/summary-mandate/summary-mandate.component.html
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.html
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.html
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.ts
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.module.ts
- libs/ui/src/lib/list/table-filter/table-filter.component.scss
Update Right List with bf-table.
#1744
> Update right-list component with reusable bf-table

- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.scss
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.scss
- libs/contract/src/lib/contract/components/table/table.component.scss
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.html
- libs/ui/src/lib/list/table-filter/table-filter.component.html
- libs/ui/src/lib/list/table-filter/table-filter.component.scss
- libs/ui/src/lib/list/table-filter/table-filter.module.ts
- libs/utils/src/lib/algolia-autocomplete/algolia-autocomplete.component.ts
- styles/components/bf-table.scss
- styles/components/mat-list.scss
- styles/components/mat-sidenav.scss
Review of the dashboard "offers and deals page" and sidenav menu
Fix #2020 and fix #2024
> Design review dashboard

- apps/catalog/catalog/src/app/dashboard/pages/home/home.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.query.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/+state/movie.store.ts
> Issue#2111 analytics

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/deal/list/list.module.ts
- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/deal/list/list.module.ts
- apps/catalog/catalog/src/app/marketplace/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/marketplace/marketplace.module.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/contract/src/lib/contract/guards/active-contract.guard.ts
- libs/contract/src/lib/contract/guards/movie-contract-list.guard.ts
- libs/contract/src/lib/contract/guards/organization-contract-list.guard.ts
- libs/movie/src/lib/distribution-deals/+state/distribution-deal.service.ts
- libs/movie/src/lib/distribution-deals/components/right-list/right-list.component.ts
- libs/movie/src/lib/distribution-deals/guards/contracts-deal-list.guard.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/guards/movie-collection.guard.ts
- libs/movie/src/lib/movie/guards/movie-contract.guard.ts
- libs/movie/src/lib/movie/guards/movie-organization-list.guard.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/organization/src/lib/member/+state/member.service.ts
- libs/organization/src/lib/member/guard/member.guard.ts
- libs/organization/src/lib/pages/organization-app-access/organization-app-access.component.ts
- Move all data queries from services to guards
- Small fix on right-list date format
> Issue#1974

- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
> clean code on movie-analytics-chart

- libs/ui/src/lib/overlay-widget/overlay-widget.component.ts
- libs/ui/src/lib/overlay-widget/overlay-widget.directive.ts
> Issue#1958 tooltip

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/title/main/main.component.html
- apps/catalog/catalog/src/app/marketplace/title/main/main.component.ts
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.html
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
- libs/contract/src/lib/contract/tunnel/summary-mandate/summary-mandate.component.html
- libs/contract/src/lib/contract/tunnel/summary-sale/summary-sale.component.html
- libs/movie/src/lib/movie/form/main/total-runtime/total-runtime.component.html
- libs/movie/src/lib/movie/form/main/total-runtime/total-runtime.component.ts
- libs/organization/src/lib/forms/organization-form/organization-form.component.html
- Fix some typos
- Avoid displaying section titles without content
- Avoid negative or demical values in total runtime inputs
close #2204
close #2202
close #2201
close #2200
close #2205
> Issues#2204 #2202 #2201 #2200 #2205

- libs/movie/src/lib/movie/form/main/main.form.ts
- libs/movie/src/lib/movie/form/main/total-runtime/total-runtime.component.html
Using validator instead of html trick to avoid negative values on input.
> Use form validator for better user experience

- apps/catalog/catalog/src/app/marketplace/title/avails/avails.component.html
- styles/components/bf-world-map.scss
- styles/theme.scss
Prepared bf-world-map.component.scss for new colors
Fix #1975 
Fix #1973
> World-map rework

- apps/catalog/catalog/src/app/catalog.module.ts
- apps/catalog/catalog/src/app/guards/user-redirection.guard.ts
- libs/auth/src/index.ts
- libs/auth/src/lib/guard/user-redirection.guard.ts
- libs/organization/src/lib/+state/organization.service.ts
- libs/utils/src/lib/routes/create-routes.ts
Create specific guard to redirect users out of landing page when needed.
close #2236
> Landing page redirection guard

- apps/catalog/catalog/src/app/landing/components/learn-more/learn-more.component.html
- apps/catalog/catalog/src/app/landing/components/learn-more/learn-more.component.ts
- apps/catalog/catalog/src/app/landing/landing.module.ts
- libs/ui/src/lib/tel-input/index.ts
- libs/ui/src/lib/tel-input/tel-input.component.html
- libs/ui/src/lib/tel-input/tel-input.component.scss
- libs/ui/src/lib/tel-input/tel-input.component.ts
- libs/ui/src/lib/tel-input/tel-input.module.ts
- libs/ui/src/lib/tel-input/tel-input.stories.ts
> added tel input component

- apps/festival/festival/src/app/marketplace/marketplace.component.html
- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- apps/festival/festival/src/app/marketplace/organization/list/list.component.html
- apps/festival/festival/src/app/marketplace/organization/list/list.component.scss
- apps/festival/festival/src/app/marketplace/organization/list/list.component.ts
- apps/festival/festival/src/app/marketplace/organization/list/list.module.ts
- apps/festival/festival/src/app/marketplace/organization/members/members.component.html
- apps/festival/festival/src/app/marketplace/organization/members/members.component.ts
- apps/festival/festival/src/app/marketplace/organization/members/members.module.ts
- apps/festival/festival/src/app/marketplace/organization/titles/titles.component.html
- apps/festival/festival/src/app/marketplace/organization/titles/titles.component.scss
- apps/festival/festival/src/app/marketplace/organization/titles/titles.component.ts
- apps/festival/festival/src/app/marketplace/organization/titles/titles.module.ts
- apps/festival/festival/src/app/marketplace/organization/view/view.component.html
- apps/festival/festival/src/app/marketplace/organization/view/view.component.ts
- apps/festival/festival/src/app/marketplace/organization/view/view.module.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list/list.module.ts
- libs/organization/src/lib/layout/view/view.component.html
- libs/organization/src/lib/layout/view/view.component.scss
- libs/organization/src/lib/layout/view/view.component.ts
- libs/organization/src/lib/layout/view/view.module.ts
Created the pages for the organization in marketplace.
Will wait for Clélia's PR for make the "members" query
> [Festival] Marketplace Organization Pages

- apps/backend-functions/src/assets/mail-templates.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/users.ts
- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- apps/catalog/catalog/src/app/dashboard/pages/contact-page/contact-page.component.html
- apps/catalog/catalog/src/app/dashboard/pages/contact-page/contact-page.component.scss
- apps/catalog/catalog/src/app/dashboard/pages/contact-page/contact-page.component.ts
- apps/catalog/catalog/src/app/dashboard/pages/contact-page/contact.module.ts
- apps/catalog/catalog/src/index.html
- package.json
Contact page for dashboard
Implementing google map for the view and try to develop function to send email from user to blockframes admin with sendgrid
> Contact page

- apps/catalog/catalog/src/app/dashboard/layout/layout.component.html
- libs/ui/src/lib/algolia-autocomplete/algolia-autocomplete.component.html
- libs/ui/src/lib/algolia-autocomplete/algolia-autocomplete.component.scss
- libs/ui/src/lib/algolia-autocomplete/algolia-autocomplete.component.ts
- libs/ui/src/lib/algolia-autocomplete/algolia-autocomplete.module.ts
- libs/ui/src/lib/algolia-autocomplete/algolia-autocomplete.stories.ts
- libs/ui/src/lib/static-autocomplete/input/input-autocomplete.component.ts
- libs/ui/src/lib/static-autocomplete/input/input-autocomplete.stories.ts
- styles/components/mat-native-control.scss
- styles/theme.scss
> Issue 2225

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-send.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesActivityPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesDetailsPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesListPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelCreditsPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelSummaryPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/index.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.html
> create movie send spec

- apps/festival/festival/src/app/dashboard/dashboard.component.html
- apps/festival/festival/src/app/dashboard/dashboard.component.ts
- apps/festival/festival/src/app/dashboard/dashboard.module.ts
- libs/organization/src/lib/pages/organization-find/organization-find.component.html
- package-lock.json
> added autocomplete

- apps/festival/festival/src/app/app.component.ts
- apps/festival/festival/src/app/marketplace/organization/list/list.component.html
- apps/festival/festival/src/app/marketplace/organization/list/list.component.scss
- apps/festival/festival/src/app/marketplace/organization/members/members.component.html
- apps/festival/festival/src/app/marketplace/organization/members/members.component.scss
- apps/festival/festival/src/app/marketplace/organization/members/members.component.ts
- apps/festival/festival/src/app/marketplace/organization/members/members.module.ts
- apps/festival/festival/src/app/marketplace/organization/titles/titles.component.html
- apps/festival/festival/src/app/marketplace/organization/titles/titles.component.scss
- apps/festival/festival/src/app/marketplace/organization/titles/titles.module.ts
- libs/account/src/lib/profile/components/card/card.component.html
- libs/account/src/lib/profile/components/card/card.component.scss
- libs/account/src/lib/profile/components/card/card.component.ts
- libs/account/src/lib/profile/components/card/card.module.ts
- libs/account/tslint.json
- libs/auth/src/lib/+state/auth.service.ts
- libs/organization/src/lib/layout/view/view.component.html
- libs/organization/src/lib/layout/view/view.component.scss
- libs/ui/src/lib/movie-card/movie-card.component.html
- libs/ui/src/lib/movie-card/movie-card.component.ts
- package-lock.json
- package.json
- styles/components/mat-card.scss
Create User card under the "account" library
Update akita-ng-fire
Update auth service to match new version of akita-ng-fire
> Create user card + update auth service

- apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
- apps/catalog/catalog-e2e/src/integration/landing/organization-creation.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/auth/LoginViewPage.ts
- apps/catalog/catalog-e2e/src/support/pages/landing/LandingPage.ts
- apps/catalog/catalog-e2e/src/support/pages/organization/OrganizationHomePage.ts
- apps/catalog/catalog-e2e/src/support/utils/utils.ts
- apps/catalog/catalog/src/app/landing/components/toolbar/toolbar.component.html
- apps/catalog/catalog/src/app/landing/components/view-marketplace/view-marketplace.component.ts
- libs/organization/src/lib/pages/organization-home/organization-home.component.html
- Create-user tests was wrongly rewritten : update it to an older state.
- Update `clearDataAndPrepareTest()` to clear `indexedDB` databases before tests.
- Fix `Error: unsafe value used in a resource URL context` on landing page.
- Update organization creation test to pass (with new users and shorter test).
close #2235
> Issue#2235

- apps/catalog/catalog-e2e/src/integration/dashboard/contract-tunnel.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-end.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesListPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelContractPage.ts
- libs/contract/src/lib/contract/form/party/party.component.html
- libs/contract/src/lib/contract/form/party/party.component.ts
- libs/ui/src/lib/algolia-autocomplete/algolia-autocomplete.component.ts
> Fix tunnel e2e tests

- apps/backend-functions/src/bigQuery.ts
> fix bigquery query

- .circleci/config.yml
> run release branch e2e test in staging env

- .circleci/config.yml
> fix regex to take all release branches in yml

- apps/backend-ops/src/assets/users.fixture.ts
- apps/catalog/catalog-e2e/src/support/utils/users.ts
> swap test users, second is admin in app

- apps/backend-ops/src/firestoreMigrations/0012.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
> create migration v12 to update storeConfig of movie main

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-functions/src/movie.ts
- apps/backend-ops/src/algolia.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/distribution-deals/form/filter.util.ts
- libs/movie/src/lib/distribution-deals/form/search.form.ts
> Festival search filter clean

- .firebaserc
- firebase.json
- package.json
move root url from `/catalog` to `/`
> Ops: root html catalog

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-ops/src/algolia.ts
Add auto-configuration of the Algolia movie index to the backend-ops
> algolia auto config

- libs/utils/src/lib/helpers.ts
toDate() now accept date as a string and return it as a javascript Date.
close #2108
> Update helpers function toDate() to handle string dates

- .circleci/config.yml
- apps/backend-ops/src/firestoreMigrations/0012.ts
- firebase.json
> Issue#2293 fix

- apps/backend-functions/src/movie.ts
- apps/backend-ops/src/algolia.ts
use `denomination` instead of `name`
> update to use org denomination

- libs/movie/src/lib/movie/form/summary/festival-prizes/festival-prizes.component.html
added comma to premiere for film detail component
> missing comma

- apps/catalog/catalog/src/app/dashboard/deal/negociation/negociation.component.html
- apps/catalog/catalog/src/app/landing/components/key-features/key-features.component.html
- libs/ui/src/lib/icon-service.ts
> fix images link

- apps/backend-ops/src/firestoreMigrations/0012.ts
- apps/backend-ops/src/firestoreMigrations/0015.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
Create migration for notifications and invitations collections
> Notif invit migration

- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.html
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list-new/list.module.ts
- libs/movie/src/lib/movie/components/movie-filter/movie-filter.component.html
- libs/movie/src/lib/movie/components/movie-filter/movie-filter.component.scss
- libs/movie/src/lib/movie/components/movie-filter/movie-filter.component.ts
- libs/movie/src/lib/movie/components/movie-filter/movie-filter.module.ts
- libs/movie/src/lib/movie/layout/list/title-list.component.html
- libs/movie/src/lib/movie/layout/list/title-list.component.scss
- libs/movie/src/lib/movie/layout/list/title-list.component.ts
- libs/movie/src/lib/movie/layout/list/title-list.module.ts
- libs/movie/tslint.json
Creating a reusable title-list layout
> refactoring title-list

- libs/user/src/lib/auth/+state/auth.service.ts
- libs/user/src/lib/auth/pages/identity/identity.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.ts
- libs/user/src/lib/auth/pages/login/login.component.ts
Fix a bug about creation of user, we can create user and create organization.
> Fix user creation

- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.ts
- apps/catalog/catalog/src/app/dashboard/pages/home/home.component.html
- apps/catalog/catalog/src/app/dashboard/pages/home/home.component.ts
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.html
- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
> wait for loading of akita in titles, home and deals pages in dashboard

- libs/user/src/lib/auth/pages/identity/identity.component.html
> fix controls in IdentityComponent

- apps/catalog/catalog-e2e/src/integration/landing/organization-creation.spec.ts
> fix users in org-creation-spec

- apps/catalog/catalog-e2e/src/integration/dashboard/contract-tunnel.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-1.spec.ts
- apps/catalog/catalog-e2e/src/support/utils/utils.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
> contract-tunnel spec

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.html
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list-new/list.module.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/distribution-deals/components/avails-filter/avails-filter.component.html
- libs/movie/src/lib/distribution-deals/form/territory/territory.component.html
- libs/movie/src/lib/movie/form/filters/seller/seller-filter.component.html
- libs/movie/src/lib/movie/form/filters/seller/seller-filter.component.ts
- libs/movie/src/lib/movie/form/filters/seller/seller-filter.module.ts
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.html
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.html
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.scss
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.module.ts
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.html
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
create or use reusable component for filters
> title filters

- libs/ui/src/lib/maintenance/maintenance.component.scss
Maintenance page takes the full size of the page now
Fix #2413
> full maintenance page

- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.ts
- apps/catalog/catalog/src/app/marketplace/title/view/view.component.ts
- libs/e2e/src/lib/pages/auth/LoginViewPage.ts
- libs/e2e/src/lib/pages/auth/WelcomeViewPage.ts
- libs/movie/src/lib/movie/components/movie-create/movie-create.component.ts
- libs/movie/src/lib/movie/form/main/main.component.html
- libs/organization/src/lib/organization/components/member-pending/member-pending.component.ts
- libs/organization/src/lib/organization/components/organization-display/organization-display.component.ts
- libs/organization/src/lib/organization/pages/member/member.component.ts
- libs/organization/src/lib/organization/pages/organization-create/organization-create.component.ts
- libs/organization/src/lib/organization/pages/organization-editable/organization-editable.component.ts
- libs/organization/src/lib/organization/pages/organization-find/organization-find.component.html
- libs/organization/src/lib/organization/pages/organization-home/organization-home.component.ts
- libs/ui/src/lib/confirm/confirm.component.ts
- libs/ui/src/lib/feedback/feedback-message.component.ts
- libs/ui/src/lib/toolbar/header/header.component.html
- libs/user/src/lib/auth/components/accept-conditions/accept-conditions.component.ts
- libs/user/src/lib/auth/components/signin-form/signin-form.component.html
- libs/user/src/lib/auth/pages/welcome-view/welcome-view.component.ts
> remove all page-id

- apps/festival/festival/src/app/landing/landing.component.html
- apps/festival/festival/src/app/landing/landing.component.ts
- apps/festival/festival/src/app/marketplace/marketplace.component.html
- apps/festival/festival/src/app/marketplace/organization/list/list.component.html
- apps/festival/festival/src/app/marketplace/organization/list/list.module.ts
- libs/movie/src/lib/movie/layout/view/view.component.html
- libs/movie/src/lib/movie/layout/view/view.component.scss
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.html
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.ts
- libs/organization/src/lib/organization/forms/organization-form/organization-form.module.ts
- libs/organization/src/lib/organization/layout/view/view.component.html
- libs/organization/src/lib/organization/layout/view/view.module.ts
- libs/user/src/lib/auth/pages/identity/identity.component.scss
- libs/utils/src/lib/dynamic-title/dynamic-title.service.ts
- libs/utils/src/lib/pipes/to-label.pipe.ts
Update of organisation activity + some stuff
> Update of organisation activity 

- libs/movie/src/lib/distribution-deals/guards/contracts-deal-list.guard.ts
> Fix deal list guard: return true if no contracts

- apps/backend-ops/src/firestoreMigrations/0017.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
Small migration script to create missing documents in documentPermissions collection
close #2472
> Create migration script to add missing documentPermissions

- apps/catalog/catalog-e2e/src/integration/landing/organization-creation.spec.ts
- libs/e2e/src/lib/pages/organization/OrganizationCreatePage.ts
> fix org-creation spec

- apps/catalog/catalog/src/app/dashboard/title/list/list.component.ts
- env/__ngcc_entry_points__.json
> fixed title page title

- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.scss
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/deal/list/list.module.ts
- libs/contract/src/lib/contract/guards/organization-contract-list.guard.ts
> Issue#2392 titles flash

- apps/catalog/catalog/src/app/dashboard/deal/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/deal/list/list.module.ts
> empty-deals

- libs/organization/src/lib/guard/organization.guard.ts
- libs/organization/src/lib/permissions/guard/permissions.guard.ts
- libs/user/src/lib/auth/+state/auth.service.ts
- libs/user/src/lib/auth/guard/auth.guard.ts
> Logout redirect

- apps/festival/festival/src/app/marketplace/title/list-new/list.component.html
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list-new/list.module.ts
- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.html
- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.ts
- libs/movie/src/lib/movie/form/filters/languages/language-filter.module.ts
- libs/ui/src/lib/static-autocomplete/input/input-autocomplete.component.ts
> language filter form & form array fix

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/dashboard/event/view/view.component.ts
- firestore.rules
- libs/event/src/lib/+state/event.service.spec.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/event/src/lib/layout/edit/edit.module.ts
- libs/notification/src/lib/invitation/+state/invitation.model.ts
- libs/notification/src/lib/invitation/invitation-list/invitation-list.component.ts
- libs/notification/src/lib/invitation/pipes/status.pipe.ts
- libs/organization/src/lib/organization/+state/organization.model.ts
- libs/ui/src/lib/icon-service.ts
- package-lock.json
- package.json
- tsconfig.json
Some update on invitation before a larger PR
> Pre updates on invitations

- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/notification/src/lib/invitation/guard/no-organization-invitation.guard.ts
- libs/organization/src/lib/organization/components/member-pending/member-pending.component.html
- libs/organization/src/lib/organization/components/member-repertory/member-repertory.component.html
- libs/organization/src/lib/organization/components/member-repertory/member-repertory.component.ts
- libs/organization/src/lib/organization/pages/member/member.component.ts
- libs/organization/src/lib/organization/pages/organization-feedback/organization-feedback.component.ts
> fix invitation guard and flow of invitations from org

- libs/ui/src/lib/list/table-filter/table-filter.component.html
Fix #2398 
Icon on bf-table alignment
> icon alignment

- apps/festival/festival/src/app/dashboard/dashboard.component.html
- apps/festival/festival/src/app/dashboard/dashboard.component.scss
- apps/festival/festival/src/app/dashboard/dashboard.component.ts
- apps/festival/festival/src/app/dashboard/dashboard.module.ts
- apps/festival/festival/src/app/marketplace/marketplace.component.html
- apps/festival/festival/src/app/marketplace/marketplace.component.scss
- apps/festival/festival/src/app/marketplace/marketplace.component.ts
- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- libs/ui/src/lib/layout/dashboard/dashboard.component.html
- libs/ui/src/lib/layout/dashboard/dashboard.component.scss
- libs/ui/src/lib/layout/dashboard/dashboard.component.ts
- libs/ui/src/lib/layout/dashboard/dashboard.module.ts
- libs/ui/src/lib/layout/marketplace/marketplace.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.scss
- libs/ui/src/lib/layout/marketplace/marketplace.component.ts
- libs/ui/src/lib/layout/marketplace/marketplace.module.ts
- libs/utils/src/lib/routes/create-routes.ts
Create a layout for marketplace & dashboard
Implement it inside the festival app.
> Create Layout for marketplace/dashboard

- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.html
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.scss
- apps/festival/festival/src/app/marketplace/title/list-new/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list-new/list.module.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/distribution-rights/components/avails-filter/avails-filter.component.html
- libs/movie/src/lib/distribution-rights/components/avails-filter/avails-filter.component.ts
- libs/movie/src/lib/distribution-rights/form/territory/territory.component.html
- libs/movie/src/lib/distribution-rights/form/territory/territory.component.ts
- libs/movie/src/lib/movie/form/filters/estimated-budget/estimated-budget.component.html
- libs/movie/src/lib/movie/form/filters/estimated-budget/estimated-budget.component.ts
- libs/movie/src/lib/movie/form/filters/estimated-budget/estimated-budget.module.ts
- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.html
- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.ts
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.html
- libs/movie/src/lib/movie/form/main/stakeholders/stakeholders.component.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/movie/src/lib/movie/layout/list/title-list.component.html
- libs/movie/src/lib/movie/layout/list/title-list.component.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.html
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.html
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
- libs/utils/src/lib/akita-helper/sort-movie-by.ts
> title search fix

- libs/ui/src/lib/media/media.model.ts
New static object for picture' size.
> new media model

- apps/festival/festival/src/app/dashboard/event/view/view.component.html
- apps/festival/festival/src/app/dashboard/event/view/view.component.scss
- apps/festival/festival/src/app/dashboard/event/view/view.component.ts
- apps/festival/festival/src/app/dashboard/event/view/view.module.ts
- libs/event/src/lib/+state/event.query.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/+state/event.store.ts
> Event analytics view

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/movie.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/users.ts
- apps/backend-ops/src/algolia.ts
- apps/backend-ops/src/main.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
> create users index, refactor algolia code & clean

- apps/festival/festival/src/app/dashboard/event/view/view.component.html
- apps/festival/festival/src/app/dashboard/event/view/view.component.scss
> fix margin of no-analytics article

- apps/catalog/catalog/src/index.html
- package-lock.json
- package.json
Google map on contact page with API key ok
> Map api key

- apps/catalog/catalog/src/styles.scss
- apps/festival/festival/src/styles.scss
- libs/movie/src/lib/movie/components/header/header.component.html
- libs/movie/src/lib/movie/components/header/header.component.scss
- libs/movie/src/lib/movie/components/slider/slider.component.html
- libs/movie/src/lib/movie/components/slider/slider.component.scss
- libs/movie/src/lib/movie/components/title-features/title-features.component.html
- libs/movie/src/lib/movie/components/title-features/title-features.component.scss
- package.json
- styles/components/bf-font-color.scss
- styles/theme.scss
- styles/themes/dark-contrast.scss
Beginning of the contrast theme, actually only for the dark.
Fix #2548
> Dark contrast theme

- apps/backend-functions/src/internals/resize-images.ts
- apps/backend-functions/src/main.ts
- libs/ui/src/lib/media/cropper/cropper/cropper.component.html
- libs/ui/src/lib/media/cropper/cropper/cropper.component.ts
- libs/utils/src/lib/file-sanitizer.ts
- package-lock.json
- package.json
- Create resizing function for images uploaded to the storage
- Force image-cropper to generate webp images
- Update uuidv4() function to generate shorter string (google cloud storage doesn't handle very long names)
> Issue#2308 cloud function

- .github/ISSUE_TEMPLATE/component.md
- apps/backend-functions/src/internals/algolia.ts
- apps/backend-ops/src/algolia.ts
- apps/catalog/catalog/src/app/landing/components/how-it-works/how-it-works.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.html
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/selection/selection.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.scss
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.ts
- libs/user/src/lib/auth/+state/auth.query.ts
> Issue 2617

- apps/backend-functions/src/data/types.ts
- apps/backend-functions/src/internals/invitations/events.ts
- apps/backend-functions/src/internals/invitations/organizations.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/movie.ts
- firestore.rules
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/notification/src/lib/invitation/+state/invitation.firestore.ts
- libs/notification/src/lib/invitation/+state/invitation.model.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/notification/src/lib/invitation/components/item/item.component.ts
- libs/notification/src/lib/invitation/invitation-item/invitation-item.component.html
- libs/notification/src/lib/invitation/invitation-item/invitation-item.component.ts
- libs/notification/src/lib/invitation/invitation-utils.ts
- libs/notification/src/lib/notification/notification-widget/notification-widget.component.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
- libs/organization/src/lib/organization/components/member-pending/member-pending.component.ts
- libs/organization/src/lib/organization/components/member-request/member-request.component.html
- libs/organization/src/lib/organization/components/member-request/member-request.component.ts
- libs/organization/src/lib/organization/pages/member/member.component.ts
- libs/organization/src/lib/organization/pages/organization-feedback/organization-feedback.component.ts
- libs/user/src/lib/auth/guard/auth.guard.ts
- libs/utils/src/lib/helpers.ts
> OK #2642 - Update the invitation flow for public events

- firestore.rules
> Add new rules for movie storeConfig AppAccess

- angular.json
- apps/backend-functions/src/movie.ts
- apps/backend-ops/src/firestoreMigrations/0012.ts
- apps/backend-ops/src/firestoreMigrations/0019.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/start/start-tunnel.component.ts
- libs/contract/src/lib/contract/+state/contract.service.ts
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- libs/movie/src/lib/movie/components/import/table-extracted-elements/movies/movies.component.ts
- libs/organization/src/lib/permissions/+state/permissions.service.ts
Add an AppAccess to movie
Fix #2591
> Data movie app access

- libs/admin/src/lib/admin-panel/forms/movie-admin.form.ts
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.html
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.scss
- libs/admin/src/lib/admin-panel/pages/movie/movie.component.ts
- libs/admin/src/lib/admin-panel/pages/movies/movies.component.html
- libs/admin/src/lib/admin-panel/pages/movies/movies.component.scss
- libs/admin/src/lib/admin-panel/pages/overview/overview.component.html
- libs/admin/src/lib/admin-panel/pages/overview/overview.component.scss
Add a form to change appAccess on movie if needed to admin panel. Did some CSS changes also.
Fix #2628 
Need PR #2619 to be merged to allow this one to work
> AppAccess in Admin panel

- apps/catalog/catalog-e2e/src/integration/landing/organization-creation.spec.ts
> unskip org creation e2e test

- apps/backend-functions/src/internals/invitations/events.ts
- apps/backend-functions/src/templates/mail.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/user/src/lib/user/+state/user.model.ts
Email for event invitation updated with template from sendgrid
> Email update

- apps/festival/festival/src/app/dashboard/dashboard.module.ts
- apps/festival/festival/src/app/dashboard/home/home.component.ts
- apps/festival/festival/src/app/dashboard/notification/notification.component.html
- apps/festival/festival/src/app/dashboard/title/view/view.module.ts
- apps/festival/festival/src/app/festival.module.ts
- apps/festival/festival/src/app/guards/festival-app.guard.ts
- apps/festival/festival/src/app/marketplace/notification/notification.component.html
- libs/notification/src/lib/notification/+state/notification.store.ts
- libs/organization/src/lib/organization/pages/organization-app-access/organization-app-access.component.html
> Release hotfix#2708

- angular.json
> festival: enable prod sourcemaps

- apps/backend-ops/src/firestoreMigrations/0022.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceHomePage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceOrganizationTitlePage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalOrganizationListPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/index.ts
- libs/ui/src/lib/layout/dashboard/dashboard.component.html
> Issue#2689 screenings

- .zeplin/components.json
> added zeplin component

- .circleci/config.yml
- apps/backend-ops/src/firestoreMigrations/0022.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival/src/app/festival-app.guard.ts
- libs/e2e/src/lib/utils/functions.ts
> Fix festival e2e

- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalDashboardHomePage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalInvitationsPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
- libs/notification/src/lib/invitation/components/action/action.component.html
- libs/ui/src/lib/layout/dashboard/dashboard.component.html
> e2e accept request for screening

- apps/backend-functions/src/internals/invitations/events.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.module.ts
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.ts
- apps/festival/festival/src/app/marketplace/event/view/view.component.html
- apps/festival/festival/src/app/marketplace/event/view/view.component.scss
- apps/festival/festival/src/app/marketplace/event/view/view.component.ts
- apps/festival/festival/src/app/marketplace/event/view/view.module.ts
- libs/event/src/lib/+state/event.firestore.ts
- libs/event/src/lib/+state/event.model.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/components/card/card.component.scss
- libs/event/src/lib/form/event.form.ts
- libs/event/src/lib/layout/review/review.component.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/event/src/lib/layout/view/view.component.scss
- libs/event/src/lib/layout/view/view.module.ts
- libs/movie/src/lib/movie/components/header/header.component.html
- libs/notification/src/lib/invitation/components/action/action.component.html
- libs/user/src/lib/user/+state/user.store.ts
- styles/components/mat-button.scss
Add organizedBy to the meeting
Bunch of small updates
> Event view

- apps/backend-functions/src/templates/mail.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.ts
- apps/catalog/catalog/src/app/marketplace/movie/search/search.component.ts
- apps/festival/festival/src/app/dashboard/dashboard.component.html
- apps/festival/festival/src/app/dashboard/dashboard.component.ts
- apps/festival/festival/src/app/dashboard/dashboard.module.ts
- apps/festival/festival/src/app/dashboard/tunnel/start/start-tunnel.component.html
- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.html
- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.ts
- libs/movie/src/lib/movie/form/main/main.form.ts
- libs/movie/src/lib/movie/layout/list/title-list.component.html
- libs/organization/src/lib/organization/components/member-add/member-add.component.html
- libs/organization/src/lib/organization/components/member-add/member-add.component.ts
- libs/organization/src/lib/organization/pages/view/view.component.html
- libs/organization/src/lib/organization/pages/view/view.component.ts
- libs/organization/src/lib/organization/pages/view/view.module.ts
Update movie form in tunnel to match recent model
Update links in mails
Update text in start of tunnel to avoid AC references
Update organization add-member component to help user comprehension
> Debug#2762

- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalDashboardHomePage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalInvitationsPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.module.ts
> Festival e2e fix

- apps/backend-functions/src/internals/invitations/organizations.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/templates/mail.ts
- env/env.ci.ts
- env/env.prod.ts
- env/env.staging.ts
- libs/utils/src/lib/apps.ts
Add email for orgAppAccess and update some others templates
Fix #2685
> Email template

- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/internals/watermark.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/templates/watermark.ts
- apps/backend-functions/src/users.ts
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.scss
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/notification/src/lib/invitation/+state/invitation.firestore.ts
- libs/notification/src/lib/invitation/+state/invitation.model.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/user/src/lib/auth/+state/auth.store.ts
- libs/user/src/lib/user/+state/user.firestore.ts
- libs/user/src/lib/user/+state/user.model.ts
Create a callable function to invit many user by email.
> Invit users function

- apps/backend-ops/src/firestoreMigrations/0022.ts
- apps/festival/festival-e2e/src/fixtures/data.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalDashboardHomePage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalInvitationsPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceHomePage.ts
- libs/notification/src/lib/invitation/components/action/action.component.html
> Fix screening invitations

- libs/landing/src/lib/how-it-works/how-it-works.component.html
- libs/landing/src/lib/toolbar/toolbar.component.html
> landing text changes

- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/environments/environment.prod.ts
- apps/backend-functions/src/environments/environment.ts
- apps/backend-functions/src/internals/email.ts
- apps/backend-functions/src/internals/invitations/events.ts
- apps/backend-functions/src/internals/invitations/organizations.ts
- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/invitation.ts
- apps/backend-functions/src/main.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-functions/src/privateConfig.ts
- apps/backend-functions/src/templates/mail.ts
- apps/backend-functions/src/users.ts
- apps/catalog/catalog/src/app/dashboard/pages/contact-page/contact-page.component.ts
- apps/catalog/catalog/src/app/marketplace/layout/layout.module.ts
- apps/catalog/catalog/src/app/marketplace/marketplace.module.ts
- libs/admin/src/lib/admin-panel/forms/test-email.form.ts
- libs/admin/src/lib/admin-panel/pages/mails/mails.component.html
- libs/admin/src/lib/admin-panel/pages/mails/mails.component.ts
- libs/landing/src/lib/learn-more/learn-more.component.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/organization/src/lib/cart/+state/cart.service.ts
- libs/user/src/lib/auth/+state/auth.service.ts
- libs/user/src/lib/auth/components/email-verify/email-verify.component.ts
- libs/utils/src/lib/apps.ts
- libs/utils/src/lib/request-demo.ts
added custom from to emails where it is possible
> added custom from to emails where it is possible

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- libs/event/src/lib/+state/event.model.ts
- libs/event/src/lib/form/create/create.component.html
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.scss
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/event/src/lib/layout/edit/edit.module.ts
- libs/notification/src/lib/invitation/+state/invitation.service.ts
- libs/notification/src/lib/invitation/form/user/user.component.html
- libs/notification/src/lib/invitation/form/user/user.component.scss
- libs/notification/src/lib/invitation/form/user/user.component.ts
- libs/notification/src/lib/invitation/form/user/user.module.ts
- libs/ui/src/lib/form/time-picker/time-picker.component.html
- libs/ui/src/lib/form/time-picker/time-picker.component.ts
- styles/components/bf-font-color.scss
create separated component for invitation form user
check if movie has upload video to create screening
More stuff
> Debug event edit page

- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.scss
- libs/movie/src/lib/movie/form/filters/budget/budget.component.html
- libs/movie/src/lib/movie/layout/list/title-list.component.html
- libs/movie/src/lib/movie/layout/list/title-list.component.scss
- styles/components/mat-slider.scss
> Movie list maintenance

- apps/catalog/catalog/src/app/app.component.ts
- apps/catalog/catalog/src/app/landing/pages/landing-page/landing-page.component.html
- libs/landing/src/lib/toolbar/toolbar.component.html
- libs/landing/src/lib/toolbar/toolbar.component.scss
- libs/landing/src/lib/toolbar/toolbar.component.ts
> Toolbar landing

- libs/notification/src/lib/invitation/form/user/user.component.html
- libs/notification/src/lib/invitation/form/user/user.component.scss
- libs/notification/src/lib/invitation/form/user/user.component.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.html
Add a message when there is too many invitations
> Add message for maxlenght

- .gitignore
- apps/backend-functions/src/internals/image.ts
- apps/backend-functions/src/main.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-image/media-image.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-image/media-image.component.ts
- apps/festival/festival/src/app/dashboard/tunnel/media-image/media-image.component.html
- libs/movie/src/lib/movie/form/summary/image/image.component.html
- libs/movie/src/lib/movie/form/summary/image/image.component.ts
- libs/movie/src/lib/movie/form/summary/image/image.module.ts
- libs/ui/src/lib/media/cropper/cropper.module.ts
- libs/ui/src/lib/media/cropper/cropper/cropper.component.html
- libs/ui/src/lib/media/cropper/cropper/cropper.component.ts
- libs/ui/src/lib/upload/file-upload/file-upload.component.html
- libs/ui/src/lib/upload/file-upload/file-upload.component.ts
- libs/ui/src/lib/upload/upload.module.ts
- libs/utils/src/lib/media/media.firestore.ts
- libs/utils/src/lib/pipes/fileName.pipe.ts
close #2636 
sometimes the functinos throws, but it still does it job. Also I guess it shoudl get caught by the if statement in the function.
> Issue 2636 part-2

- apps/festival/festival/src/app/marketplace/organization/meeting/meeting.component.ts
- libs/organization/src/lib/organization/pipes/org-address.pipe.ts
Change orgAddress Pipe, add snack bar for meeting request
Related to #2804
> Org Review

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-functions/src/orgs.ts
- apps/backend-ops/src/algolia.ts
- apps/festival/festival/src/app/dashboard/home/home.component.html
- apps/festival/festival/src/app/dashboard/title/list/list.component.html
- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/notification/notification.component.html
- apps/festival/festival/src/app/marketplace/notification/notification.component.ts
- apps/festival/festival/src/app/marketplace/notification/notification.module.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/movie/src/lib/movie/layout/list/title-list.component.html
- libs/movie/src/lib/movie/layout/list/title-list.component.scss
- libs/movie/src/lib/movie/pipes/movie-feature.pipe.ts
- libs/notification/src/lib/notification/+state/notification.service.ts
- libs/notification/src/lib/notification/+state/notification.store.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
- libs/ui/src/lib/algolia/types.ts
- libs/ui/src/lib/icon-service.ts
- libs/utils/src/lib/apps.ts
> MAINTENANCE - Movie lists #2799

- apps/festival/festival/src/app/dashboard/event/list/list.component.html
- apps/festival/festival/src/app/dashboard/event/review/review.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- apps/festival/festival/src/app/marketplace/event/session/session.component.scss
- apps/festival/festival/src/app/marketplace/event/view/view.component.html
- libs/event/src/lib/components/player/player.component.html
- libs/event/src/lib/components/player/player.component.scss
- libs/event/src/lib/components/player/player.component.ts
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/edit/edit.component.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/event/src/lib/layout/view/view.module.ts
- libs/notification/src/lib/invitation/form/user/user.component.html
- libs/notification/src/lib/invitation/form/user/user.component.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.html
> Maintenance Event

- libs/landing/src/lib/landing.module.ts
- libs/ui/src/lib/layout/app-logo/app-logo.component.ts
> Landing img

- apps/festival/festival/src/app/dashboard/event/list/list.component.html
- apps/festival/festival/src/app/dashboard/event/list/list.component.ts
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.html
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.scss
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.ts
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.module.ts
- apps/festival/festival/src/app/marketplace/event/list/list.component.html
- apps/festival/festival/src/app/marketplace/event/list/list.component.scss
- apps/festival/festival/src/app/marketplace/event/list/list.module.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.ts
- libs/event/src/lib/+state/event.service.ts
- libs/event/src/lib/components/empty/empty.component.html
- libs/event/src/lib/components/empty/empty.component.scss
- libs/event/src/lib/components/empty/empty.component.ts
- libs/event/src/lib/components/empty/empty.module.ts
- libs/event/src/lib/components/screening-item/screening-item.component.html
- libs/event/src/lib/components/screening-item/screening-item.component.scss
- libs/event/src/lib/components/screening-item/screening-item.component.ts
- libs/event/src/lib/components/screening-item/screening-item.module.ts
- libs/event/src/lib/pipes/event-link.pipe.ts
> Fixe calendar issues

- apps/catalog/catalog/src/app/dashboard/invitation/invitation.component.html
- apps/catalog/catalog/src/app/marketplace/invitation/invitation.component.html
- apps/festival/festival/src/app/dashboard/invitation/invitation.component.html
- apps/festival/festival/src/app/marketplace/invitation/invitation.component.html
- libs/notification/src/lib/invitation/components/action/action.component.html
- libs/notification/src/lib/invitation/components/action/action.component.scss
- libs/notification/src/lib/invitation/components/action/action.module.ts
- libs/notification/src/lib/invitation/components/item/item.component.html
- libs/notification/src/lib/invitation/components/item/item.module.ts
> Invitations ui

- apps/festival/festival/src/app/marketplace/organization/list/list.component.ts
- libs/organization/src/lib/organization/components/card/card.component.scss
Update image shape in org-card and exclude Archipel from the query
> Issue#2803 maintenance org list

- apps/backend-functions/src/internals/algolia.ts
- apps/backend-functions/src/internals/users.ts
- apps/backend-functions/src/movie.ts
- apps/backend-functions/src/player.ts
- apps/backend-ops/src/algolia.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/notification/src/lib/notification/+state/notification.store.ts
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
> multiple fixes

- libs/notification/src/lib/invitation/components/action/action.component.scss
- libs/notification/src/lib/invitation/components/item/item.component.html
- libs/notification/src/lib/invitation/components/item/item.component.scss
> change date of invitation-item

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- libs/ui/src/lib/carousel/carousel.component.html
- libs/ui/src/lib/carousel/carousel.component.scss
- libs/ui/src/lib/carousel/carousel.component.ts
close #2835 
would be nice to disable the buttons when it is scrolling for any miss calculation for sliding. but not important right now
> Issue 2835

- apps/festival/festival/src/app/marketplace/title/main/main.component.html
> delete festival logo

- apps/festival/festival/src/app/marketplace/home/home.component.ts
> AppAccess for movie

- apps/festival/festival/src/app/marketplace/home/home.component.ts
- libs/organization/src/lib/organization/components/chip/chip.component.html
- libs/organization/src/lib/organization/forms/organization.form.ts
- libs/organization/src/lib/organization/layout/view/view.component.html
Org-chip is now in dark-contrast-theme (movie-view) and org address has no more space (org-view)
> Org-chip and space

- apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
- libs/event/src/lib/form/event.form.ts
> added validator

- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.scss
- apps/festival/festival/src/app/marketplace/marketplace.component.html
- apps/festival/festival/src/app/marketplace/marketplace.module.ts
- libs/movie/src/lib/movie/components/card/card.component.html
- libs/movie/src/lib/movie/components/card/card.component.ts
- libs/movie/src/lib/movie/components/slide/slide.component.html
- libs/movie/src/lib/movie/components/slide/slide.component.scss
- libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.scss
- libs/ui/src/lib/slider/slider.component.html
- libs/user/src/lib/auth/components/widget/widget.component.scss
- styles/components/mat-button.scss
Toolbar design review
Fix #2910 
Header on home page marketplace
Fix #2911 
Slider for marketplace home page
Fix #2916 
Add also placeholder for movie card depending on the size given to the movie-card
> Design Review

- apps/festival/festival/src/app/dashboard/home/home.component.scss
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.html
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.scss
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.module.ts
- styles/components/mat-button.scss
> add refresh button on analytics

- apps/catalog/catalog/src/app/dashboard/invitation/invitation.component.html
- apps/catalog/catalog/src/app/dashboard/invitation/invitation.module.ts
- apps/catalog/catalog/src/app/marketplace/invitation/invitation.component.html
- apps/catalog/catalog/src/app/marketplace/invitation/invitation.module.ts
- apps/festival/festival/src/app/dashboard/invitation/invitation.component.html
- apps/festival/festival/src/app/dashboard/invitation/invitation.module.ts
- apps/festival/festival/src/app/marketplace/invitation/invitation.component.html
- apps/festival/festival/src/app/marketplace/invitation/invitation.module.ts
- libs/notification/src/lib/invitation/components/action/action.component.html
- libs/notification/src/lib/invitation/components/item/item.component.html
- libs/notification/src/lib/invitation/components/item/item.component.scss
- libs/notification/src/lib/invitation/components/list/list.component.html
- libs/notification/src/lib/invitation/components/list/list.component.scss
- libs/notification/src/lib/invitation/components/list/list.module.ts
> Invitation css

- libs/ui/src/lib/slider/slide/slide.component.html
> HOTFIX-2904 Directive was changed but the change was not reflected here.

- .firebaserc
> remco setup

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-budget-5.spec.ts
> fix QUOTAS in e2e budget

- libs/admin/src/lib/admin-panel/admin-panel.module.ts
- libs/admin/src/lib/admin-panel/pages/dev-area/dev-area.component.html
- libs/admin/src/lib/admin-panel/pages/dev-area/dev-area.component.ts
- libs/admin/src/lib/admin-panel/pages/overview/overview.component.html
- libs/admin/src/lib/admin-panel/pages/overview/overview.component.scss
- libs/admin/src/lib/admin-panel/pages/overview/overview.component.ts
> added dev area in admin panel

- .firebaserc
> remco setup fix json

- apps/festival/festival-e2e/src/fixtures/data.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/index.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceCalendarPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceNotificationsPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceOrganizationTitlePage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceScreeningPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/index.ts
- libs/e2e/src/lib/utils/functions.ts
- libs/event/src/lib/components/card/card.component.html
Add new test in create screening to work with public screening.
> Test 2695: Add public screening to calendar

- libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.scss
> cookie banner

- apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
- libs/e2e/src/lib/pages/auth/AuthLoginPage.ts
> Added click on privacy policy checkbox in e2e test

- apps/catalog/catalog-e2e/src/integration/landing/organization-creation.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- libs/ui/src/lib/app-bar.ts
> Last fix e2e

- libs/notification/src/lib/invitation/components/action/action.component.scss
- libs/notification/src/lib/invitation/components/item/item.component.html
- libs/notification/src/lib/invitation/components/item/item.component.ts
- libs/notification/src/lib/notification/components/item/item.component.html
- libs/notification/src/lib/notification/components/item/item.component.ts
> List responsive

- apps/festival/festival/src/app/dashboard/event/review/review.component.html
- apps/festival/festival/src/app/dashboard/event/review/review.component.scss
- apps/festival/festival/src/app/dashboard/event/review/review.component.ts
- apps/festival/festival/src/app/dashboard/event/review/review.module.ts
- libs/event/src/lib/+state/event.service.ts
> fix analytics in EventReview Page

- apps/backend-functions/src/internals/image.ts
Fix the temp name of images when resizing
> Fix the temp name of images when resizing

- apps/backend-functions/src/internals/image.ts
- apps/backend-functions/src/main.ts
apply some quick fix on the `onFileDelete` backend function
> onDelete quick fix

- libs/ui/src/lib/layout/dashboard/dashboard.component.html
- libs/ui/src/lib/layout/dashboard/dashboard.component.scss
- libs/ui/src/lib/layout/dashboard/dashboard.module.ts
- libs/ui/src/lib/layout/footer/footer.component.scss
- libs/ui/src/lib/layout/marketplace/marketplace.component.html
- libs/ui/src/lib/layout/marketplace/marketplace.component.scss
- libs/ui/src/lib/layout/marketplace/marketplace.module.ts
> Implemented footer in Dashboard and Marketplace Layout

- libs/event/src/lib/components/player/player.component.scss
> fix player control in full screen

- apps/festival/festival/src/app/marketplace/organization/list/list.component.ts
- libs/organization/src/lib/organization/+state/organization.model.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
- libs/organization/src/lib/organization/components/card/card.component.ts
> APP-2780 Organization fixes regarding movie count.

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-end.spec.ts
- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-main-2.spec.ts
- apps/catalog/catalog-e2e/src/integration/marketplace/create-wishlist.spec.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelMainPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/HomePage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/NavbarPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/SearchPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/ViewPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/WishlistPage.ts
- libs/organization/src/lib/organization/components/wishlist-button/wishlist-button.component.html
> Unskip catalog e2e

- apps/festival/festival/src/app/marketplace/title/main/main.component.html
- apps/festival/festival/src/app/marketplace/title/main/main.component.ts
> APP-2782 Not showing any box office values if there's no values at all.

- libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
- libs/notification/src/lib/invitation/components/item/item.component.html
- libs/notification/src/lib/invitation/components/item/item.module.ts
- libs/notification/src/lib/invitation/pipes/event-link.pipe.ts
- libs/organization/src/lib/organization/components/member-add/member-add.component.html
- libs/organization/src/lib/organization/components/member-add/member-add.module.ts
> Invitation link

- libs/ui/src/lib/layout/footer/footer.component.html
- libs/ui/src/lib/static-informations/contact/contact.component.html
> Fix text in footer and phone number on contact page

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-file/media-file.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-file/media-file.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/summary/summary.component.ts
- apps/festival/festival/src/app/dashboard/tunnel/media-file/media-file.component.html
- apps/festival/festival/src/app/dashboard/tunnel/media-file/media-file.component.ts
- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.ts
- libs/movie/src/lib/movie/+state/movie.service.ts
- merge image from the server
- upload scenario
> Quick media fix

- apps/festival/festival/src/app/dashboard/dashboard.component.ts
- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/import/src/lib/components/view-extracted-elements/organizations/view-extracted-organizations.component.ts
- libs/utils/src/lib/media/image-uploader.service.ts
- libs/utils/src/lib/media/media.firestore.ts
- libs/utils/src/lib/media/media.query.ts
- libs/utils/src/lib/media/media.service.ts
- libs/utils/src/lib/media/media.store.ts
Creating a media service that handle multiple upload to storage alogn with play/pause/cancel and display of progress percentage
> creating media service

- apps/festival/festival/src/app/marketplace/event/list/list.component.ts
- apps/festival/festival/src/app/marketplace/organization/screening/screening.component.ts
- firestore.indexes.json
> fix indexes for events

- libs/ui/src/lib/media/cropper/cropper/cropper.component.ts
- libs/ui/src/lib/media/image-reference/image-reference.form.ts
- libs/utils/src/lib/media/media.firestore.ts
- libs/utils/src/lib/media/media.service.ts
> Original filename for upload component

- libs/ui/src/lib/media/img/img.component.html
- libs/ui/src/lib/media/img/img.component.ts
- libs/ui/src/lib/media/img/img.module.ts
- libs/utils/src/lib/media/media.firestore.ts
Create `bf-img` component and update ImgRef interface.
> Create bf-img component

- apps/catalog/catalog-e2e/src/integration/marketplace/create-wishlist.spec.ts
> last fix for create wishlist tests

- libs/event/src/lib/form/create/create.component.ts
- libs/event/src/lib/layout/edit/edit.component.ts
> fix allDay of event edit to select the date, midnight to 23:59

- apps/backend-functions/src/internals/image.ts
- libs/utils/src/lib/media/media.firestore.ts
> add fallback image

- apps/festival/festival-e2e/src/fixtures/data.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventEditPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/EventPage.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalInvitationsPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceCalendarPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceEventPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceScreeningPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/index.ts
- apps/festival/festival/src/app/marketplace/event/session/session.component.html
- libs/event/src/lib/layout/edit/edit.component.html
- libs/event/src/lib/layout/view/view.component.html
- libs/notification/src/lib/invitation/components/item/item.component.html
> implement screening privacy test in screening-invitations

- apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel.spec.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/1-main.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/10-summary.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/2-storyline.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/3-credits.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/4-budget.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/5-technical-info.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/7-files.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/9-valuation.ts
- apps/catalog/catalog-e2e/src/support/movie-tunnel-tests/index.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelSummaryPage.ts
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/movie-tunnel.component.html
> Tunnel summary test

- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelChainOfTitlesPage.ts
- apps/catalog/catalog-e2e/src/support/pages/dashboard/TunnelFilesPage.ts
> fix file uploader message in e2e test

- .zeplin/components.json
- angular.json
- libs/movie/src/lib/movie/components/card/card.stories.ts
- libs/organization/.storybook/addons.js
- libs/organization/.storybook/config.js
- libs/organization/.storybook/tsconfig.json
- libs/organization/.storybook/webpack.config.js
- libs/organization/src/lib/organization/components/card-minimal/card-minimal.component.html
- libs/organization/src/lib/organization/components/card-minimal/card-minimal.component.scss
- libs/organization/src/lib/organization/components/card-minimal/card-minimal.component.ts
- libs/organization/src/lib/organization/components/card-minimal/card-minimal.module.ts
- libs/organization/src/lib/organization/components/card-minimal/card-minimal.stories.ts
- libs/organization/tsconfig.lib.json
- libs/ui/src/lib/storybook/mock.ts
> Added Organization Minimal Component + fix storybook

- libs/event/src/lib/components/player/player.component.ts
- libs/user/src/lib/auth/forms/profile-edit.form.ts
> Issue#3181

- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- apps/festival/festival/src/app/marketplace/home/home.module.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
> Added featured sales agent carousel to homepage festival

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- apps/festival/festival/src/app/marketplace/organization/member/member.component.scss
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/main/main.component.html
- apps/festival/festival/src/app/marketplace/title/main/main.component.scss
- apps/festival/festival/src/app/marketplace/title/main/main.component.ts
- libs/event/src/lib/layout/view/view.component.html
- libs/media/src/lib/components/upload/file-upload/file-upload.component.scss
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/form/summary/budget/budget.component.html
- libs/movie/src/lib/movie/pipes/movie-feature.pipe.ts
- libs/organization/src/lib/organization/components/card/card.component.html
- libs/organization/src/lib/organization/forms/organization-form/organization-form.component.html
- libs/organization/src/lib/organization/pages/view/view.component.html
> Debug work

- apps/backend-ops/src/firestoreMigrations/0003.ts
- apps/backend-ops/src/firestoreMigrations/0025.ts
- apps/backend-ops/src/firestoreMigrations/0027.ts
- apps/backend-ops/src/firestoreMigrations/0028.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
> Migration Watermark to new ImRef interface

- apps/backend-ops/src/firestoreMigrations/0028.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
> Issue 3096

- libs/media/src/lib/+state/media.service.ts
Almost always an error appeared in the console log when a new image is uploaded. This is now fixed.
> Fix error in media exists function

- .circleci/deploy-and-test-e2e.sh
> ci(test-e2e): disable interactive mode in deploy-and-test-e2e.sh

- apps/festival/festival/src/app/festival.module.ts
- libs/media/src/lib/+state/media.model.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- package-lock.json
Remove MovieCollectionGuard
Add more verification on image type
> Small quick fixes

- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.scss
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- libs/movie/src/lib/movie/components/title-filter/title-filter.component.html
- libs/movie/src/lib/movie/components/title-filter/title-filter.component.scss
- libs/movie/src/lib/movie/components/title-filter/title-filter.component.ts
- libs/movie/src/lib/movie/components/title-filter/title-filter.module.ts
- libs/movie/src/lib/movie/form/search.form.ts
- libs/movie/src/lib/movie/layout/list/title-list.component.html
- libs/movie/src/lib/movie/layout/list/title-list.component.scss
- libs/movie/src/lib/movie/layout/list/title-list.component.ts
- libs/movie/src/lib/movie/layout/list/title-list.module.ts
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.html
- libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
- libs/ui/src/lib/overlay-widget/overlay-widget.component.ts
- libs/ui/src/lib/overlay-widget/overlay-widget.directive.ts
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.html
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
- libs/utils/src/lib/animations/fade.ts
Remove MovieCollectionGuard
Put filters on the top
Use grid for the movie card
Optimise list with trackBy
Add animation on enter/leave
Remove some dead code
Improve autocomplete chips
> Update movie list page

- apps/backend-functions/src/internals/watermark.ts
- apps/backend-ops/src/firestoreMigrations/0028.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
> from hotfix/1.6.3 to develop

- .circleci/deploy-and-test-e2e.sh
> force firestore deploy to force indexes deploy

- apps/backend-ops/src/firestoreMigrations/temporary-0028.ts
> Migrate avatar, banner, logo

- apps/backend-ops/src/firestoreMigrations/temporary-0028.ts
> Migrate banner and poster

- .circleci/config.yml
- .circleci/run-firebase-emulator.sh
- package.json
> fix(run-firebase-emulator): preliminary fix for running emulator in CI

- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- apps/festival/festival/src/app/marketplace/home/home.module.ts
> Implement Featured Sales Agent Banner in homepage

- apps/backend-ops/src/firestoreMigrations/temporary-0028.ts
- apps/festival/festival/src/app/marketplace/home/home.component.html
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/promotional-elements/promotional-elements.form.ts
> Remove trailer

- apps/backend-ops/src/firestoreMigrations/0003.ts
- apps/backend-ops/src/firestoreMigrations/0025.ts
- apps/backend-ops/src/firestoreMigrations/old-types.ts
Removed duplicate old interface declarations
> Removed duplicate old interfaces code

- apps/festival/festival/src/app/marketplace/home/home.component.html
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- apps/festival/festival/src/app/marketplace/home/home.module.ts
- libs/organization/src/lib/organization/+state/organization.model.ts
- libs/organization/src/lib/organization/+state/organization.service.ts
- libs/organization/src/lib/organization/components/banner/banner.component.html
- libs/organization/src/lib/organization/components/banner/banner.component.ts
- libs/organization/src/lib/organization/components/banner/banner.module.ts
- libs/organization/src/lib/organization/components/banner/banner.stories.ts
> Implement featured sales agent component in homepage

- firestore.test.rules
- libs/notification/src/lib/notification/+state/notification.service.spec.ts
- libs/notification/src/lib/notification/+state/notification.service.ts
Setup an Unit test example that connect to the emulator.
> add notification unit testing

- apps/catalog/catalog-e2e/src/support/pages/marketplace/NavbarPage.ts
- apps/catalog/catalog-e2e/src/support/pages/marketplace/SearchPage.ts
> fix wishlist e2e test

- libs/notification/src/lib/notification/+state/notification.service.spec.ts
> Test(notif): Add more unit tests for notification service.

- apps/festival/festival-e2e/src/fixtures/data.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/pages/dashboard/FestivalInvitationsPage.ts
- apps/festival/festival/src/app/dashboard/invitation/invitation.component.html
- apps/festival/festival/src/app/marketplace/invitation/invitation.component.html
- libs/notification/src/lib/invitation/components/item/item.component.html
- libs/notification/src/lib/invitation/components/item/item.component.ts
> Fix screening invitation spec

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.scss
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
> Catalog title list

- apps/backend-functions/src/internals/watermark.ts
- apps/backend-functions/src/main.ts
- apps/backend-ops/src/firebaseSetup.ts
- apps/backend-ops/src/firestoreMigrations/0028.ts
- apps/backend-ops/src/main.ts
- apps/backend-ops/src/users.ts
Issue #3329 && #3300 
Add function to add fix watermarks
> Fix watermark in migration

- apps/festival/festival/src/app/dashboard/home/home.component.html
- libs/movie/src/lib/movie/+state/movie.firestore.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/summary/country/country.component.html
- libs/movie/src/lib/movie/form/summary/country/country.component.ts
- libs/movie/src/lib/movie/pages/end/end.component.html
- libs/movie/src/lib/movie/pages/main/main.component.html
- libs/movie/src/lib/movie/pages/media-file/media-file.component.ts
- libs/movie/src/lib/movie/pages/media-image/media-image.component.html
- libs/movie/src/lib/movie/pages/media-image/media-image.component.ts
- libs/movie/src/lib/movie/pages/start/start-tunnel.component.html
- libs/movie/src/lib/movie/pages/start/start-tunnel.component.scss
Fix some little misunderstanding during the rebase
> fix rebase

- apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
- apps/catalog/catalog/src/app/dashboard/home/home.component.html
- libs/contract/src/lib/contract/tunnel/success/success.component.html
- libs/movie/src/lib/movie/guards/movie-tunnel.guard.ts
- libs/notification/src/lib/+state/notification.store.ts
> fix titles links to title

- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-image/media-image.component.html
- apps/catalog/catalog/src/app/dashboard/movie-tunnel/media-image/media-image.component.ts
- apps/festival/festival/src/app/dashboard/tunnel/media-image/media-image.component.html
- apps/festival/festival/src/app/dashboard/tunnel/media-image/media-image.component.ts
Fix issue #3371 
Prevent rerendering all still_photos
> Prevent rerendering of all still photos

- apps/backend-functions/src/media.ts
- apps/backend-ops/src/firebaseSetup.ts
- apps/backend-ops/src/firestoreMigrations/0029.ts
- apps/backend-ops/src/firestoreMigrations/0030.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
- apps/backend-ops/src/main.ts
- apps/backend-ops/src/syncStorage.ts
- apps/backend-ops/src/users.ts
Create an ops script that re-sync the db from the storage.
> Script to sync db with storage

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel-routing.module.ts
- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- libs/movie/src/lib/movie/form/sales-cast/sales-cast.form.ts
- libs/movie/src/lib/movie/pages/artistic/artistic.component.html
- libs/movie/src/lib/movie/pages/artistic/artistic.component.scss
- libs/movie/src/lib/movie/pages/artistic/artistic.component.ts
- libs/movie/src/lib/movie/pages/artistic/artistic.module.ts
- libs/ui/src/lib/static-autocomplete/select/static-select.component.html
- libs/ui/src/lib/static-autocomplete/select/static-select.component.ts
- libs/utils/src/lib/common-interfaces/identity.ts
- libs/utils/src/lib/static-model/staticModels.ts
> App 3187 artistic page

- apps/festival/festival-e2e/src/fixtures/data.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
> fix name participant and reload for invitations

- libs/import/src/lib/components/view-extracted-elements/movies/view-extracted-movies.component.ts
- libs/movie/src/lib/movie/+state/movie.model.ts
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/techincal-info.form.ts
- libs/movie/src/lib/movie/pages/technical-info/technical-info.component.html
- libs/movie/src/lib/movie/pages/technical-info/technical-info.component.scss
- libs/movie/src/lib/movie/pages/technical-info/technical-info.component.ts
- libs/movie/src/lib/movie/pages/technical-info/technical-info.module.ts
> Issue 3196

- libs/media/src/lib/directives/image-reference/background-reference.directive.ts
- libs/media/src/lib/directives/image-reference/image-reference.directive.ts
> remove enhance & add lazyloading

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel-routing.module.ts
- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- libs/movie/src/lib/movie/pages/artistic/artistic.component.html
- libs/movie/src/lib/movie/pages/reviews/reviews.component.html
- libs/movie/src/lib/movie/pages/reviews/reviews.component.scss
- libs/movie/src/lib/movie/pages/reviews/reviews.component.ts
- libs/movie/src/lib/movie/pages/reviews/reviews.module.ts
- libs/utils/src/lib/static-model/staticModels.ts
> APP-3193 Selection & Awards page.

- apps/festival/festival-e2e/src/fixtures/data.ts
- apps/festival/festival-e2e/src/integration/dashboard/create-screening-2687.spec.ts
- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalMarketplaceEventPage.ts
- apps/festival/festival-e2e/src/support/pages/marketplace/FestivalScreeningPage.ts
Add verification of each event name on create screening test
> E2e event name

- apps/catalog/catalog-e2e/src/support/pages/marketplace/SearchPage.ts
Improve the way to find movie-card. This will also enable finding movie name in the component.
> Fix(e2e): Improve finding movie-card in the test #3376

- apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
- libs/invitation/src/lib/+state/invitation.service.ts
- package-lock.json
- package.json
Fix issue #3379 
Issue was caused by breaking changes in Akita upgrade from v4 to v5.
> Update store on update

- apps/backend-functions/src/media.ts
- apps/backend-ops/src/firebaseSetup.ts
- apps/backend-ops/src/firestoreMigrations/index.ts
- apps/backend-ops/src/main.ts
- apps/backend-ops/src/syncStorage.ts
- apps/backend-ops/src/users.ts
> Storage as a source of truth to the db

- libs/movie/src/lib/movie/form/filters/languages/language-filter.component.ts
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.html
- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts
- libs/utils/src/lib/static-model/staticModels.ts
> Fix UI not updating static checkbox on form reset

- libs/user/src/lib/user/components/card/card.component.html
- libs/user/src/lib/user/components/card/card.component.scss
- libs/user/src/lib/user/components/card/card.module.ts
> Prevent user position to wrap to new line

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
Value in app search bars in sync
> App search bars in sync

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel-routing.module.ts
- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.scss
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.ts
- libs/movie/src/lib/movie/pages/additional-information/additional-information.module.ts
> APP-3194 Additional Info Page done

- libs/movie/src/lib/movie/pages/artistic/artistic.component.html
- libs/movie/src/lib/movie/pages/artistic/artistic.component.ts
- libs/utils/src/lib/static-model/staticModels.ts
- libs/utils/src/lib/static-model/types.ts
Add 2 new static : one for director's category and one for the credit status
> add new static

- libs/ui/src/lib/static-autocomplete/check-boxes/check-boxes.component.ts
Fix for bug caused by PR [#3416](https://github.com/blockframes/blockframes/pull/3416)
> Fix unsubscribe static checkbox subscription

- apps/backend-functions/src/data/internals.ts
- apps/backend-functions/src/maintenance.ts
- apps/backend-ops/src/admin.ts
- apps/backend-ops/src/db-cleaning-main.ts
- apps/backend-ops/src/db-cleaning.spec.ts
- apps/backend-ops/src/db-cleaning.ts
- libs/testing/src/lib/firebase/functions.spec.ts
- libs/testing/src/lib/firebase/functions.ts
Refactor Unit-Test code to avoid initializing twice
`admin.initializeApp(functions.config().firebase);`
TODO: Initial commit, need to refactor more but this is the way to approach this.
> UT(db-cleaning): Refactor to init firestore admin from Jest.

- apps/festival/festival/src/app/marketplace/home/home.component.ts
Featured Sales Organization banner now also only shows organizations with at least one movie.
Open issue is still that it has to be at least one movie that is accepted.
> Only show organizations with at least one movie

- package.json
- tools/scripts/anon-firestore.ts
Some progress in relation to #3162
basic anon script that works locally - run via npm command `npm run anonymize-db`
> feat(anon-firestore.ts): add local anonymisation script & npm command

- libs/movie/src/lib/movie/components/title-filter/title-filter.component.html
- libs/movie/src/lib/movie/components/title-filter/title-filter.component.scss
Quick UI fix for overflowing text in filters for movies
> Scroll bar for too wide filters

- libs/movie/src/lib/movie/pages/main/main.component.ts
- libs/movie/src/lib/movie/pages/production/production.component.html
- libs/movie/src/lib/movie/pages/production/production.component.ts
- libs/movie/src/lib/movie/pages/production/production.module.ts
> Applying new tables to [reviews] page.

- apps/festival/festival/src/app/marketplace/home/home.component.scss
Fix Marketplace homepage to do in issue #3412
> Added missing css to upcoming events banner

- tools/scripts/get-prod-backup.ts
Use folder "tmp" which is gitignore (we could change to another folder if you prefer, but I think "tmp" is a good place)
> Use folder for gitignore

- libs/organization/src/lib/organization/components/banner/banner.component.html
- libs/organization/src/lib/organization/components/banner/banner.component.ts
- libs/organization/src/lib/organization/components/banner/banner.module.ts
- libs/organization/src/lib/organization/pipes/org-movies.pipe.ts
- libs/utils/src/lib/pipes/filter-by.pipe.ts
Remove movies that have not yet been accepted or not available for festival from movie count
fix #3308 && todo in #3412
> Count only includes accepted movies now

- libs/organization/src/lib/organization/components/banner/banner.component.scss
> Added margin

- apps/festival/festival/src/app/marketplace/home/home.component.html
> Commented featured sales agent banner component on homepage

- libs/admin/src/lib/admin-panel/components/edit-title/edit-title.component.html
- libs/movie/src/lib/movie/form/main/genres/genres.component.html
- libs/movie/src/lib/movie/form/movie.form.ts
- libs/movie/src/lib/movie/form/sales-cast/sales-cast.component.html
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.html
- libs/movie/src/lib/movie/pages/additional-information/additional-information.component.ts
- libs/movie/src/lib/movie/pages/artistic/artistic.component.html
- libs/movie/src/lib/movie/pages/main/main.component.html
- libs/movie/src/lib/movie/pages/main/main.component.ts
- libs/movie/src/lib/movie/pages/production/production.component.html
- libs/movie/src/lib/movie/pages/reviews/reviews.component.html
- libs/movie/src/lib/movie/pages/synopsis/synopsis.component.html
- libs/movie/src/lib/movie/pages/technical-info/technical-info.component.html
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.html
- libs/ui/src/lib/static-autocomplete/chips/chips-autocomplete.component.ts
- libs/ui/src/lib/static-autocomplete/select/static-select.component.html
- libs/ui/src/lib/static-autocomplete/select/static-select.component.ts
> validators updated

- libs/testing/src/lib/firebase/functions.spec.ts
> Fix(UT) : Invitation lib and firebase test setup. Fixes #3452

- apps/catalog/catalog/src/app/marketplace/title/list/list.component.html
- apps/catalog/catalog/src/app/marketplace/title/list/list.component.scss
- apps/catalog/catalog/src/app/marketplace/title/list/list.module.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.html
- apps/festival/festival/src/app/marketplace/title/list/list.component.scss
- apps/festival/festival/src/app/marketplace/title/list/list.module.ts
Fix to do from issue #3412 
Add a tooltip "Clear all filters" to clear filters button
> Add tooltip and center to clear filter buttons

- apps/festival/festival/src/app/dashboard/dashboard.module.ts
- apps/festival/festival/src/app/dashboard/event/edit/edit.component.ts
- apps/festival/festival/src/app/dashboard/event/list/list.component.ts
- apps/festival/festival/src/app/dashboard/home/home.component.ts
- apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts
- apps/festival/festival/src/app/dashboard/title/details/details.component.ts
- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/event/calendar/calendar.component.ts
- apps/festival/festival/src/app/marketplace/event/list/list.component.ts
- apps/festival/festival/src/app/marketplace/home/home.component.ts
- apps/festival/festival/src/app/marketplace/organization/list/list.component.ts
- apps/festival/festival/src/app/marketplace/organization/meeting/meeting.component.ts
- apps/festival/festival/src/app/marketplace/organization/member/member.component.ts
- apps/festival/festival/src/app/marketplace/organization/screening/screening.component.ts
- apps/festival/festival/src/app/marketplace/organization/title/title.component.ts
- apps/festival/festival/src/app/marketplace/title/list/list.component.ts
- apps/festival/festival/src/app/marketplace/title/main/main.component.ts
- apps/festival/festival/src/app/marketplace/title/screening/screening.component.ts
- apps/festival/festival/src/app/marketplace/wishlist/wishlist.component.ts
- libs/invitation/src/lib/invitation.component.ts
- libs/notification/src/lib/notification.component.ts
> add dynamic titles

- apps/backend-functions/src/data/types.ts
- apps/catalog/catalog/src/app/dashboard/right/list/list.component.ts
- apps/catalog/catalog/src/app/marketplace/right/list/list.component.ts
- libs/admin/src/lib/admin-panel/components/edit-party/edit-party.component.ts
- libs/admin/src/lib/admin-panel/pages/contract/contract.component.ts
- libs/admin/src/lib/admin-panel/pages/distribution-right/distribution-right.component.ts
- libs/admin/src/lib/admin-panel/pages/organization/organization.component.ts
- libs/contract/src/lib/contract/+state/contract.firestore.ts
- libs/contract/src/lib/contract/components/table/table.component.ts
- libs/contract/src/lib/contract/tunnel/contract-tunnel.component.ts
- libs/contract/src/lib/contract/tunnel/lobby/lobby.component.ts
- libs/import/src/lib/components/view-extracted-elements/contract/view-extracted-contracts.component.ts
- libs/movie/src/lib/distribution-rights/+state/distribution-right.firestore.ts
- libs/organization/src/lib/cart/+state/cart.model.ts
- libs/organization/src/lib/cart/+state/cart.store.ts
- libs/organization/src/lib/organization/+state/organization.firestore.ts
- libs/organization/src/lib/organization/+state/organization.model.ts
- libs/organization/src/lib/organization/forms/organization-form-description/organization-form-description.component.ts
- libs/utils/src/lib/pipes/to-label.pipe.ts
- libs/utils/src/lib/static-model/staticConsts.ts
- libs/utils/src/lib/static-model/types.ts
Change every const and rework a little the toLabel pipe.
> Move const

- libs/media/src/lib/+state/media.model.ts
Quick fix until feature/movie-form branch is merged
> Fix poster not uploading

- libs/movie/src/lib/movie/components/header/header.component.html
- libs/movie/src/lib/movie/components/header/header.component.scss
> Movie banner slimmer and fixed dark overlay

- apps/festival/festival/src/app/dashboard/home/home.component.ts
- apps/festival/festival/src/app/dashboard/title/list/list.component.ts
- firestore.rules
> fix & rules

- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel-routing.module.ts
- apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.component.ts
- libs/movie/src/lib/movie/pages/promotional-elements/media-files/media-files.component.html
- libs/movie/src/lib/movie/pages/promotional-elements/media-files/media-files.component.scss
- libs/movie/src/lib/movie/pages/promotional-elements/media-files/media-files.component.ts
- libs/movie/src/lib/movie/pages/promotional-elements/media-files/media-files.module.ts
- libs/movie/src/lib/movie/pages/summary/summary.component.ts
- libs/ui/src/lib/tunnel/layout/nav/nav.component.html
- libs/ui/src/lib/tunnel/layout/nav/nav.component.scss
> Added Media-files page.
